### ISSUE TITLE
לא מייבא ממסופון

### ISSUE THREAD

**Issue by WizMotiSaadon** [wizayala/Hashavsheva#10]
תוקן crmin.hds

**Comment by WizMotiSaadon** [comment]
[import_V2017_10_Februar_2015.zip](https://github.com/wizayala/Hashavsheva/files/126210/import_V2017_10_Februar_2015.zip)
[Uploading import_V2016_10_Februar_2016.zip…]()

**Comment by WizMotiSaadon** [comment]
[import_V2017_14_Februar_2015.zip](https://github.com/wizayala/Hashavsheva/files/129566/import_V2017_14_Februar_2015.zip)
[import_V2016_14_Februar_2016.zip](https://github.com/wizayala/Hashavsheva/files/129565/import_V2016_14_Februar_2016.zip)
סידרתי גם תקלה Similar Engine Is Not Initialised .. Terminating

**Comment by WizMotiSaadon** [comment]
[import_V2016_14_Februar_2016.zip](https://github.com/wizayala/Hashavsheva/files/129575/import_V2016_14_Februar_2016.zip)
[import_V2017_14_Februar_2015.zip](https://github.com/wizayala/Hashavsheva/files/129574/import_V2017_14_Februar_2015.zip)
סידרתי גם שיתן שינוי שם קובץ עם תאריך ושעה בשם הקובץ

**Comment by wizayala** [comment]
היי

מאיפה פה בחלון אני סוגרת את הרשומה.
זה נראה תקין

[cid:image001.png@01D16714.E19DB130]

איילה ישראלי – בדיקות

052-9594258  04-9512832

אתר : www.hash.co.il<http://www.hash.co.il>  ,  דוא"ל : ayala@wizsoft.com<mailto:ayala@wizsoft.com>

[cid:image002.png@01D16714.E19DB130]

**Comment by WizMotiSaadon** [comment]
יש כפתור 
Close issue 
בצבע אפור

**Comment by wizayala** [comment]
מצאתי
בחלון הקודם לא התחברתי אלא נכנסתי מתוך המייל שהגיע.


איילה ישראלי – בדיקות

052-9594258  04-9512832

אתר : www.hash.co.il<http://www.hash.co.il>  ,  דוא"ל : ayala@wizsoft.com<mailto:ayala@wizsoft.com>

[cid:image001.png@01D16715.BF925EF0]

**Comment by wizayala** [comment]
לא ניתן לייבא כפולים מתוך מסופון 2

**Comment by wizayala** [comment]
בנוסף מתוך התוכנה אם סימנתי פעם אחת ייבוא כפולים , זוכר את זה בכניסה הבאה  וחוזר לברירות מחדל עם היציאה מהתוכנה וכניסה מחדש

**Comment by WizMotiSaadon** [comment]
האם סימנת יבוא כפולים בהגדרות של מסופון2
?

**Comment by wizayala** [comment]
בוודאי

**Comment by WizMotiSaadon** [comment]
[import_V2016_14_Februar_2016.zip](https://github.com/wizayala/Hashavsheva/files/129629/import_V2016_14_Februar_2016.zip)
[Uploading import_V2017_14_Februar_2015.zip…]()
מייבא כפולים מתוך מסופון 2

**Comment by wizayala** [comment]
מעולה...

**Comment by WizMotiSaadon** [comment]
[import_V2017_14_Februar_2015.zip](https://github.com/wizayala/Hashavsheva/files/129646/import_V2017_14_Februar_2015.zip)
[import_V2016_14_Februar_2016.zip](https://github.com/wizayala/Hashavsheva/files/129647/import_V2016_14_Februar_2016.zip)
עכשיו אין זכרון

**Comment by wizayala** [comment]
Leave a comment
