### ISSUE TITLE
יבוא שדות נוספים - שיוך שגוי

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#100]
ביבוא שדות נוספים תקלה בשיוך של השדות.
תקלה שהייתה תוקנה וחזרה

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
מוטי
אני לא מצליחה לשחזר את התקלה  גם אם אני מוחקת סכום נוסף 1

**Comment by wizayala** [comment]
מוטי
לדעתי התיקון הוא לא נכון 
סכום נוסף 1-4בחשבונות(itemflag=0)  אמורים להיות 
extrasumname.id1-4
במידה ואין אז לא צריך לקחת את הבא בתור אלא פשוט להציג שורה ריקה 
 (itemflag=1)אותו דבר עבור פריטים 
extrasumname.id5-12
כמובן אותו דבר צריך להתייחס גם לתאריכים  חשבונות מזהה 1-2 , פריטים 3-6
מה דעתך ?

**Comment by WizMotiSaadon** [comment]
?אבל מה עושים אם מישהו משחק בטבלה ומוחק רשומות

**Comment by wizayala** [comment]
בקישור שדות סכום נוסף 1 יהיה ריק

**Comment by WizMotiSaadon** [comment]
אז זה אומר שיש בעיה גם בחשבשבת?

**Comment by wizayala** [comment]
לא חושבת. 
מחר אדבר עם הדס ואתייעץ איתה

**Comment by wizayala** [comment]
לא
תמתין עם התיקון

**Comment by WizMotiSaadon** [comment]
תוקן 
heshin.hds

**Comment by wizayala** [comment]
לגרסת לקוחות קובץ heshin.hds 
בגרסה הבאה יהיה גם תיקון בתאור השדות בקובץ odbcimp.exe
