### ISSUE TITLE
יבוא כרטיסי אשראי - ישראכרט chsh

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#103]
יש להתעלם מרשומות שקוד הרשומה ( תווים2-3) הוא 37,38,47,48
שלחתי לך במייל נפרד דוגמא לקובץ קלט המכיל רשומות כאלו

**Comment by WizMotiSaadon** [comment]
תוקן

IsracardGroupShovarimin_Chsh.HDS

**Comment by wizayala** [comment]
מוטי, תתקן גם תצוגה מקדימה בבקשה 

![image](https://user-images.githubusercontent.com/16633745/76209490-a4a9ae00-620a-11ea-9abd-8ea40fc667de.png)

**Comment by WizMotiSaadon** [comment]
תיקנתי

**Comment by wizayala** [comment]
בפועל נקלט

**Comment by wizayala** [comment]
תקין תודה
