### ISSUE TITLE
יבוא פריטים - נוספים וסוג פריט

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#105]
כאשר מייבאים פריטים עם שדה סוג פריט ושדות נוספים נוצר שיבוש שככל הנראה הוא בגלל השורות הנוספות שנוצרות בעבור הנוספים ואז סוג הפריט

Error in SQL :Cannot insert duplicate key row in object 'dbo.ITEMS' with unique index 'ITEMS_ITEMKEY'. The duplicate key value is (גבון).
The statement has been terminated.

INSERT INTO ITEMS (ITEMKEY,BDATE,CURRENCY,PURCHCURRENCY,LASTPURCHDATE,STOCKCOUNTDATE,DEFAULTWAREHOUSE,STOCKPERUNIT,MAXSTORAGEPERIOD,KDAYS,BUSEFID,FILTER )   SELECT DISTINCT IMPORTITEM.ITEMKEY,GETDATE(),COMPANYDEFENITIONS.MAINCURRENCY,COMPANYDEFENITIONS.MAINCURRENCY,'1980-01-01','1980-01-01',1,ISNULL(IMPORTITEM.STOCKPERUNIT,0),9999,1,9,'^^^^^^^^^^'  FROM         IMPORTITEM                              LEFT OUTER JOIN ITEMS ON DBO.ITEMS.ITEMKEY = DBO.IMPORTITEM.ITEMKEY                                       CROSS JOIN COMPANYDEFENITIONS   WHERE        COMPANYDEFENITIONS.ID=(SELECT MIN(ID) FROM COMPANYDEFENITIONS) AND (ITEMS.ITEMKEY IS NULL) AND (IMPORTITEM.ERRORMESSAGE IS NULL)  AND (IMPORTITEM.ITEMKEY IS NOT NULL)

**Comment by WizMotiSaadon** [comment]
תוקן
itemin.hds

**Comment by wizayala** [comment]
תקין
