### ISSUE TITLE
יבוא תנועות יומן - שיטה גמישה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#106]
תקלה ביבוא בשיטה הגמישה
---------------------------
WIZIMP~2
---------------------------
1583761739041 CJournalData::Update
---------------------------
OK   
---------------------------

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
---------------------------
WIZIMP~2
---------------------------
1583761739041 CJournalData::Update
---------------------------
OK   
---------------------------
זו ההודעה שאני מקבלת  אישור ממשיך בתהליך קליטה מתקבלת הודעה של שגויים אנכונה ואז המשך קליטה ומופיעה ההודעה הבאה :
---------------------------
WIZIMP~2
---------------------------
 CImportData::ExecuteSQL error #1# :  insert into jurnaltrans(osek874,Quant,jurnalmatchid,TransType ,Status,BatchNo   ,CostCode ,TransCredID,CurrencyCode,DatF3,TransDebID,Description,ValueDate,DueDate,Ref2            ,Referance      ,Ref3      ,suF      ,suFDlr         ,LockingIs,bdate,hour)                                           SELECT osek874,Quant,transid,										  transtype      ,										  2    ,										  171       ,										  CostCode     ,										  isnull(NULLIF(CredID1, ''),CredID2 )        ,										  CurrencyCode        ,										  DatF3 ,										  isnull(NULLIF(DebID1, ''),DebID2 )      ,										  Description       ,										  ValueDate     ,										  DueDate   ,										  Reference2             ,										  Reference            ,										  Ref3       ,										  case when Abs(CredsuF1 + CredsuF2)>Abs(DebsuF1 + DebsuF2) then (CredsuF1+CredsuF2) else (DebsuF1 + DebsuF2) end,										  case when Abs(CredsuFDlr1 + CredsuFDlr2)>Abs(DebsuFDlr1 + DebsuFDlr2) then (CredsuFDlr1+CredsuFDlr2) else (DebsuFDlr1 + DebsuFDlr2)  end            ,										  case when LEN(ISNULL(ImportJournal.CredID1,''))>0 and LEN(ISNULL(ImportJournal.CredID2,''))>0 or LEN(ISNULL(ImportJournal.DebID1,''))>0 and LEN(ISNULL(ImportJournal.DebID2,''))>0 or LEN(ISNULL(ImportJournal.TransType,''))>0  then 4 else 0 end       ,										  Convert(varchar(10), GETDATE(),120) ,										  DATEPART(hour, GETDATE())*60  +  DATEPART(minute, GETDATE()) 										   FROM ImportJournal where ('AYALAWIN10_4944' = ImportJournal.Computername And ImportJournal.ErrorMessage is null)  order by transid 
CDBException = Error converting data type varchar to float.

---------------------------
OK   
---------------------------

**Comment by WizMotiSaadon** [comment]
תוקן
WizImportMySql.dll
jurnalin.hds

**Comment by wizayala** [comment]
מוטי
כמה בעיות : 
1. אני לוחצת על הדפסת שגויים ומקבלת רשימת שגויים שלא קשורה 

![image](https://user-images.githubusercontent.com/16633745/76762079-4a27c900-6799-11ea-828d-49af17a5cfa5.png)

**Comment by wizayala** [comment]
2.  יצאתי ללא קליטה , מקבלת הודעה לא נקלטה כל רשומה ולאחר היציאה מחלון ממשק תנועות יומן , הקובץ משנה שם ל bak

**Comment by wizayala** [comment]
3. במידה ואני מבקשת לקלוט נקלט ללא כל הודעת שגיאה כפי שהיה קודם

**Comment by WizMotiSaadon** [comment]
> מוטי
> כמה בעיות :
> 
> 1. אני לוחצת על הדפסת שגויים ומקבלת רשימת שגויים שלא קשורה
> 
> ![image](https://user-images.githubusercontent.com/16633745/76762079-4a27c900-6799-11ea-828d-49af17a5cfa5.png)

תוקן

**Comment by wizayala** [comment]
בעיות 1 ו 3 הסתדרו  2 נותרה פתוחה . אפתח עליה גיט
