### ISSUE TITLE
יבוא תנועות מלאי  לזמני- פריט טבוע

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#107]
כאשר אנחנו מייבאים תנועות מלאי לזמני עם פריטים טבועים, שדה itemsinstance.balance  מקבל ערך 1 במקום את הערך 0
ואז כשמפיקים את המסמך מהזמני לקבוע , שדה itemsinstance.fix  לא משנה מ 0 ל 1 .
האם תוכל לתקן זאת ששדה itemsinstance.balance יקבל ערך 0 **רק** בקליטה לזמני. ואילו בקליטת תנועות מלאי לקבוע יקבל השדה itemsinstance.balance את הערך 1

**Comment by WizMotiSaadon** [comment]
תיקנתי
mlayin.hds

**Comment by wizayala** [comment]
תקין
