### ISSUE TITLE
יבוא תנועות יומן - הודעת שגיאה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#110]
מקבלת הודעת שגיאה בקליטה של קבצים : 
---------------------------
WIZIMP~2
---------------------------
 CImportData::OpenDB() m_db.OpenEx 1  ewsdvc CDBException exeption, e->m_strError = Connection in use

---------------------------
OK   
---------------------------
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Runtime Error!

Program: C:\2019\Has.exe

abnormal program termination

---------------------------
OK   
---------------------------
 שלחתי לך במייל נפרד קבצי קלט

**Comment by WizMotiSaadon** [comment]
WizImportMySql.dll
תוקן
