### ISSUE TITLE
יבוא תנועות יומן - שיטה גמישה 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#112]
ביציאה מהקליטה מתקבלת הודעה לא נקלטה כל רשומה אך בפועל מבצע שינוי שם לקובץ והופך אותו ל 
bak

**Comment by WizMotiSaadon** [comment]
אני יודע את זה,
זה בגלל הקובץ IMP_LIB
ששיך לגרסה הנוכחית...

אבל אני לא יכול לתקן אותו עכשיו

**Comment by wizayala** [comment]
לא הבנתי מדוע אי אפשר לתקן

**Comment by WizMotiSaadon** [comment]
כי אם אני יתקן,
ואז אצטרך לתת ללקוחות תיקון,
הם יקבלו משהו דפוק

**Comment by wizayala** [comment]
צריך לחשוב על משהו , אי אפשר להשאיר את הדברים כך

**Comment by WizMotiSaadon** [comment]
למה לחשוב, הכל כבר מוכן
רק צריך להוריד את זה יומיים לפני שיוצאת גרסה

**Comment by WizMotiSaadon** [comment]
תוקן
imp_lib.hds

**Comment by wizayala** [comment]
תקין
