### ISSUE TITLE
יבוא תנועות יומן - סרגל קליטה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#116]
בגרסה החדשה סרגל קליטה אינו נראה כך

![image](https://user-images.githubusercontent.com/16633745/77291696-6d95cb00-6ce7-11ea-9832-80f86ddbb340.png)

**Comment by WizMotiSaadon** [comment]
כמובן , כי העבודה מתבצעת בשרת
זה בשביל שיהי יותר מהיר

**Comment by wizayala** [comment]
סוגרת את הגיט, ראיתי שהוספת עכשיו מלל של קליטה זמנית, עיבוד נתונים....
