### ISSUE TITLE
יבוא תנועות יומן - גרסת לקוחות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#117]
ביבוא תנועות יומן בגרסת לקוחות מקבלת את ההודעה הבאה : 

![image](https://user-images.githubusercontent.com/16633745/77297086-75f30380-6cf1-11ea-96e5-2f431c1da19d.png)

**Comment by WizMotiSaadon** [comment]
regsvr32 wizini.dll

גרסה אחרונה של
 WIZINI

**Comment by wizayala** [comment]
תודה , הסתדר
