### ISSUE TITLE
יבוא תנועות יומן - שדה ref3

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#119]
jurnaltrans.ref3 
השדה צריך לקבל ערך 0 ולא 
null

**Comment by WizMotiSaadon** [comment]
אני חושב שזה מה שאני עושה


![image](https://user-images.githubusercontent.com/10919353/77311588-1274d000-6d09-11ea-9e80-7683192dba85.png)

**Comment by wizayala** [comment]
כך זה אצלי


![image](https://user-images.githubusercontent.com/16633745/77312353-81065d80-6d0a-11ea-973b-de7883fc47c3.png)

**Comment by WizMotiSaadon** [comment]
HSImportJournal29.sql

תוקן

**Comment by wizayala** [comment]
תקין
