### ISSUE TITLE
יבוא תנועות הנהלת חשבונות - changeable

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#121]
שדה 
jurnaltran.changable 
מקבל ערכים שונים, ביבוא החדש מקבל בכל האפשרויות מקבל ערך 0
לדוגמא : תנועה עם ממשק עם סכום שקל בלבד , מקבל ערך 7
              תנועה עם ממשק עם סכום שקל ומטח מקבל ערך 6

בגרסת לקוחות זה עובד טוב, תשווה מול הגרסה הזו מה השתנה

**Comment by WizMotiSaadon** [comment]
HSImportJournal27.sql
