### ISSUE TITLE
יבוא תנועות יומן - חשבון לא פעיל

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#123]
כאשר יש תנועה עם חשבון שהוא לא פעיל אתה נותן הודעת שגיאה בגרסה החדשה.
בגרסת לקוחות אפשרנו לקלוט עם חשבונות לא פעילים.
למה השתנה ?

**Comment by WizMotiSaadon** [comment]
לא יודע למה, 
בדקתי ב
WEB 

גם שם זה ככה

**Comment by WizMotiSaadon** [comment]
זה תיקון די וותיק

**Comment by wizayala** [comment]
אולי תיקון ותיק בגרסת ווב
בגרסת חלונות כולל גרסת לקוחות אחרונה אנחנו לא חוסמים חשבון פעיל
תתקן בבקשה שגם בגרסה הבאה אנחנו מאפשרים קליטת תנועות עם חשבון לא פעיל

**Comment by WizMotiSaadon** [comment]
HSImportJournal28.sql   תוקן

**Comment by wizayala** [comment]
תקין , תודה
