### ISSUE TITLE
יבוא תנועות יומן - איפוס סכום

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#124]
בממשק יש סכום 0.29 , נקלט טוב לטבלה הזמנית אך לטבלת 
jurnaltrans  
נקלט הסכום 
null

![image](https://user-images.githubusercontent.com/16633745/77311862-9929ad00-6d09-11ea-945a-ad0699947bad.png)

![image](https://user-images.githubusercontent.com/16633745/77312046-e4dc5680-6d09-11ea-89c5-14e1f0054818.png)

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/77312173-2f5dd300-6d0a-11ea-87f3-c3dd106fe432.png)

**Comment by wizayala** [comment]
שלחתי לך קבצי קלט במייל נפרד 
קובץ אקסל

**Comment by WizMotiSaadon** [comment]
HSImportJournal27.sql
