### ISSUE TITLE
יבוא תנועות מלאי - שדות תאריכים נוספים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#125]
שדות תאריכים נוספים 
stock.extradate1,2     stockmoves.extradate1,2
מקבל ערך 1.1.1900 במקום תאריך מערכת כברירת מחדל

**Comment by WizMotiSaadon** [comment]
תוקן 
mlayin.hds

**Comment by wizayala** [comment]
o.k
