### ISSUE TITLE
ייצוא חשבונות - נמענים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#127]
בחברה שבה אין נמענים כלל , הטבלה ריקה ( ExportAddressees) נוצר שיבוש . 
תוכל להתחבר אליי לראות את הבעיה 
![image](https://user-images.githubusercontent.com/16633745/77621122-7cc58480-6f44-11ea-84ca-dc1726074c28.png)

![image](https://user-images.githubusercontent.com/16633745/77621530-4dfbde00-6f45-11ea-8242-28fa5c6c32ea.png)

**Comment by wizayala** [comment]
העברתי לך חברה שבה יש את התקלה למחיצה הבאה : 

H:\HomeFolder\Ayala\for moti

**Comment by WizMotiSaadon** [comment]
אני העלתי מגיבוי את החברה "אשר"
והכל תקין
![image](https://user-images.githubusercontent.com/10919353/77847192-dbe4fc80-71c3-11ea-9936-1a446488a5cf.png)

**Comment by wizayala** [comment]
תקין גם אצלי
כנראה בעקבות עדכון קבצים
