### ISSUE TITLE
יבוא תנועות מלאי מחלונות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#128]
לאחר שבצעתי ייצוא תנועות מלאי וייבוא תנועות מלאי  לחברה שבצעתי עליה מולטי והתאמתי אותה לגרסה החדשה מופיע ההודעה הבאה :

![image](https://user-images.githubusercontent.com/16633745/77643289-c6739680-6f67-11ea-8c79-c91960613651.png)

---------------------------
HSD
---------------------------

Ambiguous column name 'STATUS'.

---------------------------
אישור  
---------------------------
והתוכנה נסגרת

**Comment by WizMotiSaadon** [comment]
אני חייב איזה BATCHLOG

**Comment by wizayala** [comment]
איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
MLAYIN.HDS

תוקן

**Comment by wizayala** [comment]
מוטי
צילום מסך הוא משגיאה אחרת 
בכל אופן התקלה תוקנה
