### ISSUE TITLE
ייצוא חשבונות - חיתוך חשבון ראשי

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#131]
מוטי
לא מפיק קובץ לפי חיתוך של חשבון ראשי 
בנוסף סדר הצגת חשבון ראשי אינו ממויין טוב כפי שמופיע בחשבונות 

![image](https://user-images.githubusercontent.com/16633745/77659881-49edb180-6f81-11ea-8a06-a2cac32e773c.png)

![image](https://user-images.githubusercontent.com/16633745/77659919-56720a00-6f81-11ea-980a-fc366fd4212d.png)

**Comment by WizMotiSaadon** [comment]
> בנוסף סדר הצגת חשבון ראשי אינו ממויין טוב כפי שמופיע בחשבונות


תוקן

**Comment by WizMotiSaadon** [comment]
> לא מפיק קובץ לפי חיתוך של חשבון ראשי

אני מדפיס את השאילתא למסך,
האם את רואה את החיתוך בשאילתא?

**Comment by wizayala** [comment]
תקין
