### ISSUE TITLE
ייצוא חשבונות - מפתח חשבון 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#134]
בייצוא חשבונות מופיעה ההודעה הבאה :

---------------------------
HSD
---------------------------

select * from accounts where 1 = 1 And  ( [accountkey] <= '300002' And [accountkey] >= '30001' ) 
---------------------------
אישור  
---------------------------
![image](https://user-images.githubusercontent.com/16633745/77842636-59494680-719d-11ea-9a62-6c388a18cb1c.png)

האם זה בגלל סדר השדות ?

**Comment by WizMotiSaadon** [comment]
---------------------------
זה לא ללקוחות
---------------------------

זה בשביל שתוכלי לבדוק אם השאילתא שעשיתי נכונה
בהתאם לחיתוך שביקשת

את אמורה להריץ אותה בחברה
ולראות

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/77842693-0623c380-719e-11ea-90d0-92dd344a1e28.png)

אני מניחה שהשאילתא נכונה , קיבלתי הודעה לא נמצאו תנועות להעברה. בגרסת לקוחות תתן הודעה מתאימה ,כמו באינדס חשבונות

![image](https://user-images.githubusercontent.com/16633745/77842723-6d417800-719e-11ea-9f53-f07260e6222f.png)

**Comment by WizMotiSaadon** [comment]
מה לא תקין בחתך שעשית?

**Comment by wizayala** [comment]
לא ברור לי
בודקת מול אפרת

**Comment by wizayala** [comment]
השאילתא שלך נכונה , השוותי אותה לאינדקס חשבונות

![image](https://user-images.githubusercontent.com/16633745/77843231-db3c6e00-71a3-11ea-8267-45f637287b3d.png)

**Comment by WizMotiSaadon** [comment]
נהדר
