### ISSUE TITLE
יבוא תנועות יומן - חלונות 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#136]
תנועות יומן מחלונות לחלונות  ממשק של 1380 רשומות לוקח לו 1.5 דקות 
זה לא נראה לי  מהיר כל כך....

**Comment by wizayala** [comment]
גם סימון היפוך עברית לא משנה תצוגה מקדימה אבל הקליטה נעשית נכונה

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
לקח לי סביב 2 דק'
