### ISSUE TITLE
יבוא תנועות מלאי - הכנסות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#138]
הוספנו שדה של הכנסות /הוצאות ביבוא תנועות מלאי. הנתן נכנס לטבלת 
importstock 
אך לא מתעדכן בטבלת 
stockmoves

![image](https://user-images.githubusercontent.com/16633745/77886584-ccbc8800-7271-11ea-92f3-129e446e2b1c.png)

![image](https://user-images.githubusercontent.com/16633745/77886686-fb3a6300-7271-11ea-956f-13d57ddfce8f.png)

**Comment by WizMotiSaadon** [comment]
לדעתי ההפקה מוחקת
אני שולח לך קובץ עם הודעות שלי

**Comment by wizayala** [comment]
---------------------------
HSD
---------------------------

sql before = #INSERT INTO StockMoves (DUEDATE,DETAILS,WAREHOUSE,EXTRANUM1,EXTRANUM2,EXTRADATE1,EXTRADATE2,  EXFILE,Instance,BatchNum,Localization,WarrentyDate,CancelDate,ExpireDate, BaseDate,StockID,                                     ItemKey,                                          Agent,    Reference,                                     Price,oprice,                                     Quantity,orate,                              DiscountPrc,                                   CurrencyCode,Rate,                                                    DocumentID,   VatExampt,Packs,ItemName,Unit,SaleTaxPrc,AlterNum,CommisionPrc,PurchQuantity,supplyquantity,BranchID,LineNum,BaseLineNum,ExtraText1,ExtraText2,ExtraSum1,ExtraSum2,BaseMoveID,BaseDocType,costcode,ALTERNAME,JURNALACC)  VALUES                            ('2020-03-30','',0,66,777777,'03/30/2020','03/30/2020',  '','','','','1980-01-01',#1/1/1999#,  #03/30/2020#,  #03/30/2020#,9767,'1',751,7845,0,0,1.000000000,1,0,  'ש²ח',        1,11,0,0,'תלונות חוסר סחורה עד 24 שעות מקבלתה !!','',0,'',0,1.000000000,1.000000000,1,0,0,'','',0,0,0,0,'','','40003'   );#
---------------------------
אישור  
---------------------------
---------------------------
HSD
---------------------------

sql after = #INSERT INTO StockMoves (DUEDATE,DETAILS,WAREHOUSE,EXTRANUM1,EXTRANUM2,EXTRADATE1,EXTRADATE2,  EXFILE,Instance,BatchNum,Localization,WarrentyDate,CancelDate,ExpireDate, BaseDate,StockID,                                     ItemKey,                                          Agent,    Reference,                                     Price,oprice,                                     Quantity,orate,                              DiscountPrc,                                   CurrencyCode,Rate,                                                    DocumentID,   VatExampt,Packs,ItemName,Unit,SaleTaxPrc,AlterNum,CommisionPrc,PurchQuantity,supplyquantity,BranchID,LineNum,BaseLineNum,ExtraText1,ExtraText2,ExtraSum1,ExtraSum2,BaseMoveID,BaseDocType,costcode,ALTERNAME,JURNALACC)  VALUES                            ('2020-03-30','',0,66,777777,'03/30/2020','03/30/2020',  '','','','','1980-01-01',#1/1/1999#,  #03/30/2020#,  #03/30/2020#,9767,'1',751,7845,0,0,1.000000000,1,0,  'ש²ח',        1,11,0,0,'תלונות חוסר סחורה עד 24 שעות מקבלתה !!','',0,'',0,1.000000000,1.000000000,1,0,0,'','',0,0,0,0,'','','40003'   );#
---------------------------
אישור  
---------------------------
---------------------------
HSD
---------------------------

sql after = #INSERT INTO StockMoves (DUEDATE,DETAILS,WAREHOUSE,EXTRANUM1,EXTRANUM2,EXTRADATE1,EXTRADATE2,  EXFILE,Instance,BatchNum,Localization,WarrentyDate,CancelDate,ExpireDate, BaseDate,StockID,                                     ItemKey,                                          Agent,    Reference,                                     Price,oprice,                                     Quantity,orate,                              DiscountPrc,                                   CurrencyCode,Rate,                                                    DocumentID,   VatExampt,Packs,ItemName,Unit,SaleTaxPrc,AlterNum,CommisionPrc,PurchQuantity,supplyquantity,BranchID,LineNum,BaseLineNum,ExtraText1,ExtraText2,ExtraSum1,ExtraSum2,BaseMoveID,BaseDocType,costcode,ALTERNAME,JURNALACC)  VALUES                            ('2020-03-30','',0,66,777777,'03/30/2020','03/30/2020',  '','','','','1980-01-01',#1/1/1999#,  #03/30/2020#,  #03/30/2020#,9767,'1',751,7845,0,0,1.000000000,1,0,  'ש²ח',        1,11,0,0,'תלונות חוסר סחורה עד 24 שעות מקבלתה !!','',0,'',0,1.000000000,1.000000000,1,0,0,'','',0,0,0,0,'','','40003'   );#
---------------------------
אישור  
---------------------------

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
מצויין

**Comment by wizayala** [comment]
אין בדיקה של חשבון הכנסות הוצאות האם הוא עם חשבון ראשי תואם. בודקת מול אפרת מה אפשר לעשות.

**Comment by wizayala** [comment]
מוטי
ישנן בדיקות שיש לעשות על סוג ההכנסה וסוג ההוצאה האם החשבון הראשי מתאים והאם מתאים גם לסוג המסמך.
הדס אמרה שתשוחח איתך ותשלח לך את הבדיקות שעבד עושה לפני ההפקה ואלו יהיו בדיקות שאנחנו נעשה בשלב הקליטה.
