### ISSUE TITLE
יבוא מחירים מיוחדים - עדכון תאריך עד

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#139]

**Comment by wizayala** [comment]
ביבוא מחירים מיוחדים לא מעדכן תאריךבתוקף עד , מעדכן מחירים כמויות וכו' אך לא את השדה הזה.
השדה מתעדכן בטבלת
 improtprice  
אבל לא מתעדכן בטבלת 
specialprices

**Comment by WizMotiSaadon** [comment]
רשומה בטבלה
specialprices 
אני פותח חדשה בלבד

עדכונים של רשומה קיימת רק בטבלה 
SpecialPricesMoves

ורק אם מסמנים

**Comment by wizayala** [comment]
נוכל לשוחח על זה מחר בבוקר ?
תתחבר אלי ואראה לך למה אני מתכוונת

**Comment by WizMotiSaadon** [comment]
אחרי שבדקתי את האינטרנט והחשבשבת חלונות
והתיעוד,
אני רואה שצריך לשנות את הכיתוב ולרשום
"על סמך תאריך+חשבון+פריט"

**Comment by wizayala** [comment]
מה זה על סמך תאריך?

**Comment by WizMotiSaadon** [comment]
> ביבוא מחירים מיוחדים לא מעדכן תאריךבתוקף עד 

תוקן
pricein.hds

**Comment by wizayala** [comment]
מוטי
לא ברור לי מדוע נותן הודעה שאין כמות מינימלית של 0

![image](https://user-images.githubusercontent.com/16633745/81492766-3d0fed80-92a3-11ea-8fd7-d6fecf15dd2c.png)

**Comment by wizayala** [comment]
> מה זה על סמך תאריך?

•	בדיקת עדכון מחירים קיימים יעשה לפי מפתח חשבון + מפתח פריט + תאריך תחילת תוקף.

**Comment by WizMotiSaadon** [comment]
> מה זה על סמך תאריך?

הכוונה היא שלפי הכותרת , שאני מזהה אותה חד משמעית לפי חשבון, פריט, ותאריך תוקף,
אני ניגש לתנועות ומעדכן את המחירים

**Comment by wizayala** [comment]
אתה שאלת שאלה, כשאנחנו מסמנים עדכון לפי חשבון +פריט + תאריך , הכוונה לתאריך תחילת תוקף



איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
שיפרתי את ההסבר 
במסך מחירים מיוחדים

**Comment by WizMotiSaadon** [comment]
בגלל התאריך, זה תאריך אחר

בבדיקה אני מתייחס לתאריך

**Comment by wizayala** [comment]
מוטי
מדוע מתקבלת ההודעה הזו כשיש כמות מינימלית , תסתכל כמה הודעות למעלה רשמתי עם תמונה

**Comment by WizMotiSaadon** [comment]
כי את חייבת שתהיה כמות מינימלית אפס
יש לך רשומה עם כמות כזאת?

**Comment by wizayala** [comment]
יש 
אם תסתכל בצילום מסך תראה ששורה ראשונה היא עם כמות 0

**Comment by WizMotiSaadon** [comment]
אבל זה תאריך אחר

**Comment by wizayala** [comment]
סליחה צודק, מתקנת וכבר מעדכנת

**Comment by wizayala** [comment]
לא מתעדכן , שולחת לך קבצי קלט
הנתונים נכנסים לטבלה זמנית אך לא נקלטים לטבלת מחירים מיוחדים.
אני מתייחסת לרשומה חדשה

**Comment by wizayala** [comment]
איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
ביקשת לעדכן?
יש צ'ק בוקס

**Comment by wizayala** [comment]
תרצה להתחבר?


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
תוקן

pricein.hds

**Comment by wizayala** [comment]
עכשיו נוצרה רשומה. מה הייתה התקלה ?

![image](https://user-images.githubusercontent.com/16633745/81674892-98361180-9456-11ea-934a-4791f5fd1a45.png)

**Comment by WizMotiSaadon** [comment]
שכחתי להפעיל את השאילתת הוספה

**Comment by wizayala** [comment]
תקין
