### ISSUE TITLE
יבוא תנועות מלאי - הכנסות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#143]
ביבוא תנועות מלאי כאשר אנחנו מייבאים כרטיס הכנסות יש לוודא שהוא מתאים לחשבון ראשי של הכנסות ומתאים לסוג מסמך של הכנסה ( יש לראות את ההגבלות כפי שעבד עושה במודול מסמכים)
אותו הדבר יש לעשות כאשר מגדרים כרטיס הוצאה , שתואם לחשבונות ראשיים של הוצאה ותואם למסמך שמתייחס להוצאה

**Comment by WizMotiSaadon** [comment]
תוקן

mlayin.hds

**Comment by wizayala** [comment]
שייכתי הכנסות לסוג מסמך שמצריך הוצאה. המסמך הופק

**Comment by wizayala** [comment]
מה התיקון שנעשה פה ?

**Comment by WizMotiSaadon** [comment]
התיקון הוא שאם יש בעיה עם החשבון
 JURNALACC
אז אני מודיע הודעה

**Comment by wizayala** [comment]
נדמה לי שהבדיקה היחידה שאתה עושה היא האם החשבון של ההכנסות הוא הכנסה או הוצאה. אין בדיקה האם שייכתי חשבון הוצאה למסמך של הכנסה והפוך 
יש מספר בדיקות שעבד עושה האם קיבלת את כולם מהדס?

**Comment by WizMotiSaadon** [comment]
הדס ביקשה ממני 
לבדוק מה יש בפונקציה
(Val)JurnalAcc2
של עבד

.ולעשות אותן בדיקות

אין בפונקציה 
(Val)JurnalAcc2

התייחסות לסוג המסמך

**Comment by wizayala** [comment]
או.קיי
אבדוק עם הדס מה לעשות עם זה

**Comment by wizayala** [comment]
הדס שלחה 
(val) stocktranstype
(val) stocktranstypefree

אולי טעיתי בשם של אקספרשן אבל הדס שלחה לך עוד שני קסצים שבהם מתבצעת בדיקה של ס"ת

**Comment by WizMotiSaadon** [comment]
> הדס שלחה
> (val) stocktranstype
> (val) stocktranstypefree
> 
> אולי טעיתי בשם של אקספרשן אבל הדס שלחה לך עוד שני קסצים שבהם מתבצעת בדיקה של ס"ת

כן, על זה אני עובד היום

**Comment by WizMotiSaadon** [comment]
> או.קיי
> אבדוק עם הדס מה לעשות עם זה

תיקנתי
mlayin.hds

**Comment by wizayala** [comment]
התיקון כולל את ההתיחסות לסוגי תנועה ?

**Comment by WizMotiSaadon** [comment]
> התיקון כולל את ההתיחסות לסוגי תנועה ?

כן

**Comment by WizMotiSaadon** [comment]
> מה התיקון שנעשה פה ?

אני ניגש לטבלה של החשבונות,
ואם ה
JURNALACC
לא נמצא שם אני מודיע
**חשבון נקלט הכנסות או הוצאות לא קיים בחברה הקולטת**

לאחר מכן אני בודק את השדה
שהוא
MAINACCOUNT = 7 or MAINACCOUNT = 10 or MAINACCOUNT = 9 or MAINACCOUNT = 27 or MAINACCOUNT = 28 or MAINACCOUNT = 8 or MAINACCOUNT = 3 or MAINACCOUNT = 44 or MAINACCOUNT = 3 or MAINACCOUNT = 46 or MAINACCOUNT = 47 or MAINACCOUNT = 48 or MAINACCOUNT = 49

ואם זה מספר אחר אז אני מודיע
**החשבון אינו מוגדר כחשבון הכנסות או הוצאות**

זה עונה לך על השאלה

**Comment by wizayala** [comment]
מוטי
הצלחתי להפיק חשבונית עם חשבונות ראשיים 1,2,4,5
אם כך משהו בבדיקה לא נכון

**Comment by wizayala** [comment]
תקין
