### ISSUE TITLE
יבוא חשבונות נוספים - שגויים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#145]
מתקבלת הודעת שגיאה של קליטת שדות נוספים לחשבונות, 

![image](https://user-images.githubusercontent.com/16633745/78137007-3af97a00-742d-11ea-84b3-c444cf604365.png)
לאחר אישור להמשך קליטה  מתקבלת הודעה נקלט בהצלחה כשכל הרשומות שגויות ואף רשומה לא נקלטה 

![image](https://user-images.githubusercontent.com/16633745/78137058-4fd60d80-742d-11ea-8b27-1df5aca04fb4.png)

**Comment by WizMotiSaadon** [comment]
תוקן
