### ISSUE TITLE
ייצוא קובץ חשבנות  - פעיל / לא פעיל

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#146]
האם אפשר להוסיף חיתוך לפי חשבון פעיל / לא פעיל
שדה
 accounts.dumi=3
זהו שדה של חשבון לא פעיל
 accounts.dumi=0
זהו שדה של חשבון פעיל

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
מוטי
האם אפשר שהבחירה תהיה כפי שיש באינדקס חשבונות 

![image](https://user-images.githubusercontent.com/16633745/78222326-ba3e8a80-74cd-11ea-8434-ea24c0920b7b.png)

**Comment by WizMotiSaadon** [comment]
אפשר אבל זה תכנות ממש  מסורבל

**Comment by wizayala** [comment]
האם אפשר שתיבות הסימון יהיו למטה ומעל לנמען 
ושברירת המחדל תהיה עם סימון רק בפעיל שהלקוח יצטרך לסמן "לא פעיל"

**Comment by WizMotiSaadon** [comment]
> האם אפשר שתיבות הסימון יהיו למטה ומעל לנמען
> ושברירת המחדל תהיה עם סימון רק בפעיל שהלקוח יצטרך לסמן "לא פעיל"

תוקן
accout.hds

**Comment by wizayala** [comment]
תודה
