### ISSUE TITLE
ייצוא חשבון - חשבונות מיוחדים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#147]

**Comment by wizayala** [comment]
יש שני חשבונות קבועים " ?  ",  "ללא"  הם מאופיינים ע"י השדה 
accounts.dumi=1
יש לא לייצא אותם

**Comment by WizMotiSaadon** [comment]
תוקן
accout.hds

**Comment by wizayala** [comment]
האם בכוונה השארת את השאילתא של 
select

**Comment by WizMotiSaadon** [comment]
כן, אפשר להוריד בקלות

**Comment by wizayala** [comment]
תוקן
