### ISSUE TITLE
יבוא מ xml  

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#15]
ביבוא מ
 XML 
אין המרה אוטומטית של תאריך מפורמט 
DD/MM/YYYY   
ל 
YYYY-MM-DD

**Comment by WizMotiSaadon** [comment]
[import_V2017_23_Februar_2016.zip](https://github.com/wizayala/Hashavsheva/files/144037/import_V2017_23_Februar_2016.zip)
[Uploading import_V2016_23_Februar_2016.zip…]()
תוקן
