### ISSUE TITLE
יבוא תנועות יומן- שגויים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#150]
ביבוא תנועות יומן קיבלתי הודעה על שגויים 
![image](https://user-images.githubusercontent.com/16633745/78217569-05a06b00-74c5-11ea-91ac-733a4658c707.png)

האם להמשיך בקליטה , בחרתי שלא, התקבלה הודעה לא נקלטה אף רשומה והחלון הבא הופיע 
![image](https://user-images.githubusercontent.com/16633745/78217610-1bae2b80-74c5-11ea-8820-510bcc99894a.png)

**Comment by WizMotiSaadon** [comment]
תוקן
jurnalin.hds

**Comment by wizayala** [comment]
150 תקין
