### ISSUE TITLE
יבוא פריטים / חשבונות נוספים - תחביר הודעה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#152]
מוטי
אפשר לרשום שדה תאריך לא תבנית/ פורמט/ מבנה תאריך, מה שתבחר אבל לא נראה לי שיש מילה כזאת  "תאריכי"

![image](https://user-images.githubusercontent.com/16633745/78218833-1baf2b00-74c7-11ea-91d5-b3ece632ecac.png)

**Comment by WizMotiSaadon** [comment]
extraItemin.hds

תוקן

**Comment by wizayala** [comment]
לא רואה שינוי ......
מה אמור להופיע עכשיו ?

**Comment by WizMotiSaadon** [comment]
החלפתי "מסוג תאריך"
