### ISSUE TITLE
יבוא פריטים / חשבונות - שדה ריק

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#153]
בקליטת הנוספים אני יכולה לבחור להתעלם מרשומות ריקות או 0 
למה ההודעה הזו מופיעה 

![image](https://user-images.githubusercontent.com/16633745/78219131-9a0bcd00-74c7-11ea-99e1-d433dba80f4a.png)
הרי השדה הזה ריק

**Comment by WizMotiSaadon** [comment]
תוקן
extraItemin.hds
extraHeshin.hds

**Comment by wizayala** [comment]
לא רואה כל שינוי 

![image](https://user-images.githubusercontent.com/16633745/78245408-1c0fec00-74f0-11ea-9ac7-771f704e8a38.png)

**Comment by WizMotiSaadon** [comment]
אולי תאתחלי חשבשבת

**Comment by wizayala** [comment]
אחלה
