### ISSUE TITLE
מסופון2 - משתמש

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#154]
בטבלת importlog 
שדה משתמש לא מתעדכן כאשר מבצעים קליטה מתוך מסופון 2 

![image](https://user-images.githubusercontent.com/16633745/78251610-45357a00-74fa-11ea-8046-40409290de77.png)

**Comment by WizMotiSaadon** [comment]
תוקן
imp_lib.hds

**Comment by wizayala** [comment]
מצויין
