### ISSUE TITLE
ייצוא חשבונות-  קובץ פרמטרים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#156]
האם יש סיבה לכך שקובץ הפרמטרים שנוצר אחרי שעשיתי ייצוא הוא מקודד 
utf-8 

![image](https://user-images.githubusercontent.com/16633745/78468588-0550db80-7722-11ea-97cf-0ff695bd8eb5.png)

**Comment by WizMotiSaadon** [comment]
אין סיבה,
האם זה מפריע למשהו?

**Comment by wizayala** [comment]
האם זה לא יכול לגרום לשיבוש בייבוא ?
מדוע ששני הקבצים שמיוצאים מאותה תוכנה לא יהיו מקודדים אותו הדבר ?

**Comment by WizMotiSaadon** [comment]
> האם זה לא יכול לגרום לשיבוש בייבוא ?

לא
