### ISSUE TITLE
יבוא נוספים - שדה תאריך

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#157]
כאשר מייבאים ריק בשדה תאריך יש לאפס את הרשומה ל  01/01/1997 מתקבלת הודעה שדה חייך להיות תאריכי

**Comment by WizMotiSaadon** [comment]
את יכולה לצלם לי את ההודעה?

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/78473564-5379d500-774a-11ea-9b9d-92b7682ba51d.png)


![image](https://user-images.githubusercontent.com/16633745/78473568-5d9bd380-774a-11ea-9747-90ab2adff556.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
לא חל שינוי לא מאפס תאריך

**Comment by WizMotiSaadon** [comment]
> לא חל שינוי לא מאפס תאריך

אני אמור למחוק את הרשומה
מהטבלה של השדות
הנוספים

האם זה נמחק?
אם את רוצה אני אתחבר

**Comment by wizayala** [comment]
מחשב מוכן


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
תוקן
extraitemin.hds

**Comment by wizayala** [comment]
תקין 
האם תקנת גם בחשבונות

**Comment by WizMotiSaadon** [comment]
לא,
האם גם שם יש בעיה?

ראיתי בעיה בקוד ביבוא פריטים אבל לא בחשבונות

**Comment by wizayala** [comment]
בחשבונות תקין
