### ISSUE TITLE
יבוא תנועות מלאי - הכנסה/ הוצאה מול סוג מסמך

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#158]
יש לוודא שחשבון ההכנסה מתאים לסוג המסמך :
חשבונות שהחשבון הראשי שלהם הוא :

Accounts.mainaccount = 7,10,27,8,11,44,47,48

הם חשבונות שמתאימים לסוג מסמך **הכנסה** : documentsdef.salesdoc=1

חשבונות שהחשבון הראשי שלהם הוא :

Accounts.mainaccount = 9,28,3,46,49

הם חשבונות שמתאימים לסוג מסמך **הוצאה** :  documentsdef.salesdoc=0

**Comment by WizMotiSaadon** [comment]
תיקנתי ליבוא מקובץ טקסט 
תריך לקלוט ממסופון 2 ולסמן יצירת תנועות מלאי

**Comment by wizayala** [comment]
האם זה בגלל קובץ מסופון 2 שאני לא לקחתי את האחרון שכולל את השינוי שעשית לקבצים עם תו מפריד ?

[cid:image001.png@01D60C18.F8F9FED0]


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
זו הודעה שאני מקבלת - ככל הנראה קשור לתיקון שלך למסופון 2 .
---------------------------
Error
---------------------------
חסר קובץ פרמטרים c:\קבצי ממשקים\תנועות מלאי\2019\2020\c:\קבצי ממשקים\תנועות מלאי\2019\2020\imovein.doc.Fictivi.prm
---------------------------
OK   
---------------------------

ובלי שום קשר יוצר תנועת מלאי אך לא יוצר תנועת הנה"ח שולחת לך קבצי 
err
prm2initxt.log

**Comment by WizMotiSaadon** [comment]
כן

**Comment by wizayala** [comment]
מה נסגר עם ההודעה של מסופון2 
אמרת לי לבדוק עם קובץ masofon2.exe  
האחרון וזו הההודעה 
---------------------------
Error
---------------------------
חסר קובץ פרמטרים c:\קבצי ממשקים\תנועות מלאי\2019\2020\c:\קבצי ממשקים\תנועות מלאי\2019\2020\imovein.doc .fictivi.prm
---------------------------
OK   
---------------------------

**Comment by wizayala** [comment]
תבטל את כל התיקון שעשית עם העניין של הפיקטיבי מיותר ואין שום צורך כרגע

**Comment by WizMotiSaadon** [comment]
> תבטל את כל התיקון שעשית עם העניין של הפיקטיבי מיותר ואין שום צורך כרגע

masofon2.exe
תוקן

**Comment by wizayala** [comment]
עדיין אותה הודעת שגיאה

**Comment by WizMotiSaadon** [comment]
אבל צריך להכין את הקובץ 
BAT 
מחדש
