### ISSUE TITLE
ייצוא תנועות הנהלת חשבונות- חלונות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#159]
ייצוא תנועות הנהלת חשבונות מחלונות לחלונות לא כולל את השדות הנוספים 
jurnatrans.extranum1,2
jurnaltrans.extradate1,2
jurnaltrans.documentid

**Comment by WizMotiSaadon** [comment]
תוקן
hsimp.exe
journalin.hds
journalout.hds
