### ISSUE TITLE
ייצוא תנועות מלאי חלונות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#160]
בייצוא תנועות מלאי חלונות אין את השדות החדשים 
stock.extranum1,2
stock.extradate1,2
stockmoves.extranum1,2
stockmoves,extradate1,2

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
ההודעה הבאה מתקבלת בייצוא תנועות 
---------------------------
HSD
---------------------------

Error in the Document - C:\2019\Imp_lib.hds.
Exception occurred.

Exception occurred.
Cannot perform this operation; features in this version are not available in databases with older formats.
Invoke(JetEngine,CompactDatabase,...)

Metod: CompactDatabase
---------------------------
התעלם  בטל  
---------------------------

**Comment by WizMotiSaadon** [comment]
תוקן

WizExport.mdb

**Comment by wizayala** [comment]
מעולה 
![image](https://user-images.githubusercontent.com/16633745/79457349-c6136c00-7ff8-11ea-92d9-b8fdb330dd73.png)
