### ISSUE TITLE
יבוא תנועות מלאי - חלונות 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#161]
מתקבלת ההודעה הבאה :
---------------------------
HSD
---------------------------

HSD Message
ODBC Error Requeary::[DB2][STOCKMOVES1]
Invalid column name 'Batch'.
Statement(s) could not be prepared.

---------------------------
התעלם  בטל  
---------------------------
---------------------------
HSD
---------------------------

Invalid column name 'Batch'.
Statement(s) could not be prepared.

---------------------------
אישור  
---------------------------

**Comment by wizayala** [comment]
זה קורה עם קובץ שעשיתי ייצוא שולחת לך קובץ קלט

**Comment by wizayala** [comment]
שמתי לך קובץ במחיצה 
H:\HomeFolder\Ayala\for moti

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds

**Comment by wizayala** [comment]
תוקן

**Comment by wizayala** [comment]
תקין
