### ISSUE TITLE
יבוא תנועות מלאי מחלונות - חשבון לא פעיל

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#162]
ביבוא תנועות מלאי מחלונות אנחנו חוסמים תנועות שהחשבון לא פעיל 
תיקנו את זה בשאר השיטות.

**Comment by WizMotiSaadon** [comment]
אז מה הבאג?

**Comment by wizayala** [comment]
צריך לא לחסום כפי שאנחנו עושים בשאר השיטות

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds
