### ISSUE TITLE
יבוא תנועות הנהלת חשבונות - חלונות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#163]
ביבוא תנועות הנהלת חשבונות מתקבלת ההודעה הבאה 
צריך להוסיף לטבלה שדה documentid 
![image](https://user-images.githubusercontent.com/16633745/79678551-6ccc5800-8205-11ea-8fd0-83901055c79e.png)

**Comment by WizMotiSaadon** [comment]
שלחתי מייל להדס שתוסיף בבייסיק

**Comment by wizayala** [comment]
בינתיים אני אוסיף ידנית 
תשלח לי איך הגדרת את השדה

**Comment by WizMotiSaadon** [comment]
ImportJournalHS.DocumentID     varchar(50)

**Comment by wizayala** [comment]
או.קיי הסתדר 
שאלה : תסתכל על התצוגה המקדימה של סוג מסמך למה זה לא 00 

![image](https://user-images.githubusercontent.com/16633745/79679917-c7b87c00-8212-11ea-8184-dfd584b9681e.png)

**Comment by WizMotiSaadon** [comment]
את יכולה לשלוח לי קבצי קלט?

**Comment by WizMotiSaadon** [comment]
תוקן

hsimp.exe

**Comment by wizayala** [comment]
אכן תוקן אך כעת יש תקלה אחרת ביבוא ותחת גיט נפרד
