### ISSUE TITLE
יבוא רכוש קבוע - מענק השקעה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#164]
יש לבטל את קישור שדה מענק השקעה ביבוא רכוש קבוע. 
מסתבר שאם יש את השדה הזה צריכים להיות שדות נלווים שכרגע לא מעוניינים להכניס אותם לממשק

![image](https://user-images.githubusercontent.com/16633745/79682324-f68e1c80-8229-11ea-8ac9-1bcbb2adef56.png)

**Comment by WizMotiSaadon** [comment]
odbcimp.exe
תוקן

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/79683598-f72bb080-8233-11ea-8650-52daae6c0cec.png)
אבל אם אני משתמשת ב 
wpr
  ישן ששם יש את הקישור של השדה אין הודעת שגיאה  
שולחת לך במייל את הקובץ קלט

**Comment by WizMotiSaadon** [comment]
odbcimp.exe
תוקן

**Comment by wizayala** [comment]
יופי עכשיו ביטל את הקישור 

![image](https://user-images.githubusercontent.com/16633745/79685681-43cab800-8243-11ea-9490-c9dafc7f80d2.png)
