### ISSUE TITLE
יבוא תנועות הנה"ח -  חלונות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#165]
ביבוא תנועות הנה"ח מחלונות מתקבלת ההודעה הבאה 
---------------------------
HSD
---------------------------

Error in SQL :The conversion of a varchar data type to a datetime data type resulted in an out-of-range value.
The statement has been terminated.

INSERT INTO JURNALTRANS (    TRANSCREDID  ,  CREDNAME  ,  TRANSDEBID ,  DEBNAME,  BATCHNO,  DESCRIPTION,  REFERANCE,  REF2,  TRANSTYPE,  CURRENCYCODE,  VALUEDATE,  DUEDATE,  STATUS,  CHANGABLE,  COSTCODE,  DIFFER,  CREDITTERMSHARE,  SUF,  SUFDLR,  BACHNO,  LOCKINGIS,  TYPE,  REF3,  DATF3,  BRANCH,                                                   KUPANUM,                                                    EXFILE,                                                   DET2,                                                   DETAILS,  OSEK874,  EXTRANUM1,  EXTRANUM2,  EXTRADATE1,  EXTRADATE2,  DOCUMENTID,  QUANT,BDATE,HOUR                                                        )    VALUES (          '40002'   ,          'הכנסות משרות'   ,             '30001',             'כיתנס',  245  ,   '',    7845,    7845,    'ח',     '$',     '03/31/2020',     '03/31/2020',     2,     1,     '',    0,   0 ,   2.0,   0.0,   0,   4,   0,   0,   '03/31/2020',   2,            0,             '15.jpg',            '',            '',  '911223389',  0,  0,  '31/03/2020',  '31/03/2020',  9,      0.0,CONVERT(VARCHAR(10), GETDATE(),120) ,DATEPART(HOUR, GETDATE())*60  +  DATEPART(MINUTE, GETDATE())  )
---------------------------
אישור  
---------------------------
---------------------------
HSD
---------------------------

The conversion of a varchar data type to a datetime data type resulted in an out-of-range value.
The statement has been terminated.

---------------------------
אישור  
---------------------------

**Comment by WizMotiSaadon** [comment]
תוקן
jurnalin.hds

**Comment by wizayala** [comment]
תקין
