### ISSUE TITLE
יבוא חשבונות פוטנציאליים - סימון אנסי

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#166]
ביבוא חשבונות פוטנציאלים יש לי קובץ מקודד עם 
windows1255
סימון 
ansi
תצוגה מקדימה הופכת מלל ואז נקלט טוב
ביטול סימון
 ansi
 תצוגה מקדימה רואים טוב אך קליטה משובשת

![image](https://user-images.githubusercontent.com/16633745/79684489-6f957000-823a-11ea-8529-34245644f601.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
תקין
