### ISSUE TITLE
יבוא קוד תמחיר - שינוי שם קובץ

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#167]
ביבוא קובץ קוד תמחיר קובץ טקסט , יש לי שגויים בכל הקובץ אני מקבלת הודעה שאף רשומה לא נקלטה אך בפועל נעשה שינוי שם של קובץ ל bak

**Comment by WizMotiSaadon** [comment]
לא מצליח לשחזר את הבעיה

**Comment by wizayala** [comment]
איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
טעות שלי
