### ISSUE TITLE
יבוא תנועות קופה - שדות נוספים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#169]
האם תוכל להוסיף שדות של extradate1,2   extranum1'2  ליבוא תנועות קופה
אני משערת שגם זה שינוי db  לכן צריך להעביר להדס שוב

**Comment by WizMotiSaadon** [comment]
תוקן
kupain.hds
prm2ini.dll
odbcimp.dll

**Comment by wizayala** [comment]
שדה מספר נוסף 2 ( extranum2) מקבל ערך של (extranum1)

![image](https://user-images.githubusercontent.com/16633745/79936882-39860500-8461-11ea-8a2d-d5e3214178ef.png)
![image](https://user-images.githubusercontent.com/16633745/79936892-3f7be600-8461-11ea-9837-9de967b95e26.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
תקין
