### ISSUE TITLE
יבוא תנועות קופה - עברית 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#170]
בכל הממשקים שינינו את הכפתור של סימון (ansi) לכתב ראי . האם אפשר לדאוג לזה גם ביבוא תנועות קופה
![image](https://user-images.githubusercontent.com/16633745/79821892-936ec800-8398-11ea-9366-73a94fd4e4a1.png)

**Comment by WizMotiSaadon** [comment]
kupain.hds
תוקן
