### ISSUE TITLE
יבוא מחירים מיוחדים - עברית

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#171]
האם אפשר לשנות כפתור (ansi) לכתב ראי כפי שעשינו בכל הממשקים ?

![image](https://user-images.githubusercontent.com/16633745/79821985-d2048280-8398-11ea-91d0-cc7ac7428c6c.png)

**Comment by WizMotiSaadon** [comment]
תוקן
pricein.hds

**Comment by wizayala** [comment]
לא רואה שינוי בתצוגה מקדימה בין כתב ראי וללא סימון כתב ראי

**Comment by WizMotiSaadon** [comment]
תוקן
import_v.exe

**Comment by wizayala** [comment]
תקין
