### ISSUE TITLE
יבוא תנועות קופה - עברית

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#172]
מוטי
בתצוגה מקדימה רואים ש"ח אך מתקבלת הודעת שגיאה 
![image](https://user-images.githubusercontent.com/16633745/79876101-45d37900-83f3-11ea-8112-6fbb0626f1d3.png)

![image](https://user-images.githubusercontent.com/16633745/79876122-4bc95a00-83f3-11ea-8a75-9a73930a584c.png)

אם אני אסמן כתב ראי נקלט טוב תצוגה מקדימה נראה טוב גם כן .
שולחת לך במייל נפרד קבצי קלט

**Comment by WizMotiSaadon** [comment]
תוקן
import_v.exe

**Comment by wizayala** [comment]
לא רואה שינוי 

![image](https://user-images.githubusercontent.com/16633745/79936523-64bc2480-8460-11ea-84bf-2fb3b1087d58.png)

**Comment by WizMotiSaadon** [comment]
תוקן 
kupain.hds
