### ISSUE TITLE
יבוא מספרים חליפיים - אייקונים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#174]
יש לתקן את אייקון דלת ולהזיז כפתור תצוגה מקדימה כדי ששם הקובץ יראה כולו

![image](https://user-images.githubusercontent.com/16633745/79952186-b4134c80-8482-11ea-9937-2d7fc86c4ae7.png)

**Comment by WizMotiSaadon** [comment]
איך הדלת עכשיו?

**Comment by wizayala** [comment]
נראה טוב יותר

![image](https://user-images.githubusercontent.com/16633745/79960165-c21a9a80-848d-11ea-8147-677714f72e00.png)
