### ISSUE TITLE
יבוא מחירים מיוחדים - אייקונים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#175]
יש להזיז כפתור תצוגה מקדימה כדי ששם הקובץ יראה 

![image](https://user-images.githubusercontent.com/16633745/79952301-e02ecd80-8482-11ea-9f07-91e21ed2709f.png)

**Comment by WizMotiSaadon** [comment]
תוקן, איך זה?

**Comment by wizayala** [comment]
סבבה
![image](https://user-images.githubusercontent.com/16633745/79972593-df0b9980-849e-11ea-8a83-82fd7a80394b.png)
