### ISSUE TITLE
ייצוא תנועות שירות - אייקונים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#177]
לתקן כפתור נמענים ל +

![image](https://user-images.githubusercontent.com/16633745/79952592-55020780-8483-11ea-9478-c16519fc8c10.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/79978828-357dd580-84a9-11ea-9b79-0777085f5011.png)
