### ISSUE TITLE
יבוא פריטי - נתוני אופטומיזציה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#179]
השדות של נתוני אופטומיזציה לא נקלטים 
למעט זמן ייצור אספקה, שבו עשינו תיקון לא מזמן , האם משהו השתבש?
![image](https://user-images.githubusercontent.com/16633745/79970931-57bd2680-849c-11ea-91fb-2a86ab178f2b.png)

**Comment by WizMotiSaadon** [comment]
נראה שבמעבר לגרסה מהירה שחכתי חלק מהשדות

**Comment by wizayala** [comment]
אלו הם שדות שהיו עוד לפני הגרסה

**Comment by WizMotiSaadon** [comment]
> השדות של נתוני אופטומיזציה לא נקלטים
> למעט זמן ייצור אספקה, שבו עשינו תיקון לא מזמן , האם משהו השתבש?
> ![image](https://user-images.githubusercontent.com/16633745/79970931-57bd2680-849c-11ea-91fb-2a86ab178f2b.png)

תוקן

**Comment by wizayala** [comment]
תיקון
