### ISSUE TITLE
stock. EvalCurrency יבוא שדה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#18]
לגרסה הבאה מבקשים להוסיף לממשק תנועות מלאי  ותנועות מלאי זמני שדה של מטבע לשערוך
 stock. EvalCurrency ( כמובן שצריכה להתבצע בדיקה שקוד מטבע קיים בטבלת מטבעות)

**Comment by WizMotiSaadon** [comment]
מחכה לעדכון 
DB

**Comment by wizayala** [comment]
stock. EvalCurrency למה , השדה הזה קיים

**Comment by WizMotiSaadon** [comment]
ALTER TABLE ImportStock ADD ImportStock.EvalCurrency varchar(5)

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/73171817-4fa65280-410a-11ea-9220-a1260b10ebe4.png)

**Comment by wizayala** [comment]
זו ההודעה שאני מקבלת שהרצתי את השורה הזו בשאילתא

[cid:image001.png@01D5D517.7128EFD0]


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
אז תתקני , מה הבעיה

**Comment by wizayala** [comment]
זו ההודעה שאני מקבלת לאחר שהרצתי את השאילתא

**Comment by wizayala** [comment]
תודה רבה


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/73719789-1a60bc80-4729-11ea-9522-855af2c35505.png)

**Comment by WizMotiSaadon** [comment]
> לגרסה הבאה מבקשים להוסיף לממשק תנועות מלאי ותנועות מלאי זמני שדה של מטבע לשערוך
> stock. EvalCurrency ( כמובן שצריכה להתבצע בדיקה שקוד מטבע קיים בטבלת מטבעות)

תיקנתי

**Comment by wizayala** [comment]
עדיין זו ההודעה בכניסה לייבוא תנועות מלאי

![image](https://user-images.githubusercontent.com/16633745/74138235-e9d1c480-4bf9-11ea-9275-6fcc442c9f50.png)

**Comment by wizayala** [comment]
יש להוסיף את השדה מטבע לשערוך באפשרויות של קישור שדות

**Comment by WizMotiSaadon** [comment]
![image](https://user-images.githubusercontent.com/10919353/74154160-ca975f00-4c1a-11ea-98a1-0ef13c10b846.png)

**Comment by wizayala** [comment]
stock. EvalCurrency  נכון בטבלת המטבע לא מתעדכן 

![image](https://user-images.githubusercontent.com/16633745/74218509-f1a16f80-4cb2-11ea-9eb4-8550e36c2251.png)

למרות שנכנס הערך הנכון לטבלת importstock 
![image](https://user-images.githubusercontent.com/16633745/74218636-37f6ce80-4cb3-11ea-8808-ffe5a760f3b6.png)

אך לא הערך הנכון לטבלת stock
![image](https://user-images.githubusercontent.com/16633745/74218681-4c3acb80-4cb3-11ea-9bfd-27bbb63222ee.png)

**Comment by WizMotiSaadon** [comment]
תיקנתי

**Comment by wizayala** [comment]
תקין
