### ISSUE TITLE
יבוא מספרים חליפיים - שם חליפי

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#180]
בקליטת קובץ בשיטת (odbc) שם חליפי נקלט הפוך

![image](https://user-images.githubusercontent.com/16633745/80099972-f8344900-8577-11ea-9c3d-3ea1072de3f5.png)

**Comment by WizMotiSaadon** [comment]
?אפשר קבצי קלט

**Comment by wizayala** [comment]
איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
שלחתי לך קבצי קלט , אך אני רואה שהבעיה נפתרה
