### ISSUE TITLE
ייצוא חשבונות - מזהה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#181]
לבקשתה של אביבית יש לשנות את הכיתוב על המסך במקום (id) שיהיה רשום מזהה 

![image](https://user-images.githubusercontent.com/16633745/80100965-688f9a00-8579-11ea-8753-aff086da669c.png)

**Comment by WizMotiSaadon** [comment]
AccOut.hds

**Comment by wizayala** [comment]
מצויין
