### ISSUE TITLE
יבוא תנועות מלאי - רישום תנועה הנה"ח 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#183]
קלטתי קובץ ממשק של תנועות מלאי  במסופון 2 , בקשתי שייצור תנועות הנה"ח לא נוצרה תנועה בהנה"ח לא מקובץ טקסט ולא מקובץ odbc . קובץ err  נרשם נקלט בהצלחה 
**ללא קישור** של הכנסות או ס"ת 

[AYALAWIN10_10680.992.bat] --->test2019 -6.4 -c:\קבצי ממשקים\תנועות מלאי\odbc\992.wpr - - - - -1 -AYALAWIN7 -0 -0 -

[23/04/20 18:18:25] "c:\קבצי ממשקים\תנועות מלאי\odbc\992.wpr":
[23/04/20 18:18:33] קליטת תנועות מלאי הסתיימה בהצלחה
[23/04/20 18:18:33] =============================
[23/04/20 18:18:33]

**Comment by WizMotiSaadon** [comment]
אולי תקלטי לזמני
ואז תפיקי,
?את מקבלת רמז למה אין תנועות יומן

באופן כללי
אני לא מפיק ,
אולי תשאלי את עבד

**Comment by wizayala** [comment]
או.קיי
שכחתי שדיברנו על זה בעבר
תודה


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
סגרתי , אמשיך מול עבד
