### ISSUE TITLE
יבוא קודי מיון

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#184]
על שרת 

ביבוא קודי מיון חשבונות מקבלת ההודעה הבאה :

![image](https://user-images.githubusercontent.com/16633745/80307858-6ffeaf80-87d4-11ea-8076-b2fbda7e607d.png)

**Comment by wizayala** [comment]
אצלי זה לא קורה ושלחתי לך קובץ wizimport.log

**Comment by WizMotiSaadon** [comment]
ההודעה אומרת שאת מנסה לפתוח קובץ אקסל מגרסה של אופיס
שאין במחשב את הדרייברים המתאימים

**Comment by WizMotiSaadon** [comment]
2020-04-26 15:37:35  odbcimp.exe Error opening imported DB, 
m_db.Open(NULL,FALSE,FALSE,ODBC;DSN=Excel Files;DBQ=C:\קבצי ממשקים\קודי מיון\kodacc.xlsx;DefaultDir=C:\קבצי ממשקים\קודי מיון;DriverId=1046;MaxBufferSize=2048;PageTimeout=5;) :The specified DSN contains an architecture mismatch between the Driver and Application

**Comment by wizayala** [comment]
כן הצלחתי לפתוח את הגיליון בשרת 
לאחר שיצרתי wpr  מחדש הבעיה הסתדרה
