### ISSUE TITLE
יבוא תנועות מלאי - שדה לא מתאים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#185]
איך אני יכולה להבין מתוך הודעת השגיאה איזה שדה אינו בפורמט הנכון ?

---------------------------
HSD
---------------------------

Error in SQL :The conversion of a varchar data type to a datetime data type resulted in an out-of-range value.
The statement has been terminated.

INSERT INTO STOCKMOVES (DUEDATE,DETAILS,WAREHOUSE,EXTRANUM1,EXTRANUM2,EXTRADATE1,EXTRADATE2,  EXFILE,INSTANCE,BATCHNUM,LOCALIZATION,WARRENTYDATE,CANCELDATE,EXPIREDATE, BASEDATE,STOCKID,                                     ITEMKEY,                                          AGENT,    REFERENCE,                                     PRICE,OPRICE,                                     QUANTITY,ORATE,                              DISCOUNTPRC,                                   CURRENCYCODE,RATE,                                                    DOCUMENTID,   VATEXAMPT,PACKS,ITEMNAME,UNIT,SALETAXPRC,ALTERNUM,COMMISIONPRC,PURCHQUANTITY,SUPPLYQUANTITY,BRANCHID,LINENUM,BASELINENUM,EXTRATEXT1,EXTRATEXT2,EXTRASUM1,EXTRASUM2,BASEMOVEID,BASEDOCTYPE,COSTCODE,ALTERNAME,JURNALACC)  VALUES                            ('00/00/00','detail',55,66,77.77,'00/00/00','01/01/2022',  '','','','','1980-01-01','1/1/1999',  '04/27/2020',  '04/27/2020',9897,'7003',0,0,3.500000000,3.500000000,10.000000000,1,0,  'ש"ח',        1,9,0,0,'כוסות שתיה חמה','',0,'',0,10.000000000,10.000000000,1,0,0,'','',0,0,0,0,'','',''   );
---------------------------
אישור  
---------------------------

**Comment by WizMotiSaadon** [comment]
בודקים את כל התאריכים ,
איזה תאריך לא הגיוני,

מצאתי
'00/00/00'
duedate

**Comment by wizayala** [comment]
אפשר הודעה מתאימה כמו תאריך שגוי

**Comment by wizayala** [comment]
למה מופיע גם 00/00/00 בעמודת שגיאה 

![image](https://user-images.githubusercontent.com/16633745/80360319-d2fd4e80-8887-11ea-9d1b-51a50ff0ba0a.png)

**Comment by WizMotiSaadon** [comment]
תוקן
imp_lib.hds

**Comment by wizayala** [comment]
לא רואה שינוי 

![image](https://user-images.githubusercontent.com/16633745/80452948-0693b380-8930-11ea-96dc-0c324435e5fd.png)

**Comment by WizMotiSaadon** [comment]
אני שם את התוכן המקורי במקום 
00/00/00

אבל זה עטוף ב
 <>

בשביל שלא יכנס בטעות ל טבלה

**Comment by wizayala** [comment]
טוב לא משנה 
לא קריטי
