### ISSUE TITLE
יבוא נתונים נוספים מלאי- הודעות 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#186]
יש הודעות שצריך להוריד
---------------------------
HSD
---------------------------

sql before = #update stock,ExportAdress ,importstock  set ExportAdress.ExpAddress = importstock.EAEXPADDRESS   where   (                           LEN( ISNULL(importstock.EAEXPADDRESS,'') )>0    And (LEN(ISNULL(ExportAdress.ExpAddress,'') )=0 or 1=1)      And stock.docnumber = importstock.docnumber     And stock.ID = ExportAdress.STOCKID     And stock.status = 1     And stock.ID = importstock.STOCKID     And LEN(ISNULL(importstock.ErrorMessage,''))=0      )#
---------------------------
אישור  
---------------------------

**Comment by WizMotiSaadon** [comment]
stockheaderin.hds

תוקן

**Comment by wizayala** [comment]
אני רואה הודעה :
למה 00/00/00 מופיעים גם בעמודה  שגיאה 

![image](https://user-images.githubusercontent.com/16633745/80360089-80bc2d80-8887-11ea-8a76-6da6c77af857.png)

**Comment by wizayala** [comment]
o/k
