### ISSUE TITLE
יבוא מספרים חליפיים - כתב ראי

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#187]
האם יש אפשרות שתשנה גם במספרים חליפים מ(ansi) לכתב ראי 

![image](https://user-images.githubusercontent.com/16633745/80357022-ff629c00-8882-11ea-84a9-c266be5e9d4e.png)

**Comment by wizayala** [comment]
וכמובן יש מלבד שינוי הכפתור לוודא שנקלט כהלכה. קובץ שהוא תקין עם עברית תקינה (לא כתב ראי ) נקלט הפוך

![image](https://user-images.githubusercontent.com/16633745/80358494-3174fd80-8885-11ea-9601-390d9736f984.png)

**Comment by WizMotiSaadon** [comment]
תוקן
alterin.hds

**Comment by wizayala** [comment]
עדיין נקלט הפוך
שולחת לך קבצי קלט

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/80456196-db13c780-8935-11ea-966f-4adca5aa5b91.png)
מצויין
