### ISSUE TITLE
יבוא מחירים מיוחדים - כתב ראי 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#188]
ביבוא מחירים מיוחדים קובץ עם עברית תקינה , נקלט עם עברית הפוכה. צריך לתקן את זה 

![image](https://user-images.githubusercontent.com/16633745/80364564-d21beb00-888e-11ea-9c6b-f3bb6f7410e1.png)

**Comment by WizMotiSaadon** [comment]
alterin.hds
תוקן

**Comment by wizayala** [comment]
תקין
