### ISSUE TITLE
מחירים מיוחדים- מפתח חשבון ריק

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#19]
לתרגם את null  = ללא

**Comment by WizMotiSaadon** [comment]
"את מתכוונת שם נקלט מפתח חשבון ריק אני צריך להשים שם "ללא
?

**Comment by wizayala** [comment]
שלחתי מייל עם כל השתלשלות של התכתובות עם תמונה של הודעת שגיאה


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
אני שותל עכשיו "ללא" בעצמי אם המפתח חשבון ריק

**Comment by wizayala** [comment]
מתקבלת הודעה שלא ניתן לקלוט "לא קיים מחיר לכמות מינימום" , כאשר אותה רשומה אם אני שותלת מפתח "ללא" במקום null  או ריק  הקובץ נקלט ללא כל בעיה

![image](https://user-images.githubusercontent.com/16633745/69877902-11d4ab80-12cc-11ea-993a-f6a5cb5503ce.png)

**Comment by wizayala** [comment]
לא רואה שאתה שותל. מתקבלת אותה הודעת שגיאה
אם תרצה קבצי קלט לדוגמא שאשלח אמור לי


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
תיקנתי, איך עכשיו?

**Comment by wizayala** [comment]
תקין


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
תקין , האם התיקון הוא גם לגרסת לקוחות ?

**Comment by WizMotiSaadon** [comment]
כן
