### ISSUE TITLE
יבוא תנועות מלאי - מטבע מסמך

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#190]
יש לאפשר קליטה של מטבע מסמך "ש" . 
מתקבלת הודעה מטבע מוביל צריך להיות זהה למטבע בהגדרות חברה
אם מופיע במטבע ש"ח אין בעיה.

**Comment by WizMotiSaadon** [comment]
אני רואה לפי הקוד שאני מחליף רק ב 
יבוא מטקסט

**Comment by WizMotiSaadon** [comment]
תוקן mlayin.hds
