### ISSUE TITLE
מסופון 2 - מסמכים בזמני

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#191]
מספון2 : ביבוא תנועות מלאי לזמני לא מתבצעת שליפה של מחיר למרות שמסומן שליפת מחיר 
מתוך התוכנה מבצע שליפה מסופון 2 לא מבצע שליפה

**Comment by WizMotiSaadon** [comment]
הוספתי לוגים
mlayin.hds

**Comment by wizayala** [comment]
למה הכוונה ?


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
הכוונה שתקלטי שוב ממסופון
ןאז תשלחי אלי את הקובץ לוג
WizImport.log

ואני יסתכל להבין מה השתבש

**Comment by wizayala** [comment]
מוטי
אני לא מצליחה להתחבר לשרת בתל אביב
תוכל להעביר לי את הקובץ כדי שאבדוק


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
נשלחו קבצים

**Comment by wizayala** [comment]
תוקן
