### ISSUE TITLE
תנועות הנהלת חשבונות - שיטה גמישה 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#192]
קבצי קלט לא נקלטים, על פניו נראים תקינים. לעומת זאת קבצי קלט אחחרים נקלטים כהלכה.
שלחתי לך במייל נפרד קבצי קלט וקובץ לוג

**Comment by WizMotiSaadon** [comment]
תוקן

JURNALIN.HDS
WizImportLogic.dll
WizImportMySql.dll

**Comment by wizayala** [comment]
מה הייתה הבעיה ?



איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
לא בדקתי מה אומרת מחרוזת השגיאות

**Comment by wizayala** [comment]
לא הבנתי.
מה לגבי ס"ת , למה תצוגה נראית X ובפועל נקלט Y ?


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
אה, זו בעיה אחרת,
עדיין לא סיימתי לבדוק

**Comment by WizMotiSaadon** [comment]
זה בגלל המקף המוזר, היו קבצים שמקום מקף רגיל היה מקף מוזר, אבל בקידוד של אסקיי זה בעצם צדיק...

בכל אופן תוקן

**Comment by wizayala** [comment]
האם אפשר הודעה פשוטה יותר
רק על ס" ת

---------------------------
HSD
---------------------------

WizImportLogic.ImportData,ImportJournals2 יבוא נכשל Import Failed
Function =   pIJournalData->Update
Exeption =   Import Failed
Function = 
Exeption =  שדה סוג תנועה עד 3 תווים   strField = #487   חשצ#
---------------------------
אישור  
---------------------------

**Comment by wizayala** [comment]
ההודעה לא ברורה , מופיע חשצ - והודעה שס"ת יכול להיות רק 3 תווים .
עדיף לרשום הודעה פשוטה - קובץ פרמטרים - שדה ס"ת שגוי

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
תקין - תודה
