### ISSUE TITLE
יבוא מחירי- תיקון קוסמטי

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#194]
האם אפשר למחוק את המלל זיהוי לפי כותרת ... ולהשאיר בסוגריים (תאריך תחילת תוקף+ חשבון+ פריט)

![image](https://user-images.githubusercontent.com/16633745/81691886-3e3d4800-9466-11ea-84a7-22cfb13fd921.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
תקין
