### ISSUE TITLE
ברירת מחדל עבור מטבע לשיערוך

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#195]
מוטי, ביבוא תנועות מלאי מטבע לשערוך 
ברירת מחדל של השדה
( stock.evalcurrency ) 
צריכה להיות ש"ח במסמכי יבוא וייצוא .
מסמכי יבוא וייצוא ניתן לזהות אותם לפי 
( documentsdef.exportdoc = 1 ) 
למעט סוג מסמך 142

**Comment by wizayala** [comment]
מוטי
התקלה הזו הגיע מלקוח ששדרג למהדורה 2020
אשמח אם תוכל לטפל בזה קודם

**Comment by WizMotiSaadon** [comment]
על מה הלקוח מתלונן בדיוק?
יש איזו הודעה לא נכונה שהוא מקבל?
או שהוא מצפה לקבל הודעה ולא קיבל?

**Comment by wizayala** [comment]
כשאני קולטת לזמני , נקלט לי מטבע לשערוך ומטבע המסמך $ ואין לי אפשרות לשנות. אז ראשית צריכה להתקבל הודעה בקליטה :
---------------------------
HSD
---------------------------

מטבע מוביל ומטבע לשערוך חייבים להיות שונים
---------------------------
אישור  
---------------------------

**Comment by wizayala** [comment]
לגבי הפקה של מסמך שנקלט בצורה שגויה לזמני בשלב ההפקה מהזמני מתקבלת הודעה כזו :
---------------------------
HSD
---------------------------

חלה תקלה בחישוב סהכ בתוך שורות המסמך
---------------------------
אישור  
---------------------------

**Comment by wizayala** [comment]
זו ההודעה שאני מקבלת כשאני מנסה לקלוט את המסמך 

---------------------------
HSD
---------------------------

חלה תקלה בחישוב סהכ בתוך שורות המסמך
---------------------------
אישור  
---------------------------

**Comment by wizayala** [comment]
דבר איתי כשתקבל את הקבצים.
לא היה מענה בשלוחה שלך


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
מדוע שער המסמך נקלט 1 ?
כאשר אני מקשרת שער אחר
שולחת לך בנפרד קבצים

**Comment by wizayala** [comment]
מדוע שער המסמך הוא 1 אם אני קלטתי שער אחר?

איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
זה קשור לבאג המקורי
שהוא שזה באג חדש?

**Comment by WizMotiSaadon** [comment]
> מדוע שער המסמך נקלט 1 ?
> כאשר אני מקשרת שער אחר
> שולחת לך בנפרד קבצים

זה קשור לבאג המקורי
שהוא שזה באג חדש?

**Comment by wizayala** [comment]
ייתכן וזה חדש
לרשום לך בגיט נפרד ?


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
> ייתכן וזה חדש לרשום לך בגיט נפרד ?ת
כן תודה
