### ISSUE TITLE
מטבע המסמך ומטבע שיערוך לא יכולים להיות זהים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#196]
במידה ומקשרים את שדה מטבע שערוך יש לקבל את המטבע ולוודא שהוא שונה ממטבע המסמך 
stock.currency 
במידה והמטבע זהה יש לתת הודעה :
**מטבע מוביל ומטבע לשערוך חייבים להיות שונים**

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds

**Comment by wizayala** [comment]
מוטי
שים לב שבדיקת מטבע ומטבע לשיערוך צריכה להיות גם במסמכים שקליים 
שלחתי לך קבצי קלט , תוכל לייצר תקלה כזו 

![image](https://user-images.githubusercontent.com/16633745/82138718-39dcaa80-982b-11ea-9985-a2b39bb349db.png)

**Comment by wizayala** [comment]
תקין
