### ISSUE TITLE
יבוא תנועות מלאי - שער מסמך

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#197]
במסמכי יבוא וייצוא 
מדוע שער המסמך נקלט 1 ?
כאשר אני מקשרת שער אחר
שולחת לך בנפרד קבצים

**Comment by WizMotiSaadon** [comment]
לא קיבלתי את הקבצים

**Comment by wizayala** [comment]
יש שלושה שדות של שער 

לפי הטבלה :
stock.Rate  - שער לשערוך בהנה"ח 
stock.Mainrate  - שער למטבע המסמך
stockmoves.rate - שער בתנועה

**Comment by wizayala** [comment]
במסמכי יבוא וייצוא שדה rate =1      שדה mainrate= 3.5  שזה השער לשערוך
הנתון לשערוך יכנס אך ורק מתוך שער המסמך. 
שדה "שער" לא רלוונטי  למסמכי יבוא וייצוא

**Comment by WizMotiSaadon** [comment]
אז מה לתקן?

**Comment by wizayala** [comment]
כבר מעבירה לך מסודר ,מה נותר לעשות בעניין זה


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>
