### ISSUE TITLE
יבוא תנועות מלאי - כותרת "שער" 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#198]
האם תוכל לתקן את שם השדה "שער" ל "שער לשערוך" 
להוסיף בתאור שערוך משקלים בלבד

![image](https://user-images.githubusercontent.com/16633745/81936301-b50b4a00-95fa-11ea-8bbb-c138a7e833df.png)

**Comment by WizMotiSaadon** [comment]
תוקן
odbcimp.exe

**Comment by wizayala** [comment]
תודה
