### ISSUE TITLE
עיגול לשדה כמות בסגירה של מסמך על גבי מסמך

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#2]
ביבוא תנועות מלאי מתבצע עיגול לשדה כמות בסגירה של מסמך על גבי מסמך  זה קןרה גם ביבוא מאו.די.בי.סי

**Comment by WizMotiSaadon** [comment]
תוקן
[import_V2016_24_January_2016.zip](https://github.com/wizayala/Hashavsheva/files/102246/import_V2016_24_January_2016.zip)
[import_V2017_24_January_2015.zip](https://github.com/wizayala/Hashavsheva/files/102247/import_V2017_24_January_2015.zip)

**Comment by wizayala** [comment]
לא רואה תיקון לבעיה

**Comment by WizMotiSaadon** [comment]
[import_V2016_24_January_2016.zip](https://github.com/wizayala/Hashavsheva/files/102289/import_V2016_24_January_2016.zip)
[import_V2017_24_January_2015.zip](https://github.com/wizayala/Hashavsheva/files/102288/import_V2017_24_January_2015.zip)
