### ISSUE TITLE
ספירת מלאי - עץ הרכבה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#20]
אנחנו מאפשרים לקלוט ממשק עם פריט אב מסוג עץ  הרכבה הכוונה פריט שמוגדר אב tress.levef=0  וגם trees.treetype=1 
כמו מפתח פריט = שולחן
יש לתת הודעת שגיאה " לא ניתן לקלוט ספירת מלאי לעץ הרכבה"

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
תקין
