### ISSUE TITLE
יבוא תנועות מלאי - הודעת שגיאה מטבע מסמך

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#201]
ביבוא של מסמך חשבונית ייצוא סוכן, מתקבלת הודעה שהמטבעות צריכים להיות שונים אחד מן השני והם אכן שונים . שולחת לך קבצי קלט במייל נפרד 

![image](https://user-images.githubusercontent.com/16633745/82137439-ae5e1c00-9820-11ea-9991-679943f68664.png)

**Comment by wizayala** [comment]
הייתי מצפה לקבל הודעת שגיאה דווקא בשורה השנייה של הקלט ולא הראשונה

**Comment by WizMotiSaadon** [comment]
אני צריך לראות מה קישרת

**Comment by wizayala** [comment]
שלחתי לך קבצי קלט


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
https://github.com/wizayala/Hashavsheva/issues/196#issuecomment-629757412

**Comment by wizayala** [comment]
תקין
