### ISSUE TITLE
יבוא פריטים - שדה תאריך

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#202]
מוטי
ביבוא פריטים אני מייבאת תאריך נוסף אני מקבלת הודעת שגיאה
---------------------------
HSD
---------------------------

Error in SQL :Conversion failed when converting the varchar value 'EXTRA_24' to data type int.

INSERT INTO EXTRADATES(DATF,KEF,DATFID,ITEMFLAG)  SELECT  TOP 1 WITH TIES IMPORTITEM.EXTRADATE,IMPORTITEM.ITEMKEY,IMPORTITEM.EXTRADATEID,1  FROM IMPORTITEM  WHERE IMPORTITEM.ERRORMESSAGE IS NULL AND  DATALENGTH(IMPORTITEM.EXTRADATE)>0 AND  NOT EXISTS (SELECT ID FROM EXTRADATES WHERE EXTRADATES.KEF=IMPORTITEM.ITEMKEY AND EXTRADATES.DATFID = IMPORTITEM.EXTRADATEID AND EXTRADATES.ITEMFLAG = 1 )  ORDER BY ROW_NUMBER() OVER (PARTITION BY IMPORTITEM.ITEMKEY,EXTRADATEID ORDER BY IMPORTITEM.ID DESC)
---------------------------
אישור  
---------------------------
---------------------------
HSD
---------------------------

Conversion failed when converting the varchar value 'EXTRA_24' to data type int.

---------------------------
אישור  
---------------------------

**Comment by wizayala** [comment]
זה קורה אצלי , מדובר על נתון בפורמט תאריך
זה לא קורה כאשר אני מקשרת לתאריך נוסף 4
האם זו בעיה של נוספים מעבר ל 8 הקיימים ?

**Comment by WizMotiSaadon** [comment]
HSImportItem29.sql

תוקן

**Comment by wizayala** [comment]
האם השאילתא הזו רלוונטית לגרסה הקודמת 2018 ?


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
כן, רלוונטית

**Comment by wizayala** [comment]
לא מתאים בגלל השדה החדש של שקיל
לא נורא ,
אל תתקן

[cid:image001.png@01D62D1A.3B9A35D0]



איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
האם ניתן להוציא תיקון לגרסת 2018 ?


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
כן בטח

כבר מטפל

**Comment by WizMotiSaadon** [comment]
> האם ניתן להוציא תיקון לגרסת 2018 ?

שמתי במחיצה
HSImportItem29 - V2018.sql

**Comment by wizayala** [comment]
תודה 
תקין לשתי הגרסאות
