### ISSUE TITLE
יבוא תנועות קופה - שדה ת.ז 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#204]
מוטי , ביבוא תנועות קופה , אני מקשרת שדה ת.ז ואני לא רואה שהוא נכנס לטבלה 
שולחת לך דוגמא של קבצי קלט 
מדובר על תנועת קבלה עם כרטיס אשראי, זה אמור להכנס לשדה 
creditpays.fid

**Comment by WizMotiSaadon** [comment]
kupain.hds 
תוקן

**Comment by wizayala** [comment]
תקין
