### ISSUE TITLE
יבוא תנועות מלאי - סוג תנועה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#206]
קשרתי ס"ת פטור לס"ת חייב ואני מקבלת את ההודעה הבאה , היא לא ברורה : 

סוג תנועה פטור נעול בחברה הקולטת sqlCount = #?=SELECT count(TransTypeCode) FROM TransTypes where TransTypeCode = 'ח'  AND StationID is not null#

**Comment by WizMotiSaadon** [comment]
שיפרתי את ההודעה
mlayin.hds

**Comment by wizayala** [comment]
אני מקבלת עדיין את אותה הודעה 
![image](https://user-images.githubusercontent.com/16633745/82411575-b3b6a300-9a7a-11ea-8d92-bf72bf6f6478.png)

**Comment by WizMotiSaadon** [comment]
שיפרתי עוד קצת את ההודעה

**Comment by wizayala** [comment]
אני לא מבינה מה אתה רוצה לומר בהודעה .
ממתי יש ס"ת נעול ? למה הכוונה ?

**Comment by WizMotiSaadon** [comment]
את יכולה לשלוח לי את ההודעה שאת מקבלת?

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/82419141-a1426680-9a86-11ea-9357-c8a0a1758f97.png)

**Comment by WizMotiSaadon** [comment]
אבל תיקנתי את ההודעה

**Comment by WizMotiSaadon** [comment]
אני חושב שאם יש ב 
transtype.stationID
ערך כלשהוא,
אז אסור לי לבצע פעולת מלאי עם הסוג תנועה הספציפי

**Comment by wizayala** [comment]
לא הבנתי למה ערך בשדה הזה אמור לשנות ?
האם יש התייחסות כזו בבדיקות של עבד ?

**Comment by wizayala** [comment]
ואין בכלל ערך בשדה תחנה 

![image](https://user-images.githubusercontent.com/16633745/82420389-5295cc00-9a88-11ea-8f4d-a271e75599c7.png)

**Comment by WizMotiSaadon** [comment]
נראה לי שיש לו

**Comment by wizayala** [comment]
אתה יכול להעתיק לי איפה הוא מתייחס לזה ?
צרפתי מייל עם השאילתא שהדס העבירה עם הבדיקות של עבד

איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
מה פשר ההודעה הזו :
סוג תנועה מכיל יותר מידי תנועות ואינו מתאים למסמך   sqlSearchForTransTypeMoves = #?=SELECT count(*) FROM TransTypeMoves where StationID is null AND TransType =  'פ'#

![image](https://user-images.githubusercontent.com/16633745/82445202-132da680-9aad-11ea-97e1-9aecbc7586c1.png)

**Comment by WizMotiSaadon** [comment]
כמה תנועות יש לסוג תנועה הזה? צריך לברר בטבלה TransTypeMoves

ולאן קישרת את הסוג תנועה? אם קישרת לסוג תנועה פטור, אז מותר שיהיו רק 2 תנועות

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/82451086-327d0180-9ab6-11ea-9450-b8a5a99f2614.png)

**Comment by WizMotiSaadon** [comment]
תוקן 
mlayin.hds

**Comment by wizayala** [comment]
מתקבלת הודעת שגיאה 

---------------------------
HSD
---------------------------

Error in SQL :Incorrect syntax near '|'.
Statement(s) could not be prepared.

?=SELECT SALESDOC FROM DOCUMENTSDEF WHERE DOCUMENTID =  |DOCUMENTID|
---------------------------
אישור  
---------------------------
---------------------------
HSD
---------------------------

Incorrect syntax near '|'.
Statement(s) could not be prepared.

---------------------------
אישור  
---------------------------

**Comment by WizMotiSaadon** [comment]
תוקן

Mlayin.hds
