### ISSUE TITLE
- שיפור יבוא חשבונות / פריטים נוספים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#21]
בקשה לשיפור בגרסה הבאה 2019
ביבוא נתונים נוספים חשבונות ו יבוא נתונים נוספים פריטים יש להוסיף צ'ק בוקס עם שאלה "האם לאפס רשומות קיימות"
במידה וסימנו "וי" יש למחוק רשומה מתוך טבלת extrasums/date/note 
לדוגמא בכרטיס חשבון – accountkey=30001  יש מספר סכומים נוספים .
לדוגמא השורה המסומנת sufid=2  כאשר מבקשים לאפס אותה לא ניתן לקלוט אפס או להקליד 0 אלא יש למחוק את הרשומה וכך גם בקליטת ממשק במידה ויש לי בקובץ קלט רשומה המכילה פרטים עבור חשבון 30001 ועבור אותו sufid  עם הערך 0 וסימנו וי בצ'ק בוקס יש למחוק את הרשומה מתוך הטבלה המתאימה במקרה זה extrasums  . במידה ולא סימנו וי בצ'ק בוקס יש לתת הודעת שגיאה לא ניתן לקלוט 0 או לאפס (כיום אנחנו עושים זאת).
את אותו הדבר יש לעשות עבור תאריכים  נוספים, הערות נוספות  ואותו הדבר עבור יבוא הנוספים בפריטים סכומים, תאריכים והערות.
מקווה שזה ברור.
איילה

**Comment by WizMotiSaadon** [comment]
?זה בסדר מבחינת הדס

**Comment by wizayala** [comment]
הדס השיבה במייל


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
בנסיון לעדכן סכומים נוספים מופיעה ההודעה הבאה :
![image](https://user-images.githubusercontent.com/16633745/73591775-b0170480-44fb-11ea-9499-d88a6219cd3b.png)

**Comment by wizayala** [comment]
ההודעה הבאה ביבוא הערות נוספות בחשבונות

![image](https://user-images.githubusercontent.com/16633745/73591817-261b6b80-44fc-11ea-8306-1bb288014992.png)

**Comment by wizayala** [comment]
[cid:image001.png@01D5D908.F5DF8550]


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
הודעה שנייה ביבוא הערות בחשבונות
---------------------------
HSD
---------------------------

DB Error in expression - (EX)ImportExtras
The multi-part identifier "ExtraSums.ItemFlag" could not be bound.

State:37000,Native:4104,Origin:[Microsoft][ODBC SQL Server Driver][SQL Server]

---------------------------
התעלם  בטל  
---------------------------

**Comment by wizayala** [comment]
ביבוא נתונים נוספים הערות חשבונות

[cid:image001.png@01D5D909.31202160]

---------------------------
HSD
---------------------------

DB Error in expression - (EX)ImportExtras
The multi-part identifier "ExtraSums.ItemFlag" could not be bound.

State:37000,Native:4104,Origin:[Microsoft][ODBC SQL Server Driver][SQL Server]

---------------------------
התעלם  בטל
בחירה על כפתור התעלם . היישום נתקע על סרגל קליטה


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
משהו השתבש :

![image](https://user-images.githubusercontent.com/16633745/73605693-2eca7b00-45aa-11ea-9e8e-56bdee073517.png)

**Comment by WizMotiSaadon** [comment]
regsvr32 wizini.dll

**Comment by wizayala** [comment]
תקין

**Comment by wizayala** [comment]
בודקת שעובדת טוב...


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>
