### ISSUE TITLE
יבוא חשבונות - כתובת

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#211]
יש לתקן שדה כתובת ביבוא חשבונות ולאפשר קליטה של 100 תווים ולא 50 תווים 
accounts.address

**Comment by WizMotiSaadon** [comment]
אבל אני רואה שבשדה הזה יש רק חמישים

![image](https://user-images.githubusercontent.com/10919353/83008490-e7b33a80-a01d-11ea-9d4f-7c26791e46cb.png)

**Comment by wizayala** [comment]
מוזר 
בתנועות מלאי מופיע 100 הנחתי שכך זה גם בחשבונות

**Comment by wizayala** [comment]
סבבה אז אני סוגרת את זה 
לא נתקן 
נהיה תואמים למה שקיים בחשבונות
