### ISSUE TITLE
יבוא תנועות מלאי - הודעת שגיאה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#212]
מה פשר ההודעה :
---------------------------
HSD
---------------------------

Error in SQL :String or binary data would be truncated.
The statement has been terminated.

INSERT INTO CONVERT_ERR (ERRMSG,TRANSTYPE,  ERROR,ROW_NO ,DOCTYPE)  VALUES ('ח',LEFT('ח',50), 'אחוז המעמ בסוג התנועה אינו תואם למעמ במסמךsqlTransTypeMovesCounter = #?=SELECT count(*) FROM TransTypeMoves where StationID is null AND TransType = ''ח'' And DebitCredit =  0  And 0=0 And 17.00<>TransTypeMoves.PercenF   And (select MainAccount as MA from Accounts where Accounts.AccountKey = TransTypeMoves.accountkey)=''12''#' ,2.000000000,'mlayin')
---------------------------
אישור  
---------------------------

**Comment by WizMotiSaadon** [comment]
הודעת שגיאה ארוכה מידי
תוקן

mlayin.hds

**Comment by wizayala** [comment]
מה הבעיה בהודעה הזו :  
---------------------------
HSD
---------------------------

Error in SQL :String or binary data would be truncated.
The statement has been terminated.

INSERT INTO CONVERT_ERR (ERRMSG,TRANSTYPE,  ERROR,ROW_NO ,DOCTYPE)  VALUES ('ח',LEFT('ח',50), 'אחוז המעמ בסוג התנועה אינו תואם למעמ במסמךsqlTransTypeMovesCounter = #?=SELECT count(*) FROM TransTypeMoves where StationID is null AND TransType = ''ח'' And DebitCredit =  0  And 0=0 And 17.00<>TransTypeMoves.PercenF   And (select MainAccount as MA from Accounts where Accounts.AccountKey = TransTypeMoves.accountkey)=''12''#' ,2.000000000,'mlayin')
---------------------------
אישור  
---------------------------

**Comment by WizMotiSaadon** [comment]
תיקנתי את זה ב MLAYIN.HDS  בשעה 13:59

**Comment by wizayala** [comment]
זה קורה עם הקובץ של 13:59

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds
