### ISSUE TITLE
יבוא חשבונות - מספר כרטיס אשראי

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#214]
מוטי ביבוא חשבונות מספר כרטיס אשראי 
accounts.sbcardno
אין לקלוט תווים כמו -  . / וכו/ 
זהו שדה נומרי בלבד
בודקת גם מה האורך המקסימלי הואם יכול להיות 50

**Comment by wizayala** [comment]
אורך שדה לפי ציפי צריך להיות 19 תווים

**Comment by WizMotiSaadon** [comment]
אפשר להעביר מספר כרטיס אשראי?
אברהם לא מרשה בכלל

**Comment by wizayala** [comment]
נכון בעבר ביטלנו את זה אח"כ בגרסה 2017 אם אני זוכרת נכון החזרנו באישור אברהם ובלחץ הקהל

**Comment by WizMotiSaadon** [comment]
> אורך שדה לפי ציפי צריך להיות 19 תווים

תיקנתי ODBCIMP.EXE

**Comment by WizMotiSaadon** [comment]
> מוטי ביבוא חשבונות מספר כרטיס אשראי
> accounts.sbcardno
> אין לקלוט תווים כמו - . / וכו/
> זהו שדה נומרי בלבד

תוקן
HSImport24.sql

**Comment by wizayala** [comment]
לא תיקנת הודעת שגיאה 

![image](https://user-images.githubusercontent.com/16633745/82797679-1b585e00-9e80-11ea-9c08-aa1114519f5a.png)

**Comment by WizMotiSaadon** [comment]
> לא תיקנת הודעת שגיאה

תוקן
HSImport24.sql

**Comment by wizayala** [comment]
הודעה תקינה 
יש לאפשר 21 תווים בקליטת אשראי ולא 19
בדקתי בתוכנה

**Comment by WizMotiSaadon** [comment]
> יש לאפשר 21 תווים בקליטת אשראי ולא 19

odbcimp.exe

**Comment by wizayala** [comment]
מוטי 
האם תוכל לתקן ולאפשר 21 תוים 
רוצים להוציא sp

**Comment by WizMotiSaadon** [comment]
תיקנתי אתמול
רשמתי 
odbcimp.exe

**Comment by wizayala** [comment]
עדיין לא מתריע 

![image](https://user-images.githubusercontent.com/16633745/82898973-de18cc80-9f62-11ea-96da-88fb5cff92cb.png)

**Comment by WizMotiSaadon** [comment]
הוא רושם "מספר חייב להיות ספרתי"

איזו התראה אחרת צריך?

**Comment by wizayala** [comment]
זו ההודעה שצריכה להיות לגבי יותר מ 21 תוים 
יופי 

![image](https://user-images.githubusercontent.com/16633745/82901304-651b7400-9f66-11ea-9ff5-f8188401fb1d.png)

**Comment by wizayala** [comment]
השאילתא קשורה לתיקון של מספר תווים וסימנים  מיוחדים ?

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/82901394-87ad8d00-9f66-11ea-9465-f9758ec114cb.png)

**Comment by WizMotiSaadon** [comment]
> השאילתא קשורה לתיקון של מספר תווים וסימנים מיוחדים ?

כן
