### ISSUE TITLE
יבוא תנועות מלאי - הודעת שגיאה  ס"ת 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#215]
מוטי
האם אפשר לתקן את ההודעה בשורה מס' 1 שיופיע מלל בעברית 
![image](https://user-images.githubusercontent.com/16633745/82785469-4f755400-9e6b-11ea-928b-9cfbd27bbf38.png)

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds

**Comment by wizayala** [comment]
o.k.
![image](https://user-images.githubusercontent.com/16633745/82797830-522e7400-9e80-11ea-89e5-e36888938b5b.png)
