### ISSUE TITLE
יבוא תנועות מלאי- סוג תנועה משובש

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#216]

**Comment by wizayala** [comment]
למה אתה מתכוון בסוג תנועה משובש ?
במקרה הזה שיבשתי חשבון ראשי

**Comment by WizMotiSaadon** [comment]
> למה אתה מתכוון בסוג תנועה משובש ?
אני מתכוון שאני בודק את הטבלאות 
TransTypes
TransTypeMoves

ובודק אם הסכומים נכונים

עבור הסוג תנועה הנבדק

תוכלי לצלם לי איזה הודעת שגיאה את מקבלת
?

**Comment by wizayala** [comment]
תסתכל יצרתי שיבוש בסכומים של ס"ת "ח" 

![image](https://user-images.githubusercontent.com/16633745/82810485-531ed000-9e97-11ea-80d1-b8dac3432d27.png)



![image](https://user-images.githubusercontent.com/16633745/82810501-5c0fa180-9e97-11ea-8f39-5e0f03165d04.png)

**Comment by WizMotiSaadon** [comment]
אז יצרת שיבוש 
ואני מודיע שיש שיבוש,
אז איפה הסוגיה
?

**Comment by wizayala** [comment]
בהודעות של עבד יש רישום מסודר לכל סוג של תקלה , האם אתה משתמש בהם ?
במקרה הזה עבד מודיע "אחוז בחשבון הכנסות חייב להיות 100"

**Comment by WizMotiSaadon** [comment]
לא משתמש בהודעות,   רק בודק שיבוש

**Comment by wizayala** [comment]
סבבה
