### ISSUE TITLE
יבוא תנועות מלאי - סוג תנועה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#217]
מה פשר ההודעה ?

---------------------------
HSD
---------------------------

סוג תנועה פטור סיילדוק=0
---------------------------
אישור  
---------------------------
אח"כ מקבלת שגויים שקצת יותר ברורים 

![image](https://user-images.githubusercontent.com/16633745/83002008-2db7d080-a015-11ea-95c3-77501839795c.png)

**Comment by WizMotiSaadon** [comment]
> מה פשר ההודעה ?

שכחתי הודעה עבורי
תוקן
mlayin.hds
