### ISSUE TITLE
יבוא תנועות הנהלת חשבונות - אסמכתא

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#218]
בגרסה קודמת כאשר היו תווים של טקסט בשדה אסמכתא , הורדנו לגמרי את התווים וקלטנו רק את הספרות של האסמכתא .
בגרסה 2020 אנחנו נותנים הודעת שגיאה

![image](https://user-images.githubusercontent.com/16633745/83348899-fdd03c00-a338-11ea-8014-f2029ccaf452.png)

![image](https://user-images.githubusercontent.com/16633745/83348908-14769300-a339-11ea-8aac-5eb404a97850.png)

**Comment by WizMotiSaadon** [comment]
אז מה הבאג

**Comment by wizayala** [comment]
אם בגרסה קודמת "ניטרלת" את האותיות, תעשה זאת גם בגרסה הזו

**Comment by wizayala** [comment]
ממתי הסינון הזה של האותיות , לא זכור לי שביקשנו את זה בעבר ?

**Comment by WizMotiSaadon** [comment]
לא זכור לי שסיננתי אי פעם, 
גם לא רואה סיבה הגיונית לסנן

**Comment by wizayala** [comment]
בגרסה 2018 הקובץ נקלט לאחר סינון של האותיות משדה האסמכתא.
לדעתי זה קורה רק בקבצי טקסט  כי בשיטת odbc  אתה נותן הודעת שגיאה

**Comment by wizayala** [comment]
בכל מקרה לצערי מכיוון שזו טעות היסטורית , יש לתקן אותה בגרסה 2020 כי ישנו לקוח שעובד כך שנים

**Comment by wizayala** [comment]
את התיקון יש לבצע **רק** לשיטה הגמישה אין לתקן עבור כל שאר השיטות

**Comment by wizayala** [comment]
תקין
