### ISSUE TITLE
התעלמות משם הקובץ :יבוא דפי בנק - דואר

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#22]
יש לי השערה שכאשר קובץ אקסל מכיל את המילה "דואר" בקליטה של קבצים דרך odbc  אתה מוסיף באופן אוטומטי סינון נתונים
האם אפשר שזה לא יהיה והסינון יופיע רק בממשק בשיטה של בנק דואר. 
בנוסף דווקא בשיטה של בנק הדואר אם אני קולטת קובץ שהשם של הקובץ אינו מכיל "דואר" ניפוי הנתונים לא מופיע.
לסיכום : בקליטה ב odbc  השורה של ניפוי נתונים אינה צריכה להופיע כלל גם אם המילה דואר מופיעה
             בקליטה של בנק דואר השורה של ניפוי נתונים צריכה להופיע ולא משנה איך קוראים לקובץ 
אני מקווה שהעניין ברור

**Comment by WizMotiSaadon** [comment]
אז איך אני אדע שהקובץ מגיע מבנק הדואר?

אני צריך לעבד אותו כי הוא מגיע לא מסודר

**Comment by wizayala** [comment]
קובץ שמבצעים קליטה דרך בנק הדואר אתה יודע שמדובר בקובץ דואר ולא לפי שם קובץ

**Comment by wizayala** [comment]
השבתי לך בגיט


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
האם יש אפשרות שנסדר את זה ל sp  ?

**Comment by WizMotiSaadon** [comment]
מה יש לסדר?

**Comment by wizayala** [comment]
הבנת את הבעיה?
העניין הוא שלקוחות השומרים קובץ וקוראים לו בשם המכיל את המילה **דואר** , אתה באופן אוטומטי מתייחס לזה כאל קובץ בנק הדואר.
אני ביקשתי שלא תעשה זאת .
התייחסות אל קובץ בנק דואר לא תהיה לפי שם הקובץ אלא רק אם בחרו בשיטה של ייבוא בנק דואר
מקווה שברור
![image](https://user-images.githubusercontent.com/16633745/87242711-c674a500-c437-11ea-8c1c-c78459af5c43.png)

**Comment by WizMotiSaadon** [comment]
לא הבנתי את הבעיה

**Comment by wizayala** [comment]
מעולה תודה
