### ISSUE TITLE
יבוא תנועות מלאי - חשבון ראשי 49 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#220]
מדוע מתקבלת הודעת שגיאה ביבוא תנועות עם ס"ת שחשבון ההוצאה שלו הוא 49 , במסמכי רכש ?

**Comment by WizMotiSaadon** [comment]
מה ההודעת שגיאה?

**Comment by wizayala** [comment]
תסתכל על הודעות שגיאה 1,3 

![image](https://user-images.githubusercontent.com/16633745/83351233-d6826a80-a34a-11ea-85c0-1df6ad37ed10.png)

**Comment by WizMotiSaadon** [comment]
אישרתי בטעות 46 במקום 49

תיקנתי 
mlayin.hds

**Comment by wizayala** [comment]
אגב זו לא טעות לאשר 46
יש לאשר גם 46 וגם 49

**Comment by WizMotiSaadon** [comment]
הוספתי ל 
MLAYIN.HDS
את 46

כלומר עכשיו אני מאשר את 

'3'
'46'
'49'
'13'
'14'

**Comment by wizayala** [comment]
מעולה 
תודה
