### ISSUE TITLE
יבוא תנועות הנהלת חשבונות - timeout expired

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#222]
שני לקוחות שלנו נתקלו בהודעת שגיאה (מצרפת תמונה) , לאחר שיחה עם הדס ככל הנראה יש לתקן ולהוסיף
timeout=0 
בנקודות מסויומת, עליך לשוחח עם הדס שתאמר לך היכן יש לבצע תיקונים.
![timeout](https://user-images.githubusercontent.com/16633745/83727267-7989fb80-a64d-11ea-8417-4de5f2f125bb.jpg)

**Comment by WizMotiSaadon** [comment]
שלחתי לה אימייל

**Comment by wizayala** [comment]
הלקוחה מפעילה לחץ כבד מאד על הסניף .
מה הדס צריכה להעביר אליך ?


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
תוקן
WizImportMySql.dll

**Comment by wizayala** [comment]
תקין אצל הלקוחה
