### ISSUE TITLE
יבוא תנועות מלאי - ס"ת לא קיים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#224]
ייבאתי תנועות מלאי עם ס"ת שאינם קיימים בחברה ואז מתקבלות ההודעות הבאות:
---------------------------
HSD
---------------------------

Error in SQL 
---------------------------
אישור  
---------------------------

---------------------------
HSD
---------------------------

RunTime Error In ((EXE)bIsStockTransTypeOK) At Line->13
Converting Problem: Closing quot is missing - ?=SELECT count(*) FROM TransTypeMoves where StationID is null AND TransType = 1750501819  And 1=main  And ((select MainAccount as MA from Accounts where Accounts.AccountKey = TransTypeMoves.accountkey)=1750501818 ')
---------------------------
אישור  
---------------------------
---------------------------
HSD
---------------------------

RunTime Error In ((EXE)bIsStockTransTypeOK) At Line->13
Converting Problem: Closing quot is missing - ?=SELECT count(*) FROM TransTypeMoves where StationID is null AND TransType = 1750501819  And 1=main  And ((select MainAccount as MA from Accounts where Accounts.AccountKey = TransTypeMoves.accountkey)=1750501818 ')
---------------------------
אישור  
---------------------------
---------------------------
HSD
---------------------------

Incorrect syntax near 'חי'.

---------------------------
אישור  
---------------------------
אישור והתוכנה נסגרת 
ס"ת שאינו קיים הוא אכן "חי"

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds

**Comment by wizayala** [comment]
![Uploading image.png…]()

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/84121304-a79d8000-aa3f-11ea-93ce-0e6ef1d0cde3.png)
