### ISSUE TITLE
יבוא תנועות מלאי - ס"ת שגוי

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#225]
האם יש אפשרות לתת הודעה שמכוונת היכן הבעיה?
לדוגמא  הבעיה בשגויים פה שקשירתי ס"ת חייב במעמ בטור של ס"ת פטור ממעמ 
הבעיה היא אינה במבנה של ס"ת "ח "

![image](https://user-images.githubusercontent.com/16633745/84112594-b715cc80-aa31-11ea-8ff4-80b58535a784.png)

**Comment by WizMotiSaadon** [comment]
מה ההודעה המדוייקת שאני אמור לתת
?

**Comment by wizayala** [comment]
הודעה שהבעיה היא עבור שדה ס"ת פטור

**Comment by wizayala** [comment]
סוג תנועה פטור ממע"מ משובש

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
מוטי, אני לא אתעקש על התיקון הזה אך השאלה שלי היא האם אתה יודע באיזה שדה יש את הבעיה. כי אם אתה מבין ששדה ס"ת פטור מעמ הוא מכיל נתון שגוי האם אפשר לתת הודעה ששדה ס"ת פטור ממעמ שגוי  ולא הודעה כזו . אם זה מורכב מדי אז נעזוב את זה כך 

![image](https://user-images.githubusercontent.com/16633745/84123878-1d571b00-aa43-11ea-8f51-4d64aec05600.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
מעולה 
![image](https://user-images.githubusercontent.com/16633745/84126057-17166e00-aa46-11ea-980b-651e0a9151f7.png)
