### ISSUE TITLE
בדיקת גרסה רגיסטרי מול DB ביבוא ממסופון2 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#226]
בכדי שתהיה תאימות מלאה בין הרגיסטרי ל
 DB
תשווה 5 תווים ראשונים בלבד,
אם זהה תחזיר שתקין
אם שונה תפעיל את הפונקציה מה-
Start_up
תוריד את ההודעה

**Comment by WizMotiSaadon** [comment]
תוקן
imp_lib.hds -> (EX)IsVersionOK

**Comment by wizayala** [comment]
איך אני יכולה לבדוק את זה ?
שאשנה גרסה של החברה  ?

**Comment by wizayala** [comment]
לא רואה כל הבדל 
שמרתי את קובץ ההפעלה של מסופון 2 מחדש 
שינתי את הגרסה באחת החברות 


[AYALAWIN10_3360.rate.bat] --->test2019 -4.2 -c:\קבצי ממשקים\מטח\קליטת שערי מטח.wpr - - - - - - -0 -1 -

**Comment by WizMotiSaadon** [comment]
צריך להוריד את ה
-Batch

בשביל לראות מה אני משווה

?להתחבר

**Comment by wizayala** [comment]
[cid:image001.png@01D63F22.BAA23980]


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
---------------------------
HSD
---------------------------

ImportStr = #test2019 -4.2 -²c:\קבצי ממשקים\מטח\קליטת שערי מטח.wpr² - - - - - - -0 -1 -#
---------------------------
אישור  
---------------------------
---------------------------
HSD
---------------------------

RegistryVersion = #2018a# DBversion = #2020a#  sort = #2#
---------------------------
אישור  
---------------------------
---------------------------
HSD
---------------------------

גירסה לא מעודכנת
---------------------------
אישור  
---------------------------
---------------------------
HSD
---------------------------

Error From OpenTextFile:C:\A2002\rate.bat.err
---------------------------
אישור  
---------------------------
---------------------------
HSD
---------------------------

ImportStr = #test2019 -4.2 - - - - - - - -0 -1 -#
---------------------------
אישור  
---------------------------

**Comment by wizayala** [comment]
הבדיקה נעשית מול sp  ולא גרסה
