### ISSUE TITLE
יבוא תנועות יומן - שורת 999999

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#228]
בממשק בשיטה הגמישה יש שורת סיום המורכבת מ 999999999999
ככל הנראה אתה מנסה לתרגם אותה לתאריכים וכו' ואז מתקבלת הודעת שגיאה.
ברגע שהורדתי את השורה הזו הקובץ נקלט.
מעבירה לך קבצים במייל נפרד 
זו הודעת השגיאה:
---------------------------
WIZIMP~2
---------------------------
 CImportData::ExecuteSQL error #1# :  execute ImportJournalProcessTempTable 'AYALAWIN10_14348' , 1  
CDBException = Arithmetic overflow error converting varchar to data type numeric.
The statement has been terminated.
Arithmetic overflow error converting varchar to data type numeric.
The statement has been terminated.
Arithmetic overflow error converting varchar to data type numeric.
The statement has been terminated.
Arithmetic overflow error converting varchar to data type numeric.
The statement has been terminated.
Arithmetic overflow error converting varchar to data type numeric.
The statement has been terminated.

---------------------------
OK   
---------------------------

**Comment by WizMotiSaadon** [comment]
תוקן
WizImportLogic.dll
WizImportMySql.dll

**Comment by wizayala** [comment]
תקין
