### ISSUE TITLE
יבוא ממסופון 2 - בדיקת גרסה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#229]
האם יש אפשרות שההודעה של חוסר התאמה במספר גרסה יופיע בקובץ err 
היום לא נרשם דבר , גם לא שהממשק הסתיים בהצלחה 
בהמשך לגיט #226

**Comment by WizMotiSaadon** [comment]
תוקן
imp_lib.hds

**Comment by wizayala** [comment]
תקין

**Comment by wizayala** [comment]
מוטי
הבקשה הייתה אם אני מריצה לדוגמא עדכון של שערי מט"ח שיעדכן את שערי המטח  ובחברות שבן הגרסה אינה נכונה שתופיע הודעה חברה X אינה תואמת לגרסה ברגיסטרי.

**Comment by WizMotiSaadon** [comment]
אבל מה הקשר לשערי מטח?
אם את רצה אני יכול לא לבצע את הבדיקה ביבוא שערי מטח

**Comment by wizayala** [comment]
הבקשה הזו התחילה מיבוא שערי מטח , במקום להיתקע על חברה שהגרסה אינה תואמת לתת הודעה בקובץ err  ולהתקדם ליבוא שערים בחברה הבאה 
כן צריך לבצע את הבדיקה בכל הממשקים

**Comment by WizMotiSaadon** [comment]
תיקנתי,
רושם הודעה לקובץ 
וממשיך הלאה

**Comment by wizayala** [comment]
שלחתי לך מייל עם קובץ שגיאות לא רואה שרושם דבר

**Comment by WizMotiSaadon** [comment]
לא הגיע

**Comment by wizayala** [comment]
#250 פתחתי גיט נוסף 
צרפתי אליו קובץ שגיאות

**Comment by wizayala** [comment]
לאחר התייעצות עם אפרת והדס יישאר כך
