### ISSUE TITLE
יבוא תנועות מלאי - הדפסת מסמכים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#23]
בקליטת תנועות מלאי נתבקשנו להוסיף אפשרות של הדפסת מסמך.
הדפסת המסמך תהיה לפי ההגדרות הקיימות לפי ההיררכיה לפי מה שמוגדר בחשבון, בהגדרות חברה לפי סוג המסמך

האם תוכל להוסיף זאת?

**Comment by WizMotiSaadon** [comment]
הדס מאשרת?

**Comment by wizayala** [comment]
כן


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
ההדפסה של המסמך יהיה לאחר שלב ההפקה ופורמט ההדפסה לפי מה שמוגדר בכרטיס חשבון ואם אין הגדרה מסויימת אז לפי מה שמוגדר בהגדרות חברה לסוג המסמך
מכאן בדיקה ראשונה היא האם למפתח החשבון יש הגדרה של פורמט הדפסה :
accdocrpt.accountkey.**rptid** 
documentsdef.documentid.**rptformat** 
השדות המודגשים הם מתוך 
wizcomp.dbo
rptdocs.rptnum

מקווה שברור
אם תרצה תוכל להתחבר ואראה לך במה מדובר

**Comment by WizMotiSaadon** [comment]
תודה,
"שלחתי מייל להדס בקשר ל"איך מדפיסים
נחכה שתחזור אלי

**Comment by wizasher** [comment]
אני מקבל 
![image](https://user-images.githubusercontent.com/69102026/108626648-eeaa9480-7459-11eb-9ce6-ce70dd0e7568.png)
ואחרי אישור הוא יוצא להדפסה

**Comment by WizMotiSaadon** [comment]
אולי זו הודעה של אופיר?
[H-Facebook]<https://www.facebook.com/Hashavshevetldt/>

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/108627901-7f846e80-7460-11eb-9a34-2d2925b1aa34.png)
ההודעה הזו חוזרת עבור כל stockid

**Comment by WizMotiSaadon** [comment]
אני חושב שזו
 לא הודעה שלי,
אולי של אופיר

**Comment by wizayala** [comment]
אני אבדוק עם אופיר

**Comment by wizayala** [comment]
אופיר יבדוק את הנושא מחר

**Comment by wizayala** [comment]
אופיר שם קובץ 
ledger.hds 
חדש בטסט
עכשיו ההודעה לא מופיעה

**Comment by wizasher** [comment]
גם אצלי לא מופיע , ממשיך לבדוק .
תודה

**Comment by wizasher** [comment]
מופיע הדפסה אחרי הפקה גם בקליטת מסמכים לזמני , מפריע לנו שיש אופציה כזאת ?
![image](https://user-images.githubusercontent.com/69102026/108962131-fd26c500-7680-11eb-810c-71db091b3caf.png)

**Comment by wizayala** [comment]
בוקר טוב, 
בדיוק התכוונתי לכתוב שזה מיותר ביבוא בזמני
אין הפקה בזמני
זה צריך להיות אפור / לא פעיל

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
סימון הדפסה לאחר הפקה מופיעה במסופון 2 
אולי כדאי שהסימון הזה יהיה 
בהגדרות כלליות יבוא

**Comment by wizayala** [comment]
מוטי
האם תוכל לתקן את זה שההדפסה תופיע בחלון של הגדרות כלליות יבוא ?

**Comment by WizMotiSaadon** [comment]
כן בהקדם האפשרי

**Comment by WizMotiSaadon** [comment]
?אולי יהיה מצב שיבוא אחד ירצו להדפיס והשני לא ירצו

אני חושב שזה מה שדיברתי בזמנו עם דקל
והיא אמרה לי לאפשר החלטה על כל שורה

**Comment by wizayala** [comment]
אתייעץ עם אפרת

**Comment by wizayala** [comment]
רישום פנימי 
קובץ
 mlayin.hds 7.4.21

**Comment by wizayala** [comment]
ההודעה הזו מופיעה 

![image](https://user-images.githubusercontent.com/16633745/120098157-00789380-c13d-11eb-9e69-2639dddce26c.png)
לאחר כל מסמך ז"א שאם יש לי בבקובץ קלט 5 מסמכים , אני צריכה לאשר 5 פעמים את ההודעה

**Comment by WizMotiSaadon** [comment]
איך אני יכול להעתיק מחרוזת מצילום מסך
?

**Comment by wizayala** [comment]
מוטי 
זה של אופיר 
הוא העביר קובץ מעודכן של 
ledger.hds 31.5.21

אשר 
הקובץ נמצא ב 
h:\test\hashavshevet

**Comment by wizayala** [comment]
אשר,
אם אצלך זה תקין אפשר לסגור את הגיט

**Comment by WizMotiSaadon** [comment]
אה יופי

**Comment by wizasher** [comment]
אצלי מדפיס אחרי קליטת מלאי בכמה שיטות גם במסופון2
רק שאחרי קליטה ממסופון2 גם לא מלאי המסך של הדוס נשאר על המסך 
אני עם קובץ 
Masofon2.exe  21/2/21
זה נראה כמו הודעה משליחת מייל , למרות שלא מסומן לי כרגע לשלוח מייל 
ERR

![image](https://user-images.githubusercontent.com/69102026/120278022-71df5000-c2bd-11eb-8cae-209e0e431511.png)

**Comment by WizMotiSaadon** [comment]
יש פקודה לשליחת מייל

יש פקודה לפתוח קובץ שגיאות

אם אתה לא רוצה שישלח או יפתח פשוט תשים 
REM
לפני הפקודה

**Comment by wizasher** [comment]
תודה , בודק

**Comment by wizasher** [comment]
אני לא מצליח ,
אתה מתכוון בקובץ הזה ?
![image](https://user-images.githubusercontent.com/69102026/120286981-7a3c8880-c2c7-11eb-85db-07f482331f2b.png)

**Comment by WizMotiSaadon** [comment]
לא, 
התכוונתי
בקובץ
BATCH

**Comment by WizMotiSaadon** [comment]
יש בקובץ
 BATCH
שתי פקודות ל
POWER SHELL

אם אתה לא רוצה פקודה
תשים 
REM

**Comment by wizasher** [comment]
עכשיו הבנתי ,
זה הסתדר 
תודה

**Comment by wizasher** [comment]
אני רואה שכשאני שומר שוב פעם דרך מסופון2 הגדרה חדשה, אז שוב פעם אני צריך לשים 
REM
בתחילת שורה .
יש אפשרות שברירת המחדל תישמר עם 
REM
?
כי אצל הלקוח יופיע מסמך הדוס על המסך בכל פעם שהוא יגדיר מסופון2

**Comment by WizMotiSaadon** [comment]
תוקן
masofon2.exe

**Comment by wizasher** [comment]
עובד מצוין .
תודה

**Comment by wizayala** [comment]
גם אצלי תקין 
מדפיס ממסופון2

**Comment by wizasher** [comment]
כשאני קולט מסמכים מסוג "מלאי" - יתרת פתיחה העברה בין מחסנים 
ואני מסמן הדפסה בסיום זה נותן לי הודעת שגיאה 
![image](https://user-images.githubusercontent.com/69102026/124711409-b5555b80-df06-11eb-992a-7126f7d1e19f.png)
מסמכים "רגילים" הזמנה חשבונית הוא מדפיס בסיום .
למרות שבשני המקרים אני קולט מאקסל

**Comment by WizMotiSaadon** [comment]
> כשאני קולט מסמכים מסוג "מלאי" - יתרת פתיחה העברה בין מחסנים
> ואני מסמן הדפסה בסיום זה נותן לי הודעת שגיאה
> מסמכים "רגילים" הזמנה חשבונית הוא מדפיס בסיום .

שלחתי אימייל לעבד
**כנראה שהתקלה היא בפונקציה (EX)PrintMimshak בקובץ ledger.hds

להמתין שנורית תחזור מהחופש?**

**Comment by WizMotiSaadon** [comment]
> שלחתי אימייל לעבד
> 
> **כנראה שהתקלה היא בפונקציה (EX)PrintMimshak בקובץ ledger.hds להמתין שנורית תחזור מהחופש?**

עבד ענה:
**אני אעביר את זה לאופיר יטפל בזה**
