### ISSUE TITLE
יבוא תנועות מלאי ס"ת 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#230]
מוטי
אפשר לעדכן בקבצי זיפ את קובצים 
mlayin.hds(9.6.20)    odbcimp.exe  (28.5.20)
המכילים את האפשרות של קישור ס"ת .
תוודא בבקשה שאנחנו מתייחסים לכרטיסי הכנסות חייבים במעמ 
mainaccounts.mainaccountid = 7,10,47
הכנסות פטורות ממעמ
mainaccounts.mainaccountid = 8,11,44,47
הוצאות 
mainaccounts.mainaccountid = 3,46,49

בגיטים הקודמים רשמתי עוד כרטיסים ואני רואה שרק אלו מופיעים אצל עבד.

**Comment by WizMotiSaadon** [comment]
מעודכן
