### ISSUE TITLE
 אפסים במקום רווחים יבוא תנועות יומן - שיטה גמישה 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#231]
בגרסה קודמת 2018 התעלמנו מתווים nul  כפי שניתן לראות אותם בצילום מסך 
בגרסה 2020 מתקבלת הודעה שלא ניתן לקלוט ללא סכום חובה 
רק אחרי שערכתי את הקובץ (3 שורות ראשונות ) נקלט טוב בגרסה 2020
למה ? מה משעות התו הזה ?
שולחת לך במייל נפרד את הקבצים

![image](https://user-images.githubusercontent.com/16633745/84589057-ced7c100-ae34-11ea-9223-eaa193fc522a.png)

**Comment by WizMotiSaadon** [comment]
בודק

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
מה זה התו הזה ?

**Comment by wizayala** [comment]
לא רואה הבדל , עדיין "צועק" על שורות שלא תיקנתי , עם התווים nul
![image](https://user-images.githubusercontent.com/16633745/84590233-70631080-ae3d-11ea-8644-673e5a5d3e8a.png)

**Comment by WizMotiSaadon** [comment]
זה אחרי שלקחת את הקובץ
WizImportLogic.dll

?

**Comment by wizayala** [comment]
כן , לא עשיתי ריגסטרי

**Comment by wizayala** [comment]
בקשתי שיבדקו אפשרות שבית התוכנה ימלא ברווחים ולא ב 0 nul

**Comment by wizayala** [comment]
שוחחתי עם בית התוכנה שישנה את זה .
ככל הנראה לא ישנה אלא יעביר להם קובץ אקסל
