### ISSUE TITLE
יבוא - שדה מיון

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#233]
ביבוא (מכל הסוגים) כאשר מייבאים שדה id אוטומטי לשדה מיון מתקבלת הודעה :
---------------------------
יבוא מטבלה
---------------------------
שדה מקושר כבר לא קיים בטבלת קלט: #ID#
---------------------------
OK   
---------------------------

**Comment by wizayala** [comment]
בגרסה קודמת זה לא קורה

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by WizMotiSaadon** [comment]
> בגרסה קודמת זה לא קורה

כי זו בדיקה חדשה שעשיתי
והבדיקה לא הייתה מספיק טובה

**Comment by wizayala** [comment]
התקלה היא רק לשדה אוטומטי, אם זה שדהה מזהה שאני יצרתי אותו אז אין לי תקלה , הבנתי נכון ?



איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
תקין

**Comment by WizMotiSaadon** [comment]
לא חייב שדה אוטומטי

**Comment by WizMotiSaadon** [comment]
נכון,
זה משהו שלא ממש התעמקתי בו
האמת
