### ISSUE TITLE
יבוא תנועות יומן - הודעת שגיאה 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#236]
מקבלת הודעת שגיאה , מה הוא מתקשה לייבא 

![image](https://user-images.githubusercontent.com/16633745/84773636-5c5a1300-afe5-11ea-876c-66a76fd9bc8a.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
הייתה לנו הודעה דומה בנוגע לשורת סיום 9999999
ומה הבעיה בסכום זהו סכום שניתן להקיש אותו

**Comment by WizMotiSaadon** [comment]
ואיך זה נראה בטבלה אחרי שמקישים אותו?

**Comment by wizayala** [comment]
[cid:image001.png@01D64483.6D1BA0A0]



[cid:image002.png@01D64483.6D1BA0A0]
איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
טוב אפשר להתחבר לראות?

**Comment by wizayala** [comment]
כן , כמה דקות.
עדיין לא עדכנתי קבצים מאתמול תחילה אעדכן ואז תתחבר , בסדר?


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
מוכן להתחברות   148 721 498

[cid:image001.png@01D64486.EEB36910]


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
לא צריכה להיות בעיה לקלוט סכום שכזה נקלט בגרסה קודמת

**Comment by WizMotiSaadon** [comment]
תוקן

HSImportJournal35.sql

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/84884459-6b4ecd00-b09a-11ea-86f3-36c261f722b9.png)

**Comment by WizMotiSaadon** [comment]
מה מנסים לקלוט פה?

**Comment by wizayala** [comment]
זה אותו קובץ קלט עם הסכום הגדול


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
אז צריך לקחת את ה 
WizImportSql.dll

**Comment by wizayala** [comment]
שמת חדש?
זה הודעות אחרי קבצי dll  האחרונים ששמת 16.6


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
כן, שמתי היום חדש

**Comment by wizayala** [comment]
---------------------------
WIZIMP~2
---------------------------
 CImportData::ExecuteSQL error #1# :  insert into jurnaltrans(type,osek874,Quant,jurnalmatchid,TransType ,Status,BatchNo   ,CostCode ,TransCredID,CurrencyCode,DatF3,TransDebID,Description,ValueDate,DueDate,Ref2            ,Referance      ,Ref3      ,suF      ,suFDlr         ,LockingIs,extradate1,extradate2,extranum1,extranum2,bdate,hour)                                           SELECT type,osek874,Quant,transid,										  transtype      ,										  2    ,										  316       ,										  CostCode     ,										  isnull(NULLIF(CredID1, ''),CredID2 )        ,										  CurrencyCode        ,										  DatF3 ,										  isnull(NULLIF(DebID1, ''),DebID2 )      ,										  Description       ,										  ValueDate     ,										  DueDate   ,										  Reference2             ,										  Reference            ,										  Ref3       ,										  case when Abs(CAST(CredsuF1    as DECIMAL(12,2))+CAST(CredsuF2    as DECIMAL(12,2)))>Abs(CAST(DebsuF1    as DECIMAL(12,2))+CAST(DebsuF2    as DECIMAL(12,2))) then (CAST(CredsuF1    as DECIMAL(12,2))+CAST(CredsuF2    as DECIMAL(12,2))) else (CAST(DebsuF1    as DECIMAL(12,2))+CAST(DebsuF2    as DECIMAL(12,2))) end,										  case when Abs(CAST(CredsuFDlr1 as DECIMAL(12,2))+CAST(CredsuFDlr2 as DECIMAL(12,2)))>Abs(CAST(DebsuFDlr1 as DECIMAL(12,2))+CAST(DebsuFDlr2 as DECIMAL(12,2))) then (CAST(CredsuFDlr1 as DECIMAL(12,2))+CAST(CredsuFDlr2 as DECIMAL(12,2))) else (CAST(DebsuFDlr1 as DECIMAL(12,2))+CAST(DebsuFDlr2 as DECIMAL(12,2))) end,										  case when LEN(ISNULL(ImportJournal.CredID1,''))>0 and LEN(ISNULL(ImportJournal.CredID2,''))>0 or LEN(ISNULL(ImportJournal.DebID1,''))>0 and LEN(ISNULL(ImportJournal.DebID2,''))>0 or LEN(ISNULL(ImportJournal.TransType,''))>0  then 4 else 0 end       ,										  extradate1,extradate2,extranum1,extranum2,										  Convert(varchar(10), GETDATE(),120) ,										  DATEPART(hour, GETDATE())*60  +  DATEPART(minute, GETDATE()) 										   FROM ImportJournal where ('AYALAWIN10_13536' = ImportJournal.Computername And ImportJournal.ErrorMessage is null)  order by transid 
CDBException = Arithmetic overflow error converting varchar to data type numeric.
The statement has been terminated.

---------------------------
OK   
---------------------------

**Comment by WizMotiSaadon** [comment]
אפשר לשלוח לי קבצי קלט?

**Comment by wizayala** [comment]
איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
WizImportMySql.dll

תוקן

**Comment by wizayala** [comment]
עדיין אותה הודעת שגיאה

**Comment by WizMotiSaadon** [comment]
אבל תיקנתי במקום 
DECIMAL(12,2)

DECIMAL(18,2)

**Comment by wizayala** [comment]
תתחבר מחר אליי


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>
