### ISSUE TITLE
יבוא תנועות יומן - מהירות קליטה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#238]
נראה שמהירות הקליטה השתנה ונהייתה איטית יותר בין מהדורה 2020 לבין מהדורה 2020sp1
שלחתי לך במייל קובץ ההבדל בין שתי המהדורות הוא זמן קליטה 
2020 - 10 שניות 
2020sp1 - 20 שניות 

רעיון ???

**Comment by wizayala** [comment]
הבעיה הזו הגיעה מלקוחה , יש הסבר מדוע יש הבדל במהירות קליטה בין שתי הגרסאות

**Comment by WizMotiSaadon** [comment]
זה יבוא יומן בשיטה המפורטת?

**Comment by wizayala** [comment]
מקוצרת

**Comment by wizayala** [comment]
נראה תקין כאשר התקנתי על המחשב בת"א מול שרת dev13 
החזרתי לולרי שיבדקו אולי תחנות אחרות, חברה אחרת, שינוי רשת שיבדקו מול הבנים מה אפשר לעשות לשיפור מהירות
