### ISSUE TITLE
מסופון 2 - הודעות שגיאה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#239]
לבקשת הדס , כשמפעילים את מסופון 2 יש כל מיני הודעות שמפריעות למהלך העבודה, לדוגמא כאשר יש הודעה של תחנה אחרת קולטת , זה נרשם בקובץ err של המסופון 2 אך יחד עם זאת קובץ odbcimp.exe  נשאר פתוח בתוך מנהל המישמות ובפהעלות הבאות של מסופון 2 זה תמיד תקוע על זה.
הדס מבקשת שתוריד את כל ההודעות הללו , אפשר לרשום אותם לתוך קובץ err או קובץ לוג אחר.
לפי בדיקה של הדס זה קורה בכל קבצי ה exe  שלנו ( import_v, odbcimp.exe ...... )
זה דחוף ל sp הקרוב !!!!

**Comment by WizMotiSaadon** [comment]
תוקן
odbcimp.exe
