### ISSUE TITLE
יבוא תנועות מלאי  - מטבע ללא שער

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#24]
ביבוא תנועות מלאי כאשר מתבצעת שליפת מחיר ויש מטבע מט"ח שאין לו שער, המסמך מופק בכל זאת.
חשבונית יכולה להיקלט על סכום 0 , מטבע בתנועה $ שער- 0
בתוכנה זה לא אפשרי כמובן מחייב שער , בממשק נותן הודעת שגיאה אך בסוף קולט עם שער 0
יש לתקן ולתת הודעת שגיאה בהתאם: "אין אפשרות לקלוט מסמך ללא שער."

**Comment by wizayala** [comment]
אין שום הודעת שגיאה זה נקלט עם  שער 0 וזה לא צריך להיות כך.

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/73605666-d85d3c80-45a9-11ea-9582-f570762747d8.png)
 מקבלת את ההודעה הבאה בכניסה ליבוא תנועות מלאי

**Comment by WizMotiSaadon** [comment]
regsvr32 wizini.dll

**Comment by wizayala** [comment]
עשיתי את קודם


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
עדיין אותה בעיה שלחתי לך באג בנפרד

**Comment by WizMotiSaadon** [comment]
איך זה עכשיו?

**Comment by wizayala** [comment]
מתקבלת הודעת שגיאה 
---------------------------
HSD
---------------------------

לא נמצא שער, יש לעדכן שערי מטח 9480
---------------------------
אישור  
---------------------------
 לאחר לחיצה על אישור  ממשיך בקליטה ומופיעה ההודעה הבאה :
---------------------------
HSD
---------------------------

חלק מהרשומות לא נקלט בהצלחה
---------------------------
אישור  
---------------------------
 בפועל הרשומה נקלטה עם שער 0

![image](https://user-images.githubusercontent.com/16633745/74678721-782ee300-51c4-11ea-878b-91a646d5583c.png)

**Comment by wizayala** [comment]
לא תקין השבתי לך בגיט


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
אולי תבקשי מעבד שלא יפיק

**Comment by wizayala** [comment]
אם אתה חושב שזה החלק של עבד אז אעביר לו את התקלה

**Comment by wizayala** [comment]
יותר טוב

![image](https://user-images.githubusercontent.com/16633745/77849446-51f15f80-71d4-11ea-879c-b67bfce33998.png)
