### ISSUE TITLE
masofon2 - bathlog 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#240]
לתוך קובץ 
batchlog.txt  
נרשמים כל מיני הודעות שקשורות לממשקים וזה מנפח מאד את הקובץ ומקשה על העבודה.
הודעות כמו : 
17/06/2020 16:35:07.364
HSD - [c:\2019\search.hds]
AYALAWIN10/user/4584
Doc:[imp_lib.hds] Expression:[(EX)IsVersionOK]
 Message: 
RegistryVersion = #2018a# DBversion = #2018a#  sort = #2#

**Comment by WizMotiSaadon** [comment]
הורדתי את זה

**Comment by wizayala** [comment]
או.קיי 
מסתבר שזה מנפח את הקובץ אצל לקוחות במיוחד אלו שמריצים מסופון2 כל 5 דק

**Comment by WizMotiSaadon** [comment]
תיקנתי
imp_lib.hds
