### ISSUE TITLE
יבוא תנועות שירות - סוג מסמכים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#241]
האם אפשרי להוסיף בסוג מסמך 
כרטיס עבודה 67, כרטיס עבודה סוכן 72, 107 הזמנת שירות , 117 הזמנת שרות סוכן, 106 הצעת מחיר שרות
האם אפשרי , יש מספיק מקום ?

![image](https://user-images.githubusercontent.com/16633745/85218309-cab22300-b3a1-11ea-8471-5dd85d479edd.png)

**Comment by WizMotiSaadon** [comment]
תוקן
odbcimp.exe
