### ISSUE TITLE
יבוא תנועות מלאי - תחנה אחרת

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#242]
אני יכולה להיכנס וליבוא תנועות מלאי מכמה ישומים כולל מסופון2 , אני מקבלת הודעה של "תחנה אחרת משתמשת "
אני מקבלת הודעה כזו :
---------------------------
HSD
---------------------------

Error:Updating Recordset Record :[DB2][IMPORTLASTFILES] Failed .
Attempt to scroll past end or before beginning of data.
---------------------------
אישור  
---------------------------

**Comment by WizMotiSaadon** [comment]
אם תחנה אחרת משתמשת
ויש הודעה 
אז הכל בסדר?
לא מתערבבים נתונים?

**Comment by wizayala** [comment]
ניסיתי לקלוט ממסופון2 ומתוך התוכנה לאותו db  אומנם לא התערבבו קבצים אך לא הייתה הודעה של תחנה אחרת כן מופיעה ההודעה הבאה:

![image](https://user-images.githubusercontent.com/16633745/85222425-846dbb80-b3c3-11ea-816c-425f34ac93e9.png)

זה צריך בכלל להיחסם ,להופיע תחנה אחרת משתמשת.

**Comment by WizMotiSaadon** [comment]
אבל איפה רשומה ההפניה ל
 WPR
 הזה
?

**Comment by wizayala** [comment]
טופל עם הדס
