### ISSUE TITLE
יבוא - קבצי לוג

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#244]
שולחת לך במייל נפרד מספר קבצי לוג שנוצרים אשמח אם תוכל להסביר לי מה המשמעות של כל אחד 
מהם:

WizImport.log
ODBCErr2.txt
odbcimp_log04.txt
Prm2IniLog.txt
Prm2IniLogError.log
WizImportError.log

**Comment by WizMotiSaadon** [comment]
עבורי יבוא בשיטה המהירה, כל מיני קשקושים שלי
**WizImport.log**


באגים שיטה מהירה, צריך להיות ריק
**WizImportError.log**

לא מכיר
**ODBCErr2.txt**

מאקסל לטבלה זמנית  odbcimp.exe
**odbcimp_log04.txt**

מDAT+PRM לקובץ TXT+schema.ini
**Prm2IniLog.txt**  prm2ini.dll


מDAT+PRM לקובץ TXT+schema.ini  באגים , צריך להיות ריק
**Prm2IniLogError.log**
