### ISSUE TITLE
יבוא רכוש קבוע - תאריך הפעלה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#246]
יש לאפשר קליטה תאריך הפעלה ( importasset.startdate ) רק במידה ומדובר על טבוע חדש ( importassett.instacekey )שלא קיים בטבלת itemsinstance 
במידה והטבוע קיים אין לאפשר שינוי של שדה תאריך הפעלה

**Comment by WizMotiSaadon** [comment]
לא הצלחתי לשחזר את הבעיה

**Comment by wizayala** [comment]
נכון גם אצלי זה לא מעדכן מתקבלת הודעה שטבוע קיים
