### ISSUE TITLE
יבוא תנועות יומן - איטיות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#249]
לקוחות מתלוננים על איטיות בקליטת תנועות יומן (שלחתי לך מייל עם wizimport.log ) 
התקלה הזו מגיע מלקוח ויש לא מעט לקוחות המתלוננים על איטיות בעקבות עדכון   2020a sp1

**Comment by WizMotiSaadon** [comment]
תוקן
jurnalin.hds
WizImportMySql.dll

**Comment by wizayala** [comment]
העברתי קבצים לסניף שיבדקו האם משפר קליטה

**Comment by wizayala** [comment]
לקוח חזר ושעכשיו הקליטה מהירה יותר
