### ISSUE TITLE
יבוא פריטים - שדה "שקיל"

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#25]
בייבוא פריטים יש להוסיף אפשרות של ייבוא שדה "שקיל" , הכוונה לשדה  Items. WeightItem 
כאשר השדה הזה מקבל ערכים של 0 או 1 
0= לא שקיל ( אין סימון בתיבה)
1 = שקיל ( יש סימון בתיבה)

**Comment by WizMotiSaadon** [comment]
ביקשתי מהדס להוסיף

**Comment by wizayala** [comment]
השדה קיים **Items. WeightItem** , אנחנו צריכים להוסיף אותו לתוך טבלת importitem

**Comment by WizMotiSaadon** [comment]
כמובן

**Comment by WizMotiSaadon** [comment]
ALTER TABLE ImportItem ADD WeightItem varchar(50);

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
האם צריך להריץ את השאילתא הזו ?
HSImportItem25.sql


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
מוטי
לא צריך להופיע ? ליד שם השדה "שקיל"
בתאור השדה יש להוסיף לא שקיל = 0, שקיל =1
בנוסף יש לבדוק מהו סוג הפריט items.stockperunit  רק עבור ערכים (0,4,5,6 ) אפשר לאפשר קליטה של שדה Items. WeightItem  עבור שאר הערכים יש לתת הודעה " סוג פריט נוכחי אינו יכול להיות פריט שקיל"

![image](https://user-images.githubusercontent.com/16633745/74097841-81abb180-4b19-11ea-8564-9674cc111dae.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
יש לתקן את הודעת השגיאה "שדה שקיל ... " "שדה שקילות.... "

![image](https://user-images.githubusercontent.com/16633745/74712351-beb92780-522e-11ea-8486-01a097b8079d.png)

**Comment by wizayala** [comment]
בנוסף לא התייחסת ךבקשה שלי לאפשר רק לסוג מסויים של פריטים קליטה של שדה שקיל:
**בנוסף יש לבדוק מהו סוג הפריט items.stockperunit רק עבור ערכים (0,4,5,6 ) אפשר לאפשר קליטה של שדה Items. WeightItem עבור שאר הערכים יש לתת הודעה " סוג פריט נוכחי אינו יכול להיות פריט שקיל"**

**Comment by wizayala** [comment]
מוטי
לא תקין מהבחינה של התייחסות לסוג פריט . כתבתי לך בגיט


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
> בנוסף לא התייחסת לבקשה שלי לאפשר רק לסוג מסויים של פריטים קליטה של שדה שקיל:
> **בנוסף יש לבדוק מהו סוג הפריט items.stockperunit רק עבור ערכים (0,4,5,6 ) אפשר לאפשר קליטה של שדה Items. WeightItem עבור שאר הערכים יש לתת הודעה " סוג פריט נוכחי אינו יכול להיות פריט שקיל"**

itemin.hds
תוקן

**Comment by wizayala** [comment]
לא רואה שינוי

**Comment by WizMotiSaadon** [comment]
![image](https://user-images.githubusercontent.com/10919353/75425846-2b79a380-594c-11ea-84d5-2bd6effbc6fd.png)

**Comment by wizayala** [comment]
מוטי
התקלה הזו לא נפתרה עדיין

**Comment by WizMotiSaadon** [comment]
?אפשר להתחבר

**Comment by wizayala** [comment]
אפשר שנתחבר מחר בבוקר .

**Comment by WizMotiSaadon** [comment]
מתברר שאת ה 
StockPerUnit

אני לוקח מהמשתמש
![image](https://user-images.githubusercontent.com/10919353/77996193-d7d8ec00-7335-11ea-9c02-b2b0edcda2f3.png)

**Comment by wizayala** [comment]
לא ידעתי שיש שדה כזה במשתמש

**Comment by WizMotiSaadon** [comment]
אבל זה הגיוני שאם השדה לא מקושר אני אמור לקחת מהפריט בחברה

**Comment by WizMotiSaadon** [comment]
תיקנתי שאני מעדכן את ה 
stockperunit
מטבלת הפריטים במידה ואין לי קישור של השדה הזה

HSImportItem28.sql

**Comment by wizayala** [comment]
נראה שזה תקין עכשיו אבל תוריד את ההודעות הללו 
---------------------------
HSD
---------------------------

is valid 1
---------------------------
אישור  
---------------------------

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/78015470-20060780-7352-11ea-933a-c0f5cda374d1.png)

**Comment by WizMotiSaadon** [comment]
ההודעות זה בקובץ ששלחתי לך במייל
אז תוכלי בבקשה לקחת מהזיפ
itemin.hds

**Comment by wizayala** [comment]
הודעות שגיאה נכונות:
![image](https://user-images.githubusercontent.com/16633745/78029177-d5dc5080-7368-11ea-8cb9-af251ee825b7.png)

אך בפועל מעדכן למרות השגיאה
![image](https://user-images.githubusercontent.com/16633745/78029240-e987b700-7368-11ea-9994-c19489d545e6.png)

**Comment by WizMotiSaadon** [comment]
תוקן
itemin.hds

**Comment by wizayala** [comment]
תקין
