### ISSUE TITLE
מסופון 2 - בדיקת גרסה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#250]
עדיין אין הודעת שגיאה בתוך קובץ השגיאות של מסופון2 על חברות שאינן תואמות את הגרסה. האם יש אפשרות להוסיף ?
מצרפת לך קובץ err  כיצד נראה 
[rate.bat.ok.DMY-30.06.20.HMS-11.23.59.LOG](https://github.com/wizayala/Hashavsheva/files/4850859/rate.bat.ok.DMY-30.06.20.HMS-11.23.59.LOG)

**Comment by WizMotiSaadon** [comment]
אני לא מחפש לכל החברות , רק לחברה הקולטת
