### ISSUE TITLE
יבוא מאו.די.בי.סי - כללי

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#251]
האם יש אפשרות להגדיל את החלון שבו אנו בוחרים קובץ , שם קובץ 
**עותק של דוח ערך מלאי מ_שמן - תיקון מחירים.xls**
לא רואים את כל שם הקובץ בחלון בחירת קובץ

![image](https://user-images.githubusercontent.com/16633745/86531360-32e82500-bec9-11ea-9ce9-c806807bbc82.png)

**Comment by WizMotiSaadon** [comment]
זה מה שמיקרוסופט נותנת

http://www.weberpackaging.com/pdfs/odbc_settings_excel.pdf
