### ISSUE TITLE
יבוא תנועות מלאי - שדה פרטים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#252]
בקשה : האם אפשר כאשר מקשרים או מייבאים בפרמטרים שדה פרטים (שורה 13) בפרמטרים ולא מקשרים שדה פרטים בתנועה ( שורה 71 בפרמטרים) שהנתון שקיים עבור שדה פרטים יעודכן באופן אוטומטי לשדה פרטים בתנועה

**Comment by WizMotiSaadon** [comment]
כבר עשינו את זה
זה באג #66 
אמרת לי לגנוב את הפרטים מהכותרת

**Comment by wizayala** [comment]
בכל אופן שדה פרטים
  stock.details 
לא עובר לשדה 
stockmoves.details
שולחת לך מייל נפרד עם קבצי קלט

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds
