### ISSUE TITLE
אפשרות לאפס יתרה לאספקה ביבוא כותרות מסמכים ממסופון2

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#253]
יש להוסיף את האפשרות במסופון 2 לסמן ביטול יתרה לאספקה כפי שקיים היום בייבוא נתונים נוספים מסמכים

![image](https://user-images.githubusercontent.com/16633745/87239675-720efc80-c41a-11ea-80b0-3f6f98f4b289.png)

**Comment by WizMotiSaadon** [comment]
את מתכוונת לאיפוס?

**Comment by wizayala** [comment]
כן

**Comment by WizMotiSaadon** [comment]
![image](https://user-images.githubusercontent.com/10919353/91970795-dbc3cc80-ed20-11ea-853f-48e847be5832.png)

**Comment by WizMotiSaadon** [comment]
תוקן
stockheaderin.hds
masofon2.exe

**Comment by wizayala** [comment]
לא עובד אצלי מתוך מסופון 2
כן עובד מתוך התוכנה
קובץ שגיאות נרשם שבוצע בהצלחה.
בנוסף איפה אני רואה ביטל יתרה לאספקה בתוך קובץ 
masofon2.ini ?
![image](https://user-images.githubusercontent.com/16633745/92321684-92cb8b00-f034-11ea-9ab3-65bec15b5e64.png)
[stockmoves.bat.ok.DMY-06.09.20.HMS-11.26.05.LOG](https://github.com/wizayala/Hashavsheva/files/5179264/stockmoves.bat.ok.DMY-06.09.20.HMS-11.26.05.LOG)

**Comment by WizMotiSaadon** [comment]
> בנוסף איפה אני רואה ביטל יתרה לאספקה בתוך קובץ
> masofon2.ini ?

ResetDeliveryBalance

**Comment by wizayala** [comment]
סבבה , מצאתי את זה בקובץ אך עדיין לא מעדכן

![image](https://user-images.githubusercontent.com/16633745/92322020-65341100-f037-11ea-853f-98b65db42291.png)

**Comment by WizMotiSaadon** [comment]
> לא עובד אצלי מתוך מסופון 2

stockheaderin.hds
תוקן

**Comment by wizayala** [comment]
עכשיו מאפס יתרה אך אינו דורס שדות טקסט

**Comment by WizMotiSaadon** [comment]
> עכשיו מאפס יתרה אך אינו דורס שדות טקסט

?יש לך שדה טקסט ספציפי לדוגמא

**Comment by wizayala** [comment]
stockmoves.detalis
stockmoves.costcode
ועוד

**Comment by WizMotiSaadon** [comment]
אולי
stockmoves.tree
?שווה 2

?אולי ססטוס בזמני
[H-Mobile]<https://h-erp.co.il/h-mobile/>

**Comment by wizayala** [comment]
עכשיו תקין , אולי הייתה לי טעות בתנועה.

**Comment by wizayala** [comment]
ממשיכה לבדוק....

**Comment by wizayala** [comment]
ראה גם גיט  #350
