### ISSUE TITLE
יבוא דפי בנק פועלים - מסופון 2

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#254]
נתבקשנו לאפשר ייבוא דפי בנק פועלים מתוך מסופון 2 
בצעת שינויים בקבצים הללו :
Oshtnuin.hds
Imp_lib.hds
Bankin.hds
Masofon2.exe

לאחר שהעתקתי את הקבצים הללו ונכנסתי ליבוא דפי בנק פועלים מתוך התוכנה מופיעה ההודעה הבאה : 
---------------------------
HSD
---------------------------

oshtnuin.hds OPEN MasofonFileName = ##
---------------------------
אישור  
---------------------------
---------------------------
HSD
---------------------------

קובץ לא נמצא
---------------------------
אישור  
---------------------------

**Comment by wizayala** [comment]
יבוא בנק פועלים שיטה חדשה 

![image](https://user-images.githubusercontent.com/16633745/87241524-b2777600-c42c-11ea-8d18-cd99f8b924f3.png)

אישור ונותן להתקדם הלאה

**Comment by wizayala** [comment]
עדכנתי קבצים אחרונים מהזיפ האחרון ובכניסה ליבוא בנק פועלים מתוך התוכנה מופיעה ההודעה הבאה :
---------------------------
HSD
---------------------------

oshtnuin.hds OPEN MasofonFileName = ##
---------------------------
אישור  
---------------------------
![image](https://user-images.githubusercontent.com/16633745/87925669-4bd80500-ca89-11ea-800e-6dcb15a38bca.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
עדיין מופיע החלון הבא:
עוד לא הגעתי כלל לחלון של בחירת קובץ

![image](https://user-images.githubusercontent.com/16633745/87932110-a37b6e00-ca93-11ea-928f-065bf023ce85.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
יופי כעת ניתן להכנס לבחירת קובץ ללא הודעה
עדיין צריך לסדר את העניין של להחזיר את הכפתור של מיפוי חשבון וחברה

**Comment by WizMotiSaadon** [comment]
> עדיין צריך לסדר את העניין של להחזיר את הכפתור של מיפוי חשבון וחברה

החזרתי

**Comment by wizayala** [comment]
מצויין
