### ISSUE TITLE
יבוא דפי בנק פועלים 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#255]
לאחר מיפוי מתוך כפתור  כל המיפויים מתקבלת ההודעה הבאה :
![image](https://user-images.githubusercontent.com/16633745/87241555-17cb6700-c42d-11ea-819e-6d78df90f366.png)

**Comment by wizayala** [comment]
מדוע ביטלת את האפשרות של מיפוי חשבון 

![image](https://user-images.githubusercontent.com/16633745/87241570-2fa2eb00-c42d-11ea-925a-506b3c4e3e98.png)

**Comment by WizMotiSaadon** [comment]
> לאחר מיפוי מתוך כפתור כל המיפויים מתקבלת ההודעה הבאה :
> ![image](https://user-images.githubusercontent.com/16633745/87241555-17cb6700-c42d-11ea-819e-6d78df90f366.png)

את יכולה לשלוח לי 
CTRL_C
?

**Comment by wizayala** [comment]
---------------------------
HSD
---------------------------

Error in SQL :Incorrect syntax near '-'.
Statement(s) could not be prepared.

?=SELECT FULLNAME FROM DEMO-AYALA.DBO.ACCOUNTS WHERE ACCOUNTKEY = '???'
---------------------------
אישור  
---------------------------

**Comment by wizayala** [comment]
---------------------------
HSD
---------------------------

oshtnuin.OnError = #Incorrect syntax near '-'.
Statement(s) could not be prepared.
#
---------------------------
אישור  
---------------------------

**Comment by wizayala** [comment]
---------------------------
HSD
---------------------------

DB Error in expression - (EX)GetAccName
Incorrect syntax near '-'.
Statement(s) could not be prepared.

State:37000,Native:102,Origin:[Microsoft][ODBC SQL Server Driver][SQL Server]
State:37000,Native:8180,Origin:[Microsoft][ODBC SQL Server Driver][SQL Server]

---------------------------
התעלם  בטל  
---------------------------

**Comment by WizMotiSaadon** [comment]
זו בעיה עם המקף בשם של בה 
DB

אני אמור לעטוף בגרשיים , אני מברר איך עושים את זה

**Comment by WizMotiSaadon** [comment]
תיקנתי
Oshtnuin.hds

**Comment by wizayala** [comment]
יש להחזיר את האפשרות של מיפוי חשבון 

![image](https://user-images.githubusercontent.com/16633745/87925808-804bc100-ca89-11ea-80ed-60699cae4bac.png)

**Comment by wizayala** [comment]
ההודעה הזו גם חוזרת 👍 
---------------------------
HSD
---------------------------

Error in SQL :Invalid object name 'DEMOAYALA.DBO.ACCOUNTS'.
Statement(s) could not be prepared.

?=SELECT FULLNAME FROM DEMOAYALA.DBO.ACCOUNTS WHERE ACCOUNTKEY = '???'
---------------------------
אישור  
---------------------------

**Comment by WizMotiSaadon** [comment]
זה נראה שאין לך חברה שנקראת
demoayala

את יודעת מאיפה זה בא
?

**Comment by wizayala** [comment]
דווקא הייתה לי חברה בשם demo-ayala
מתחילה שוב אחרי מחיקה של התו - בשם db 
ואחרי שמחקתי את טבלת 
poalimreminder
