### ISSUE TITLE
יבוא כרטיסי אשראי  - ישראכרט

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#256]
שולחת לך קובץ ששיניתי בשורה 78 או סוג הרשומה ל 23 , קוד רשומה שאינו מוגדר במנה קובץ והרשומה נקלטה בכל זאת 

chsh
למיטב זכרוני אנחנו מייתחסים לסוגי הרשומות 
מה קרה פה ?

**Comment by WizMotiSaadon** [comment]
יש לי רשימה של סוגים שאני לא מקבל

כל השאר אני מקבל

23 
לא נמצא ברשימה של 
"לא לקבל"

**Comment by wizayala** [comment]
איזה סוגים אתה לא מקבל ?

**Comment by WizMotiSaadon** [comment]
If(
              StrCmp( Mid({Line},1,2) ,"**37**" )=1,
               Return(0) 
           )[;]

     If(
              StrCmp( Mid({Line},1,2) ,"**38**" )=1,
               Return(0) 
           )[;]


     If(
             StrCmp( Mid({Line},1,2) ,"**47**" )=1,
               Return(0) 
           )[;]

     If(
              StrCmp( Mid({Line},1,2) ,"**48**" )=1,
               Return(0) 
           )[;]

    




         If(
              StrCmp( Mid({Line},0,1) ,"**6**" )=0,
               Return(0) 
           )[;]




         //hamchaot, we dont want it
         If(
              StrCmp( Mid({Line},17,3) ,"**050**" )=1,
               Return(0) 
           )[;]


         //dalkanim, we dont want it
         If(
                  StrCmp( Mid({Line},27,3) ,"**060**" )=1
             Or StrCmp( Mid({Line},27,3) ,"**061**" )=1 ,
               Return(0) 
           )[;]

**Comment by WizMotiSaadon** [comment]
כל המספרים שנמצאים בין כוכביות אני לא מקבל

**Comment by wizayala** [comment]
טוב נשאיר ככה

**Comment by wizayala** [comment]
האם הסינון זה מתייחס גם לקבצי ריכוז pch

**Comment by WizMotiSaadon** [comment]
ל 
PCH
:יש סינון אחר



//בקובץ PCH  את לא קולטת קוד רשומה 37 שזה בעצם העברה לבנק 
//קוד זה נמצא מטור 2 עד טור 3
//2018-02-08
                  StrCmp( Mid({Line},1,2) ,"**37**" )=1 
            Or StrCmp( Mid({Line},1,2) ,"**47**" )=1 
            Or StrCmp( Mid({Line},1,2) ,"**38**" )=1 
            Or StrCmp( Mid({Line},1,2) ,"**48**" )=1 ,



//Dalkanim, ignore the whole record
 StrCmp( Mid({Line},27,3) ,"**060**" )=1 
 StrCmp( Mid({Line},27,3) ,"**061**" )=1 ,

//checks, ignore the whole record
 StrCmp( Mid({Line},27,3) ,"**050**" )=1 ,
