### ISSUE TITLE
יבוא שערי מטח

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#257]
ביבוא שערי מט"ח כאשר אני מסמנת יבוא מאתר בנק ישראל , האם אפשר שתצוגה מקדימה , יהיה לא פעיל, כדי שאמנע מהודעות שלקוח בטעות ילחץ על תצוגה מקדימה 

![image](https://user-images.githubusercontent.com/16633745/87246201-748e4800-c454-11ea-97df-8f370f0e1926.png)

**Comment by WizMotiSaadon** [comment]
תוקן
ratein.hds

**Comment by wizayala** [comment]
מצויין תודה
