### ISSUE TITLE
יבוא שערי מטח - חברה לא קיימת 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#258]
האם יש אפשרות לקבל הודעה אחרת וברורה יותר כמו  חברה לא קיימת .
האם יש אפשרות לאחר אישור על ההודעה התוכנה לא תיסגר אלא תתקדם הלאה ( כמו במסופון 2 )

---------------------------
HSD
---------------------------

Error in SQL :Invalid object name 'LAHOVITCH.dbo.Rates'.

update [LAHOVITCH].dbo.Rates   set [LAHOVITCH].dbo.Rates.Rate=Rates.Rate, [LAHOVITCH].dbo.Rates.calculated=rates.calculated   from [LAHOVITCH].dbo.Rates r1, rates  where r1.CurrencyCode=Rates.CurrencyCode and r1.DatF=Rates.DatF   and Rates.datf>='07/10/2020' and Rates.datf<=DATEADD(day,30,'07/10/2020')  and (Rates.CurrencyCode='$' or Rates.CurrencyCode='י' or Rates.CurrencyCode='לש'    or Rates.CurrencyCode='פש' or Rates.CurrencyCode='אירו')
---------------------------
אישור  
---------------------------

**Comment by wizayala** [comment]
ראיתי שהעברת קובץ אך התקלה נותרה

**Comment by WizMotiSaadon** [comment]
הקובץ היה על כיבוי של כפתורים לא רלוונטיים

**Comment by WizMotiSaadon** [comment]
> האם יש אפשרות לקבל הודעה אחרת וברורה יותר כמו חברה לא קיימת .
> האם יש אפשרות לאחר אישור על ההודעה התוכנה לא תיסגר אלא תתקדם הלאה ( כמו במסופון 2 )

תוקן

**Comment by wizayala** [comment]
כעת קולט ולא "מתרסק" כשיש חברה שלא קיימת  אך אין שום הודעה , נרשם נקלט בהצלחה

**Comment by wizayala** [comment]
האם לזה התכוונת ?

**Comment by WizMotiSaadon** [comment]
אם החברה לא קיימת אני מראש לא מעדכן אותוה
זה בסדר?

**Comment by WizMotiSaadon** [comment]
> האם לזה התכוונת ?

למה התכוונתי?

**Comment by wizayala** [comment]
טוב , העיקר שזה לא מתרסק
