### ISSUE TITLE
יבוא תנועות מלאי - מסמך ייצוא

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#259]
מדוע אנחנו מחייבים שמטבע המסמך חייב להיות תואם למטבע מוביל
מדובר על מסמך ייצוא אין שום בעיה שהמטבע יהיה כל מטבע שארצה

![image](https://user-images.githubusercontent.com/16633745/87430749-53f9f580-c5ee-11ea-95bf-2423bcfb8ffa.png)
 שולחת לך במייל נפרד קבצי קלט

**Comment by WizMotiSaadon** [comment]
?סוג מסמך 31 זה יצוא

![image](https://user-images.githubusercontent.com/10919353/87510848-fa8cd780-c67c-11ea-85f3-d915a7290e94.png)

**Comment by WizMotiSaadon** [comment]
זה מה שרשום אצלי שזה יצוא

        If (      TempDocID=28   
             Or TempDocID=29  
             Or TempDocID=35   
             Or TempDocID=36 
             Or TempDocID=38   
             Or TempDocID=57   
             Or TempDocID=62 
             Or TempDocID=94 
             Or TempDocID=96 
             Or TempDocID=100 
             Or TempDocID=119 
             Or TempDocID=120 ,

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds

עדכנתי את רשימת המסמכי יצוא

**Comment by wizayala** [comment]
מעניין שזה לא היה רשום כי הוספנו כבר בעבר את המסמך 
אם אני מבינה נכון ההודעה הופיע כי אתה שערת שמדובר על סוג מסמך שיקלי ולכן ציפת שיהיה שקל ולא מטבע זר. נכון ?

**Comment by WizMotiSaadon** [comment]
>  כי הוספנו כבר בעבר 

לא זכור לי,

>אם אני מבינה נכון ההודעה הופיע כי אתה שערת שמדובר על סוג מסמך שיקלי

זה נראה כמו מסמכים חדשים
שלא התייחסתי אליהם בכלל

**Comment by wizayala** [comment]
טוב , כעת זה קתין
