### ISSUE TITLE
יבוא ספירת מלאי - שדה סוכן 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#260]
מוטי , נעשה שינוי בברירת המחדל של שדה סוכן
 newstockcount.agent   
במידה ואין שדה מקושר או שדה ריק אנחנו שותלים ברירת מחדל של null 
כעת יש לתת את הערך 1-
מקווה שברור

![image](https://user-images.githubusercontent.com/16633745/87638692-e6181000-c74c-11ea-966a-ede63788691b.png)

**Comment by WizMotiSaadon** [comment]
תוקן
StockTakingIn.HDS

**Comment by wizayala** [comment]
הערך צריך להיות 1-   ולא 1
תסתכל בתמונה ששלחתי לך בהודעה למעלה 
כפי שזה נקלט עכשיו זה לא נכון 


![image](https://user-images.githubusercontent.com/16633745/87655459-f20dcd00-c760-11ea-9c6b-deb44e8735bf.png)

**Comment by WizMotiSaadon** [comment]
הבנתי,
פשוט בהודעה הראשונית המינוס ברח

**Comment by wizayala** [comment]
יופי 
עכשיו זה טוב
