### ISSUE TITLE
יבוא תנועות יומן - המרה שגויה של תו 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#261]
בפקודות יומן שיטה מקוצרת , קובץ מקודד אסקי דוס , תו "-" הוחלף לתו "צ"

**Comment by wizayala** [comment]
תוקן

**Comment by wizayala** [comment]
מוטי בוקר טוב
פתחתי את הגיט הזה ושלחתי לך הבוקר מייל 
הפעם ישנה בעיה הפוכה שה "צ" הוחלף ב "-" 
איך פותרים את זה ?

**Comment by WizMotiSaadon** [comment]
למה את לא מוסיפה צילום מסך?

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/88266419-dca42000-ccd7-11ea-872b-19504533b3db.png)

![image](https://user-images.githubusercontent.com/16633745/88266460-efb6f000-ccd7-11ea-97f5-061f0a77f4b2.png)

**Comment by wizayala** [comment]
לבקשתך

**Comment by WizMotiSaadon** [comment]
תוקן
WizImportLogic.dll

**Comment by wizayala** [comment]
תודה, גם הפעם הייתי צריכה לעשות רג'יסטרי לקובץ
