### ISSUE TITLE
יבוא תנועות מלאי- שדה פרטים בתנועה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#265]
כאשר שדה פרטים בתנועה גדול מ 20 תוים נופל בהודעה  ואח"כ יוצא לגמרי מהתוכנה
Error in SQL :String or binary data would be truncated.
The statement has been terminated
 יש לתקן את ההודעה להודעת שגיאה , חריגה מגדול ... משהו בדומה לזה.
שלחתי לך קובץ קלט לדוגמא

**Comment by wizayala** [comment]
מדובר בקבצי טקסט

**Comment by WizMotiSaadon** [comment]
תוקן
PRM2INI.DLL

**Comment by wizayala** [comment]
האם התיקון כולל גם קובץ mlayin.hds ?

**Comment by WizMotiSaadon** [comment]
בכל קובץ יש תיקון של תקלה אחרת

**Comment by wizayala** [comment]
מוטי
עדכנתי את שני הקבצים ועדיין אותה הודעת שגיאה כפי ששלחתי לך

**Comment by WizMotiSaadon** [comment]
אבל את שלחת לי שתי הודעות,
את יכולה לרשום את ההודעה שוב?

**Comment by wizayala** [comment]
זו אותה הודעה , עשיתי כפי שאמרת הרצתי את השאילתא וכשבטלתי אתץ שדה הפרטים זה הסתדר 

INSERT INTO STOCKMOVES (DUEDATE,DETAILS,WAREHOUSE,EXTRANUM1,EXTRANUM2,EXTRADATE1,EXTRADATE2,  EXFILE,INSTANCE,BATCHNUM,LOCALIZATION,WARRENTYDATE,CANCELDATE,EXPIREDATE, BASEDATE,STOCKID,                                     ITEMKEY,                                          AGENT,    REFERENCE,                                     PRICE,OPRICE,                                     QUANTITY,ORATE,                              DISCOUNTPRC,                                   CURRENCYCODE,RATE,                                                    DOCUMENTID,   VATEXAMPT,PACKS,ITEMNAME,UNIT,SALETAXPRC,ALTERNUM,COMMISIONPRC,PURCHQUANTITY,SUPPLYQUANTITY,BRANCHID,LINENUM,BASELINENUM,EXTRATEXT1,EXTRATEXT2,EXTRASUM1,EXTRASUM2,BASEMOVEID,BASEDOCTYPE,COSTCODE,ALTERNAME,JURNALACC)  VALUES                            ('07/23/2020','משאית ירושלים שיהיה.. חשוב לספ',0,0,0,'07/23/2020','07/23/2020',  '','','','','1980-01-01','1/1/1999',  '07/23/2020',  '07/23/2020',11072,'1512-25',4,0,40.000000000,40.000000000,2.000000000,1,0.000000000,  'ש"ח',        1,11,0,0,'','',0,'',0,2.000000000,2.000000000,1,0,0,'','',0,0,0,0,'','',''   );

**Comment by wizayala** [comment]
אחרי שמחקתי את שדה פרטים, הסתדר

![image](https://user-images.githubusercontent.com/16633745/88309230-b2258780-cd16-11ea-82d7-bc9fadebc964.png)

**Comment by WizMotiSaadon** [comment]
תוקן
PRM2INI.DLL

**Comment by wizayala** [comment]
מופיע כעת הודעה ששדה פרטים גדול מדי ( ההודעה מופיעה פעמיים , למה ?)
בנוסף אם אני מנסה לקלוט בכל זאת אני עדיין מקבלת את ההודעות ואז התוכנה נסגרת.
האם אפשר שיהיו שגויים מסודרים

**Comment by WizMotiSaadon** [comment]
איזה הודעות את מקבלת עדיין?
אני צריך צילום מסך

**Comment by wizayala** [comment]
---------------------------
Error
---------------------------
שדה פרטים בתנועה רחב מידי,יכול להיות עד 20
---------------------------
OK   
---------------------------
---------------------------
HSD
---------------------------

Error in SQL :String or binary data would be truncated.
The statement has been terminated.

INSERT INTO STOCKMOVES (DUEDATE,DETAILS,WAREHOUSE,EXTRANUM1,EXTRANUM2,EXTRADATE1,EXTRADATE2,  EXFILE,INSTANCE,BATCHNUM,LOCALIZATION,WARRENTYDATE,CANCELDATE,EXPIREDATE, BASEDATE,STOCKID,                                     ITEMKEY,                                          AGENT,    REFERENCE,                                     PRICE,OPRICE,                                     QUANTITY,ORATE,                              DISCOUNTPRC,                                   CURRENCYCODE,RATE,                                                    DOCUMENTID,   VATEXAMPT,PACKS,ITEMNAME,UNIT,SALETAXPRC,ALTERNUM,COMMISIONPRC,PURCHQUANTITY,SUPPLYQUANTITY,BRANCHID,LINENUM,BASELINENUM,EXTRATEXT1,EXTRATEXT2,EXTRASUM1,EXTRASUM2,BASEMOVEID,BASEDOCTYPE,COSTCODE,ALTERNAME,JURNALACC)  VALUES                            ('07/26/2020','משאית ירושלים שיהיה.. חשוב לספ',0,0,0,'07/26/2020','07/26/2020',  '','','','','1980-01-01','1/1/1999',  '07/26/2020',  '07/26/2020',11106,'1512-25',4,0,40.000000000,40.000000000,2.000000000,1,0.000000000,  'ש"ח',        1,11,0,0,'','',0,'',0,2.000000000,2.000000000,1,0,0,'','',0,0,0,0,'','',''   );
---------------------------
אישור  
---------------------------
---------------------------
HSD
---------------------------

String or binary data would be truncated.
The statement has been terminated.

---------------------------
אישור  
---------------------------

**Comment by WizMotiSaadon** [comment]
תיקנתי 
MLAYIN.HDS

**Comment by wizayala** [comment]
עכשיו אומנם לא נופל בהודעות שגיאה אבל קולט ?
פשוט קצצת לבדך.
כל הרעיון אנחנו לא נקצוץ לבד תווים
אני מצפה שתופיע הודעה שדה פרטים בתנועה

**Comment by wizayala** [comment]
עכשיו תקין 

![image](https://user-images.githubusercontent.com/16633745/88510563-f56c4880-cfeb-11ea-9991-58f02f4946ef.png)
