### ISSUE TITLE
יבוא תנועות יומן - שיטה מקוצרת

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#266]
כאשר יש קובץ קלט שבו ישבאמצע הקובץ רשומה סוגרת של 99999 ואח"כ רשומה פותחת ושוב מקבץ של שורות לקליטה ורשומה סוגרת.
הקובץ נקלט כהלכה והיא מתעלמת מרשומות הפותחות והסוגרות.
האם תמיד היה כך ?
שלחתי לך קובץ לדוגמא

**Comment by WizMotiSaadon** [comment]
לא זכור לי לאחרונה תיקון בנושא 
00000000000
99999999999

אני מבין שמה שקורה עכשיו זה תקין?

**Comment by wizayala** [comment]
לא יודעת אם זה תקין 
בינתיים נשאיר כך
