### ISSUE TITLE
יבוא תנועות יומן - שדות הערות, הערות נוספות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#267]
מוטי
ביבוא מאקסל כאשר אני מקשרת שדות הערות והערות נוספות
details   det2
אני רואה שנכנסים לטבלה הזמנית 
importjurnal 
אך הם אינם נכנסים לטבלת 
jurnaltrans

![image](https://user-images.githubusercontent.com/16633745/88473110-dfdf1c00-cf22-11ea-9012-cf39ffd68ec5.png)

![image](https://user-images.githubusercontent.com/16633745/88473130-22085d80-cf23-11ea-81bb-2a7fc89a014d.png)

**Comment by WizMotiSaadon** [comment]
תוקן
HSImportJournalMergeTempToConstantTable14.sql

**Comment by wizayala** [comment]
שדה הערות נוספות לא מתעדכן

**Comment by WizMotiSaadon** [comment]
WizImportMySql.dll

תוקן
