### ISSUE TITLE
יבוא תנועות הנה"ח - הערות/ הערות 2

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#268]
בקובץ פרמטרים נרשם  כך :

0	0	הערות נוספות	שורה 26
0	0	הערות נוספות 2	שורה 27

בפועל נראה שזה הפוך

![image](https://user-images.githubusercontent.com/16633745/88474301-b2e43680-cf2d-11ea-88d4-9aa23e51332d.png)

**Comment by wizayala** [comment]
ובפועל לא נקלט דבר 


![image](https://user-images.githubusercontent.com/16633745/88474315-dad39a00-cf2d-11ea-9bcc-73479b429696.png)

**Comment by WizMotiSaadon** [comment]
אפשר קבצי קלט?

**Comment by WizMotiSaadon** [comment]
WizImportMySql.dll

**Comment by wizayala** [comment]
שורות 26,27 לאילו שדות מקשורים ?

**Comment by WizMotiSaadon** [comment]
הערות נוספות	שורה 27
הערות נוספות 2	שורה 26

**Comment by WizMotiSaadon** [comment]
> בקובץ פרמטרים נרשם כך :
> 
> 0 0 הערות נוספות שורה 26
> 0 0 הערות נוספות 2 שורה 27
> 
> בפועל נראה שזה הפוך

ההערות לא נכונות

**Comment by WizMotiSaadon** [comment]
הוחלף הסדר
תוקן ל פרמטרים
תוקן לאקסל

PRM2INI.DLL
odbcimp.exe

**Comment by wizayala** [comment]
בקובץ טקסט עדיין נראה שקלט הפוך
שורה 26
נקלטה ל det2
![image](https://user-images.githubusercontent.com/16633745/88477280-686fb380-cf47-11ea-924e-dfbec34fab9a.png)

**Comment by WizMotiSaadon** [comment]
תוקן
import_v.exe
WizImportLogic.dll
WizImportMySql.dll

**Comment by wizayala** [comment]
אני מסתכל על הזיפ האחרון 
איפה הקבצים האלו ?
![Screenshot_6](https://user-images.githubusercontent.com/16633745/88478478-66aaed80-cf51-11ea-858b-ff84362414e2.png)

**Comment by wizayala** [comment]
תקין בשעה טובה
האם יש צורך בזה : HSImportJournalMergeTempToConstantTable14.sql

**Comment by WizMotiSaadon** [comment]
לא צריך
