### ISSUE TITLE
יבוא תנועות יומן - שורות ריקות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#270]
כאשר יש שורות ריקות בקובץ נקלטת רק שורה אחת, ברגע שאני מבטל את השורות הריקות הקובץ נקלט כהלכה. בגרסאות קודמות הקובץ נקלט בצורה תקינה

![image](https://user-images.githubusercontent.com/16633745/88524768-72a2b800-d002-11ea-973f-2e055dcfc628.png)

בגרסה קודמת הופיעו שגיאות על השורות הריקות והקובץנקלט

![image](https://user-images.githubusercontent.com/16633745/88524916-a54cb080-d002-11ea-8217-c58743f753e7.png)

**Comment by WizMotiSaadon** [comment]
תוקן
WizImportLogic.dll

**Comment by wizayala** [comment]
אילו תוים הפריעו לך ?

**Comment by WizMotiSaadon** [comment]
תו 10

**Comment by wizayala** [comment]
שזה LF ?

**Comment by WizMotiSaadon** [comment]
כן
