### ISSUE TITLE
יבוא פריטים - שדה סכום עם פסיק

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#272]
כאשר יש שדה סכום עשרוני עם פסיק , לדוגמא 2,000.123
הממשק נופל בהודעת שגיאה 
UPDATE  items  SET items.Price = IMPORTitem.Price   	  FROM items,IMPORTitem 
 --WHERE	(    items.itemKEY = IMPORTitem.itemKEY 	           AND LEN( LTRIM(IMPORTitem.Price)) <> 0           AND IMPORTitem.Price IS NOT NULL           AND IMPORTitem.ERRORMESSAGE IS NULL  )

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds

**Comment by wizayala** [comment]
למה התיקון ב mlayin.hds 
התקלה הייתה ביבוא פריטים ?

**Comment by wizayala** [comment]
תיקנת itemin.hds

**Comment by wizayala** [comment]
תקין בשתי הגרסאות
