### ISSUE TITLE
יבוא תנועות יומן - שדה כמות עם פסיק

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#273]
יבוא שדה כמות בפורמט עם פסיק נופל בהודעה הבאה 

---------------------------
WIZIMP~2
---------------------------
 CImportData::ExecuteSQL error #1# :  insert into jurnaltrans(DETAILS,DET2,type,osek874,Quant,jurnalmatchid,TransType ,Status,BatchNo   ,CostCode ,TransCredID,CredName,CurrencyCode,DatF3,TransDebID,DebName,Description,ValueDate,DueDate,Ref2,Referance,Ref3,suF,suFDlr,LockingIs,extradate1,extradate2,extranum1,extranum2,bdate,hour)      SELECT DETAILS,DET2,type,osek874,Quant,transid, transtype      , 2    , 373       , CostCode     , isnull(NULLIF(CredID1, ''),CredID2 ),(SELECT fullname from ACCOUNTS where AccountKey = isnull(NULLIF(CredID1, ''),CredID2 ))        , CurrencyCode        , DatF3 , isnull(NULLIF(DebID1, ''),DebID2 ),(SELECT fullname from ACCOUNTS where AccountKey = isnull(NULLIF(DebID1, ''),DebID2 ))      , Description       , ValueDate     , DueDate   ,Reference2             ,Reference            ,Ref3       ,case when Abs(CAST(CredsuF1    as DECIMAL(18,2))+CAST(CredsuF2    as DECIMAL(18,2)))>Abs(CAST(DebsuF1    as DECIMAL(18,2))+CAST(DebsuF2    as DECIMAL(18,2))) then (CAST(CredsuF1    as DECIMAL(18,2))+CAST(CredsuF2    as DECIMAL(18,2))) else (CAST(DebsuF1    as DECIMAL(18,2))+CAST(DebsuF2    as DECIMAL(18,2))) end,case when Abs(CAST(CredsuFDlr1 as DECIMAL(18,2))+CAST(CredsuFDlr2 as DECIMAL(18,2)))>Abs(CAST(DebsuFDlr1 as DECIMAL(18,2))+CAST(DebsuFDlr2 as DECIMAL(18,2))) then (CAST(CredsuFDlr1 as DECIMAL(18,2))+CAST(CredsuFDlr2 as DECIMAL(18,2))) else (CAST(DebsuFDlr1 as DECIMAL(18,2))+CAST(DebsuFDlr2 as DECIMAL(18,2))) end,										  case when LEN(ISNULL(ImportJournal.CredID1,''))>0 and LEN(ISNULL(ImportJournal.CredID2,''))>0 or LEN(ISNULL(ImportJournal.DebID1,''))>0 and LEN(ISNULL(ImportJournal.DebID2,''))>0 or LEN(ISNULL(ImportJournal.TransType,''))>0  then 4 else 0 end       ,										  extradate1,extradate2,extranum1,extranum2,										  Convert(varchar(10), GETDATE(),120) ,										  DATEPART(hour, GETDATE())*60  +  DATEPART(minute, GETDATE()) 										   FROM ImportJournal where ('AYALAWIN10_17172' = ImportJournal.Computername And ImportJournal.ErrorMessage is null)  order by transid 
CDBException = Error converting data type varchar to float.

---------------------------
OK   
---------------------------

**Comment by WizMotiSaadon** [comment]
תוקן
WizImportMySql.mdb

jurnalin.hds

**Comment by wizayala** [comment]
תקין
