### ISSUE TITLE
יבוא כרטיסי אשראי - ישראכרט PCH/ CHSH

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#275]
ביבוא ישראכרט מסוג PCH/ CHSH
מודול התחשבנות מופיע בין התווים 18-20 בקבצי קלט
יש להתייחס גם למודל התחשבנות שמתחיל ב 1

•	תחת מודל התחשבנות 001  ישראכרט– יכנסו סוגי כרטיסים 001, 011, 071, 088,022, 060,061 , 031,040 גם רשומות שמתחילות ב 1  כמו 131, 140, 101, 111 .....
•	תחת מודל התחשבנות 090 אמריקן אקספרס – יכנסו סוגי כרטיסים  090,091 כמו כן סוגי כרטיסים 191,190

**Comment by WizMotiSaadon** [comment]
אני חושב ש
040,041
 זה אמינית

**Comment by wizayala** [comment]
אין לנו אמינית בקבצים החדשים 

![image](https://user-images.githubusercontent.com/16633745/88800030-239a8580-d1b0-11ea-9120-3461f872393a.png)

**Comment by WizMotiSaadon** [comment]
אבל בפורמט ששלחת לי רשום שיש,

ויזה - 040

כלומר
"וויזה אמינית"

**Comment by wizayala** [comment]
שלחתי לך מסמך המכיל תכתובות וסיכומים לגבי סוגי המודולוים

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
משום מה נקלטת לי רשומה אחת פחות
לא מצליחה לזהות איזו 
[01291442.CHS.20170602.txt](https://github.com/wizayala/Hashavsheva/files/4999121/01291442.CHS.20170602.txt)

יש 1168 רשומות נקלטו 1167

**Comment by WizMotiSaadon** [comment]
השורה האחרונה היא בסכום אפס
לא נקלטת גם  אצלי
