### ISSUE TITLE
יבוא כרטיסי אשראי - סוג התחשבנות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#276]
יש אישור מאפרת שנוסיף עמודה נוספת שתקרא מודל התחשבנות 
שים לב שבמבנה של rst  זה מופיע בתווים 16-18
בקבצים החדשים  chsh  pch   זה מופיע בתווים 18-20

אפשר להוסיף אחרי השובר

![image](https://user-images.githubusercontent.com/16633745/88801396-504f9c80-d1b2-11ea-9daf-8c69b05f64db.png)

**Comment by WizMotiSaadon** [comment]
צריך לבקש מהדס אם כך שדה חדש
בטבלה 
bankpages

**Comment by wizayala** [comment]
ימתין לגרסה עם db

**Comment by WizMotiSaadon** [comment]
> האם גם לתצוגה מקדימה יש צורך ב db ?

לא

**Comment by wizayala** [comment]
האם תוכל לסדר שבתצוגה המקדימה יהיה אפשר לראות סוג התחשבנות , לא לקלוט לתוך דפי הבנק כרגע

**Comment by WizMotiSaadon** [comment]
הייתי בטוח שסידרתי את זה
את בטוחה שאין?

**Comment by wizayala** [comment]
הסתדר אחרי רג'יסטרי
