### ISSUE TITLE
יבוא כרטיסי אשראי - תצוגה מקדימה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#277]
בתצוגה מקדימה של קבצי rst  יש טעות , לא נלקחים כל הרשומות .
[52604379.RST.20191002.SHICHZUR.txt](https://github.com/wizayala/Hashavsheva/files/4998835/52604379.RST.20191002.SHICHZUR.txt)
לדוגמא בקובץ שצירפתי מציג באמינית רק רשומות מסוג 040 ולא מוסיף רשומות מסוג 140
אינו מציג כלל רשומות של אמריקן כשיש בקובץ רשומות של 190

**Comment by wizayala** [comment]
בפועל קולט באמינית 911 רשומות כשמציג רק 9 בתצוגה המקדימה.
אמריקן לא ניתן לקלוט כלל כי לא מציג דבר

![image](https://user-images.githubusercontent.com/16633745/88882064-c77c4380-d239-11ea-8968-35ae164ac1a2.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
עדיין לא רואה דבר ביבוא אמריקן

![image](https://user-images.githubusercontent.com/16633745/89117041-2d1f3880-d4a3-11ea-8b34-6ffb5ce5894c.png)

שלחתי לך בגיט הזה את הקובץ קלט

**Comment by WizMotiSaadon** [comment]
אולי רגיסטרי
Igib_imp.dll

**Comment by wizayala** [comment]
הסתדר
