### ISSUE TITLE
יבוא תנועות קופה זמני- סוג תנועה 43

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#279]
מתקבלת הודעת שגיאה על סוג תנועה 43 , עבור קבלות תרומה 

![image](https://user-images.githubusercontent.com/16633745/89121859-6d92ac80-d4cb-11ea-815a-a96153174abd.png)

**Comment by WizMotiSaadon** [comment]
תוקן
שיודיע רק 
ביבוא עם ההפקה

**Comment by wizayala** [comment]
למה הכוונה שיודיע בהפקה ?

**Comment by WizMotiSaadon** [comment]
> למה הכוונה שיודיע בהפקה ?

הכוונה שיש יבוא קופה רגיל, זה עם ההפקה, ויש יבוא קופה חדש בלי הפקה, אז אני עושה את הבדיקה רק ליבוא עם ההפקה

**Comment by wizayala** [comment]
איזו בדיקה
זה סוג תנועה תקין שצריך לקבל בדיוק כמו סוג תנועה 33
ההבדל הוא שבסוג תנועה 43 צריך לרשום 
stock.terminaldoc=1

**Comment by WizMotiSaadon** [comment]
אבל ביבוא הנוכחי עם ההפקה אני לא מקבל אשראי

**Comment by wizayala** [comment]
בוודאי שאנחנו מקבלים אשראי 
סוג תנועה 3,13,23
אשראי תנועות תשלומים ועסקאות רגילות

**Comment by WizMotiSaadon** [comment]
?וביבוא הנוכחי עם ההפקה אמורים לקבל 43
