### ISSUE TITLE
ייבוא ממסופון2 בנק פועלים ובנק לאומי

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#28]
ייבוא ממסופון2 בנק פועלים ובנק לאומי

**Comment by WizMotiSaadon** [comment]
אין אפשרות לעשות מעבר חברה

**Comment by wizayala** [comment]
הבנתי .
אעדכן את אפרת


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>
