### ISSUE TITLE
יבוא פריטים - גרסה 2018

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#280]
ביבוא פריטים יש כפילות במחירונים
זה קורה עם הקובץ האחרון ללא משקל 
![image](https://user-images.githubusercontent.com/16633745/89121913-d67a2480-d4cb-11ea-8054-ac3362daa08f.png)

**Comment by WizMotiSaadon** [comment]
אז זה לא קשור ל
itemin.hds

**Comment by wizayala** [comment]
מוטי
העברנו ללקוח קובץ itemin.hds  
מגרסה 2018asp2

**Comment by WizMotiSaadon** [comment]
נקווה לטוב
