### ISSUE TITLE
יבוא תנועות קופה זמני- הודעת שגיאה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#283]
מתקבלת הודעת שגיאה כזו לאחר התיקון 

---------------------------
HSD
---------------------------

sql = #UPDATE  STOCK SET STOCK.DOCNUMBER = DOCUMENTSDEF.CURRENFNUMBER     FROM STOCK,DOCUMENTSDEF     WHERE (    STOCK.ID  >=  11398        AND  STOCK.BATCH=9996         and status=6         AND DOCUMENTSDEF.FIXNUMERATOR = 1        And DOCUMENTSDEF.DocumentID = STOCK.DocumentID        )#
---------------------------
אישור  
---------------------------

**Comment by WizMotiSaadon** [comment]
תוקן
