### ISSUE TITLE
יבוא תנועות קופה זמני- רשימת שגויים 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#284]
לאחר הודעת השגיאה שמופיע בגיט #283  מופיעה הודעה "חלק מהרשומות לא נקלטו" ואז חלון השגוויים הבא שלא ברור מה לא תקין ולמה מתייחס 

![image](https://user-images.githubusercontent.com/16633745/89148752-63bc8800-d563-11ea-81bf-929dca56a4b9.png)

**Comment by WizMotiSaadon** [comment]
זה נראה שיש תנועות עם סכום אפס

אפשר קבצי קלט?

**Comment by WizMotiSaadon** [comment]
תוקן
