### ISSUE TITLE
יבוא תנועות קופה זמני- סוג תנועה 43

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#285]
רשומה שסוג התנועה שלה 43 מקבלת סטטוס 6 , למה ?

![image](https://user-images.githubusercontent.com/16633745/89148851-a0887f00-d563-11ea-93c8-ca1925517327.png)

**Comment by wizayala** [comment]
הצלחת בסוף לייצר את התקלה עם ס"ת 43 ?

**Comment by WizMotiSaadon** [comment]
תוקן
kupain.hds

**Comment by wizayala** [comment]
מעולה
