### ISSUE TITLE
יבוא תנועות קופה לקבוע - שגיאת המרה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#286]
מתקבלת ההודעה הבאה ביבוא תנועות קופה

---------------------------
HSD
---------------------------

Error in SQL :Arithmetic overflow error converting expression to data type int.
The statement has been terminated.

INSERT INTO CREDITPAYS (FID,FBANKFIRM,FTRANTIME,FVALIDMONTH,FVALIDYEAR,FL4DIGITS,LAST4DIG,FFIXEDSUM,PAYMENTSSUM,TYPE,DOCNUM,CURRENCYDLR,CURRENCY,STATUS,SUF,FTOTAL,SUFDLR,CREDITFIRM,FFIRMNAME,PAYMENTS,FPAYNUM,VALUEDATE,AVERAGEDATE,STOCKID,DETAILS,CARDDATE,ACCKEY,FDEALTYPE,FFIRSTSUM,FIRSTPAYMENT,FCREDTYPE,FCOINTYPE,FDEALCOD,FTRANDATE,FFIRSTTRANDATE,PRNTFORMAT,KUPANUM,BRANCHID) VALUES   ('',NULL,'01/01/1999',12,13,'4575423232',4575423232,0,0,'רגיל',33325,'$','ש"ח',0,333.000000000,333.000000000,0,'דיינרס','דיינרס',1,1-1,'08/03/2020','08/03/2020',11409,RIGHT('cheq',20),'12/31/2023','זכריה צביקה','01',0,333.000000000,1,1,'00','01/01/1999','01/01/1999',1,0,2)
---------------------------
אישור  
---------------------------

**Comment by WizMotiSaadon** [comment]
זה ארבע ספרות אחרונות, איזה תוכן מיובא עבור השדה ארבע ספרות אחרונות?

**Comment by wizayala** [comment]
אורך השדה היה גדול מ 4 תווים
אפשר לתת הודעת שגיאה מסודרת
ברגע שתיקנתי את השדה זה נקלט כהלכה 
importkupa.fl4digit

**Comment by WizMotiSaadon** [comment]
תיקנתי
