### ISSUE TITLE
יבוא דפי ישראכרט - PCH

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#287]
בתצוגה המקדימה של PCH שצריך להיות בין תווים 18-20 אלא מופיע מספר עסק 11-17 , מדוע ?

![image](https://user-images.githubusercontent.com/16633745/89156627-abe3a680-d573-11ea-989a-0d6ad9100924.png)

**Comment by wizayala** [comment]
מוטי, האם תוכל רק לתקן את זה כדי שאוכל לשחרר את הקבצים

**Comment by WizMotiSaadon** [comment]
אני לא מבין מה צריך לעשות

**Comment by wizayala** [comment]
לתקן תצוגה מקדימה 
הוספנו עמודה של סוג התחשבנות 
בעבור קבצים מסוג rst  מודל התחשבנות בתווים 16-18
בקבצים מסוג chsh, pch  מודל ההתחשבנות הוא בין התווים 18-20

**Comment by WizMotiSaadon** [comment]
> לתקן תצוגה מקדימה
> הוספנו עמודה של סוג התחשבנות
> בעבור קבצים מסוג rst מודל התחשבנות בתווים 16-18
> בקבצים מסוג chsh, pch מודל ההתחשבנות הוא בין התווים 18-20

תיקנתי

**Comment by wizayala** [comment]
למה בכלל אנחנו מציגים תווים 11-17 בכלל ?
![image](https://user-images.githubusercontent.com/16633745/89160613-ff58f300-d579-11ea-8acf-c702a0517f40.png)

**Comment by WizMotiSaadon** [comment]
אולי מישהו ביקש
לא זכור לי

**Comment by wizayala** [comment]
לא נורא. שישאר עד שיצעקו או יבקשו אחרת
