### ISSUE TITLE
יבוא תנועות קופה זמני- מספר עותקים 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#288]
יש להוסיף מספר עותקים לתנועות הנוצרות בטבלת stock
stock.copies
יש לקחת את מספר העותקים מתוך שדה 
DocumentsDef.copies  
להעתיק לתוך שדה 
stock.copies

**Comment by WizMotiSaadon** [comment]
את יכולה להוסיף את זה למסמך?

**Comment by wizayala** [comment]
[ממשק תנועות קופה לזמני.docx](https://github.com/wizayala/Hashavsheva/files/5015018/default.docx)

**Comment by WizMotiSaadon** [comment]
> יש להוסיף מספר עותקים לתנועות הנוצרות בטבלת stock
> stock.copies
> יש לקחת את מספר העותקים מתוך שדה
> DocumentsDef.copies
> להעתיק לתוך שדה
> stock.copies

תיקנתי
