### ISSUE TITLE
יבוא תנועות קופה - רשימת שגויים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#289]
קיבלתי ברישמת השגויים הודעת שגיאה שלא ברור לי למה השורה השנייה מתייחסת
![image](https://user-images.githubusercontent.com/16633745/89181631-d138da80-d59c-11ea-9c8c-1c200ab845ce.png)

**Comment by wizayala** [comment]
ההודעה השנייה מתייחסת לכך שחסרים הגדרת חשבונות במט"ח להפקדות אשראי

**Comment by WizMotiSaadon** [comment]
![image](https://user-images.githubusercontent.com/10919353/89183904-a486c200-d5a0-11ea-9541-caa37aeac33d.png)

**Comment by wizayala** [comment]
השגויים שלך הם כנראה אחרי שערכתי את הקובץ קלט

**Comment by wizayala** [comment]
לא משנה הבנתי את ההודעה
