### ISSUE TITLE
מסופון 2 - רשימה אב

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#29]
מסופון2 – חברות יופיעו לפי אב

**Comment by WizMotiSaadon** [comment]
לא מבין

**Comment by wizayala** [comment]
הכוונה היא שרשימת החברות במסופון 2 יופיעו לפי סדר הא-ב
![image](https://user-images.githubusercontent.com/16633745/73854472-4704f900-483b-11ea-9e26-e803139e7ee8.png)

**Comment by WizMotiSaadon** [comment]
תוקן
wizini.dll    (regsvr32.exe)
masofon2.exe

**Comment by wizayala** [comment]
תקין
