### ISSUE TITLE
יבוא תנועות קופה זמני- אסמכתא קבלת מט"ח 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#290]
כאשר אני מייבאת קבלת מט"ח שדה האסמכתא מקבל 0 במקום את הספרור הנוכחי כי שנעשה כשמדובר סוג מסמך של קבלה בשקלים
![image](https://user-images.githubusercontent.com/16633745/89181796-1230ef00-d59d-11ea-8e60-c775614598cb.png)

**Comment by WizMotiSaadon** [comment]
?ואני אמור לתקן משהו

**Comment by wizayala** [comment]
כן, אתה אמור לשתול שדה אסמכתא נוכחית כמו שאתה עושה בקבלה שיקלית

**Comment by WizMotiSaadon** [comment]
?אבל מה האסמכתא הנוכחית של קבלת מט"ח אצלך
בטבלה 
[DocumentsDef]

**Comment by wizayala** [comment]
צודק היה אצלי 0 , בודקת ....

**Comment by wizayala** [comment]
אליפות!!
טעות שלי
