### ISSUE TITLE
יבוא תנועות קופה לזמני - כותרת

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#291]
מוטי תעדכן בבקשה את הכותרת של המסך ליבוא תנועות קופה לזמני

![image](https://user-images.githubusercontent.com/16633745/89256053-f6285e80-d62b-11ea-9eb4-daefb85a250f.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
תודה
