### ISSUE TITLE
יבוא תנועות קופה זמני - מסך כניסה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#292]
במסך הראשי של יבוא תנועות קופה לזמני יש לבטל את האופציה של יבוא מקופה רושמת וגם לבטל את הסימון של כפילות מסמכים, לא רלוונטי
ישאר רק קליטת חשבונות חדשים וכתב ראי

![image](https://user-images.githubusercontent.com/16633745/89256263-646d2100-d62c-11ea-9051-f4b3c6f94e74.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
אחלה
