### ISSUE TITLE
יבוא תנועות קופה זמני - מסלול קבצים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#293]
בכניסה ראשונה ליבוא תנועות קופה בזמני , לא מציג את ברירת המחדל לחיפוש קבצי קלט טקסט 

![image](https://user-images.githubusercontent.com/16633745/89260182-6fc44a80-d634-11ea-8e1c-eb5dd515fc34.png)

לאחר כניסה ליבוא תנועות קופה לקבוע , יציאה וכניסה חוזרת ליבוא תנועות קופה בזמני , מסלול הקבצים חוזר למסלול ברירת המחדל 
![image](https://user-images.githubusercontent.com/16633745/89260242-8ff40980-d634-11ea-8ff2-598eea26d7a1.png)

**Comment by WizMotiSaadon** [comment]
imp_lib.hds
