### ISSUE TITLE
יבוא תנועות קופה - פורמט תאריך שגוי

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#294]
כשיש לי תאריך שגוי , המכיל תווים מתקבלת הודעה. האם אפשר לתקן להודעת שגיאה , תאריך לא תקין 

---------------------------
HSD
---------------------------

Error in SQL :Conversion failed when converting date and/or time from character string.

INSERT INTO STOCK (TERMINALDOC,REF3,REMARKS,REFERENCE,DOCUMENTID,ISSUEDATE,USEFID,CURRENCY,EVALCURRENCY,DOCNUMBER,DUEDATE,PAYDATE,VALUEDATE,DETAILS,BATCH,STATUS,ACCOUNTKEY,ACCOUNTNAME,ADDRESS,CITY,PHONE,AGENT,BRANCHID,KUPANUM,EXTRATEXT1,EXTRATEXT2,EXTRATEXT3,EXTRATEXT4,EXTRATEXT5,CONTACTMAIL,EXTRASUM1,EXTRASUM2,EXTRASUM3,EXTRADATE1,EXTRADATE2,EXTRANUM1,EXTRANUM2)  VALUES                  (0,0,'',0,31,'08/04/2020',2,'ש"ח','$',33322,'08/04/2020','08/04/2020','08/04/2020','',9996,6,'ידידיה סלע','נוצר בעקבות קליטת תנועות יומן','','','',0,2,0,'','','','','1@1.com','1@1.com',0,0,0,'08/31/2020','**8/11/20h0**',0,0)
---------------------------
אישור  
---------------------------

**Comment by WizMotiSaadon** [comment]
זה מודיע עכשיו?

**Comment by WizMotiSaadon** [comment]
תוקן
