### ISSUE TITLE
ייצוא תנועות מלאי - שליפת חתך

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#295]
לבקשת לקוחות בייצוא תנועות מלאי אנחנו שולפים הגדרות אחרונות של חתך , תאריכים , אסמכתאות וכו'
יש לשלוף רק את סוגי המסמכים וברירת המחדל תופיע בעבור כל החתכים האחרים

**Comment by WizMotiSaadon** [comment]
תוקן 
stockout.hds

**Comment by wizayala** [comment]
נבדק ע"י איילה - תקין 9.8.20
