### ISSUE TITLE
יבוא תנועות קופה - אשראי 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#296]
יש לעדכן שדה creditpays.fvalidyear  את הערך 21 במקום 13

**Comment by WizMotiSaadon** [comment]
תוקן
kupain.hds

**Comment by wizayala** [comment]
מוטי
מתברר שתמיד השנה 
creditpays.fvalidyear 
הוא תמיד שנה אחת קדימה מהשנה של תאריך המחשב.
האם תוכל לעשות חישוב של שנה אחת קדימה ואותה לשתול בתוך השדה הזה ?

**Comment by WizMotiSaadon** [comment]
אפשר ארבע ספרות?

למשל
2021

או שעדיף
21
?

**Comment by wizayala** [comment]
21

**Comment by WizMotiSaadon** [comment]
תוקן
kupain.hds

**Comment by wizayala** [comment]
תקין - איילה
