### ISSUE TITLE
שגיאה בפיצול

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#298]
![image](https://user-images.githubusercontent.com/69102026/89385244-fb5adb80-d707-11ea-9935-ab35526e5efa.png)

**Comment by wizayala** [comment]
הודעת השגיאה בחלון הראשון נובעת בגלל דיוק עשרוני של הסכום .
אם תסתכל בחלון שצרפתי תוכל לראות שבקבלה שאנחנו מייבאים (11499) יש דיוק עשרוני שאם נסכם את הכל מקבל 700.000000001
אם תראה את הפיצול בקבלה שהופקה מתוך התוכנה וכל לראות שהסכומים נרשמו בדיוק עשרוני של שתי ספרות אחרי הנקודה והתשלום הראשון תוקן בצורה כזו שבמקום 50 נרשם 49.99


![image](https://user-images.githubusercontent.com/16633745/89392701-8e007800-d712-11ea-97da-e0036d746377.png)

**Comment by WizMotiSaadon** [comment]
זה קשור אלי?

**Comment by wizayala** [comment]
מוטי 
אחרי שהראיתי לך את הבעיה אבקש מאיתן שישלח לך את תהליך חישוב פיצול התשלומים 
ואת  התשלומים יש לרשום נכון בטבלת 
creditpayssplit.suf
לרשום נכון את הסה"כ של הקבלה והתשלום הראשון וסכום כל תשלום נוסף 
creditpays.suf, creditpays.fTotal
creditpays.FirstPayment , creditpays.fFirstSum 
creditpays.PaymentsSum, creditpays.fFixedSum

מקווה שברור

**Comment by wizayala** [comment]
איתן שלח לך במייל את תהליך חישוב הסכומים כולל עיגול לשתי ספרות אחרי הנקודה

**Comment by wizayala** [comment]
TEMP<<Val({TC___[DB1][CreditPays]Payments},0)[;]

If (TEMP=1,
    c<<Val({TC___[DB1][CreditPays]Sum},2),
    Return (c) )[;]

sum<<Val(       Val({TC___[DB1][CreditPays]Sum})/Val({TC___[DB1][CreditPays]Payments}),9                        )[;]
Rsum<<Val(    Val({TC___[DB1][CreditPays]Sum})/Val({TC___[DB1][CreditPays]Payments}),2                         )[;]
If(Val(        Val(sum*TEMP)-Val(Rsum*TEMP)                   )!=0,
   b<<Val(   
                Val( 
                      Val({TC___[DB1][CreditPays]Sum})/Val(TEMP) 
                    ,2)   +
                 Val(   
                      Val(sum*TEMP)-Val(Rsum*TEMP) 
                      )   
               ,2),
        Return(b)     )[;]


a<<Val (      
              Val({TC___[DB1][CreditPays]Sum})/Val(TEMP)     
            ,2) [;]
Return(a)



התשובה מתעדכנת לתוך השדה : TC___[DB1][CreditPays]FirstPayment

**Comment by WizMotiSaadon** [comment]
תשלום ראשון הבנתי, מה עם שאר התשלומים?

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/89896089-8430b600-dbe5-11ea-991e-9f4daa586f10.png)

**Comment by wizayala** [comment]
יש עוד שדות , שים לב

![image](https://user-images.githubusercontent.com/16633745/89896135-9a3e7680-dbe5-11ea-8b47-1adbe2224596.png)

**Comment by WizMotiSaadon** [comment]
תיקנתי
השתמשתי בפונקציה משלי

**Comment by wizayala** [comment]
מוטי
החישוב שלך נכון אבל כשנכנסים לתוכנה מתבצע אוטומטית כ=עיגול ואז לא ניתן להפיק את המסמך.
הפתרון הוא שאתה תרשום את הסכומים עם דיוק עשרוני של שתי ספרות ואז הבעיה נפתרת

**Comment by WizMotiSaadon** [comment]
תיקנתי למאה אגורות

**Comment by wizayala** [comment]
מצויין - נראה טוב

**Comment by wizasher** [comment]
תשלום ראשון מצליח להפיק 
![image](https://user-images.githubusercontent.com/69102026/90106269-daba0380-dd4f-11ea-8ff5-5d288eaf29b0.png)
 שלחתי מייל עם קבצי בדיקה והסבר
תודה

**Comment by WizMotiSaadon** [comment]
איך זה עכשיו
עם ה
50.01 ?

**Comment by wizayala** [comment]
תקין
