### ISSUE TITLE
יבוא תנועות קופה לזמני - מסופון 2

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#299]
האם יש אפשרות להוסיף שורה ליבוא תנועות קופה בזמני ושם צריכה להיות אופציה של פתיחת חשבונות חדים ללא האפשרות של בדיקת כפילות 

![image](https://user-images.githubusercontent.com/16633745/89390218-1715b000-d70f-11ea-93e8-d1bb177a0835.png)

**Comment by WizMotiSaadon** [comment]
הוספתי
Masofon2.exe

[H-Mobile]<https://h-erp.co.il/h-mobile/>
