### ISSUE TITLE
סגירה של מסמך בסיס מול מסמך סוגר כשהם באותו קובץ קלט

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#3]
רק ביבוא מחלונות לחלונות אנחנו מאפשרים סגירה של מסמך בסיס מול מסמך סוגר כשהם באותו קובץ קלט.
כיום אתה לא מאפשר.
שים לב שעבדנו על זה בחודש 9.15 שם עשינו תיקון של הדלקת דגל של מסמך הבסיס 
ובדיקה של כמויות לסגירה

**Comment by WizMotiSaadon** [comment]
אולי בגלל שעשית סינון?

**Comment by wizayala** [comment]
לא עשיתי סינון

**Comment by WizMotiSaadon** [comment]
לא עשית הגבלה עם דוקומנט אידי = 4?

**Comment by wizayala** [comment]
לא

איילה ישראלי – בדיקות

052-9594258  04-9512832

אתר : www.hash.co.il<http://www.hash.co.il>  ,  דוא"ל : ayala@wizsoft.com<mailto:ayala@wizsoft.com>

[cid:image001.png@01D156A9.03AF0AC0]

**Comment by WizMotiSaadon** [comment]
![image](https://cloud.githubusercontent.com/assets/10919353/12536005/d9bbf134-c29f-11e5-990f-602cc3b63aad.png)

**Comment by wizayala** [comment]
????

איילה ישראלי – בדיקות

052-9594258  04-9512832

אתר : www.hash.co.il<http://www.hash.co.il>  ,  דוא"ל : ayala@wizsoft.com<mailto:ayala@wizsoft.com>

[cid:image001.png@01D156AC.FEBD5680]

**Comment by WizMotiSaadon** [comment]
הוספתי את הצילום מסך... שיהיה לתיעוד

**Comment by wizayala** [comment]
איך באמת מוסיפים צילום מסך , מבלי לשמור אותו תחילה כקובץ ?


איילה ישראלי – בדיקות

052-9594258  04-9512832

אתר : www.hash.co.il<http://www.hash.co.il>  ,  דוא"ל : ayala@wizsoft.com<mailto:ayala@wizsoft.com>

[cid:image001.png@01D156AE.6C9C5CE0]

**Comment by WizMotiSaadon** [comment]
צריך PASTE
במקום שכותבים

**Comment by WizMotiSaadon** [comment]
[import_V2016_24_January_2016.zip](https://github.com/wizayala/Hashavsheva/files/102847/import_V2016_24_January_2016.zip)
[import_V2017_24_January_2015.zip](https://github.com/wizayala/Hashavsheva/files/102848/import_V2017_24_January_2015.zip)
תוקן
