### ISSUE TITLE
יבוא שערי מט"ח בלי לחייב קוד עובד - מסופון 2

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#30]
ייבוא שערי מט"ח גם בשיטות אחרות מלבד בנק ישראל ללא קוד עובד

**Comment by WizMotiSaadon** [comment]
תיקנתי

**Comment by wizayala** [comment]
עדיין לא תקין . 
מאפשר לי להגדיר במסופון 2 ללא קוד עובד בפועל לאחר שמפעילים קובץ מסופון2 , בקובץ err מופיע הודעה לא ניתן לקלוט ללא קוד עובד
שלחתי לך במייל נפרד את קובץ err

**Comment by WizMotiSaadon** [comment]
תוקן
imp_lib.hds

**Comment by wizayala** [comment]
תקין
