### ISSUE TITLE
תנועות קופה זמני - קבלת מט"ח 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#300]
יש להגדיר ספרור לפי סעיף 8 המתוקן 
[ממשק תנועות קופה לזמני.docx](https://github.com/wizayala/Hashavsheva/files/5027194/default.docx)

8.	 שדה אסמכתא יכיל את הספרור הבא בתור לאותו סוג מסמך קשיח documentsdef.currenfnumber , לדוגמא המספר הבא בתור לקבלה הוא 10 וקובץ הקלט מכיל 5 רשומות של קבלות שונות שדה האסמכתא יהיה בכל חמשת הרשומות 10 , שדה האסמכתא יתעדכן בהתאם בשלב ההפקה של המסמך . מספר האסמכתא יהיה לפי התנאי הבא :

אם שדה stock.terminaldoc = 1 יש לקחת ספרור נוכחי , documentsdef.currenfnumber ברשומה שבה documentsdef.doumentid=54 

אם שדה stock.terminaldoc = 0 יש לקחת ספרור נוכחי , documentsdef.currenfnumber ברשומה שבה documentsdef.doumentid=31

**Comment by WizMotiSaadon** [comment]
לדעתי זה מתבצע

![image](https://user-images.githubusercontent.com/10919353/89392358-1e8a8880-d712-11ea-90c5-ea319b94c314.png)

**Comment by wizayala** [comment]
אתה לוקח את הספרור שמוגדר בסוג מסך 44
עבור סוג מסמך 44 יש לקחת את הספרור מסוג מסמך 31

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
תקין
