### ISSUE TITLE
יבוא תנועות מלאי - הכנסות בפריט פטור ממעמ

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#301]
יש לבצע בדיקה כאשר אני מקשרת חשבון הכנסות , יש לבדוק שחשבון ראשי של ההכנסות תואם להגדרות מעמ של פריט .
מכאן אם שדה items.VatExampt=1 
יש לוודא שבמידה ומקושר שדה הכנסות  
stockmoves.jurnalacc  
הוא שווה להכנסות פטורות ז"א 
accounts.mainaccount=8',44,44,48

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds

**Comment by wizayala** [comment]
מצויין

**Comment by wizayala** [comment]
נבדק ע"י איילה - תקין 9.8.20

**Comment by wizayala** [comment]
נבדק ע"י אשר ואיילה - תקין
