### ISSUE TITLE
יבוא תנועות מלאי - פריט חייב במעמ מול הכנסות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#302]
יש לבצע בדיקה כאשר אני מקשרת חשבון הכנסות , יש לבדוק שחשבון ראשי של ההכנסות תואם להגדרות מעמ של פריט .
מכאן אם שדה items.VatExampt=0 
יש לוודא שבמידה ומקושר שדה הכנסות  
stockmoves.jurnalacc  
הוא שווה להכנסות jhhcu, ז"א 
accounts.mainaccount=7,10,47

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds

**Comment by wizayala** [comment]
מצוין

**Comment by wizayala** [comment]
נבדק ע"י איילה - תקין 9.8.20

**Comment by wizayala** [comment]
נבדק ע"י אשר ואיילה - תקין
