### ISSUE TITLE
יבוא תנועות מלאי - חשבון פטור ממעמ

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#303]
יש לבצע בדיקה כאשר אני מקשרת חשבון הכנסות , יש לבדוק שחשבון ראשי של ההכנסות תואם להגדרות מעמ של חשבון לקוח  .
מכאן שאם מפתח הלקוח בתנועות המלאי שלי פטור ממעמ 
accounts.VatExampt=1
יש לוודא שבמידה ומקושר שדה הכנסות  
stockmoves.jurnalacc  
הוא שווה להכנסות פטורות ז"א 
accounts.mainaccount=8',44,44,48

**Comment by WizMotiSaadon** [comment]
איך זה קשור אלי?

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds

**Comment by wizayala** [comment]
הבדיקה היא לא מול הלקוח 
היא עדיין מול הפריט

**Comment by WizMotiSaadon** [comment]
אני לא מבין, 
"מה הכוונה "עדיין
?

**Comment by wizayala** [comment]
לא נעשית בדיקה מול הלקוח
יש לוודא האם לקוח פטור ממעמ או לא .
אם פטור יש לשלוף הכנסות פטורות מתוך רשומת הפריט

**Comment by WizMotiSaadon** [comment]
איפה רשמת לי בעבר שאני צריך 
"לשלוף הכנסות פטורות מתוך רשומת הפריט"
?

אני לא זוכר בקשה כזאת

**Comment by WizMotiSaadon** [comment]
salesacc חייבות

vatfreeesale 

purchacc הוצאות

**Comment by WizMotiSaadon** [comment]
> אם פטור יש לשלוף הכנסות פטורות מתוך רשומת הפריט

עכשיו אני שולף
?האם תקין

**Comment by wizayala** [comment]
נבדק ע"י אשר ואיילה - תקין
