### ISSUE TITLE
יבוא תנועות מלאי - חשבון חייב במעמ

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#304]
יש לבצע בדיקה כאשר אני מקשרת חשבון הכנסות , יש לבדוק שחשבון ראשי של ההכנסות תואם להגדרות מעמ של חשבון לקוח  .
מכאן שאם מפתח הלקוח בתנועות המלאי שלי חייב במעמ 
accounts.VatExampt=0
יש לוודא שבמידה ומקושר שדה הכנסות  
stockmoves.jurnalacc  
הוא שווה להכנסות פטורות ז"א 
accounts.mainaccount=7,10,47

**Comment by WizMotiSaadon** [comment]
לא הבנתי למה זה קשור אלי,
אם יש לקוח פטור ממע"מ ויש לו MAINACCOUNT  לא מתאים אני אמור להתריע על זה?

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds

**Comment by wizayala** [comment]
נבדק ע"י אשר ואיילה - תקין
