### ISSUE TITLE
יבוא קופה זמני - קובץ טקסט

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#306]
ביבוא קובץ טקסט מאחד שתי רשומות לרשומה אחת למרות שסוג תנועה שונה 
אשלח קבצי קלט במייל נפרד

**Comment by WizMotiSaadon** [comment]
?האם אני מאחד גם ביבוא קופה לקבוע
?ואם כן, האם זה תקין

**Comment by WizMotiSaadon** [comment]
מה עם זה,
האם זה מבוטל?

**Comment by wizayala** [comment]
לדעתי זה תקין , אבדוק שוב

**Comment by wizayala** [comment]
מוטי
עדיין אתה מאחד שתי רשומות שסוג התנועה שונה , האחד 33 והשני 43
שורה תחתונה עדיין לא תקין

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
תקין - איילה

**Comment by wizasher** [comment]
תקין - אשר
