### ISSUE TITLE
יבוא קופה זמני - כותרת פרמטרים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#307]
ביבוא קובץ טקסט האם אפשר לשנות כותרת של מטבע מכירה ( שורה 14) למטבע מוביל בקבלה 

![image](https://user-images.githubusercontent.com/16633745/89514533-a9d15000-d7de-11ea-9e73-21fab18cfe19.png)

**Comment by WizMotiSaadon** [comment]
תוקן
import_v.exe

**Comment by wizayala** [comment]
מצויין תודה 

![image](https://user-images.githubusercontent.com/16633745/89726385-bc3bcb80-da22-11ea-821b-019e18ad27a4.png)
