### ISSUE TITLE
יבוא קופה זמני -  איחוד תנועות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#308]
בקבצי קלט ששלחתי לך במייל תראה שאם אתה קולט את הממשק הוא מאחד בין שתי הרשומות. לא ניתן לאחד רשומות גם אם החשבון והאסמכתא זהים, שני אמצעי תשלום זהים לא יוכלו להתקבל באותה קבלה ז"א לא ניתן לקלוט שתי תנועות אשראי האחת ויזה,ף השנייה ישראכרט לאותה קבלה בגלל שהאסמכתא והלקוח תאריך זהים .

**Comment by WizMotiSaadon** [comment]
?אז אני צריך להודיע על שגיאה

?או לפצל

**Comment by wizayala** [comment]
מוטי
טעות שלי
ניתן לקלוט יותר מכרטיס אשראי אחד לאותה קבלה

סוגרת את הרשומה זו טועות שלי
