### ISSUE TITLE
יבוא תנועות קופה זמני - סטטוס 6 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#310]
ביבוא תנועות קופה זמני כשיש רשומה שלסוג תנועה 43 (קבלת תרומה) מתקבלת הודעות שגיאה ואז יוצא מהתוכנה :

![image](https://user-images.githubusercontent.com/16633745/89726941-07f17380-da29-11ea-9096-de43eed2d0bd.png)

---------------------------
HSD
---------------------------

Error in SQL :Incorrect syntax near the keyword 'SET'.

UPDATE  SET EXTRATEXT1 = NULL FROM STOCK WHERE ('' = EXTRATEXT1 AND    STOCK.BATCH=9996  AND STOCK.ID >= 11631  AND STOCK.STATUS = 6 )
---------------------------
אישור  
---------------------------
---------------------------
HSD
---------------------------

Incorrect syntax near the keyword 'SET'.

---------------------------
אישור  
---------------------------

**Comment by wizayala** [comment]
אגב תקלה דומה הייתה ביבוא מאו.די.בי.סי ותוקנה
ראה גיט #283

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizasher** [comment]
נבדק - תקין 10.8 אשר

**Comment by wizayala** [comment]
תקין
