### ISSUE TITLE
יבוא תנועות מלאי - שליפת שער

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#311]
האם יש אפשרות לשליפת שער באופן אוטומטי ?
במידה ויש לי מטבע שונה משקל  בתנועה
שקל<> stockmoves.CurrencyCode
יישלף שער מתוך טבלת השערים  rates בהתאמה לתאריך המסמך    stock.valuedate
צריכה להיות התאמה של מטבע ותאריך
ואז השער יישתל באופן אוטומטי בשדה 
stockmoves.rate

**Comment by WizMotiSaadon** [comment]
אפשר,
אני צריך לבקש אישור מהדס?

**Comment by WizMotiSaadon** [comment]
מה קורה עכשיו?
אם לא מייבאים שער בתנועה?

האם אני מודיע על שגיאה?

**Comment by WizMotiSaadon** [comment]
select rate from rates where CurrencyCode = '~~MovementCurrencyCode^'  and DatF = '~~TempValueDate^'

**Comment by wizayala** [comment]
אם יש לי תנועה עם מט"ח ללא שער אנחנו נותנים הודעת שגיאה

**Comment by wizayala** [comment]
זה שיפורים , זה דחוף כרגע !!!

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds

**Comment by wizasher** [comment]
עדין לא שולף שער בתנועה ולא מודיע על תקלה

**Comment by WizMotiSaadon** [comment]
מה המטבע של התנועה?

**Comment by wizasher** [comment]
CAD

**Comment by WizMotiSaadon** [comment]
הוספתי לוגים לקובץ 
mlayin.hds
תוכל לנסות שוב ואז לשלוח לי
WizImport.log
ממחיצת התוכנה?

**Comment by wizasher** [comment]
שלחתי במייל , תודה

**Comment by WizMotiSaadon** [comment]
> עדין לא שולף שער בתנועה  

תראה לי צילום מסך של הטבלה
stockmoves
בשביל שאראה שזה לא שולף

**Comment by wizasher** [comment]
![image](https://user-images.githubusercontent.com/69102026/90108907-a6484680-dd53-11ea-89b7-e81ddba00219.png)
בבקשה

**Comment by WizMotiSaadon** [comment]
אבל אני רואה שהמטבע זה שקל
אמרת לי שמטבע התנועה הוא 
CAD

**Comment by wizayala** [comment]
מוטי
האם הקובץ שנמצא בזיפ הוא הקובץ שאיתו אוכל לבדוק את הגיט הזה ?

**Comment by WizMotiSaadon** [comment]
כן, עם ההודעות

**Comment by wizayala** [comment]
הודעה 1:


---------------------------
HSD
---------------------------

(SQL)UpdateStockMovesRecord sql = #INSERT INTO StockMoves (DUEDATE,DETAILS,WAREHOUSE,EXTRANUM1,EXTRANUM2,EXTRADATE1,EXTRADATE2,  EXFILE,Instance,BatchNum,Localization,WarrentyDate,CancelDate,ExpireDate, BaseDate,StockID,                                     ItemKey,                                          Agent,    Reference,                                     Price,oprice,                                     Quantity,orate,                              DiscountPrc,                                   CurrencyCode,Rate,                                                    DocumentID,   VatExampt,Packs,ItemName,Unit,SaleTaxPrc,AlterNum,CommisionPrc,PurchQuantity,supplyquantity,BranchID,LineNum,BaseLineNum,ExtraText1,ExtraText2,ExtraSum1,ExtraSum2,BaseMoveID,BaseDocType,costcode,ALTERNAME,JURNALACC)  VALUES                            ('09/01/2020',left('',20),0,0,0,'09/01/2020','09/01/2020',  '','','','','1980-01-01',#1/1/1999#,  #09/01/2020#,  #09/01/2020#,14187,'7001',0,0,20.220000000,20.220000000,12.000000000,1,0,  'ש²ח',        1,11,0,0,'כוסות חד פעמיות','',0,'',0,12.000000000,12.000000000,1,0,0,'','',0,0,0,0,'','',''   );#
---------------------------
אישור  
---------------------------
האם אתה צריך את ההודעות ?

**Comment by wizayala** [comment]
מבדיקה ראשונית שלי נראה שעובד בצורה תקינה.
האם קובץ 
mlayin.hds
 שנמצא בזיפ כולל את התיקונים שעשינו של מחסן ופרטים מרשומת כותרת לרשומת תנועה ?

**Comment by wizayala** [comment]
המערכת שותלת בטבלת 
rates 
שערים 31 יום קדימה שהלקוח אינו רואה מתוך התוכנה 
לטעמי קצת יכול לבלבל לקוח , ממתינה לתגובתה של אפרת

**Comment by WizMotiSaadon** [comment]
> מבדיקה ראשונית שלי נראה שעובד בצורה תקינה.

את יכולה להראות לי צילום מסך של
stockmoves
?

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/91855397-ca6db800-ec6d-11ea-9edd-91471ded49a5.png)

**Comment by WizMotiSaadon** [comment]
נראה טוב,
אז נשאר לנו רק להוריד את ההודעות?

**Comment by wizayala** [comment]
כן

**Comment by WizMotiSaadon** [comment]
> כן

הורדתי הודעות

**Comment by wizayala** [comment]
תקין גם אצל אשר
