### ISSUE TITLE
יבוא תנועות קופה זמני טקסט - סטטוס 6

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#312]
מתקבלת הודעת שגיאה גם עבור תנועות עם סוג תנועה 33
ראה גיט #310 
---------------------------
HSD
---------------------------

Error in SQL :Incorrect syntax near the keyword 'SET'.

UPDATE  SET EXTRATEXT1 = NULL FROM STOCK WHERE ('' = EXTRATEXT1 AND    STOCK.BATCH=9996  AND STOCK.ID >= 11633  AND STOCK.STATUS = 6 )
---------------------------
אישור  
---------------------------

**Comment by wizayala** [comment]
אגב 
התקלה הזו עכשיו גם ב odbc 
הקבצים האחרונים "קילקלו" מה שקודם עבד

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizasher** [comment]
נבדק - תקין 10.8 אשר

**Comment by wizayala** [comment]
תקין - איילה 10.8
