### ISSUE TITLE
קליטת תנועות מלאי ODBC עם חשבון הכנסות

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#313]
אם מקשרים חשבון הכנסות פטור /חייב מקבלים הודעה ,
"הגדרות המע"מ של חשבון המסמך אינן מתאימות לחשבון הוצאות .
![image](https://user-images.githubusercontent.com/69102026/89766961-aa7d2580-db01-11ea-99aa-d99f83a5fc8b.png)

**Comment by wizayala** [comment]
מוטי,
אתה צריך קבצי קלט לדוגמא ?

**Comment by WizMotiSaadon** [comment]
אבל מה חשבון המסמך ומה ה 
vatexamp 
שלו
?

**Comment by wizayala** [comment]
פריט וחשבון חייבים במעמ, אין בפריט חשבון הכנסות / הוצאות

**Comment by WizMotiSaadon** [comment]
...החלפתי את המספרים

תיקנתי אבל אני עובד עדיין על באג 303

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds

**Comment by wizayala** [comment]
עדיין אותה תקלה

**Comment by wizayala** [comment]
אצלי עכשיו תקין , אשר גם אצלך תקין ?

**Comment by wizayala** [comment]
תקין
