### ISSUE TITLE
יבוא תנועות מלאי - חשבון ראשי/ מעמ/ סוג מסמך

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#314]
מקווה שזה יעשה סוג של סדר 

  
[בדיקת הכנסה.xlsx](https://github.com/wizayala/Hashavsheva/files/5050911/default.xlsx)

**Comment by WizMotiSaadon** [comment]
כשאת רושמת "בהוצאות אין התייחסות לדגל מעמ"

את מתכוונת "במסמך רכש אין התייחסות לדגל מעמ בפריט או בחשבון"  ?

**Comment by WizMotiSaadon** [comment]
תוקן לפי הטבלה

**Comment by wizayala** [comment]
מוטי
אני יכולה לסגור את הגיט הזה ? אתה צריך אותו פתוח בגלל האקסל ?
