### ISSUE TITLE
יבוא תנועות מלאי - פריט פטור הכנסה חייבת 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#315]
ביבוא תנועות מלאי יש לבדוק אם הפריט הוא פטור ממעמ items.vatexampt=1  יש לבדוק שכרטיס ההכנסות שמקושר ( jurnalacc) צריך להיות מסוג של הכנסות פטורות (לפי הטבלה )

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
תקין אך אפשר שפירוט ההודעה יהיה בעברית פשוטה

![image](https://user-images.githubusercontent.com/16633745/89877121-4ffacc80-dbc8-11ea-8d68-7576fcb3668c.png)

**Comment by WizMotiSaadon** [comment]
כלומר במקום
ACCKEY
לרשום
מפתח חשבון
וכו
?

[H-Mobile]<https://h-erp.co.il/h-mobile/>

**Comment by wizayala** [comment]
באישורו של אשר נשאיר את ההודעה כפי שהיא
