### ISSUE TITLE
יבוא תנועות מלאי - הכנסה מול סוג מסמך 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#316]
יש לבדוק שכרטיס שמקושר לשדה jurnalacc   מוגדר כהוצאה ( mainaccount=3,46,49) אינו יכול להיות בסוג מסמך שהוא מכירה 
לדוגמא - חשבון שמקשור לשדה jurnalacc שהחשבון הראשי שלו הוצאות ( accounts.mainaccount=3) לא ניתן להפיק מסמך מסוג מכירה 
documentid=1   שמוגדר כ documentsdef.salesdoc=1

מקווה שיותר ברור

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
גם פה אשמח שתופיע הודעה ברורה יותר 

![image](https://user-images.githubusercontent.com/16633745/89877547-e62ef280-dbc8-11ea-895d-bee6473fa9fb.png)

**Comment by wizayala** [comment]
נשאיר את ההודעה כפי שהיא מופיעה עכשיו באישורו של אשר :)
