### ISSUE TITLE
יבוא תנועות קופה לזמני - טבלת creditpayssplit

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#317]
מוטי
בהמשך לשיחתנו עם איתן והדס , בממשק תנועות קופה לזמני , לא ירשמו תנועות לתוך טבלת 
creditpayssplit 
יש עדיין לעשות את החשיוב של הסכמום ( סכום ראשון וסכום כל תשלום ) לפי מה שאיתן רשם 
אבל לאחר ההפקה של איתן ירשמו התנועות בהתאמה בתוך טבלת credippayssplit

**Comment by WizMotiSaadon** [comment]
> מוטי
> בהמשך לשיחתנו עם איתן והדס , בממשק תנועות קופה לזמני , לא ירשמו תנועות לתוך טבלת
> creditpayssplit

תוקן

**Comment by wizayala** [comment]
מעולה
