### ISSUE TITLE
יבוא תנועות קופה זמני - קבלת מטח תשלומים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#318]
בקבלת מט"ח התשלום הראשון מתקזז מהסכום המשוערך ( השקלי) במקום מסכום המט"ח 
במזהה מלאי 12445
הפקתי קבלת מט"ח ע"ס 100$ 
סכום קבלה משוערך  350שקלים
שני תשלומים, תשלום ראשון ע"ס 30 
תראה שסכום התשלום השני הוא 320 במקום 60
לעומת זאת תראה קבלת מט"ח שהפקתי מהתוכנה , מזהה 12443
סכום קבלת מט"ח 100$
סכום קבלה משוערך 300 ש"ח 
תשלום ראשון 40
תשלום שני 60

![image](https://user-images.githubusercontent.com/16633745/90107581-b3fccc80-dd51-11ea-8291-d0d24cfc6768.png)

**Comment by WizMotiSaadon** [comment]
תוקן
kupain.hds

**Comment by wizayala** [comment]
תקין
