### ISSUE TITLE
יבוא קבלות זמני - חיוב סכום שיערוך שקלי ברשומה מטחית

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#319]
אין לאפשר ממשק של קבלת מט"ח ללא סכום משוערך, יש לתת הודעת שגיאה.
בתוכנה לא מאפשר קבלת מט"ח ללא סכום שקל 

![image](https://user-images.githubusercontent.com/16633745/90109835-07bce500-dd55-11ea-9c6d-9c43dcc17c6a.png)

**Comment by WizMotiSaadon** [comment]
.לפי מה שאני רואה בקוד אני לא מאפשר
?את הצלחת לקלוט אשראי עם מטבע חוץ וסכום שקלי אפס

**Comment by wizayala** [comment]
שולחת לך קבצי קלט

**Comment by WizMotiSaadon** [comment]
תיקנתי
kupain.hds

**Comment by wizayala** [comment]
מעולה

![Uploading image.png…]()
