### ISSUE TITLE
יבוא תנועות יומן  -שיטה מפורטת/ מקוצרת

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#322]
בכניסהלשיטה מפורטת או מקוצרת במידה ובמחיצה נמצאים קבצים
movein.doc   movein.dat 
מתקבלת הודעה חסר קובץ פרמטרים
ההודעה הזו מיותרת מכיוון ששיטה מפורטת או מקוצרת צריכה לפנות לקובץ movein.dat בלבד

![image](https://user-images.githubusercontent.com/16633745/90328516-93c54b80-dfa5-11ea-869f-27ae421e0243.png)
![image](https://user-images.githubusercontent.com/16633745/90328519-9b84f000-dfa5-11ea-8531-dadb9f3a4ab3.png)

**Comment by WizMotiSaadon** [comment]
תוקן
Prm2Ini.dll

**Comment by wizayala** [comment]
מעולה
