### ISSUE TITLE
יבוא תנועות מלאי - שדה מחסן 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#324]
מוטי 
אותו תיקון שעשינו עבור שדה פרטים יש לעשות עבור שדה מחסן 
הכוונה שאם שדה מחסן מוגדר רק בכותרת , לדוגמא בקובץ פרמטרים מוגדר מחסן בשורה 12 ולא מוגדר לי מחסן בתנועה שורה 72
יש להעתיק שדה מחסן 
importstock.wharehouse
לתוך שדה 
importstock.smwharehouse

**Comment by wizayala** [comment]
שהתיקון יהיה על קובץ mlayin.hds  ששלחת לי במייל

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
מוטי
עדיין לא תקין 
אם שדה מחסן אינו מקושר במחסן בתנועה , יש להעתיק שדה מחסן בכותרת שמקושר 
מה שקורה כרגע הוא שאנחנו שותלים מחסן מתוך רשומת המשתמש ( אלו הם הגדרות מחסן בהגדרות חברה)
אשלח לך במייל נפרד קבצי קלט לדוגמא

**Comment by WizMotiSaadon** [comment]
נתתי עדיפות לכותרת
[H-Mobile]<https://h-erp.co.il/h-mobile/>

**Comment by wizayala** [comment]
מעולה תודה 
נראה תקין בטקסט ובאו.די.בי.סי

**Comment by wizayala** [comment]
מוטי
פתחתי את הגיט, מהסיבה שהקובץ האחרון אינו כולל את התיקון הזה.
שים לב כאשר מוגדר שדה מחסן בשורה 12 בקובץ פרמטרים ולא מוגדר שדה מחסן בשורה 72
יש להעתיק את המחסן משורה 12 לשורות של התנועה הכוונה ל 
stocmoves.wharehous

**Comment by wizayala** [comment]
אתה מכניס לשדה מחסן בשורת התנועה את המחסן לפי הגדרות חברה

**Comment by wizayala** [comment]
שים לב שדה מחסן גם יכול להכיל ערכים שונים.
שולחת לך במייל קובץ אקסל תסתכל על שורות של אסמכתא 7846

**Comment by wizayala** [comment]
מעולה נראה אצלי תקין
העברתי גם לבדיקתו של אשר

**Comment by wizasher** [comment]
אצלי תקין 
![image](https://user-images.githubusercontent.com/69102026/92741281-1b289380-f387-11ea-8e61-eea07ba3daec.png)
