### ISSUE TITLE
יבוא פריטים - שגיאת המרה במחיר

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#325]
ההודעה הבאה מתקבלת כאשר במחיר שמקושר מופיע הערך נקודה **.**

UPDATE  items  SET items.Price = IMPORTitem.Price   	  FROM items,IMPORTitem  WHERE	(    items.itemKEY = IMPORTitem.itemKEY 	           AND LEN( LTRIM(IMPORTitem.Price)) <> 0           AND IMPORTitem.Price IS NOT NULL           AND IMPORTitem.ERRORMESSAGE IS NULL  )
Error converting data type varchar to float.

יש לתת הודעה מתאימה 
שולחת לך במייל נפרד קבצי קלט שתוכל לראות דוגמא

**Comment by WizMotiSaadon** [comment]
תוקן
odbcimp.exe

**Comment by wizayala** [comment]
לא מתקבלת שום הודעת שגיאה.
נקלט בהצלחה 
מתורגם ל 0.00
נראה לי תקין שאין הודעת שגיאה , ממתינה לתשובתה של אפי בעניין .

**Comment by wizayala** [comment]
מוטי
אפרת מבקשת שדווקא השורה הזו תצא עם הודעת שגיאה

**Comment by WizMotiSaadon** [comment]
אז צריך לבקש מאיליה שהפונקציה 
במנוע
IsStringReal
תחזיר אפס אם היא מקבלת נקודה

אין לי שליטה על הפונקציה הזאת

**Comment by wizayala** [comment]
אפרת אמרה שלא מצא אידאלי, אבל אם זה אומר לדבר עם איליה אז נשאיר את זה כך
