### ISSUE TITLE
יבוא חשבונות - שדה טקסט עם פסיק בקובץ או.די.בי.סי

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#326]

**Comment by wizayala** [comment]
UPDATE  ACCOUNTS  SET ACCOUNTS.MAXCREDIT = IMPORTACCOUNT.MAXCREDIT   	  FROM ACCOUNTS,IMPORTACCOUNT  WHERE	(    ACCOUNTS.ACCOUNTKEY = IMPORTACCOUNT.ACCOUNTKEY     And IMPORTACCOUNT.ID = (select MAX(id) from ImportAccount where ACCOUNTS.ACCOUNTKEY = IMPORTACCOUNT.ACCOUNTKEY AND LEN( LTRIM(IMPORTACCOUNT.MAXCREDIT)) <> 0           AND IMPORTACCOUNT.MAXCREDIT IS NOT NULL)   	           AND LEN( LTRIM(IMPORTACCOUNT.MAXCREDIT)) <> 0           AND IMPORTACCOUNT.MAXCREDIT IS NOT NULL           AND IMPORTACCOUNT.ERRORMESSAGE IS NULL  )

Error converting data type varchar to float.

שולחת לך קבצי קלט

**Comment by wizayala** [comment]
הייתה לנו תקלה דומה בפקודות יומן , #273

**Comment by WizMotiSaadon** [comment]
> 
> שולחת לך קבצי קלט

לא הגיע

**Comment by WizMotiSaadon** [comment]
תוקן
odbcimp.exe
