### ISSUE TITLE
יבוא תנועות קופה - תשלום של מספר כרטיסי אשראי

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#328]
ביבוא תנועות קופה **לקבוע** כאשר יש לי יותר מכרטיס אשראי אחד באותה קבלה אך יש לי שני מטבעות שונים יש להפריד לשתי קבלות.
כרגע אתה מאחד לקבלה אחת.

**Comment by WizMotiSaadon** [comment]
בקבצי קלט ששלחת לי אני רואה שלא קישרת מטבע
זה בכוונה ככה?

**Comment by wizayala** [comment]
טעות שלי
סוגרת את הגיט
