### ISSUE TITLE
ביבוא קופה לזמני יש לפצל כל רשומת קלט לטרנסקציה נפרדת

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#329]
לבקשת הדס , כאשר יש לי יותר מאמצעי תשלום אחד **באותה קבלה לאותו מטבע** האם יש אפשרות להפריד את זה לשתי רשומות בטבלת
stock 
כדי שבהפקה ברצף (החלק של איתן ) יהיו שתי קבלות .
**מדובר רק על יבוא תנועות קופה לזמני**

**Comment by WizMotiSaadon** [comment]
> כאשר יש לי יותר מאמצעי תשלום אחד 
אבל
בטלפון אמרת לי שאני צריך להפריד גם אם כרטיס האשראי שונה

**Comment by WizMotiSaadon** [comment]
אני יכול להפריד לפי ארבע ספרות אחרונות
זה מתאים?

**Comment by wizayala** [comment]
לא בטוחה

**Comment by WizMotiSaadon** [comment]
?מאיפה אני אמור לקחת מספר כרטיס אשראי

**Comment by wizayala** [comment]
כשיש לי יותר מרשומה אחת לאותו לקוח, לאותה קבלה ואותו תאריך  אז אפשר להפריד לשתי רשומות ולא לאחד

**Comment by wizayala** [comment]
> ?מאיפה אני אמור לקחת מספר כרטיס אשראי

אנחנו לא מייבאים מספר כרטיס רק 4 ספרות

**Comment by WizMotiSaadon** [comment]
> > ?מאיפה אני אמור לקחת מספר כרטיס אשראי
> 
> אנחנו לא מייבאים מספר כרטיס רק 4 ספרות

?אז לפי איזה שדה להפריד

**Comment by WizMotiSaadon** [comment]
בשיחה טלפונית נסגר לרשום בסטוק בטרנסקציה נפרדת כל פעולת החלפה

**Comment by WizMotiSaadon** [comment]
תוקן
kupain.hds

**Comment by wizayala** [comment]
אחלה , תודה
