### ISSUE TITLE
עברית הפוכה בקבצי טקסט 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#33]
כאשר בקובץ טקסט יש עברית תקינה אז בתצוגה המקדימה ובקליטה :
ללא סימון ansi רואים עברית הפוכה והקליטה היא תקינה ( פה אתה הופך בגלל דוס)
עם סימון ansi  רואים עברית תקינה והקליטה הפוכה ( פה זה בגלל כתב ראי)

**Comment by WizMotiSaadon** [comment]
תוקן
igib_imp.dll

**Comment by wizayala** [comment]
תקין בדקתי עברית חלונות תקינה, עברית חלונות הפוכה ועברית דוס

**Comment by wizayala** [comment]
מוטי
התיקון בסדר נראה תקין. במקביל פתחתי לך קריאה #43 , האם זה משהו שאשר לתקן?
אני מעדיפה לשלוח קבצי תיקון פעם אחת


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>
