### ISSUE TITLE
יבוא תנועות קופה - שגיאה בסוג תנועה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#330]
לקוח בטעות מייבא מלל לשדה ס"ת האם אפשר שתתקבל הודעה בהתאם ולא ההודעה הבאה: 

![image](https://user-images.githubusercontent.com/16633745/91034273-6d3e8a80-e60d-11ea-80df-0248f0a841c2.png)

**Comment by wizayala** [comment]
שולחת לך במייל נפרד קבצי קלט

**Comment by WizMotiSaadon** [comment]
> שולחת לך במייל נפרד קבצי קלט

לא הגיע
תיקנתי בלי קבצי קלט

**Comment by wizayala** [comment]
עדיין אותה הודעת שגיאה
שלחתי לך קבצי קלט

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
מעולה
![image](https://user-images.githubusercontent.com/16633745/91043020-746c9500-e61b-11ea-8af1-6cbf34cffcfe.png)
