### ISSUE TITLE
יבוא תנועות קופה לזמני - רישום בטבלת importlog

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#331]
מה הסיבה שלא נרשם
 stockid  
בטבלת 
importlog

![image](https://user-images.githubusercontent.com/16633745/91144041-2065bd00-e6bc-11ea-9ab7-51843fc7896e.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
מצויין

![image](https://user-images.githubusercontent.com/16633745/91147299-bdc2f000-e6c0-11ea-870d-7c962de38127.png)
