### ISSUE TITLE
יבוא תנועות מלאי - הוספת צ'ק בוקס

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#332]
מוטי
לבקשת אפרת האם אפשר להוסיף צ'ק בוקס לשאלה האם לשלוף שערים
בהתאם לתיקון שעשית בגיט #311 

![image](https://user-images.githubusercontent.com/16633745/92088923-353a0300-edd6-11ea-9ea5-967896bbbdb1.png)

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds

**Comment by wizayala** [comment]
מעולה , תודה
