### ISSUE TITLE
מסופון2 - בחירת מנה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#333]
מוטי 
במסופון 2 ניתן לבחור מספר מנה בהנה"ח 
אין לאפשר קליטה למנות קבועות ולמנות 9992 ו9993

![image](https://user-images.githubusercontent.com/16633745/92318965-1462ef00-f01c-11ea-972a-a1a1c08531b9.png)

**Comment by WizMotiSaadon** [comment]
Wizini.dll
תוקן

**Comment by wizasher** [comment]
אצלי תקין

**Comment by wizayala** [comment]
תקין
