### ISSUE TITLE
יבוא כותרות מסמכים - הודעת שגיאה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#335]

**Comment by wizayala** [comment]
יש היפוך בין העמודות 

![image](https://user-images.githubusercontent.com/16633745/92321489-184e3b80-f033-11ea-8cc7-3ed64da25f53.png)

**Comment by wizayala** [comment]
מוטי , האם תוכל לתקן את ההיפוך הזה בין העמודות 
![image](https://user-images.githubusercontent.com/16633745/97101441-17866d00-16a6-11eb-86e1-2b57ca85063f.

**Comment by WizMotiSaadon** [comment]
אני לא מצליח לראות את ההיפוך
איך היית רוצה שזה יראה?

**Comment by wizayala** [comment]
השגיאה 31/12/201 צריכה להיות בעמודה השמאלית שהכותרת שלה היא "פירוט השגיאה"
השגיאה "תאריך נוסף לתנועה לא תקין יופיע בעמודה הימנית שהכותרת שלה היא "שגיאה " 
מקווה שברור

**Comment by WizMotiSaadon** [comment]
תוקן
stockheaderin.hds

**Comment by wizayala** [comment]
תקין
