### ISSUE TITLE
יבוא תנועות קופה זמני - קבלה במט"ח 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#336]
בקבלות שהמטבע המוביל הוא מט"ח לא מתבצעת בדיקה שסכום תשלום ראשון הוא קטן מסכום הקבלה  הכולל
ואז הקבלה נראית כל : 
![image](https://user-images.githubusercontent.com/16633745/92385206-20cd7180-f11a-11ea-85c8-051c2668d107.png)

לעומת זאת כאשר אני מבצעת את אותו הדבר בקבלה שהמטבע המוביל הוא שקל מתקבלת הודעת שגיאה מתאימה

![image](https://user-images.githubusercontent.com/16633745/92385173-114e2880-f11a-11ea-9d2f-7d9a1b75153e.png)

**Comment by WizMotiSaadon** [comment]
תוקן
kupain.hds

**Comment by wizasher** [comment]
אצלי עובד מצוין - תודה

**Comment by wizayala** [comment]
גם אצלי עכשיו מתקבלת הודעה בני המטבעות

![Uploading image.png…]()
