### ISSUE TITLE
יבוא חשבונות - תזוזה ביבוא odbc

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#337]
ביבוא חשבונות בשיטת 
odbc
חלה ככל הנראה תזוזה בשדות של הנוספים , כתוצאה מכך מתעדכנים נתונים בשדות הלא נכונים 
מדובר בשינוי בין הגרסאות 2018 לגרסה 2020

**Comment by WizMotiSaadon** [comment]
תוקן לפריטים וחשבונות

odbcimp.exe

**Comment by wizayala** [comment]
מה הייתה התקלה ? כדי שאוכל לשחזר אותה

**Comment by wizayala** [comment]
התקלה גם בפריטים ? 
למה?

**Comment by WizMotiSaadon** [comment]
צריך להכין קובץ 
WPR 
בגרסה ישנה, 
לקשר שדות הערות נוספות
ואז לפתוח אותו 
בגרסה הלא תקינה
ואחרי זה בגרסה התקינה

**Comment by wizayala** [comment]
עשיתי את, ראיתי את התקלה ואת התיקון. העברתי כבר  לת"א
