### ISSUE TITLE
יבוא חשבונות ופריטים- או.די.בי.סי

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#338]
בעקבות השינוי שנעשה , הוספת שתי שורות ריקות , יש לרשום משהו כמו 
לא בשימוש
לא פעיל זמנית

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/95451444-7478e800-0970-11eb-99c6-d259cb5ce768.png)

**Comment by WizMotiSaadon** [comment]
תוקן
odbcimp.exe

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/95670850-1ed35400-0b99-11eb-9776-9828f44a34da.png)

![image](https://user-images.githubusercontent.com/16633745/95670855-327eba80-0b99-11eb-8411-851f607c2fe0.png)

**Comment by wizayala** [comment]
תקין
