### ISSUE TITLE
ממשק חשבונות דרך או.די.בי.סי שדה מייל

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#339]
הגיע מאפרת , בקליטת חשבונות דרך ODBC ניתן לקלוט אקסל עם 250 תווים בשדה דוא"ל (למרות שרשום 50 בטבלה המקשרת)
אבל כשמנסים דרך אקסס או SQL אין אפשרות לבחור שדה דוא"ל כי כנראה רשום שהוא מוגבל ל- 50 תווים .
תודה 
![image](https://user-images.githubusercontent.com/69102026/93175438-4b31b700-f738-11ea-97ad-801ef45d42e9.png)

![image](https://user-images.githubusercontent.com/69102026/93175612-90ee7f80-f738-11ea-807c-dd4cada42039.png)

**Comment by WizMotiSaadon** [comment]
![image](https://user-images.githubusercontent.com/10919353/93180122-5fc57d80-f73f-11ea-9a8e-c395fbbffb2b.png)

**Comment by WizMotiSaadon** [comment]
במחיצה של אילה

**Comment by wizasher** [comment]
אצלי עובד , שולח לאפרת , תודה רבה

**Comment by wizayala** [comment]
גם אצלי תקין
