### ISSUE TITLE
קליטת תנועות יומן - שגיאה על תאריך

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#34]

**Comment by WizMotiSaadon** [comment]
הבאג הזה לא קשור אלי,
זה קשור לאיליה

בשורה 250 יש תאריך 
11/07/0419

ואני בודק אותו עם פונקציה של איליה 
CheckDate("11/07/0419")[;]

והוא מחזיר לי שהתאריך תקין
