### ISSUE TITLE
יבוא תנועות קופה לזמני- שגיאת  כתיב

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#340]
מוטי
תתקן בבקשה להסתיים בהצלחה במקום הסתיימה בהצלחה

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/93423090-d25c6780-f8bd-11ea-84bc-6f42713c070c.png)

**Comment by WizMotiSaadon** [comment]
תוקן
kupain.hds

**Comment by wizasher** [comment]
אצלי מצוין , תודה
![image](https://user-images.githubusercontent.com/69102026/93737500-0d2b0c00-fbec-11ea-835a-2648771a105b.png)

**Comment by wizayala** [comment]
גם אצלי , אעדכן את אביבית ... היה לה חשוב 😊
