### ISSUE TITLE
הודעה ביבוא בשיטת או.די.בי.סי

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#341]
ביבוא בשיטת 
odbc  
מופיע החלון הבא כאשר אני מעלה קובץ 
wpr 
![image](https://user-images.githubusercontent.com/16633745/93428073-82829e00-f8c7-11ea-9e8e-21020903d74e.png)

**Comment by wizayala** [comment]
ההודעה הזו לא מופיעה עם קובץ 
odbcimp.exe
מתאריך 13.9.2020

**Comment by WizMotiSaadon** [comment]
תוקן
odbcimp.exe

**Comment by wizasher** [comment]
עדכנתי את הקובץ , אצלי אין את ההודעה . תודה

**Comment by wizayala** [comment]
תקין
