### ISSUE TITLE
יבוא תנועות מלאי - שדה עיר מעל 50 תווים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#342]
מוטי
לקוח מתלונן שאנחנו נותנים הודעת שגיאה כאשר מייבא שדה עיר שגדול מ 50 תווים.
הלקוח מצפה שננהג כפי שעשינו במהדורות קודמות וקצצנו כל מה שמעבר ל 50 תווים.
נתבקשנו לתת הודעת שגיאה כזו 
במקביל בודקת מול אפרת מה לעשות לאחר שהגיעה תלונה מלקוח על העניין . האם לקצוץ כפי שעשינו בגרסאות קודמות או להשאיר הודעת שגיאה כפי שאנחנו עושים היום.
תצטרך להמתין לתשובה של אפרת.

![image](https://user-images.githubusercontent.com/16633745/93780771-3ae67400-fc31-11ea-94e5-06ecf989b6db.png)

**Comment by wizasher** [comment]
אפי ביקשה שיתעלם, ויקצץ את התווים שהם מעל 50 ( מימין לשמאל ) ללא הודעה מקדימה . תודה רבה

**Comment by WizMotiSaadon** [comment]
תוקן
odbcimp.exe

**Comment by wizasher** [comment]
אצלי נקלט מצוין . תודה

**Comment by wizayala** [comment]
תקין
