### ISSUE TITLE
יבוא פריטים - תזוזה בשדות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#343]
מוטי 
שוב יש תזוזה בשדות בעקבות הוספת שתי שורות ביבוא ב odbc  
תכף אבדוק בחשבונות 

![image](https://user-images.githubusercontent.com/16633745/94110513-6c3a8c00-fe4b-11ea-9199-5949c84a203c.png)

**Comment by wizayala** [comment]
לפי מה שאשר שלח במייל התזוזה היא גם בחשבונות.
האם זה קורה גם אצלך מוטי ?

**Comment by wizayala** [comment]
אני רוצה לשחרר 
odbcimp.exe  
שפתר שתי תקלות

**Comment by WizMotiSaadon** [comment]
כן, 
תיקנתי לפני שבועיים בערך
פריטים וחשבונות

האם אני צריך לתקן עוד משהו?

**Comment by wizayala** [comment]
התקלה של התזוזה חזרה על עצמה בקובץ 
odbcimp.exe
האחרון 
תבדוק שוב בבקשה

**Comment by WizMotiSaadon** [comment]
בדקתי,
התיקון עם העיר כולל בתוכו את התיקון שלהתזוזה

אני יכול להתחבר לראות איך זה קורה אצלך ?

יוצרים קובץ 
WPR
עם הגרסה הישנה

ופותחים אותו עם הגרסה החדשה

**Comment by wizayala** [comment]
![Uploading image.png…]()

**Comment by WizMotiSaadon** [comment]
תיקנתי עבור הפריטים
