### ISSUE TITLE
יבוא תנועות יומן - שיבוש בסכומים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#344]
מעבירה לך קובץ תסתכל על שורה 463 מופיע 18000000.00
בפועל נקלט 18000000.50
מצרפת קובץ קלט 

![image](https://user-images.githubusercontent.com/16633745/94116155-54ff9c80-fe53-11ea-9900-15ee617cb6fb.png)

**Comment by WizMotiSaadon** [comment]
WizImportMySql.dll

תוקן
[H-Mobile]<https://h-erp.co.il/h-mobile/>

**Comment by wizayala** [comment]
האם מדובר על המרה של סימן או תו לא נכון ?

**Comment by WizMotiSaadon** [comment]
> האם מדובר על המרה של סימן או תו לא נכון ?

מדובר על מספר ענק,
וההמרה שלו לא התבצע כיאות

**Comment by wizayala** [comment]
תקין
תקלה רק בקבצי טקסט , לא נתקלנו בה באקסל
