### ISSUE TITLE
יבוא עצים - הודעת שגיאה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#345]
מוטי
אני מקבלת את ההודעה הבאה :

Error in SQL :Incorrect syntax near the keyword 'WHERE'.

update  trees set  itemkey='BFA0CH BA-00B0',levef=1,ParentKey='BFA0CH DA-00A1L',DirectParentKey='BFA0CH DA-00A1L',HasSons=2,SonQuant=1.000000000,TreeType=1 ,Details='' ,UseFID=30 ,VersionNum =                                           WHERE trees.itemkey='BFA0CH BA-00B0'  and trees.LeveF = 1  And trees.ParentKey='BFA0CH DA-00A1L'

התקלה הזו מופיעה אצל לקוח שעבר לגרסה 2020a sp3
עבד עשה שינוי בסקריפט של שחזור העצים , (שולחת לך מייל עם הסקריפט )
לפי מה שהבנתי מעבד זה לא אמור לשנות כי אנחנו קוראים לאותו סקריפט .

אם זה כלל לא קשור לסקריפט , מה התקלה ?

**Comment by WizMotiSaadon** [comment]
לא שמתי ברירת מחדל
לשדה
VersionNum 

איזה ברירת מחדל את רוצה להשים לשדה הזה?

**Comment by wizayala** [comment]
אצלי נכנס null  ולפי מה שאני רואה במידה והלקוח מנהל היסטוריה איתן צריך להחזיר ערך אך לדעתי לא רלוונטי כי כרגע אנחנו לא מכניסים ערכים לשדות החדשים

איילה ישראלי - בדיקות
H-erp.co.il<https://h-erp.co.il/>

[https://h-erp.co.il/images/signature/yt.png]<https://www.youtube.com/channel/UCESnJ0sklbG-ozF-RR5BI6g>

[https://h-erp.co.il/images/signature/in.png]<https://www.linkedin.com/company/hashavshevet-wizsoft/>

[https://h-erp.co.il/images/signature/fb.png]<https://www.facebook.com/Hashavshevetldt/>



[https://h-erp.co.il/images/signature/h-erp.png]<https://h-erp.co.il/>

**Comment by wizayala** [comment]
תסתכל על גיט #53

**Comment by WizMotiSaadon** [comment]
תוקן
treein.hds
 UpdateControlerValue("**stLastVersionNum**",ExecuteAnyDocExpr(Add_str(Add_str(GetApplicationPath(),"\") , "Trees1.hds") ,"(EX)SaveLastVersion",{st_parit_av})),

stLastVersionNum get default 0 instead of ''

**Comment by wizayala** [comment]
מוטי
מה התיקון ?

**Comment by WizMotiSaadon** [comment]
התיקון הוא שאם אני מקבל מאיתן ערך ריק עבור 
VERSIONNUM
אז אני שם אפס

**Comment by wizasher** [comment]
אצלי עדיין נופל ,
כשאני לא מקשר שדה פרטים 
![image](https://user-images.githubusercontent.com/69102026/94775584-c944bd80-03c8-11eb-9a6c-6fa5b1c9e716.png)

כשאני מקשר שדה פרטים 
![image](https://user-images.githubusercontent.com/69102026/94775713-06a94b00-03c9-11eb-9c1c-8cd82472c466.png)

**Comment by wizayala** [comment]
מוטי
לאחר התייעצות עם הדס יש לשתול את הערך 1 בשדה 
trees.versionnum
לא צריך לקבל ערכים מאיתן 
תמיד כאשר 
companydefs.treever=0
כל עץ קיים ועץ חדש יקבל את הערך 
trees.versionnum=1

מקווה שזה ברור

**Comment by WizMotiSaadon** [comment]
> מוטי
> לאחר התייעצות עם הדס יש לשתול את הערך 1 בשדה
> trees.versionnum
> לא צריך לקבל ערכים מאיתן
> תמיד כאשר
> companydefs.treever=0
> כל עץ קיים ועץ חדש יקבל את הערך
> trees.versionnum=1
> 
> **את התיקון יש לעשות על הקובץ שקיים בגרסת לקוחות**
> 
> מקווה שזה ברור

תיקנתי
treein.hds

**Comment by wizayala** [comment]
תקין

**Comment by wizasher** [comment]
לקחתי TREEIN.HDS מ- 4.10 ועדיין נופל אצלי . (אותה הודעה שצילמתי למעלה )
זה קשור ל- SQL 2005 או שזה אמור לפתור בכל מקרה ?
תודה

**Comment by wizayala** [comment]
שלחתי לך מייל שבו צריך להריץ גם סקריפטים של עבד

**Comment by wizayala** [comment]
מתברר כי בגרסת סקל 2005 עדיין יש בעיה, 
מוטי שלח לאשר קובץ תיקון יש לוודא שהתיקון תקין גם בגרסאות אחרות של סקל כולל החומר של הלקוח 
להמשך בדיקתו של אשר

**Comment by wizayala** [comment]
אשר אפשר לסגור את זה , נכון ?

**Comment by wizasher** [comment]
כן , תקין .
