### ISSUE TITLE
יבוא עצים - שדה פרטים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#346]
כשבקובץ קלט שלי שדה פרטים ריק והוא מקושר לשדות קלט 
נכנס הערך 0 לשדה
trees.details

**Comment by wizayala** [comment]
מה עם זה ?
האם תיקנת את זה ?

**Comment by WizMotiSaadon** [comment]
![Uploading image.png…]()

**Comment by wizayala** [comment]
תקין
