### ISSUE TITLE
יבוא עצים - הודעת שגיאה קונפיגורטור

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#347]
מוטי
יש להוסיף בדיקה נוספת 
בייבוא עצי מוצר יש לוודא שמפתח האב שמתקבל בממשק אינו נמצא בטבלה 
TreesConfigurator
הבדיקה תעשה מול השדות
TreesConfigurator.itemkey
TreesConfigurator.LeveF=0

במידה ומפתח האב נצא בטבלת 
TreesConfigurator
יש לתת הודעה מתאימה : 
"פריט אב זה קיים בקונפיגורטור"

מקווה שזה ברור

**Comment by WizMotiSaadon** [comment]
> TreesConfigurator.levelf=0

התכוונת  
TreesConfigurator.** LeveF**=0
?

**Comment by WizMotiSaadon** [comment]
parit_avInTreesConfiguratorNum<<ExecuteSql("DB1",FormatString("?=select count (id ) from  TreesConfigurator where TreesConfigurator.LeveF=0 and TreesConfigurator.itemkey = '~st_parit_av^'   "))[;]

**Comment by wizayala** [comment]
כן

**Comment by WizMotiSaadon** [comment]
![image](https://user-images.githubusercontent.com/10919353/94802971-3c622a00-03f1-11eb-99a8-3fd6f64fbe9b.png)

**Comment by wizayala** [comment]
לא הבנתי מה כתבת קודם ?

**Comment by WizMotiSaadon** [comment]
> לא הבנתי מה כתבת קודם ?

זה סימן בשבילי איפה לחפש אם יום אחד אצטרך לתקן שם משהו

**Comment by wizayala** [comment]
תקין

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/95015625-931c6d80-0656-11eb-8b30-d2cacd406a79.png)
