### ISSUE TITLE
יבוא  תנועות יומן - מנה תקציבית

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#348]
כאשר קובץ קלט מכיל מספר תנועות שהן עם ס"ת " תק" אנחנו מודיעים שתנועות אלו יכנסו למנה תקציבית . 
משום מה את שאר התנועות אנחנו לא קולטים.
יש לקלוט את התנועות עם ס"ת "תק" למנה תקציבית אחת ואת התנועות האחרות למנה אחרת מנה רגילה.
שולחת לך קבצי קלט במייל נפרד

**Comment by wizayala** [comment]
תקין

**Comment by WizMotiSaadon** [comment]
תוקן
PRM2INI.DLL
WizImportMySql.dll
WizImportLogic.dll

**Comment by wizayala** [comment]
תקין
