### ISSUE TITLE
יבוא תנועות יומן - שורות שלא נקלטו

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#349]
מוטי
השורות היחידיות שנקלטו הן השורות עם ס"ת 
שורה עם ס"ת חל ו- תק
כל השאר שהן שורות תקינות ומופיעות בטבלת 
importjurnal  
לא נקלטו , למה ?
בנסיונות נוספים כאשר הוספתי ס"ת התנועות נקלטו
כאשר אין ס"ת התנועות לא נקלטו.
שולחת לך במייל נפרד קבצי קלט 
![image](https://user-images.githubusercontent.com/16633745/95061461-4db67980-0704-11eb-910e-e546e5b22103.png)

**Comment by WizMotiSaadon** [comment]
תוקן
WizImportMySql.dll

**Comment by wizayala** [comment]
מה הייתה הבעיה ?

**Comment by WizMotiSaadon** [comment]
אם יש שדה שהתוכן שלו הוא
NULL
אז אי אפשר להשוות אותו למחרוזת

ואני ניסיתי להשוות למחרוזת
"תק"
[H-Facebook]<https://www.facebook.com/Hashavshevetldt/>

**Comment by wizayala** [comment]
ההשוואה היא רק מול מחרוזת "תק" ?

**Comment by WizMotiSaadon** [comment]
כן
[H-Facebook]<https://www.facebook.com/Hashavshevetldt/>

**Comment by wizayala** [comment]
תקין
