### ISSUE TITLE
יבוא כותרות מלאי - דריסת נתונים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#350]
ביבוא נתונים נוספים למסמכים כאשר אני מסמנת דריסת נתונים וביטול יתרה לאספקה , הנתונים אינם נדרסים והיתרה לאספקה מתאפסת. 
כאשר אני מסמנת רק דריסת נתונים ללא ביטול יתרה לאספקה הנתונים נדרסים 
התקלה הזו גם מתוך התוכנה וגם ממסופון 2

**Comment by WizMotiSaadon** [comment]
?איך אני יכול להבין אם התקלה היא בשורה הראשונה או בשניה



> ביבוא נתונים נוספים למסמכים כאשר אני מסמנת דריסת נתונים וביטול יתרה לאספקה , הנתונים אינם נדרסים והיתרה לאספקה מתאפסת.
?זו התקלה

> כאשר אני מסמנת רק דריסת נתונים ללא ביטול יתרה לאספקה הנתונים נדרסים
?או זאת

**Comment by WizMotiSaadon** [comment]
אולי אני לא צריך לאפשר את שני הסעיפים ביחד?

**Comment by wizayala** [comment]
בגרסה קודמת לא הייתה בעיה עם זה

**Comment by wizayala** [comment]
מה הבעיה עם זה שתדרוס שדות טקסט ואח"כ תאפס יתרה ?

**Comment by WizMotiSaadon** [comment]
תוקן
StockHeadIn.hds

SET importstock.ErrorData = 'stockmoves.id = '+ CAST(stockmoves.ID AS varchar(50))  ,
importstock.ErrorMessage = 'לא ניתן לאפס בתנועה זו את שדה כמות לאספקה'

**Comment by WizMotiSaadon** [comment]
> ביבוא נתונים נוספים למסמכים כאשר אני מסמנת דריסת נתונים וביטול יתרה לאספקה , הנתונים אינם נדרסים והיתרה לאספקה מתאפסת.

תוקן
StockHeadIn.hds

SET importstock.ErrorData = 'stockmoves.id = '+ CAST(stockmoves.ID AS varchar(50)) ,
importstock.ErrorMessage = 'לא ניתן לאפס בתנועה זו את שדה כמות לאספקה'

**Comment by wizayala** [comment]
האם יש תלות אחד בשני ?
הכוונה האם מתבצע דריסת נתונים בלבד ללא ביטול יתרה לאספקה וההיפך ?

**Comment by WizMotiSaadon** [comment]
עכשיו אין

**Comment by wizayala** [comment]
לא ברור לי מההודעה מדוע לא ניתן לאפס ?
יש יתרה לאספקה 

![image](https://user-images.githubusercontent.com/16633745/95985148-e77cd580-0e2c-11eb-9c8b-88d9c583134e.png)



![image](https://user-images.githubusercontent.com/16633745/95985413-3cb8e700-0e2d-11eb-97d4-f9919a2c7f46.png)

**Comment by wizayala** [comment]
סימנתי איפוס יתרה ועדכון
הייתה שורה שאותה היה צריך לאפס ( מזהה תנועה 41905)
ותנועה שאותה היה צריך לעדכן שדות נוספים
למרות הודעת השגיאה גם עדכון נתונים לא בוצע בשתי הטבלאות
stock     stockmoves

**Comment by WizMotiSaadon** [comment]
> לא ברור לי מההודעה מדוע לא ניתן לאפס ?
> יש יתרה לאספקה
> 

אני בודק לפי סוג מסמך
ואם אני רואה ש
DOCUMENTSDEF.STOCKUPDATE=0 AND DOCUMENTSDEF.UPDATFJURNAL=0 AND DOCUMENTSDEF.HSDOC=1
אז אני לא נותן לאפס כמות לאספקה

**Comment by wizayala** [comment]
11
![image](https://user-images.githubusercontent.com/16633745/95988392-84417200-0e31-11eb-9be5-7fa432838bbe.png)

**Comment by WizMotiSaadon** [comment]
אני רואה באמת שעבור המסמך הזה
DOCUMENTSDEF.STOCKUPDATE=0 AND DOCUMENTSDEF.UPDATFJURNAL=0 AND DOCUMENTSDEF.HSDOC=1

ולכן אני מודיע שאני לא יכול לאפס

כלומר את צריכה לאפס ידנית
ולראות מה קורה עם שאר השדות

**Comment by wizayala** [comment]
מוטי 
יש לך טעות עבור התנאי הזה כן מאפסים 
בקובץ 
stockheadin.hds  
מתאריך 6.9.2020 זה עובד , ז"א יש איפוס
מצרפת לך מסמך הכנו על זה בעבר , עמוד 3
[ממשק עדכון מסמכים תוספת.docx](https://github.com/wizayala/Hashavsheva/files/5378254/default.docx)

**Comment by WizMotiSaadon** [comment]
> מוטי
> יש לך טעות עבור התנאי הזה כן מאפסים

תיקנתי
stockheadrin.hds

**Comment by wizayala** [comment]
תקין בשתי שיטות הייבוא

**Comment by wizasher** [comment]
גם אצלי תקין ב-2 השיטות
