### ISSUE TITLE
יבוא לאומי קארד - תיקון כתיב

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#351]
מוטי
האם תוכל לתקן בבקשה את הכתיב בהודעה 
לשנות מכארד לקארד 

![image](https://user-images.githubusercontent.com/16633745/95763486-c181f480-0cb7-11eb-9e46-12627076caf7.png)

**Comment by WizMotiSaadon** [comment]
איפה ההודעה?

**Comment by wizayala** [comment]
![Uploading image.png…]()

**Comment by WizMotiSaadon** [comment]
leumicardin.HDS

תוקן

**Comment by wizayala** [comment]
תקין

![image](https://user-images.githubusercontent.com/16633745/95942138-15d9c100-0deb-11eb-9bb3-c8373d3c212c.png)
