### ISSUE TITLE
יבוא כרטיסי אשראי - בחירת חשבון בנק 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#352]
מוטי בבקשה להוסיף ביבוא ארבעת שיטות כרטיסי אשראי
החל מהשורה המסומנת בכחול והשלוש שמתחת 
בחלון של הגדרת החשבון כותרת : בחירת חשבון בנק 

![image](https://user-images.githubusercontent.com/16633745/95761852-91395680-0cb5-11eb-8486-f8e156f34eda.png)

**Comment by wizayala** [comment]
זו דוגמא לחלון שבו מופיע הכיתוב של בחירת חשבון בנק 
![Uploading image.png…]()

**Comment by WizMotiSaadon** [comment]
תוקן 
bankin.hds

**Comment by wizayala** [comment]
תקין
