### ISSUE TITLE
יבוא רשימות - כפילות של ערכים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#353]
מוטי
ביבוא רשימות אין לייבא את אותו ערך פעמיים לאותה רשימה לאותו 
listname

יש לאפשר ערך "**תל אביב** "  לשם רשימה **ערים**
                 ערך  "**תל אביב
** "  לשם רשימה **מחוז**
[ממשק רשימות.docx](https://github.com/wizayala/Hashavsheva/files/5385220/default.docx)

**Comment by wizayala** [comment]
מוטי 
האם הוצאת תיקון על זה ?

**Comment by WizMotiSaadon** [comment]
כן
ListIn.HDS

**Comment by wizasher** [comment]
אצלי עדיין לא מעדכן אם יש אותו ערך ברשימה אחרת

**Comment by WizMotiSaadon** [comment]
> אצלי עדיין לא מעדכן אם יש אותו ערך ברשימה אחרת

תוקן
ListIn.HDS

**Comment by wizasher** [comment]
אצלי עכשיו תקין . תודה

**Comment by wizayala** [comment]
גם אצלי תקין , מעבירה ל sp4
