### ISSUE TITLE
יבוא תנועות קופה לזמני - מסופון2

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#354]
במסופון 2 הגדרתי יבוא תנועות קופה לזמני טקסט וגם או.די.בי.סי שמרתי את הקובץ 

![image](https://user-images.githubusercontent.com/16633745/96360098-58203c80-1122-11eb-922d-777216d523af.png)

לאחר מכן אני נכנסת שוב לחלון של מסופון2 ומסתכלת על הקובץ ואז אני רואה בסוג היבוא - מיון פריטים

![image](https://user-images.githubusercontent.com/16633745/96360223-c87b8d80-1123-11eb-9d2f-c55b6945994b.png)

**Comment by WizMotiSaadon** [comment]
תוקן
masofon2.exe

**Comment by wizayala** [comment]
עכשיו בהגדרת קבצי טקסט מאבד את ההגדרה של קובץ פרמטרים ומבנה קובץ ( מה שהוגדר כשהגדרתי את הקובץ bat)

![image](https://user-images.githubusercontent.com/16633745/96459830-3ced2400-122b-11eb-93de-883e768033dc.png)

**Comment by WizMotiSaadon** [comment]
> עכשיו בהגדרת קבצי טקסט מאבד את ההגדרה של קובץ פרמטרים ומבנה קובץ ( מה שהוגדר כשהגדרתי את הקובץ bat)

תוקן

**Comment by wizasher** [comment]
זה נראה שהוא לא מצליח לסיים את הפעולה של הייבוא . בצילום מסך זה הקובץ שנוצר (אני שולח לך למייל) וכשאני מנסה שוב להריץ את קובץ ה- bat  ,הוא מודיע שתחנה אחרת מעדכנת ..
![image](https://user-images.githubusercontent.com/69102026/96541785-66e52b80-12a9-11eb-9d68-4e878dd4a6db.png)

**Comment by wizayala** [comment]
לא מצליח לקרוא את קובץ kupain.dat 
שולחת לך במייל קובץ err

**Comment by WizMotiSaadon** [comment]
תוקן
IMP_LIB.HDS
prm2ini.dll

**Comment by wizasher** [comment]
אצלי נקלט מצוין

**Comment by wizayala** [comment]
גם אצלי תקין
