### ISSUE TITLE
יבוא חשבונות - מסופון2 תו מפריד

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#355]
כאשר יש פסיק בתוך שדה מסויים, והשדה עטוף במרכאות, אין להתייחס לפסיק כמפריד שדה.

בנוסף יש להסיר את המרכאות מימין ומשמאל

**Comment by WizMotiSaadon** [comment]
תוקן
WizImportLogic.dll

**Comment by wizayala** [comment]
תקין
