### ISSUE TITLE
קליטת קופה לקובץ זמני מקובץ טקסט 

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#356]
צריך לעשות בדיקה על שדה "שם חשבון אשראי"(שדה חובה) גם בממשק מקובץ טקסט .
כמו שמתריע בקליטה מ- ODBC. תודה
![image](https://user-images.githubusercontent.com/69102026/97100896-36cecb80-16a1-11eb-81f7-5e76a266a152.png)

**Comment by WizMotiSaadon** [comment]
מה היה ה 
transtype 
?

**Comment by wizasher** [comment]
סליחה , לא הבנתי .. 
עד עכשיו בקובץ טקסט הוא בדק שדות חובה של : מפתח לקוח , מספר קבלה , סוג תנועה . וצריך להוסיף לו שיבדוק גם ושם כרטיס האשראי , כמו בקליטה ממשק ODBC .
מה זה transtype ?

**Comment by WizMotiSaadon** [comment]
> מה זה transtype ?

סוג תנועה 33 אשראי קבלה מקור.
סוג תנועה 43 אשראי קבלה תרומה.

מה העברתם?

**Comment by WizMotiSaadon** [comment]
Or {TransType}=43

kupain.hds

**Comment by wizasher** [comment]
עכשיו אני רואה שרק ב- 43 הוא לא מתריע ,
ב- 33 יש התרעה . תודה

**Comment by WizMotiSaadon** [comment]
תיקנתי את זה אם ככה

**Comment by wizasher** [comment]
מעולה ! מתריע גם ב- 33 וגם ב- 43 , תודה

**Comment by wizayala** [comment]
גם אצלי תקין 
מתריע גם מקובץ טקסט ומ odbc 
על שני סוגי תנועה 33, 43
