### ISSUE TITLE
ממשק אינדקס חשבונות מטבע התחשבנות 

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#357]
בקליטת ממשק חשבונות כשאני רוצה לעדכן מטבע התחשבנות מטח , 
לא משתנה matchcurrflag=0 , 
ולא משתנה matchcurr למטבע שבממשק .
בטבלה
 ImportAccount 
רואים את המטבע .

![image](https://user-images.githubusercontent.com/69102026/97402434-3a5d8f00-18fb-11eb-89b4-f0cbcfd530fa.png)
![image](https://user-images.githubusercontent.com/69102026/97402486-4f3a2280-18fb-11eb-95f3-bde36522a324.png)

**Comment by WizMotiSaadon** [comment]
אתה יכול לרשום את כל המלל באנגלית בשורה חדשה?
אני לא מבין מה רשום

**Comment by wizasher** [comment]
אני אשלח במייל

**Comment by WizMotiSaadon** [comment]
מה המטבע מוביל בחברה הקולטת?

**Comment by wizasher** [comment]
דולר $

**Comment by WizMotiSaadon** [comment]
?ומה מטבע השיערוך

**Comment by wizasher** [comment]
ניסיתי מטבע התחשבנות גם "לש" וגם $

**Comment by WizMotiSaadon** [comment]
> לא משתנה matchcurrflag=0 ,

אני מעביר את הדגל לאפס רק אם המטבע התחשבנות שונה ממטבע מוביל.
מכיוון שהמטבע המוביל הוא דולר, ואתה מנסה לקלוט מטבע התחשבנות דולר,
הדגל התחשבנות בכרטיס לקוח נשאר אחד

**Comment by wizasher** [comment]
אבל אם אני משנה ידנית מטבע התחשבנות למטח בכרטיס חשבון .
אז משתנה  matchcurrflag=0 .
נראה לי שגם בממשק זה צריך לעשות אותה פעולה .
נחכה לאיילה שתסתכל על זה .
תודה

**Comment by WizMotiSaadon** [comment]
?אפשר קבצי קלט

**Comment by wizasher** [comment]
שולח במייל

**Comment by wizayala** [comment]
מוטי
התקלה היא כאשר מדובר בחשבון קיים, אז לא מתעדכן דגל מטבע התחשבנות
accounts.matchcurrflag
כאשר אני מייבאת חשבון חדש זה עובד מצויין גם הדגל וגם המטבע מתעדכנים
אם לא ברור תוכל להתחבר אליי

**Comment by wizayala** [comment]
אשר,
סגרתי את הגיט 
הכל תקין
אכן יש לאפשר קליטה של מטבע התחשבנות אך ורק לחשבון קיים
