### ISSUE TITLE
יבוא פריטים - סוג פריט 7/8

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#359]
מוטי
ביבוא פריטים אנחנו לא מאפשרים לעדכן סוג פריט 7 או 8 
items.stockperunit
אין לאפשר פתיחת פריטים חדשים  **אבל.....**
אם הפריט קיים **יש לאפשר עדכון שדות**

**Comment by WizMotiSaadon** [comment]
בלי קשר,
אני רואה לפי הקוד שאני כן מקבל 8
בן מטריצה

מודיע על שגיאה רק על 7

**Comment by wizayala** [comment]
מוטי
האם יש אפשרות שתוציא תיקון היום ?

**Comment by WizMotiSaadon** [comment]
יש כאן בעיה חייב להודות
אני יכול להחליף את ה 7 ב 
NULL

אבל אז הפריט יפתח בלי קוד

**Comment by wizayala** [comment]
למה הכוונה ?
פריט בלי מפתח ?

**Comment by WizMotiSaadon** [comment]
הכוונה שיפתח פריט חדש
אבל בלי
stockperunit

זה יקרה אם אחליף את ה 7 ב 
NULL

**Comment by wizayala** [comment]
אבל למה לפתוח פריט חדש
לא צריך להתעסק עם פריט חדש
אני אתקשר , אחדד את הנקודה

**Comment by WizMotiSaadon** [comment]
אני יכול לא לפתוח,
השאלה היא אם אני אמור לתת הודעת שגיאה

**Comment by wizayala** [comment]
אם הפריט קיים בטבלת פריטים , נעדכן את השדות המקושרים מבלי לשנות שדה סוג פריט 
stockperunit
אם הפריט לא קיים בטבלת פריטים , אין לקלוט פריט זה ולתת הודעת שגיאה כפי שקיים היום

**Comment by WizMotiSaadon** [comment]
-- git#359
update importitem set importitem.ErrorData = importitem.StockPerUnit ,importitem.ErrorMessage = 'Item.57'  -- StockPerUnit must be 0,1,2,3,4,5,6,8,9
where not (importitem.StockPerUnit  like '[012345689]' or ISNULL(importitem.StockPerUnit, '') = '' )
and (not exists (SELECT ID from ITEMS where ItemKey = importitem.itemkey) or exists (SELECT stockperunit from ITEMS where ItemKey = importitem.itemkey and stockperunit <>7 ))   ;

**Comment by WizMotiSaadon** [comment]
סקריפט תוקן
HSImportItem.sql
נמצא במחיצה

**Comment by wizayala** [comment]
מתקבלת הודעת שגיאה של סוג הפריט למרות שמדובר בפריטים קיימים

![image](https://user-images.githubusercontent.com/16633745/97575321-3a41ba00-19f5-11eb-941a-da0842db8edf.png)

**Comment by WizMotiSaadon** [comment]
אז אולי יש כבר לפריט סוג פריט אחר
[H-Facebook]<https://www.facebook.com/Hashavshevetldt/>

**Comment by wizayala** [comment]
רוצה להתחבר ?

**Comment by wizayala** [comment]
תקין לגבי סוג פריט 7
עם קובץ
itemin.hds 
ששלחת לי במייל
כעת צריך  לתקן פריט מסוג 8

**Comment by WizMotiSaadon** [comment]
תיקנתי
HSImportItem.sql
עבור סוג 8

שמתי במחיצה
[H-Facebook]<https://www.facebook.com/Hashavshevetldt/>

**Comment by wizayala** [comment]
מאפשר לי פתיחת פריט חדש  ועדכון פריט קיים בסוג 8 
לגבי פריט חדש מסוג 8 צריכה להתקבל הודעת שגיאה

**Comment by WizMotiSaadon** [comment]
![Uploading image.png…]()

**Comment by WizMotiSaadon** [comment]
את צריכה להריץ את הסקריפט
אולי אתחבר

**Comment by wizayala** [comment]
, למרות שהרצתי את הסקריפט , עדיין מקבלת הודעה רק על פריט מסוג 7 ולא 8
תוכל להתחבר אליי

![image](https://user-images.githubusercontent.com/16633745/97795711-127b6d80-1c12-11eb-976a-6b0eac1237c7.png)

**Comment by wizayala** [comment]
האם נראה לך שתוכל לתקן את גם היום ?

**Comment by wizayala** [comment]
עכשיו אף פריט לא נקלט כולל אלו שקיימים
התקשרתי לא הייתה תשובה, אם תרצה להתחבר עדכן אותי

![image](https://user-images.githubusercontent.com/16633745/97801960-f5ae5c80-1c48-11eb-9106-c439251d4bfd.png)

**Comment by wizayala** [comment]
יופי נראה טוב יותר , ממשיכה בבדיקות
![image](https://user-images.githubusercontent.com/16633745/97805840-21d5d780-1c61-11eb-983d-6e2964dba395.png)
במידה ותקין להעביר רק קובץ 
itemin.hds 
ללא סקריפט ?

**Comment by wizayala** [comment]
בחברה שבה לא הרצתי את הסקריפט פריט קיים מסוג 7 לא נקלט 

![image](https://user-images.githubusercontent.com/16633745/97805986-0e773c00-1c62-11eb-8bbe-c47bb48ca2d8.png)

**Comment by WizMotiSaadon** [comment]
מה לעשות, ככה זה בסקריפט הישן


[H-Facebook]<https://www.facebook.com/Hashavshevetldt/>

**Comment by wizasher** [comment]
לקחתי רק את התיקון של ה- HDS  ועדיין לא מעדכן פריט קיים מטריצה . תודה

**Comment by wizasher** [comment]
הרצתי את הסקריפט בחברה אחרת , הודעת השגיאה השתנתה אבל גם שם לא נותן לקלוט שינוי בפריט .
![image](https://user-images.githubusercontent.com/69102026/97838241-72444800-1ce8-11eb-9904-8f1fd8753d9c.png)

**Comment by wizayala** [comment]
התקלה הזו נפתרה , נכון ?

**Comment by wizasher** [comment]
כן, השאלה אם להשאיר פתוח עד לתיקון של HDS בלבד ?

**Comment by wizayala** [comment]
השאלה האם זה אפשרי , מוטי מה אתה אומר ??

**Comment by WizMotiSaadon** [comment]
אפשר להשאיר פתוח עד שתצא גרסה
עם עדכוני
sp

**Comment by wizayala** [comment]
אשר , אני חושבת שאשפר לסגור את הגיט הזה , נכון ?

**Comment by wizasher** [comment]
גם לי נראה  , מקסימום נפתח שוב ..

**Comment by wizayala** [comment]
אמרת , סגרתי :)
