### ISSUE TITLE
ייבוא תנועות מלאי - יבוא מחלונות  

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#360]
אני מקבלת הודעת שגיאה שלא ניתן לקלוט בגלל שהפריט לא קיים בחברה הקולטת למרות שהוא קיים 
מדובר על פריט מכפלה שמוגדר כך בשתי החברות המייצאת והמייבאת.

![image](https://user-images.githubusercontent.com/16633745/97580059-83950800-19fb-11eb-8bc0-0a878f0b57f0.png)

**Comment by wizayala** [comment]
החומר נמצא אצלי תוכל להתחבר לראות את התקלה

**Comment by WizMotiSaadon** [comment]
לפי ההודעה
הבעיה היא עם סוג הפריט

לא עם הפריט עצמו

**Comment by wizayala** [comment]
גם סוג הפריט זהה

**Comment by wizayala** [comment]
למה הוא מזהה 0 בסוג הפריט , הראיתי לך שמדובר על סוג פריט 3 בשתי החברות

![image](https://user-images.githubusercontent.com/16633745/97593144-1046c280-1a0a-11eb-9b31-9a1b4e8b37ca.png)

בינתיים אריץ בדיקת נתונים בחברה הקולטת

**Comment by wizayala** [comment]
בדיקת נתונים תקינה .....

**Comment by WizMotiSaadon** [comment]
אז בחברה ששלחה את הקובץ 
עבור הפריט 
MAN 230g green 100q7 
?3 יש לו סוג פריט 

אולי הסוג פריט היה אפס
בזמן היצוא
?ואחרי היצוא הוא הוחלף ל 3

**Comment by wizayala** [comment]
סוג הפריט בחברה המייצאת הוא 3 בזמן הייצוא
החומר אצלי תוכל גם להתחבר ולראות 
אלו הם החברות שהראיתי לך כשהתחברת

**Comment by WizMotiSaadon** [comment]
אני יאחר היום
-----------------------
בתוך הקובץ 
MDB
מה רשום בשדה 
stockmoves.itemkey_stockperunit
?

**Comment by WizMotiSaadon** [comment]
תוקן
hsimp.exe

**Comment by wizayala** [comment]
עכשיו תקין 
התקלה הייתה רק עבור סוג פריט 3 ?
