### ISSUE TITLE
יבוא דפי ישראכרט - CHS

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#361]
מתקבלת הודעה חשבון לא פעיל ביבוא ישראכרט בשיטת 
CHS
הבעיה נובעת מחשבון שמוגדר בשדה 
importbankaccremiver.AMINITINSHOVARIMACCKEYDOLLAR
importbankaccreminder.AMINITINSHOVARIMACCKEYSHEKEL
החשבון שבשדות הללו היה מוגדר לא פעיל אך שים לב איך מסך הקליטה נראה :
![image](https://user-images.githubusercontent.com/16633745/97805716-7f1d5900-1c60-11eb-842b-1df73fef02ec.png)
אין פה הגדרה של אמינית ( בעבר הרחוק היה עד שהתבטל אמינית והורדנו אותו )
בכל אופן ביבוא צריך להתייחס רק לארבעת הכרטיסים הרשומים בחלון בחירת חשבונות בנק

**Comment by WizMotiSaadon** [comment]
אני לא רואה איזו בעיה

**Comment by wizayala** [comment]
חשבון "אמינית" מוגדר כחשבון לא פעיל ברגע ששיניתי לסטוטס פעיל הקובץ נקלט ללא כל הודעה 

![image](https://user-images.githubusercontent.com/16633745/97806021-3ebeda80-1c62-11eb-9d0d-650c07810363.png)

**Comment by WizMotiSaadon** [comment]
נהדר, אני אמור לעשות משהו?
[H-Facebook]<https://www.facebook.com/Hashavshevetldt/>

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/97806078-7ded2b80-1c62-11eb-805e-ef158d0b10cc.png)

**Comment by wizayala** [comment]
כן לא להתייחס לחשבון אמינית איפה אתה רואה שהוא מוגדר בחלון הזה :

![image](https://user-images.githubusercontent.com/16633745/97806107-95c4af80-1c62-11eb-866b-3531743681e4.png)

**Comment by WizMotiSaadon** [comment]
IsracardGroupShovarimin_Chsh.HDS 

תוקן

**Comment by wizasher** [comment]
אצלי עדיין יש הודעה על חשבון לא פעיל

**Comment by WizMotiSaadon** [comment]
זו הודעה לא מספיק טובה כי היא לא מציית את שם החשבון
אבל היא לא שלי

בדקת את כל ה4 חשבונות 
לראות שהם פעילים?
אולי ההודעה מהם?

אם תרצה אתחבר

**Comment by wizasher** [comment]
כל ה- 4 פעילים , אני מחבר אותך . תודה

**Comment by WizMotiSaadon** [comment]
תוקן
IsracardGroupShovarimin_Chsh.HDS

**Comment by wizasher** [comment]
נקלט מצוין , בלי ההודעה על חשבונות לא פעילים . תודה

**Comment by wizayala** [comment]
אשר, מה הייתה התקלה אצלך ?

**Comment by wizayala** [comment]
מוטי, מה היה התיקון שפתר לאשר את הבעיה ?

**Comment by WizMotiSaadon** [comment]
אני לא עושה חישוב מחדש של יתרות דפי בנק עבור החשבונות אמינית

**Comment by wizayala** [comment]
איך זה מתקשר לתקלה של אשר ?

**Comment by WizMotiSaadon** [comment]
לפני שעושים חישוב יתרות מחדש יש בדיקה של פעיל / לא פעיל
עם הודעה

**Comment by wizayala** [comment]
תודה
