### ISSUE TITLE
יבוא תנועות הנה"ח - מנה תקציבית

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#362]
מוטי 
תקלה של קליטת תנועות רגילות ותנועות תקציביות חזרה על עצמה.
ראה גיט #348

**Comment by wizayala** [comment]
בדקתי ב odbc

**Comment by WizMotiSaadon** [comment]
?אני יכול להתחבר לראות

**Comment by WizMotiSaadon** [comment]
(2 != TYPE or TYPE is null  )

תוקן
WizImportMySql.dll

**Comment by wizasher** [comment]
אצלי תקין גם בטקסט וגם ב
ODBC

**Comment by wizayala** [comment]
תקין
