### ISSUE TITLE
יבוא תנועות הנה"ח - קובץ וסניף

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#363]
מוטי
ביבוא תנועות הנה"ח , לא נקלט ים השדות קובץ וסניף
importjurnal.exefile     importjurnal.branch
השדות נכנסים לטבלת 
importjurnal
אך לא נכנסים לטבלת 
jurnaltrans 

![image](https://user-images.githubusercontent.com/16633745/98199496-ed4d6e80-1f33-11eb-9d70-a9b6ef64814e.png)

**Comment by WizMotiSaadon** [comment]
תוקן
WizImportMySql.dll

**Comment by wizayala** [comment]
במידה והסניף אינו מקושר יש לקחת את מספר הסניף מהגדרות המשתמש או הגדרות חברה

**Comment by WizMotiSaadon** [comment]
> במידה והסניף אינו מקושר יש לקחת את מספר הסניף מהגדרות המשתמש או הגדרות חברה
> לפי הסדר הזה : משתמש
> users.branch
> אם אין משתמשים אז הגדרות חברה
> companydefinisions.dftbranch

jurnalin.hds->>(EX)DoFinalProccesing

לפי הקוד
.אני עושה את זה רק ממסופון

אני לא יודע מה הסיבה
?יש לך איזה רעיון

**Comment by wizayala** [comment]
לא
צריך להיות זהה בשני המקרים מהתוכנה וממסופון2

**Comment by WizMotiSaadon** [comment]
תקין

**Comment by wizasher** [comment]
אצלי לוקח מהממשק את הסניף ואת הקובץ המקשר בצורה תקינה .
אבל אם לא מופיע סניף בממשק הוא לא לוקח כלום - ריק .
![image](https://user-images.githubusercontent.com/69102026/98458493-e1fb7c80-2199-11eb-9482-daadbcd97eef.png)

**Comment by wizayala** [comment]
אותו הדבר אצלי
מוטי צריך לתקן במקרה שאין שדה מקשור או כשהשדה של הסניף ריק  יש לשתול לפי ברירת המחדל 
**במידה והסניף אינו מקושר יש לקחת את מספר הסניף מהגדרות המשתמש או הגדרות חברה
לפי הסדר הזה : משתמש
users.branch
אם אין משתמשים אז הגדרות חברה
companydefinisions.dftbranch**

**Comment by WizMotiSaadon** [comment]
אני יכול לראות מה הכוונה
jurnaltrans.branch
ריק
?

כי השדה הזה לא יכול להיות ריק
הוא חייב להכיל אפס

**Comment by wizasher** [comment]
NULL
![image](https://user-images.githubusercontent.com/69102026/98459115-39045000-21a0-11eb-8466-4953b9e1c6ac.png)

**Comment by wizayala** [comment]
אתה רוצה להתחבר ?

**Comment by wizayala** [comment]
גם אצלי
מחשב מוכן להתחברות
![image](https://user-images.githubusercontent.com/16633745/98459138-854f9000-21a0-11eb-809b-b378cc19b6b8.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizasher** [comment]
אצלי נראה מצוין

**Comment by wizayala** [comment]
תקין 
גם ממסופון 2
