### ISSUE TITLE
יבוא תנועות הנה"ח - מסופון2 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#364]
מוטי
ביבוא תנועות הנה"ח ממסופון2  בשיטה גמישה אתה מוחק את הקובץ שאותו אתה מייבא
הכוונה אם אני מייבאת קבצי 
movein.doc  
movein.prm
אני רואה שלאחר הקליטה ממסופון 2 קובץ
movein.doc 
נמחק ולא נעשה שינוי שם , מה שכן קורה אם אני קולטת מתוך התוכנה

**Comment by wizayala** [comment]
בשיטה המפורטת לא עושה שינוי שם

**Comment by WizMotiSaadon** [comment]
> בשיטה המפורטת לא עושה שינוי שם

ממסופון2 
?או מרגיל

**Comment by wizayala** [comment]
ממסופון2 
מהתוכנה עובדת תקין

**Comment by WizMotiSaadon** [comment]
הגרסה של הקובץ
imp_lib.hds
22/10/2020 11:00

?

**Comment by WizMotiSaadon** [comment]
תוקן

JURNALIN.HDS
IMP_LIB.HDS

**Comment by wizasher** [comment]
אצלי נקלט מצוין עם שינוי סיומת הקובץ

**Comment by wizayala** [comment]
שינוי שם קובץ נעשה בממשק בשיטה גמישה
בשיטה המפורטת  לא מוצא את הקובץ  והקובץ קיים 
לאחר בדיקה אני רואה שיש שינוי במסלול של הקובץ 
מוטי , תוכל להתחבר אלי כדי שאדגים לך

**Comment by WizMotiSaadon** [comment]
לא מצליח לשחזר את הבעיה
?את יכולה להשמים לי מסופון איני במחיצה
[H-Facebook]<https://www.facebook.com/Hashavshevetldt/>

**Comment by wizayala** [comment]
H:\HomeFolder\Ayala\for moti

**Comment by wizayala** [comment]
ראינו שזה קורה רק במפורטת

**Comment by WizMotiSaadon** [comment]
אולי ננסה באנגלית?

**Comment by wizayala** [comment]
אתה מתכוון למסלול ?
במקוצרת זה גם היה מסלול עם מלל ומספרים  וזה עבד טוב

**Comment by WizMotiSaadon** [comment]
אבל לא בחרנו אותה מחיצה

**Comment by wizayala** [comment]
כאשר שיניתי את המסלול של המפורטת למסלול קצר יותר זה בסדר 
אז הבעיה היא באורך של המסלול ?

**Comment by WizMotiSaadon** [comment]
> כאשר שיניתי את המסלול של המפורטת למסלול קצר יותר זה בסדר
> אז הבעיה היא באורך של המסלול ?

בודק

**Comment by WizMotiSaadon** [comment]
לקחתי מחיצה ממש ארוכה
c:\1234567890\1234567890\1234567890\1234567890\1234567890\movein.dat

תקין,
כנראה יש בעיה במחיצה הספציפית

**Comment by wizayala** [comment]
מוטי
מה נסגר עם זה ? מה הבעיה באורך המחיצה ?

**Comment by WizMotiSaadon** [comment]
אין בעיה באורך המחיצה
לקחתי מחיצה באורך גדול ואין בעיה כלשהיא

**Comment by wizayala** [comment]
לא חושבת שהמחיצה שלי הייתה כל כך ארוכה ובכל זאת הייתה בעיה .
זו המחיצה :
C:\קבצי ממשקים\תנועות יומן\2019\מפורטת\תיקיה חדשה

**Comment by WizMotiSaadon** [comment]
אבל איך זה ממחיצה פשוטה כמו 
c:\123
