### ISSUE TITLE
יבוא תנועות יומן - תנועות תקציביות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#365]
כאשר מופיע ה שאלה האם לפתוח מנה תקציבית כאשר חלק מן התנועות בקובץ קלט הן תקציביות (ס"ת תק) אני עונה על השאלה בלא 

![image](https://user-images.githubusercontent.com/16633745/98235784-fe65a200-1f6a-11eb-9abd-395f83ee3e55.png)

מופיעה החלון הבא : 
![image](https://user-images.githubusercontent.com/16633745/98235742-eaba3b80-1f6a-11eb-86a8-3fe043b52c94.png)

**Comment by WizMotiSaadon** [comment]
תוקן
jurnalin.hds

**Comment by wizasher** [comment]
אצלי אין הודעת שגיאה , וכל הפקודות נכנסות למנה אחת (גם הרגילות וגם ס"ת תק). נראה תקין .

**Comment by wizayala** [comment]
תקין
