### ISSUE TITLE
crm ייבוא תנועות 

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#366]
בייבוא תנועות 
crm
כשאני משדך בשדה "עדיפות" ו"בוצעה התקשרות" מלל במקום שדה מספרי או byte - זה מתרסק . תודה

**Comment by WizMotiSaadon** [comment]
אפשר צילום מסך?

**Comment by wizasher** [comment]
בבקשה
![image](https://user-images.githubusercontent.com/69102026/98644304-f2962900-2338-11eb-8b63-c24299273412.png)

**Comment by wizasher** [comment]
ואחרי אישור
![image](https://user-images.githubusercontent.com/69102026/98644401-16f20580-2339-11eb-83cf-87827e8e6550.png)

**Comment by WizMotiSaadon** [comment]
אתה יכול את ההודעה הגדולה 
להעתיק עם 
ctrl C
במקום צילום מסך?

ולהדביק פה

תודה

**Comment by wizasher** [comment]
Error in SQL :The name "מלל" is not permitted in this context. Valid expressions are constants, constant expressions, and (in some contexts) variables. Column names are not permitted.

INSERT INTO CRMAIN (  ACCOUNTKEY,  ACCOUNTFLAG,  BRANCH,  MDATE,  MTIME,  CONTACT,  DETAILS,  NEXTDATE,  NEXTTIME , PRIORITY,  MORECALL,  MSENDTO,  ECRTEXT1,  ECRTEXT2,  ECRTEXT3,  ECRTEXT4,  ECRTEXT5,  ECRTEXT6,  ECRTEXT7,  ECRTEXT8,  ECRTEXT9,   ECRTEXT10,  ECRTEXT11,  ECRTEXT12,  ECRTEXT13,  ECRTEXT14,  ECRTEXT15, ECRNUM1,  ECRNUM2,  ECRNUM3,  ECRNUM4,  ECRNUM5,  ECRNUM6,  ECRNUM7,  ECRNUM8,  ECRNUM9,  ECRNUM10,  ECRNUM11,  ECRNUM12,  ECRNUM13,  ECRNUM14,  ECRNUM15,  ECRDATE1,  ECRDATE2,  ECRDATE3,  ECRDATE4,  ECRDATE5 ,  EXTRATIME1,  EXTRATIME2,  EXTRATIME3,  MENDDATE , MENDTIME , USEFID,  MTYPE,  MSTATUS,  STATUS,  DONUSER,  DONDATE,  NEXTDONE )      VALUES (  'CRM1',  0,  9,  '04/20/2019',  750.000000000,  'איש קשר',  'תיאור',  '04/20/2020',  750.000000000,  מלל,  0,  2, 'טקסט קצר מספר 1',  'טקסט קצר מספר 2',  'טקסט קצר מספר 3',  'טקסט קצר מספר 4',  'טקסט קצר מספר 5',   'שדה קומבו מספר 1',  '',  '',  '',  '', 'טקסט ארוך מספר 1',  'טקסט ארוך מספר 2',  'טקסט ארוך מספר 3',  'טקסט ארוך מספר 4',  'טקסט ארוך מספר 5',   1000,  2000,  3000,  4000,  5000,   111.000000000,  222.000000000,  333.000000000,  444.000000000,  555.000000000,   1,  0,  0,  0,  0,  '01/01/2001',  '2020-11-10',  '2020-11-10',  '2020-11-10',  '2020-11-10',  930.000000000,  0,  0,  '12/31/2025',  1439.000000000,  1,  'פגישה',  'הצגת מבנה',  0,  '8',  '12/31/2025',  מלל    )

**Comment by WizMotiSaadon** [comment]
תוקן
CrMainIn.HDS

**Comment by wizasher** [comment]
מעולה - הודעה ברורה  , תודה

**Comment by wizayala** [comment]
אצלי הוא נופל כשקשרתי שם חשבון (מלל ) לשדה סוג חשבון 

---------------------------
HSD
---------------------------

Error in SQL :Conversion failed when converting the varchar value 'יוסי' to data type int.

UPDATE  IMPORTCRMAIN SET IMPORTCRMAIN.ERRORMESSAGE = 'סוג חשבון אפס מחייב מפתח חשבון',  IMPORTCRMAIN.ERRORDATA = 'IMPORTCRMAIN.AccountKey is empty'  FROM  IMPORTCRMAIN    WHERE (LEN(IMPORTCRMAIN.ACCOUNTFLAG) = 0 OR IMPORTCRMAIN.ACCOUNTKEY IS NULL)  AND  IMPORTCRMAIN.ACCOUNTFLAG = 0
---------------------------
אישור  
---------------------------

**Comment by wizayala** [comment]
צריך לעשות תיקון על כל השדות  מסוג 
byte

**Comment by WizMotiSaadon** [comment]
> אצלי הוא נופל כשקשרתי שם חשבון (מלל ) לשדה סוג חשבון
> 

תוקן
CrMainIn.HDS

**Comment by wizayala** [comment]
ועכשיו נופל בהתקשרות נוספת

---------------------------
HSD
---------------------------

Error in SQL :Incorrect syntax near 'קצר'.

INSERT INTO CRMAIN (  ACCOUNTKEY,  ACCOUNTFLAG,  BRANCH,  MDATE,  MTIME,  CONTACT,  DETAILS,  NEXTDATE,  NEXTTIME , PRIORITY,  MORECALL,  MSENDTO,  ECRTEXT1,  ECRTEXT2,  ECRTEXT3,  ECRTEXT4,  ECRTEXT5,  ECRTEXT6,  ECRTEXT7,  ECRTEXT8,  ECRTEXT9,   ECRTEXT10,  ECRTEXT11,  ECRTEXT12,  ECRTEXT13,  ECRTEXT14,  ECRTEXT15, ECRNUM1,  ECRNUM2,  ECRNUM3,  ECRNUM4,  ECRNUM5,  ECRNUM6,  ECRNUM7,  ECRNUM8,  ECRNUM9,  ECRNUM10,  ECRNUM11,  ECRNUM12,  ECRNUM13,  ECRNUM14,  ECRNUM15,  ECRDATE1,  ECRDATE2,  ECRDATE3,  ECRDATE4,  ECRDATE5 ,  EXTRATIME1,  EXTRATIME2,  EXTRATIME3,  MENDDATE , MENDTIME , USEFID,  MTYPE,  MSTATUS,  STATUS,  DONUSER,  DONDATE,  NEXTDONE )      VALUES (  'CRM1',  0,  9,  '04/20/2019',  750.000000000,  'איש קשר',  'תיאור',  '04/20/2020',  750.000000000,  1,  טקסט קצר מספר 1,  3, 'טקסט קצר מספר 1',  'טקסט קצר מספר 2',  'טקסט קצר מספר 3',  'טקסט קצר מספר 4',  'טקסט קצר מספר 5',   'שדה קומבו מספר 1',  '',  '',  '',  '', 'טקסט ארוך מספר 1',  'טקסט ארוך מספר 2',  'טקסט ארוך מספר 3',  'טקסט ארוך מספר 4',  'טקסט ארוך מספר 5',   1000,  2000,  3000,  4000,  5000,   111.000000000,  222.000000000,  333.000000000,  444.000000000,  555.000000000,   1,  0,  0,  0,  0,  '01/01/2001',  '2020-11-11',  '2020-11-11',  '2020-11-11',  '2020-11-11',  930.000000000,  0,  0,  '12/31/2025',  1439.000000000,  2,  'פגישה',  'הצגת מבנה',  0,  '3',  '12/31/2025',  1    )
---------------------------
אישור  
---------------------------

**Comment by WizMotiSaadon** [comment]
> ועכשיו נופל בהתקשרות נוספת
> 
תוקן

**Comment by wizayala** [comment]
תקין.
אשר צריך לעבור על כל השדות ולוודא שאכן תקין בכל המקומות.

**Comment by wizasher** [comment]
בדקתי את כל השדות עם "מלל" על כולם יש הודעה חוץ משדה סניף וסטטוס ששם זה מתרסק

**Comment by WizMotiSaadon** [comment]
> בדקתי את כל השדות עם "מלל" על כולם יש הודעה חוץ משדה סניף וסטטוס ששם זה מתרסק

תוקן

**Comment by wizayala** [comment]
אצלי תקין

**Comment by wizasher** [comment]
גם אצלי תקין . תודה
