### ISSUE TITLE
ייבוא פקודות יומן מאקסל שדה הערות

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#368]
לבקשת אפי ,לקצץ את שדה הערות אם הוא חורג מ- 50 תווים .תודה

**Comment by WizMotiSaadon** [comment]
תוקן
odbcimp.exe

**Comment by wizayala** [comment]
תקין בשדות הערות , הערות נוספות

**Comment by wizasher** [comment]
גם אצלי תקין ,תודה
