### ISSUE TITLE
יבוא ספירת מלאי - פריט אצווה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#369]
ביבוא תנועות ספירת מלאי פריט מסוג אצווה 
items.stopckperunit=4
חייב לייבא שדה אצווה 
importstocktakin.batchnum
צריך לתת הודעה מתאימה

**Comment by WizMotiSaadon** [comment]
תוקן
![image](https://user-images.githubusercontent.com/10919353/99053404-a13ca280-25a1-11eb-9224-078bb237e5c2.png)

**Comment by WizMotiSaadon** [comment]
> יש לשים לב שאין לאפשר שדה אצווה לפריטים שאינם מסוג
> items.stopckperunit=4

תוקן

**Comment by wizayala** [comment]
במקרה והפריט הוא מסוג פריט רגיל , אין לאפשר קליטת אצווה 

![image](https://user-images.githubusercontent.com/16633745/99169754-c7805080-270f-11eb-95f2-bda44ba5255d.png)

**Comment by wizayala** [comment]
הודעה תקינה כאשר מדובר על פריט שהוא אצווה וחסר נתון אצווה 

![image](https://user-images.githubusercontent.com/16633745/99170251-ef6fb400-270f-11eb-9a76-bc06fb6c60c1.png)

**Comment by WizMotiSaadon** [comment]
> במקרה והפריט הוא מסוג פריט רגיל , אין לאפשר קליטת אצווה

את יכולה לצלם לי את סוג הפריט
של
7001
?

**Comment by wizayala** [comment]
תקין עם הקובץ 
StockTakingIn.HDS

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/99180709-61a4c080-2731-11eb-836b-9c6c266303f1.png)

**Comment by wizasher** [comment]
גם אצלי מצוין
