### ISSUE TITLE
יבוא הלוואות - קוד תמחיר

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#37]
הוספנו שדה של קוד תמחיר ביבוא הלוואות בתאריך 7/18
שדה : new filed:
ImportLoan.costcode varchar(8)

הקובץ האחרון שיש לי הוא loanin.hds מתאריך 18.2.19 ואני לא רואה את השדה החדש.

**Comment by WizMotiSaadon** [comment]
אני מחכה שהדס תכניס את השדה ל 
DB

**Comment by wizayala** [comment]
גם פה אין צורך הוספנו את השדה הזה


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
ALTER TABLE importloan
ADD costcode varchar(8);

**Comment by wizayala** [comment]
השדה הזה כבר קיים אצלי
[cid:image001.png@01D5DB57.2AF848D0]


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
בהדפסת השגויים אין תאור תקלה כפי שמופיע על המסך

![image](https://user-images.githubusercontent.com/16633745/73742186-84428b80-4754-11ea-8bd9-42db5642c295.png)

**Comment by WizMotiSaadon** [comment]
CNVerr.ard לעדכן

**Comment by wizayala** [comment]
או.קיי
עדכנתי גם את הדס שתבדוק את הקובץ בסט ההתקנה של התוכנה


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
תקין
