### ISSUE TITLE
יבוא תנועות מלאי - מסמך ע"ס מסמך כמות גדולה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#370]
קליטה של מסמך ע"ס מסמך כיום אנחנו עושים אך ורק אם כמות תנועת המלאי בממשק שווה או קטנה לכמות של תנועת הבסיס. 
נתבקשנו לאפשר קליטת של תנועת מלאי  גם כאשר כמות תנועת המלאי בממשק היא שווה או גדולה לכמות של תנועת הבסיס אך זה יתאפשר אך ורק לסוגי מסמכים מסוימים.
התנאי של מסמכים הוא שמסמך הבסיס הוא מסוג

 documentsdef.stockupdate=0
שלחתי לכם מסמך במייל

**Comment by wizayala** [comment]
זו ההודעה שמתקבלת כיום אם הכמות היא גדולה מדי 

![image](https://user-images.githubusercontent.com/16633745/99186176-46e54280-2757-11eb-83c1-b511c55a08e0.png)

**Comment by WizMotiSaadon** [comment]
תוקן 
mlayin.hds
{st_DocumentsDef_StockUpdate}!=0 And

**Comment by wizasher** [comment]
אצלי עדיין נותן הודעה על כמות גדולה 
![image](https://user-images.githubusercontent.com/69102026/99233385-d2b0aa80-27fb-11eb-971a-68a28fd42d1a.png)

**Comment by WizMotiSaadon** [comment]
איזה סוג מסמך הוא סוגר?

**Comment by wizasher** [comment]
ת.משלוח סוכן סוגר הזמנה

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizasher** [comment]
נקלט מצוין עם כמות גבוהה מהבסיס .אני יעשה עוד בדיקות מסביב .תודה

**Comment by wizasher** [comment]
אצלי תקין

**Comment by wizayala** [comment]
בדקתי עבור נעילת מסמך במסמך אחר - תקין
