### ISSUE TITLE
יבוא תנועות יומן - מסופון2 כתב ראי

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#371]
ביבוא תנועות יומן ממסופון2 אין את האפשרות של כתב ראי

**Comment by WizMotiSaadon** [comment]
תוקן לתנועות יומן בלבד
jurnalin.hds

**Comment by wizayala** [comment]
מה התיקון ?
מה מבצע היפוך של כתב ראי ?
oem2ansi
ansi2ansi ?

**Comment by WizMotiSaadon** [comment]
oem2ansi

**Comment by wizasher** [comment]
אצלי תקין , תודה

**Comment by wizayala** [comment]
גם אצלי תקין

**Comment by wizayala** [comment]
אשר :
צריך לוודא שתקין מתוך התוכנה , קבצי דוס, עברית הפוכה, עברית תקינה וכו '..

**Comment by wizayala** [comment]
בדקתי מספר קבצים , אצלי נראה תקין

**Comment by wizasher** [comment]
אצלי תקין
