### ISSUE TITLE
 שדה תאריך ושעה - ייבוא תנועות הנה"חש מאקסל

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#372]
כאשר קולטים מאקסל והתאריך מוצג "תאריך ושעה" זה נכנס לטבלאות גם בצורה של "תאריך ושעה" ואז כשרוצים בהמשך בחשבשבת לעשות פעולות על פקודות היומן(כמו שערוך למטח/שקלים) יש לו בעיה עם תאריך מסוג כזה .
אפי ביקשה שבקליטה לטבלאות תמיד זה יכנס כתאריך ללא שעה . תודה
![image](https://user-images.githubusercontent.com/69102026/99380787-12969100-28d3-11eb-9ca8-cc2f51099993.png)
![image](https://user-images.githubusercontent.com/69102026/99380862-2d690580-28d3-11eb-8d6c-2c44078ab4d0.png)

**Comment by WizMotiSaadon** [comment]
אפשר לשלוח לי קובץ קלט?

**Comment by wizasher** [comment]
שולח במייל

**Comment by wizayala** [comment]
באג שהיה וחזר 


תנועות   יומן | קליטה של פורמט תאריך עם   שעה 00000 , היה מעדכן שעת קליטה | wizimportlogic.dll | 16.06.2020 | 2020a sp2
-- | -- | -- | -- | --
תנועות   יומן | קליטה של   פורמט תאריך עם שעה 00000 , היה מעדכן שעת קליטה | hsimportjurnal.sql | 17.06.2020 | 2020a sp2

**Comment by WizMotiSaadon** [comment]
CONVERT(char(10), ValueDate,120)     ,\
CONVERT(char(10), DueDate,120)   ,\


תוקן
**WizImportMySql.dll**

**Comment by wizasher** [comment]
אצלי מצוין , תודה

**Comment by wizayala** [comment]
שאלה לידע כללי , מדוע התיקון הוא ב 
wizimportmysql.dll
ולא כמו שהיה קודם בקובץ
wizimportlogic.dll

**Comment by WizMotiSaadon** [comment]
התיקון הקודם התייחס לתאריך שלא קושר ואז הייתי שם ברירת מחדל מערכת עם שעה
לא מאופסת

המקרה הזה הוא לשדה שקושר אבל בכל זאת השעה לא הייתה מאופסת
ואז צריך לקצוץ את השעה

**Comment by wizayala** [comment]
תודה על ההסבר המפורט
