### ISSUE TITLE
ייבוא תנועות מלאי מתרסק כשיש מלל

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#373]
, בייבוא תנועות מלאי מתרסק שיש מלל בשדות :  מס' שורת בסיס, עותקים, טלפון נוסף, תאריך נוסף , מחסן בתנועה מספר נוסף 1  מספר נוסף 2 ,. תודה .

**Comment by WizMotiSaadon** [comment]
תוקן
למרות שאני לא מבין עדיין 
מה הכוונה טלפון נוסף

**Comment by wizasher** [comment]
התבלבלתי , הכוונה "טלפון"

**Comment by WizMotiSaadon** [comment]
אני יכול להתחבר לראות את זה?

**Comment by wizasher** [comment]
הכל תקין , חוץ מטלפון ותאריך נוסף
 יש אפשרות שכשהו מודיע על תקלה הוא מרכז את כל התקלות ביחד  או שזה בלתי אפשרי וברגע שהוא מזהה בעיה הוא עוצר ומודיע ?

**Comment by wizasher** [comment]
מצוין , הכל תקין .תודה
איילה - יש קובץ מתקן חדש 
odbcimp.exe

**Comment by wizayala** [comment]
תקין גם אצלי
