### ISSUE TITLE
קליטת פקודות יומן בשיטה הגמישה - שדה כמות

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#374]
כל הכמות נקלטת כשלמים ללא ערך עשרוני,  בגירסה 2018  ארבעה הספרות האחרונות ניקלטו כערך עשרוני אחרי הנקודה
אני מצרף צילום מסך של 2018ושל 2020
![image](https://user-images.githubusercontent.com/69102026/99502895-60b89c80-2986-11eb-819f-05d6687b03a7.png)
![image](https://user-images.githubusercontent.com/69102026/99502948-70d07c00-2986-11eb-8b63-cf900e06ef91.png)
תודה

**Comment by WizMotiSaadon** [comment]
כנראה שבשדה קלט לא הייתה נקודה עשרונית אז חילקתי במאה
זה תרגיל שאני עושה עם שדה כספי

?אני מבין שבגרסה האחרונה זה תקין

**Comment by wizasher** [comment]
נכון בשדה של הממשק אין נקודה עשרונית .אבל במהדורה 2018 זה נתן לו את 4 ספרות אחרונות כערך עשרוני וב- 2020 זה נותן מספר שלם . נשאל את איילה מה צריך להיות כאשר אין נקודה עשרונית

**Comment by WizMotiSaadon** [comment]
לדעתי בגרסה 
2018
זו טעות

כלומר אני לא אמור לחלק ב 100

**Comment by wizayala** [comment]
היי, 
החלוקה בכלל צריכה להיות ב 1000, ולא ב 100
בגרסה 2020 אין חלוקה כלל לכן צריך לתקן את זה 
נראה שבגרסה 2018 הייתה חלוקה ב 100 שגם היא שגויה.
לדעתי בשורה תחתונה צריך לחלק ב 1000, כאשר מגיע נתון ללא דיוק עשרוני , אבקש אישור מאפרת לתיקון

**Comment by WizMotiSaadon** [comment]
לדעתי
החלוקה היא רק עבור כסף כי אם אין נקודה עשרונית 
אז מדובר באגורות

את אומרת שאם הכמות בלי נקודה עשרונית אז זה מגיעה בגרמים?

**Comment by wizayala** [comment]
למען האמת , אין לי מושג 
אבל אני רואה ששדה כמות הוא עם דיוק עשרוני של 4 ספרות
אדבר מחר בבוקר עם אפרת

**Comment by wizayala** [comment]
מוטי
לאחר שיחה עם אפרת אנחנו נמשיך טעות היסטורית ונחלק את שדה כמות ב 100
אשמח אם תוכל לטפל בזה , יש לקוח שממתין לתיקון

**Comment by WizMotiSaadon** [comment]
תיקנתי
WizImportMySql.dll

**Comment by wizayala** [comment]
אצלי תקין

**Comment by wizasher** [comment]
גם אצלי תקין
