### ISSUE TITLE
יבוא קבצי טקסט - תו מפריד

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#375]
מוטי
יש לדאוג לאפשרות של יבוא קבצי טקסט ממסופון 2 עם תו מפריד "tab "

**Comment by WizMotiSaadon** [comment]
m_DelimitedChar = strImportFileFormat.GetAt(10);

**Comment by wizayala** [comment]
ועכשיו בעברית......

**Comment by WizMotiSaadon** [comment]
אני יכול שאם שמים לי תו מפריד 
(t)
אז אני יפריד את השדות לפי טאבים
זה מתאים?

**Comment by wizayala** [comment]
רוצה קובץ דוגמא של הפרדה בטאבים ?

**Comment by WizMotiSaadon** [comment]
> רוצה קובץ דוגמא של הפרדה בטאבים ?

אשמח

**Comment by wizayala** [comment]
שלחתי לשניכם במייל נפרד

**Comment by wizayala** [comment]
מוטי 
איפה זה עומד ?
מה התו המפריד יהיה בסופו של דבר האות "t" או הסימן של הטאב שזה החץ ?

**Comment by WizMotiSaadon** [comment]
תני לי דוגמא איך נראה החץ

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/100334248-31d0a500-2fdc-11eb-84d9-7ad544a1dcd9.png)

**Comment by wizayala** [comment]
בנוסף שלחתי לך מייל עם קובץ 
imovein.doc
עם תו מפריד "טאב"
