### ISSUE TITLE
מסופון2 כתב ראי לחשבונות ופריטים

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#376]
יש אפשרות כמו בגיט 371 לקלוט "כתב ראי " גם מקובץ חשבונות ופריטים , תודה

**Comment by wizayala** [comment]
אשר, סליחה לא ראיתי שכבר פתחת גיט
הוספתי גיט שמפרט את כל הממשקים שצריך

**Comment by wizasher** [comment]
סבבה , סוגר
