### ISSUE TITLE
יבוא ממסופון 2 - כתב ראי

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#377]
מוטי
יש לעשות תיקון לקליטת קבצים ממסופון2 אשר יש בהם כתב ראי , 
יבוא חשבונות
יבוא חשבונות פוטנציאלים
יבוא פריטים
יבוא תנועות מלאי / זמני
יבוא קופה / זמני
יבוא מחירים מיוחדים

**Comment by wizayala** [comment]
עשינו תיקון לכך בגיט  #371

**Comment by wizayala** [comment]
מה זה הקובץ
itemin_fast.hds  ?

**Comment by WizMotiSaadon** [comment]
יבוא פריטים מהיר
עדיין לא ללקוחות, רק שומר אותו בזיפ שלא ילך לאיבוד

**Comment by wizayala** [comment]
חשבונות - תקין

**Comment by wizayala** [comment]
חשבונות פוטנצאליים - תקין
תנועות מלאי - תקין 
תנועות מלאי זמני - תקין

**Comment by wizayala** [comment]
מחירים מיוחדים , תאור הפריט נקלט הפוך , שם החשבון נקלט תקין דווקא 

![image](https://user-images.githubusercontent.com/16633745/100331388-c33e1800-2fd8-11eb-9499-e2ded00993ce.png)

**Comment by wizayala** [comment]
תנועות קופה תקין

**Comment by wizayala** [comment]
מוטי שים לב לשיבוש בקליטת מחירים מיוחדים

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by WizMotiSaadon** [comment]
> מוטי שים לב לשיבוש בקליטת מחירים מיוחדים

תוקן

**Comment by wizayala** [comment]
מצויין

![image](https://user-images.githubusercontent.com/16633745/101281065-bf2ea900-37d5-11eb-8ab2-9f649fff4a92.png)

**Comment by wizayala** [comment]
אשר 
נעביר את שאר הקבצים ל
 2020asp5
לאחר שאתה תסיים את הבדיקות שלך

**Comment by wizasher** [comment]
סיימתי לבדוק , הכל מצוין . תודה רבה .

**Comment by wizayala** [comment]
העברתי ל 2020asp5

**Comment by wizasher** [comment]
יש קובץ 
itemin.hds
3.9.20
עם קליטה מהירה שאנחנו מעבירים אותו למהדורה 2021
יש בו את התיקון של גיט #359 
אבל חסר את התיקון של הגיט הזה #377
תוכל בבקשה לתקן ואני אשלח לגלי 
תודה 
לשלוח לך את הקובץ מ-
3.9.20
?

**Comment by WizMotiSaadon** [comment]
> לשלוח לך את הקובץ מ-
> 3.9.20
> ?

כן

**Comment by wizasher** [comment]
תוכל בבקשה לתת לתיקון הזה עדיפות כדי שאשלח לגלי קובץ מתוקן ל- 2021
תודה

**Comment by WizMotiSaadon** [comment]
סידרתי את זה ושלחתי לך

**Comment by wizasher** [comment]
תודה רבה 
בודק

**Comment by wizayala** [comment]
אצלי מבצע היפוך בקליטת פריטים ממסופון 2 עם עברית הפוכה

**Comment by wizayala** [comment]
האם קובץ
itemin_fast.hds 
ששלחת בתאריך 20.7.21
מתאים לגרסה 
2021 ?

**Comment by wizayala** [comment]
הוא לא מופיע בתוך הזיפ

**Comment by WizMotiSaadon** [comment]
> האם קובץ
> itemin_fast.hds
> ששלחת בתאריך 20.7.21
> מתאים לגרסה
> 2021 ?

כן

**Comment by WizMotiSaadon** [comment]
> הוא לא מופיע בתוך הזיפ

![image](https://user-images.githubusercontent.com/10919353/126877226-9203618c-9768-4fbf-a10b-85f2e0c6e0fe.png)

**Comment by WizMotiSaadon** [comment]
> אצלי מבצע היפוך בקליטת פריטים ממסופון 2 עם עברית הפוכה

כלומר תקין?

**Comment by wizasher** [comment]
אצלי תקין עברית הפוכה.
בודק מסביב

**Comment by wizasher** [comment]
אני מקבל על פריטים מסוג 
טבוע , מונה ומכפלה
בפריט מסוג זה כמות באריזה חייבת להיות אפס
והכנסתי 0
עם טקסט לעמודות 
![image](https://user-images.githubusercontent.com/69102026/126895196-fb7e754e-f3d6-4fe8-9cc3-7189444f1030.png)

אני שולח קובץ

**Comment by WizMotiSaadon** [comment]
אתה יכול לתת לי צילום של התקלה
כדי שאוכל לחפש אותה בקוד
?

**Comment by wizasher** [comment]
![image](https://user-images.githubusercontent.com/69102026/126895742-1661a085-b07b-4cf5-9380-18728ec93ddb.png)
