### ISSUE TITLE
ייצוא אחיד -חברה ללא משתמשים 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#379]
בחברה שבה אין משתמשים הדס מבקשת שתבטל את החלון הבא 

![image](https://user-images.githubusercontent.com/16633745/100348032-f8556500-2fee-11eb-8f69-4a7b27d87807.png)

**Comment by WizMotiSaadon** [comment]
WizBkmvWin.exe

תוקן

**Comment by wizayala** [comment]
אצלי תקין , לדעתי אפשר להעביר ליוליאן
