### ISSUE TITLE
תיקון לטבלת IMPORTLOG

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#380]
מדריך רצה לדעת מי המשתמש שקלט את הממשק  "סוכנים/מחסנים/סניפים"
יש טבלה בשם 
IMPORTLOG
שזה כמו לוג על הממשקים ..
הממשק של "סוכנים/מחסנים/סניפים" לא היה נכנס לשם .
מוטי הוסיף אותו .
שם הקובץ המתקן 
 AgentWHin.HDS

**Comment by wizayala** [comment]
מוטי
יש לתקן את סוג היבוא שאינו מתעדכן בטבלת 
importlog  
נרשם 0 במקום 
odbc...

![image](https://user-images.githubusercontent.com/16633745/100995579-a6698d80-3560-11eb-83f1-1fcd9921517e.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
תקין גם ממסופון 2

![image](https://user-images.githubusercontent.com/16633745/101275257-fb014880-37ac-11eb-944a-f382a4b2e10a.png)

**Comment by wizayala** [comment]
במסופון2
האם אפשרת לתקן במקום "**שמות סוכנים**" שיופיע סוכנים, מחסנים, סניפים כמו בתוכנה 


![image](https://user-images.githubusercontent.com/16633745/101275277-12d8cc80-37ad-11eb-832e-887cf2bb3ddc.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
תודה 
![image](https://user-images.githubusercontent.com/16633745/101280994-34e64500-37d5-11eb-9d94-23a335778568.png)

**Comment by wizasher** [comment]
גם אצלי מצוין . תודה
