### ISSUE TITLE
ייצוא חשבונות - שדה עם אנטר

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#381]
במידה ויש לי שדה שעשיתי בו 
ctrl+enter
זה משבש את הייצוא של קובץ חשבונות 

![image](https://user-images.githubusercontent.com/16633745/101010575-036a4100-356b-11eb-89f6-7044f02c7dd1.png)

![image](https://user-images.githubusercontent.com/16633745/101010714-0d8c3f80-356b-11eb-8d6e-3819213f022d.png)

שולחת לשניכם קבצים לדוגמא

**Comment by WizMotiSaadon** [comment]
תוקן
מייצא בלי השבירת שורה

AccOut.hds

**Comment by wizasher** [comment]
אצלי מצוין .תודה

**Comment by wizayala** [comment]
עדיין רואה שיבוש בקובץ 

![image](https://user-images.githubusercontent.com/16633745/102006023-242e5580-3d26-11eb-97b2-47533eedc30a.png)

מעבירה מייל עם קבצי קלט 
ייתכן והשיבוש נובע בגלל שדות אחרים שהם ארוכים מדי ?

**Comment by WizMotiSaadon** [comment]
תנסי בבקשה לתקן את השבירת שורות 
ולייצא מחדש

וככה נדע אם זה בגלל שבירת שורות או סיבה אחרת

**Comment by wizayala** [comment]
אחרי התיקון שעשית לשדה 
details
אמשיך לבדוק שדות נוספים

**Comment by wizasher** [comment]
אצלי עובד טוב בשדות נוספים

**Comment by wizayala** [comment]
תקין
