### ISSUE TITLE
ממשק של פקודות יומן עם תו אסקי באמצע 

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#383]
הקבצים נקלטים ב- 2018 – כל השורות (700)
ב- 2020 זה קולט חצי בלי להודיע הודעה .
כשאני פותח את הקובץ יש סימנים לא ברורים במקום שהוא מפסיק לקלוט . 
(SUB)
אם אני מוחק את 2 השורות זה קולט את כל הקובץ גם ב- 2020 .
תודה

**Comment by WizMotiSaadon** [comment]
תוקן
WizImportLogic.dll

**Comment by wizasher** [comment]
אצלי תקין. תודה

**Comment by wizasher** [comment]
אם תוכל בבקשה לתקן את הקובץ מהתאריך 23.10.2020 כי זה התיקון האחרון בחשבשבת .תודה

**Comment by WizMotiSaadon** [comment]
> אם תוכל בבקשה לתקן את הקובץ מהתאריך 23.10.2020 כי זה התיקון האחרון בחשבשבת .תודה

מה שם הקובץ?

**Comment by wizasher** [comment]
WizImportLogic.dll

**Comment by WizMotiSaadon** [comment]
14/12/2020 16:45 
זה התאריך המעודכן

יש אותו בזיפ?

**Comment by wizasher** [comment]
נכון , את התיקון שעשית ב- 14.12 היה צריך לעשות בקובץ מ-  23.11 כי באמצע היה עוד תיקון ב- 22.11 שהיה קשור ל- 
API 
![image](https://user-images.githubusercontent.com/69102026/102318432-fe04f180-3f81-11eb-83a0-0aa412d2b68a.png)
אם לא ברור אני אתקשר להסביר . תודה

**Comment by WizMotiSaadon** [comment]
התיקון האחרון מטפל גם ב
API

וגם בבעיה של התו ג'יבריש

**Comment by wizasher** [comment]
נכון , בגלל שרצינו להפריד בין הקבצים שמטפלים ב
API
לקבצים שמטפלים בחשבשבת (מה שדיברנו שנעשה תיקיות נפרדות בהמשך) והתיקון האחרון מטפל גם  בתו ג'יבריש (שזה קשור לחשבשבת)וגם ב 
API
לכן אם אפשר שאת התיקון של התו ג'יבריש תעשה על הקובץ מ- 23.10 שזה פעם האחרונה שהקובץ תיקן מה שקשור לחשבשבת

**Comment by WizMotiSaadon** [comment]
העיניין הוא שכל קומפילציה התאריך של הקובץ משתנה, זה קובץ בינארי

**Comment by wizasher** [comment]
אני אבדוק עם איילה מה היא מציעה . תודה

**Comment by wizayala** [comment]
התיקון צריך להיות על הקובץ האחרון מגרסת לקוחות 
הקובץ נמצא במחיצה
H:\HomeFolder\Ayala\for moti

**Comment by WizMotiSaadon** [comment]
שמתי תיקון גרסת לקוחות 
2020-12-17

**Comment by wizasher** [comment]
אצלי נקלט מצוין. תודה .

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/102707043-0883fb80-42a0-11eb-9c1e-808108f2de81.png)


![image](https://user-images.githubusercontent.com/16633745/102707058-30735f00-42a0-11eb-9e73-c37778678150.png)

מדוע אנחנו שותלים בשדה
importjurnal.exefile    , jurnaltrans.exefile
את הערך /

**Comment by wizayala** [comment]
כשאין נתון הערך צריך להיות 
null

**Comment by WizMotiSaadon** [comment]
> מדוע אנחנו שותלים בשדה
> importjurnal.exefile , jurnaltrans.exefile
> את הערך /

אולי זה מה שמגיע מהקובץ קלט

**Comment by WizMotiSaadon** [comment]
הדס בקשה ממני להוסיף סלאש

//add "\" as hadas request
sql<<FormatString("
update |tableName|
set |tableName|.|FieldName| = '\' + |tableName|.|FieldName|
where CHARINDEX('\',|tableName|.|FieldName|,0) <> 1 and CHARINDEX(':',|tableName|.|FieldName|,0) <> 2
",1)[;]


ExecuteSql("DB1",sql)[;]

**Comment by wizayala** [comment]
מעניין , אבדוק איתה

**Comment by wizayala** [comment]
זאת הייתה הכוונה של הדס : 
רק אם מקבלים שם קובץ להוסיף \, אם אין שלא יעדכן את השדה.
לכן במקרה הנוכחי מכיוון שאין שדה מקושר ואין נתון אין צורך להוסיף את התו \

**Comment by WizMotiSaadon** [comment]
> זאת הייתה הכוונה של הדס :
> רק אם מקבלים שם קובץ להוסיף , אם אין שלא יעדכן את השדה.
> לכן במקרה הנוכחי מכיוון שאין שדה מקושר ואין נתון אין צורך להוסיף את התו \

תוקן
imp_lib.hds

**Comment by wizayala** [comment]
עדיין מופיע /

**Comment by WizMotiSaadon** [comment]
אולי יש לך טעות?

**Comment by wizayala** [comment]
לא יצאתי מהתוכנה ....
עכשיו אצא מהתוכנה

**Comment by wizayala** [comment]
יציאה מהתוכנה פתרה את הבעיה

**Comment by wizayala** [comment]
ולבקשת הדס כאשר **יש** קובץ מקושר בקובץ קלט יש להוסיף בסוף את התו \
קשירתי קובץ והוא ללא התו הנוסף שהדס בקשה 

![Uploading image.png…]()

**Comment by WizMotiSaadon** [comment]
אני כבר מוסיף בהתחלה,
אז להוסיף גם בסוף וגם בהתחלה?

**Comment by wizayala** [comment]
סליחה , זה תקין
נראה אותו דבר אם אני מקלידה מתוך התוכנה קובץ

**Comment by wizayala** [comment]
סוגרת את הגיט ,
 זה תקין גם כאשר אני מקשרת קובץ עם \
וגם כאשר אני מקשרת רק שם קובץ
