### ISSUE TITLE
מסופון2 - קליטת דפי בנק - API

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#384]
לבקשת הדס , בקליטת דפי בנק ממסופון2 להוסיף את האפשרות של 
Delimited 
(אני אשלח לך את המייל )
תודה רבה

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizasher** [comment]
מה הקובץ המתקן ?

**Comment by WizMotiSaadon** [comment]
genbank.hds

**Comment by wizasher** [comment]
זה מאפשר קליטה ב
Delimited
לכל הבנקים ?

**Comment by WizMotiSaadon** [comment]
רק לפורמט חשבשבת

**Comment by wizasher** [comment]
בגרסה של ה
API
הצלחנו לקלוט דפי בנק בשיטת חשבשבת 
יש לנו קובץ 
genbank.hds
מתאריך 12/12/2020
אם אני זוכר נכון , מה שהדס ביקשה בזמנו הכוונה לשאר הבנקים .
 אני לא יודע אם כרגע זה רלוונטי בנקים  ב- 
API
 כי עבד אמר שבנקים זה בעדיפות תחתונה כרגע  
תודה

**Comment by wizasher** [comment]
סוגר עד להודעה חדשה בנושא 
API
