### ISSUE TITLE
api - masofon2

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#385]
יש להוסיף מזהה חברה 
wizcomp.companies.id 
מזהה החברה יופיע בסוגריים לי שם החברה המייבאת לדוגמא :
test2019 (id=3)
![image](https://user-images.githubusercontent.com/16633745/102478012-c3748500-4065-11eb-9a04-5ab627c309bf.png)

![image](https://user-images.githubusercontent.com/16633745/102478205-ffa7e580-4065-11eb-8ece-db22929b18f2.png)

**Comment by wizayala** [comment]
חשוב מאד 
יש לבצע את התיקון על הקובץ
masofon2.exe
שנמצא במחיצה : 
H:\HomeFolder\Ayala\for moti

**Comment by WizMotiSaadon** [comment]
wizini.dll תוקן

**Comment by wizayala** [comment]
אין צורך לשנות קובץ 
masofon2.exe 
?

קובץ 
wizini.dll 
+
masofon2.exe 26.10.2020

יעבדו יחד ?

**Comment by WizMotiSaadon** [comment]
כן, הם עובדים ביחד

**Comment by wizayala** [comment]
תודה
