### ISSUE TITLE
יבוא תנועות שירות - שיטת חלונות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#387]
לקוח אשר מייצא תנועות שירות בשיטת חלונות אין ל דרך לייבא את זה כמו שמייבאים מחלונות לחלונות תנועות מלאי/ הנה"ח 
בצעת תיקון בקובץ odbcimp.exe
האם יש לייבא את טבלת exportservice ?
אם כן האם תוכל לומר לי מהו שדה שעתון לחיוב אצלך ?

**Comment by WizMotiSaadon** [comment]
אני לא ערוך לקלוט מחלונות,
רק בשיטת 
ODBC

אם את רוצה אתחבר תראי איזה שדות מתקשרים
את רק צריך לבחור את הטבלה של היבוא תנועות שירות וכל השדות מקושרים לבד

**Comment by wizayala** [comment]
לא שוחרר ללקוחות
