### ISSUE TITLE
העברה בין מחסנים - מפתח ללא

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#389]
מדוע מתקבלת הודעה "חשבון ראשי לא מתאים" כאשר אני מקלידה מפתח חשבון "ללא" במסמך העברה בין מחסנים
כאשר אני משאירה את המפתח ריק לאותו סוג מסמך הוא שותל מפתח חשבון "ללא" ואין בעיה עם חשבון ראשי 

![image](https://user-images.githubusercontent.com/16633745/103087626-cbe23800-45f0-11eb-82ae-1ff8456fa06e.png)

**Comment by WizMotiSaadon** [comment]
יכול להיות שיש לך בטבלה של החשבונות 
רשומה עם מפתח חשבון ריק?

**Comment by WizMotiSaadon** [comment]
שיפרתי את הודעת השגיאה, 
את יכולה לצלם לי שוב מסך שגיאות?

**Comment by wizasher** [comment]
בוקר טוב ,
![image](https://user-images.githubusercontent.com/69102026/103264265-df0b5400-49b2-11eb-8d33-ef9640301876.png)

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds

**Comment by wizasher** [comment]
עכשיו נקלט מצוין , אני אבדוק גם בשאר המסמכים שיש "ללא" . תודה

**Comment by wizasher** [comment]
בדקתי מסמך יתרת פתיחה ,יציאה כללית, כניסה כללית עם "ללא" ועם שדה ריק - נקלט מצוין ,נרשם במסמך "ללא ".תודה

**Comment by wizayala** [comment]
כאשר המפתח הוא ריק או "ללא" 
אם אפשר לתקן את הערכים הבאים 
stock.accountname  = null
stock.conract=null
stock.exfile=null
stock.osek874=null
stockmoves.exfile=null
stockmoves.altername=null

לא נראה לי קריטי ודחוף בזמנך

**Comment by wizayala** [comment]
באופן עקרוני התקלה תוקנה, מקבל כעת את הערך "ללא"

**Comment by WizMotiSaadon** [comment]
> כאשר המפתח הוא ריק או "ללא"
> אם אפשר לתקן את הערכים הבאים
> stock.accountname = null
> stock.conract=null
> stock.exfile=null
> stock.osek874=null
> stockmoves.exfile=null
> stockmoves.altername=null
> 
> לא נראה לי קריטי ודחוף בזמנך

למה זה?
לא יכול להיות שם קובץ כל שהוא ם מפתח חשבון ריק?

**Comment by wizayala** [comment]
לא הבנתי למה אתה מתכוון 
תנועה צריכה להירשם בטבלאות אותו דבר בין אן מדובר על ערך במפתח חשבון או בין אם מדובר על מפתח ללא או ריק

**Comment by wizayala** [comment]
מוטי מה קורה עם זה ?

**Comment by WizMotiSaadon** [comment]
?את יכולה לעשות ציטוט כדי שאבין לאיזו סוגיה את מתכוונת

**Comment by wizayala** [comment]
> > כאשר המפתח הוא ריק או "ללא"
> > אם אפשר לתקן את הערכים הבאים
> > stock.accountname = null
> > stock.conract=null
> > stock.exfile=null
> > stock.osek874=null
> > stockmoves.exfile=null
> > stockmoves.altername=null
> > לא נראה לי קריטי ודחוף בזמנך
> 
> למה זה?
> לא יכול להיות שם קובץ כל שהוא עם מפתח חשבון ריק?

**Comment by WizMotiSaadon** [comment]
את מתכוונת ששדה הקובץ צריך להיות
 NULL
?במקום ריק

**Comment by wizayala** [comment]
> את מתכוונת ששדה הקובץ צריך להיות
> NULL
> ?במקום ריק

כן

**Comment by wizayala** [comment]
?????
מה קורה עם זה ?

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds

**Comment by wizayala** [comment]
תודה

**Comment by wizasher** [comment]
אצלי תקין

**Comment by wizayala** [comment]
תקין - סוגרת
