### ISSUE TITLE
יבוא דפי בנק - לאומי שיטה חדשה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#390]
יבוא דפי בנק  בנק לאומי שיטה חדשה, מתקבלת הודעה שהיתרה אינה מתאימה למרות שהיתרה תואמת

![image](https://user-images.githubusercontent.com/16633745/103192086-13faa680-48e0-11eb-94c8-2b918d08a58b.png)

**Comment by WizMotiSaadon** [comment]
LeumiIn.hds

תוקן

**Comment by wizasher** [comment]
אצלי תקין , תודה

**Comment by wizayala** [comment]
גם אצלי - תקין
