### ISSUE TITLE
יבוא בנק לאומי - שדה פרטים ארוך יותר

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#392]
בנק לאומי מוציא קובץ עם שדה פרטים ארוך יותר

**Comment by WizMotiSaadon** [comment]
תוקן
leumiin.hds
igib_imp.dll

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/104124927-4d112d00-535c-11eb-9a42-a085a654f618.png)

כאשר אני מנסה לקלוט פרטים ארוכים דרך שיטת לאומי עם קובץ פרמטרים מתאים

**Comment by WizMotiSaadon** [comment]
מה הגודל של 
bankpges.details
אצלך?

**Comment by wizayala** [comment]
בנק לאומי שיטה חדשה - 50 פרטים ומעלה תצוגה מקדימה תקין, נקלט תקין כמה חשבונות

בנק לאומי שיטה חדשה - שדה פרטים מקוצר , תצוגה מקדימה תקין , חוץ מכותרות, אבל נקלט תקין כמה חשבונות
בנק לאומי שיטה ישנה - שדה פרטים מקוצר עם קובץ פרמטרים ישן 

סיכום ביניים

**Comment by WizMotiSaadon** [comment]
מה הפשט?

**Comment by wizayala** [comment]
גם אתה רואה שטיסל ?

**Comment by WizMotiSaadon** [comment]
בהחלט

**Comment by wizayala** [comment]
אני לומדת בחבורתא עם אשר מנסה להבין מה הפשט

**Comment by WizMotiSaadon** [comment]
> אני לומדת בחבורתא עם אשר מנסה להבין מה הפשט

חסדי השם

**Comment by WizMotiSaadon** [comment]
> אני לומדת בחבורתא עם אשר מנסה להבין מה הפשט

איזה שפיצים

**Comment by WizMotiSaadon** [comment]
> בנק לאומי שיטה ישנה - שדה פרטים מקוצר עם קובץ פרמטרים ישן

תוקן
genbank.hds

**Comment by wizayala** [comment]
על מה ולמה התיקון ?

**Comment by WizMotiSaadon** [comment]
> על מה ולמה התיקון ?

אני מקצץ את השדה הגדול שמגיע מעכשיו כדי שיכנס ל50 תווים שיש לנו
בטבלה 
PANKPAGES

**Comment by wizayala** [comment]
לא היה צורך
בניתי פרמטרים מתאימים ל 50 תוים וזה נקלט היטב

**Comment by WizMotiSaadon** [comment]
מעולה

**Comment by wizayala** [comment]
יש להחזיר את קובץ 
genbank.hds  
מתאריך 14.7.2020

**Comment by wizayala** [comment]
לאחר שנוודא שהקובץ הישן הוחזר לזיפ
אפשר לסגור את הגיט הזה.


אשר האם יש משהו פתוח בעניין הזה ?

**Comment by wizasher** [comment]
מבחינתי הכל סגור

**Comment by WizMotiSaadon** [comment]
מאיפה אני אמור למצוא אותו?

**Comment by WizMotiSaadon** [comment]
> יש להחזיר את קובץ
> genbank.hds
> מתאריך 14.7.2020

מאיפה אני אמור למצוא אותו?

**Comment by wizayala** [comment]
שמתי לך במחיצה 
H:\HomeFolder\Ayala\for moti

**Comment by WizMotiSaadon** [comment]
> שמתי לך במחיצה
> H:\HomeFolder\Ayala\for moti

ואיפה אני אמור להשים אותו
?

**Comment by wizayala** [comment]
בזיפ שאתה מכין לנו

**Comment by WizMotiSaadon** [comment]
שמתי בזיפ והעברתי למחיצה

**Comment by wizayala** [comment]
מעולה, תודה
סוגרת את הגיט
