### ISSUE TITLE
כותרות למסמכים דרך מסופון2 

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#393]
בממשק כותרות למסמכים דרך מסופון2 
אם מסומן ביטול יתרה לאספקה .
ואין שדה "מזהה שורה" באקסל .
לא מעדכן שדות, גם אלו שלא קשורות למזהה שורה .
 ב-
 ERR
 רושם שעודכן בהצלחה למרות שלא עדכן.
אם יש מזהה שורה או לא מסומן "יתרה לאספקה" הוא כן מעדכן .

**Comment by WizMotiSaadon** [comment]
> בממשק כותרות למסמכים דרך מסופון2
> אם מסומן ביטול יתרה לאספקה .
> ואין שדה "מזהה שורה" באקסל .
> לא מעדכן שדות, גם אלו שלא קשורות למזהה שורה .
> ב-
> ERR
> רושם שעודכן בהצלחה למרות שלא עדכן.
> אם יש מזהה שורה או לא מסומן "יתרה לאספקה" הוא כן מעדכן .

?אז בעצם צריך להודיע הודעת שגיאה אם המזהה שורה לא מקושר

**Comment by wizasher** [comment]
הם ביקשו שגם אם מסומן "ביטול יתרה לאספקה" ואין שדה "מזהה שורה " מקושר , הוא יעדכן את השדות שלא ברמת השורה כמו סכום נוסף , הערות וכו'

**Comment by WizMotiSaadon** [comment]
update IMPORTSTOCK set importstock.ErrorData = importstock.smid , importstock.ErrorMessage = 'שדה תנועה מחייב מזהה תנועה שנמצא בחברה הקולטת'

where (LEN(isnull(importstock.smID,''))=0 or importstock.smID LIKE '%[^0-9]%' or (importstock.smID not in (SELECT ID from stockmoves)))

**Comment by WizMotiSaadon** [comment]
stockheaderin.hds

**Comment by wizasher** [comment]
אצלי תקין ,גם שדות ברמת מסמך כשאין מזהה שורה ומסומן איפוס יתרה.
וגם איפוס יתרה עובד כשיש מזהה שורה .

**Comment by wizayala** [comment]
תקין אצלי
