### ISSUE TITLE
יבוא תנועות מלאי - הודעה לגבי סוג מסמך- חייב להיות מספרי שלם 

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#394]
בייבוא תנועות מלאי מתקבלת הודעה לגבי שדה סוג מסמך, חייב להיות מספרי 
התקלה נובעת מתוספת 
WIN_
 למסמך מסוג חלונות בטבלה זמנית
קובץ מתקן 
odbcimp.exe  12/01/2021
עובד תקין 
 לבדוק את שאר הממשקים ב
ODBC
ולעדכן את אפי

**Comment by wizasher** [comment]
לא ברור על איזה שדה ההודעה 
![image](https://user-images.githubusercontent.com/69102026/104594065-4bf04080-5679-11eb-9ce5-88de4ebc31b1.png)

**Comment by WizMotiSaadon** [comment]
אולי מספר אסמכתא?

**Comment by wizayala** [comment]
זה שדה שבכלל לא בשימוש

![image](https://user-images.githubusercontent.com/16633745/104594807-5b23be00-567a-11eb-9b64-c76313b26638.png)

**Comment by wizayala** [comment]
מוטי
האם התיקונים מתבססים על קובץ  odbcimp.exe  
מגרסה קודמת 
מה ששלחתי לך ?

**Comment by WizMotiSaadon** [comment]
כן, גרסת לקוחות

**Comment by wizasher** [comment]
הורדתי את השידוך שלו והכל נקלט , מוזר שהוא שודך 
![image](https://user-images.githubusercontent.com/69102026/104595518-67f4e180-567b-11eb-994f-cc59ffd3e5ec.png)

**Comment by wizayala** [comment]
אשר הסתדר לך עם השדה הזה
refnum 
?

**Comment by wizasher** [comment]
כן , משכתי שוב את הקובץ שוב , ולא שודך

**Comment by wizayala** [comment]
אז אפשר לסגור את הגיט ?

**Comment by wizasher** [comment]
כן , סוגר
