### ISSUE TITLE
יבוא תנועות יומן - מטבע 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#396]
מתקבלת הודעה כזו : 
![image](https://user-images.githubusercontent.com/16633745/104885080-19dc2880-5970-11eb-8e86-c6f28dccbaca.png)

בגרסה 2018 נקלט היטב ואילו בגרסה 2020 לא נקלט , מה ההגיון ? למה שינינו ?

**Comment by WizMotiSaadon** [comment]
אולי זה לא קשור לגרסה אלא קשור למטבע הראשי בחברה

**Comment by wizayala** [comment]
בשתי החברות בשתי הגרסאות המטבע המוביל הוא שקל

**Comment by WizMotiSaadon** [comment]
אני לא יודע מה הסיבה,
?ההודעה לדעתך נכונה

**Comment by wizayala** [comment]
מוטי
במחשבה שניה ושלישית ההודעה היא נכונה 
אני לא יכולה מתוך התוכנה להכניס תנועות שהמטבע שלהן הוא שקל
אני יכולה בחברה שהמטבע המוביל שלה הוא שקל להכניס לשדה מטבע בתנועות רק מטבעות זרים אחרים 
לכן אני סוגרת את הגיט הזה
