### ISSUE TITLE
עדכון כותרות מלאי - או.די.בי.סי

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#398]
ביבוא כותרות מלאי ( נתונים נוספים למסמכים) כאשר אני בוחרת שיטת 
odbc 
ולוחצת על הפעלה מיד נרשם  בוצע בהצלחה לא הגעתי כלל לחלון של קישור התנועות
זה קורה עם קובץ 
odbcimp.exe   24.1.21

![image](https://user-images.githubusercontent.com/16633745/105630084-8d3dd880-5e4f-11eb-8b22-317369993dd0.png)

**Comment by WizMotiSaadon** [comment]
מה רשום בלוגים?

**Comment by WizMotiSaadon** [comment]
![image](https://user-images.githubusercontent.com/10919353/105631258-43a4bc00-5e56-11eb-85d8-8a136609139c.png)

**Comment by WizMotiSaadon** [comment]
אולי יש בעיה עם הקובץ
odbcimp.exe?
אולי לא קיים?

**Comment by wizayala** [comment]
לאיזה לוג אתה מתכוון ?
אתה רוצה להתחבר ?

**Comment by wizayala** [comment]
148 721 498

**Comment by WizMotiSaadon** [comment]
תיקנתי
תודה

**Comment by wizayala** [comment]
תקין
