### ISSUE TITLE
ממשק קופה לקבוע דרך או.די.בי.סי עם אותו מס' אסמכתא 

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#399]
כשאני קולט ממשק קופה לקבוע דרך 
ODBC
עם כמה סוגי תשלומים - ש'קים, מזומן, אשראי
ובכל שורה יש את אותו מס' אסמכתא 
זה נקלט כקבלה נפרדת לכל סוג תשלום . במקום לקבלה אחת עם 3 סוגי תשלומים .
![image](https://user-images.githubusercontent.com/69102026/105714947-a913ae00-5f25-11eb-9ea1-bbe0101eb698.png)

**Comment by WizMotiSaadon** [comment]
במקום לקבלה אחת עם 3 סוגי תשלומים 

?מי מאשר שזה נכנס לקבלה אחת

**Comment by wizasher** [comment]
בדקתי שוב עם איילה , 
אם יש אותה אסמכתא ואותו תאריך ואותו מפתח לקוח - זה צריך להיכנס לקבלה אחת .

**Comment by WizMotiSaadon** [comment]
שלחתי התכתבות שלי עם איילה בנושא

**Comment by WizMotiSaadon** [comment]
?מה קישרת במטבע מוביל

**Comment by wizasher** [comment]
השארתי ריק 
![image](https://user-images.githubusercontent.com/69102026/105822539-dcf1e080-5fc4-11eb-94fd-70910af0ae8e.png)

**Comment by WizMotiSaadon** [comment]
?אפשר קבצי קלט

**Comment by wizasher** [comment]
עם הקובץ החדש אני מקבל תקלה כשאני לוחץ הפעלה
![image](https://user-images.githubusercontent.com/69102026/106563643-c3a4e300-6534-11eb-9085-51168a108d6c.png)
Failed Second Try To Open Recordset Table Name :[DB2][IMPORTKUPA]
Invalid column name 'STOCK_CONTACTMAIL'.
Invalid column name 'CREDITPAYS_FSHOVAR'.
Statement(s) could not be prepared.

**Comment by WizMotiSaadon** [comment]
new fields:
ImportKupa.CreditPays_fShovar    varchar(50)
ImportKupa.stock_ContactMail    varchar(250)

**Comment by wizasher** [comment]
אני עדיין מקבל את אותה הודעת שגיאה גם בחברה שהוספתי את השדות החדשים , אולי לא הוספתי טוב את השדות ?
![image](https://user-images.githubusercontent.com/69102026/106868667-b96f1a00-66d7-11eb-8243-ac7a37f04bdf.png)

**Comment by WizMotiSaadon** [comment]
לא הוספת טוב
:השמות הנכונים


stock_ContactMail

CreditPays_fShovar

**Comment by wizayala** [comment]
אשר 
שהשדות יראו כך:

![image](https://user-images.githubusercontent.com/16633745/106873516-35b82c00-66dd-11eb-9170-30cb7d173ce0.png)

**Comment by wizayala** [comment]
אצלי זה הסתדר 
רק יש לשים לב שהתיקון הוא על קובץ שמיועד לגרסה הבאה ( הוא כולל שינוי db )

**Comment by wizasher** [comment]
תודה , 
גם אצלי עובד מצוין . גם מסופון2 .

**Comment by wizayala** [comment]
קובץ הועבר לתיקייה של 
H:\HomeFolder\Ayala\2021
