### ISSUE TITLE
הודעת שגיאה כמות גדולה מדי 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#4]
ביבוא תנועות מלאי מחלונות לחלונות כאשר הכמות גדולה מדי לסגירה מתקבלת הודעה נכונה בפירוט וטקסט הודעת השגיאה הוא מסמך הבסיס כבר בסגירה ביבוא הנוכחי.
יש לשנות את ההודעה לכמות לסגירה גבוהה מדי

**Comment by WizMotiSaadon** [comment]
[import_V2016_25_January_2016.zip](https://github.com/wizayala/Hashavsheva/files/102870/import_V2016_25_January_2016.zip)
[Uploading import_V2017_25_January_2015.zip…]()
תוקן

**Comment by WizMotiSaadon** [comment]
[import_V2016_25_January_2016.zip](https://github.com/wizayala/Hashavsheva/files/102873/import_V2016_25_January_2016.zip)
[import_V2017_25_January_2015.zip](https://github.com/wizayala/Hashavsheva/files/102872/import_V2017_25_January_2015.zip)
תוקן

**Comment by wizayala** [comment]
סגרתי רשומות
נראה תקין
לא בדקתי תיקונים אחרים שעשינו כמו פריטי מכפלה , האם יש צורך ?


איילה ישראלי – בדיקות

052-9594258  04-9512832

אתר : www.hash.co.il<http://www.hash.co.il>  ,  דוא"ל : ayala@wizsoft.com<mailto:ayala@wizsoft.com>

[cid:image001.png@01D15754.0E1F0B80]

**Comment by WizMotiSaadon** [comment]
לא

**Comment by wizayala** [comment]
יופי , אז אני מעבירה את הקובץ , לא בדקתי טקסט בדקתי odbc  ובדקתי חלונות לחלונות

איילה ישראלי – בדיקות

052-9594258  04-9512832

אתר : www.hash.co.il<http://www.hash.co.il>  ,  דוא"ל : ayala@wizsoft.com<mailto:ayala@wizsoft.com>

[cid:image001.png@01D15754.C6B93170]
