### ISSUE TITLE
ממשק פריטים שדה - כמות באריזה

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#400]
כשקולטים ממשק פריטים בפריט מסוג טבוע ,מונה ומכפלה .יש הודעה על שדה ,כמות באריזה 
"כמות באריזה חייבת להיות 0" למרות שיש 0 בשדה .
אם אפשר שיכניס 0 או יתעלם , או שההודעה תיהיה ששדה זה צריך להיות ריק .
תודה
![image](https://user-images.githubusercontent.com/69102026/106121054-ca5fde80-615f-11eb-8f69-71662f2e1458.png)
![image](https://user-images.githubusercontent.com/69102026/106121110-db105480-615f-11eb-8aa8-41ee12577d7b.png)

**Comment by WizMotiSaadon** [comment]
itemin.hds

תוקן

**Comment by wizayala** [comment]
תקין אצלי

**Comment by wizasher** [comment]
גם אצלי תקין ,תודה
