### ISSUE TITLE
תיקון קובץ mlayin

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#401]
לבקשת עבד יש לתקן את הקובץ 
mlayin.hds 

כן , ראיתי ש ב (EX)IssueAccess
אתה קורא ל (EX)IssueOneStockRecord
ושם יש הודעה 
mes<<Add_str(mes,Space(1)),
mes<<Add_str(mes,{TC___[DB2][IMPORTSTOCK2ISSUE]ID}),
MessageBox(mes), 
צריך להחזיר ערך וב EXP המקורי אחרי ROLLBACK לתת את ההודעה .

**Comment by wizayala** [comment]
מוטי 
תן לנו הסבר על מה מדובר

**Comment by WizMotiSaadon** [comment]
תיקנתי,
משחרר נעילה ואחרי זה מודיע

**Comment by WizMotiSaadon** [comment]
> מוטי
> תן לנו הסבר על מה מדובר

.יש תרחיש שההפקה נכשלה, ואז אני מודיע הודעה, שההפקה נכשלה, הלקוח לוחץ אוקיי ואז אני משחרר את הנעילה

.אבל יש חשש שהלקוח לא ילחץ על ההודעה, ואז הכל נעול ואף אחד לא יכול לעבוד

.אז עכשיו אני משחרר ואחרי זה מודיע

**Comment by wizasher** [comment]
אבל כשהלקוח לוחץ אוקיי , הוא עדיין בתוך הממשק וכשיש מישהו בתוך הממשק זה עדיין נועל , לא כך ?

**Comment by WizMotiSaadon** [comment]
ברגע שהוא לוחץ אני משחרר מייד
אבל אם הוא הולך לטייל אז הכל נעול

בגלל זה עבד רוצה שקודם כל אשחרר ואחרי זה אודיע

**Comment by wizasher** [comment]
ז"א אחרי שהוא לחץ אוקי ,למרות שהוא עדיין בממשק, משתמש אחר לא יקבל "תחנה נועלת"

**Comment by WizMotiSaadon** [comment]
> ז"א אחרי שהוא לחץ אוקי ,למרות שהוא עדיין בממשק, משתמש אחר לא יקבל "תחנה נועלת"

נכון

**Comment by wizasher** [comment]
יפה , תודה

**Comment by wizasher** [comment]
תוכל בבקשה לרשום איזה ממשקים קשורים לקובץ 
mlayin.hds
כדי שנבדוק אותם . תודה

**Comment by WizMotiSaadon** [comment]
יבוא תנועות מלאי זמני
יבוא תנועות מלאי קבוע

**Comment by wizasher** [comment]
תודה

**Comment by wizasher** [comment]
אני בודק מסמכים למאגר זמני ,
כשאני קולט ומקבל הודעה שהתגלו שגיאות ואני רואה את הטבלה עם השגיאות  , ואני לוחץ המשך .
בשלב הזה אני עדיין נעול מלהיכנס לאותו ממשק .
![image](https://user-images.githubusercontent.com/69102026/106378550-7991f500-63ae-11eb-987e-d656d169d2f4.png)
בשלב הבא שאני מקבל "התגלו שגיאות בקובץ קלט האם לקלוט " ואני לוחץ לא 
גם בשלב הזה אני עדיין נעול מלהיכנס לאותו ממשק 
![image](https://user-images.githubusercontent.com/69102026/106378584-beb62700-63ae-11eb-874f-717f284716dd.png)
![image](https://user-images.githubusercontent.com/69102026/106378619-ff15a500-63ae-11eb-9e18-a148c34a1b9f.png)
רק כשיצאתי מהדלת הוא נתן לי להיכנס .

**Comment by WizMotiSaadon** [comment]
> אני בודק מסמכים למאגר זמני ,
> כשאני קולט ומקבל הודעה שהתגלו שגיאות ואני רואה את הטבלה עם השגיאות , ואני לוחץ המשך .
> בשלב הזה אני עדיין נעול מלהיכנס לאותו ממשק .

נראה לי תקין

**Comment by wizasher** [comment]
אז לא הבנתי מה השתנה אם זה עדיין נותן תחנה נועלת ?

**Comment by WizMotiSaadon** [comment]
אני צריך להתחבר לראות

**Comment by WizMotiSaadon** [comment]
בשביל לבדוק נעילת טרנזקציה במקרה הספציפי הזה צירך ליצור
הודעה
**חלה תקלה בהפקה נא להתקשר לסניף השרות מזהה**

ואז בהודעה לראות אם מצליחים להכנס לתוכנה ולתקן למשל כתובת של לקוח

----------------------------------------------------------------------
תקלה בהפקה אני יכול להשים תקלה פיקטיבית אם אתה רוצה

**Comment by WizMotiSaadon** [comment]
> אני בודק מסמכים למאגר זמני ,
> כשאני קולט ומקבל הודעה שהתגלו שגיאות ואני רואה את הטבלה עם השגיאות , ואני לוחץ המשך .
> בשלב הזה אני עדיין נעול מלהיכנס לאותו ממשק .

זו נעילת 
HDS

עבד דיבר על נעילת טרנזקציה שבה מחכים עד שכל ההחלפות מתבצעות
EXCHANGES
או נכשלות 

ואז משחררים לכולם לעבוד על ה 
DB

**Comment by wizasher** [comment]
כשאני קולט ממשק תנועות מלאי , איזה דטא בייס ננעל 
stock , StockMoves, importstock 
נכון?

**Comment by WizMotiSaadon** [comment]
רק ההפקה נועלת,
את כל ה 
DB

**Comment by wizasher** [comment]
וכשיש הודעה לדוגמא על אסמכתא או שדה אחר הדטא בייס גם ננעל ?
![image](https://user-images.githubusercontent.com/69102026/107140859-d00eae80-692d-11eb-85b6-4535faee0d90.png)

**Comment by WizMotiSaadon** [comment]
לא

**Comment by wizasher** [comment]
הבנתי , אז אשמח לתקלה פקטיבית ואבדוק . תודה

**Comment by wizayala** [comment]
איפה זה עומד ?

**Comment by WizMotiSaadon** [comment]
תקין לגמרי
אפשר לסגור לדעתי

**Comment by wizayala** [comment]
לאחר התייעצות עם עבד ייכנס לגרסה הבאה .
אין לנו דרך לבדוק את זה
