### ISSUE TITLE
דפי בנק או.די.בי.סי דרך מסופון2

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#402]
הגיע מולרי ,
לקוח עם 
SP4
בקליטת דפי בנק בשיטת 
odbc
דרך מסופון2 יש הודעה שהטבלה ריקה .
בקליטה הרגילה דרך הממשקים זה נקלט .
ניסיתי לבדוק עם 
odbcimp 
מתאריכים קודמים וזה עדיין אותה הודעה , כנראה זה קובץ אחר ?!
תודה 
![image](https://user-images.githubusercontent.com/69102026/108067078-ec66c580-7068-11eb-83d4-4c6ac8d57c33.png)
![image](https://user-images.githubusercontent.com/69102026/108067163-0d2f1b00-7069-11eb-8847-7da370880b2c.png)

**Comment by WizMotiSaadon** [comment]
תו לי להתחבר לראות

טלפון שלי
035683829

**Comment by wizasher** [comment]
החלפתי את הקובץ 
BANKIN.HDS
לקובץ האחרון של מהדורה 2018 מתאריך  16/04/19
וזה נקלט טוב 
ניסיתי עם 2 העדכונים האחרונים וזה עדיין נותן את אותה ההודעה 
אז אם אני מבין נכון צריך לתקן את הקובץ 
BANKIN.HDS
מ- 16/04/19
בשתי התיקונים האחרונים 
![image](https://user-images.githubusercontent.com/69102026/108198146-f3064300-7123-11eb-8f81-935455b451c1.png)

**Comment by wizasher** [comment]
קובץ מתקן 
GENBANK.HDS
בקליטה דרך הממשקים הרגילים כשאני בוחר שיטת 
ODBC
אחרי שאני מכניס את המפתח חשבון אני מקבל הודעה 
"ODBC"
פעמיים , ואז הוא נכנס לשידוך שדות 
![image](https://user-images.githubusercontent.com/69102026/108206320-edfac100-712e-11eb-9f09-a1b3ddb942b7.png)

**Comment by WizMotiSaadon** [comment]
תיקנתי

**Comment by wizasher** [comment]
אצלי נראה תקין .
 איילה , תוכלי בבקשה לבדוק גם אצלך, ואם אין בעיה להעביר לולרי  את הקובץ 
GENBANK.HDS 
17/02/2021   15:18
אני מעביר לך במייל 
תודה

**Comment by wizayala** [comment]
תקין גם אצלי , מעבירה לאפרת וולרי
