### ISSUE TITLE
יבוא תנועות הנהלת חשבונות - חשבון חדש

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#403]
ביבוא תנועות הנהלת חשבונות כל השיטות כאשר יש חשבון חדש בפקודות היומן היה  ניתן לראות בשם החשבון 
"הוקם בעקבות תנועות יומן"
כך נראה חשבון 9004 בגרסה קודמת 
![image](https://user-images.githubusercontent.com/16633745/108617104-4fb37780-741c-11eb-9aa4-3dc93f0efcb9.png)
 כך חשבון 9004 בגרסה הנוכחית 
![image](https://user-images.githubusercontent.com/16633745/108617139-8d180500-741c-11eb-9c56-d5f10568f3e0.png)

**Comment by WizMotiSaadon** [comment]
?אז מה לרשום בעצם

**Comment by wizayala** [comment]
צריך שיהיה רשום חשבון הוקם בעקבות....
כמו שהיה בגרסה 2018 , צרפתי צילום מסך

**Comment by wizayala** [comment]
סליחה שיהיה
נוצר בעקבות קליטת תנועות יומן זר

**Comment by WizMotiSaadon** [comment]
כלומר להוסיף 
"זר"

?

**Comment by wizayala** [comment]
כן

**Comment by WizMotiSaadon** [comment]
תוקן
JURNALIN.HDS

**Comment by wizasher** [comment]
אצלי עדיין לא מעדכן "נוצר בעקבות קליטת תנועות יומן זר" בשיטה המקוצרת .
.בשיטה המפורטת כן רואים .
קורה גם מתוך התוכנה וגם במסופון 2

**Comment by WizMotiSaadon** [comment]
יש אפשרות לצלם לי?

**Comment by wizasher** [comment]
![image](https://user-images.githubusercontent.com/69102026/108957598-70790880-767a-11eb-93aa-1bf21215a35c.png)
![image](https://user-images.githubusercontent.com/69102026/108957646-87b7f600-767a-11eb-8e41-fcab462ffb41.png)

**Comment by wizayala** [comment]
אצלי תקין

![Uploading image.png…]()

**Comment by wizayala** [comment]
מוטי 
גם את הגיט הזה יש לתקן

**Comment by WizMotiSaadon** [comment]
אני צריך להתחבר לאשר, לראות מה קורה ב 
DB

הסיבה היא שאני לא מבין אם הבעיה היא רק בתצוגה המקוצרת
או ביבוא של שיטה מקוצרת

**Comment by wizasher** [comment]
שולח חיבור

**Comment by wizayala** [comment]
גם אצלי לא תקין  בשיטה המפורטת
תוכל להתחבר אם תרצה

**Comment by WizMotiSaadon** [comment]
jurnalin.hds
תוקן

**Comment by wizasher** [comment]
אני לא רואה קובץ 
jurnalin.hds
מהיום

**Comment by WizMotiSaadon** [comment]
?עכשיו
[H-Facebook]<https://www.facebook.com/Hashavshevetldt/>

**Comment by wizasher** [comment]
עכשיו יש .
תודה

**Comment by wizasher** [comment]
נראה מצוין , מופיע בכל השדות .
.אני אמשיך לבדוק מסביב 
תודה

**Comment by wizayala** [comment]
אצלי נראה תקין  בשיטה המפורטת

**Comment by wizasher** [comment]
אצלי תקין בכל השיטות ובמסופון2
תודה
