### ISSUE TITLE
ממשק חשבונות שדה הנחה 

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#404]
לבקשת אפי , בקליטת קובץ חשבונות בשדה הנחה אם אין נק' עשרונית צריך לחלק ב- 100 
תודה

**Comment by WizMotiSaadon** [comment]
כלומר אם מתקבל 
70
אני שם אחוז הנחה 
0.7
?

**Comment by WizMotiSaadon** [comment]
תוקן
WizImportMySql

**Comment by wizasher** [comment]
אני עדיין מקבל הודעה 
![image](https://user-images.githubusercontent.com/69102026/109611101-681b4480-7b36-11eb-89a1-8e11b5b9bb30.png)
![image](https://user-images.githubusercontent.com/69102026/109612821-fa244c80-7b38-11eb-9115-b9caf6e10ce4.png)

**Comment by WizMotiSaadon** [comment]
?אפשר קובץ קלט
[H-Facebook]<https://www.facebook.com/Hashavshevetldt/>

**Comment by wizasher** [comment]
נשלח במייל

**Comment by WizMotiSaadon** [comment]
שלחת לי המייל קובץ אקסל
תיקנתי את זה רק עבור קובץ טקסט
?תוכל לברר לאיזה קובץ קלט היא התכוונה

**Comment by wizasher** [comment]
שאלתי את אפי , היא אמרה רק עבור קובץ טקסט .
תודה

**Comment by wizasher** [comment]
גם בקובץ טקסט עדיין יש הודעה , אני שולח לך קבצי טקסט במייל

![image](https://user-images.githubusercontent.com/69102026/109774509-18f21400-7c09-11eb-8bba-e1adfa0bdbe7.png)

**Comment by wizayala** [comment]
אצלי תקין
קובץ טקסט
![image](https://user-images.githubusercontent.com/16633745/109972517-11f9fd00-7d00-11eb-8a37-e3cac026ef00.png)

**Comment by wizayala** [comment]
אשר , אז אני סוגרת את הגיט הזה , נכון ?

**Comment by wizasher** [comment]
כן , תודה

**Comment by wizayala** [comment]
הקובץ הועבר ל
2020a sp6

**Comment by wizasher** [comment]
אני פותח שוב את הגיט לצורך תיקון , 
"אפי:  "אם אין נקודה בקובץ טקסט ההנחיה היא לחלק
![image](https://user-images.githubusercontent.com/69102026/115341206-d84a5c00-a1b0-11eb-94cf-09b603429c29.png)
תודה

**Comment by wizayala** [comment]
מוטי
יש לך תיקון לזה ?

**Comment by WizMotiSaadon** [comment]
זה לא בעיה לתקן, אבל אני לא סגור על זה
שצריך לתקן

**Comment by wizayala** [comment]
למה ?
אשר בדק זאת מול אפרת וזו ההנחיה שלה

**Comment by WizMotiSaadon** [comment]
אבל מה עושים עם כל הלקוחות שקולטים הנחה 
?בלי נקודה עשרונית

נניח 7

עכשיו הם יקבלו 
0.07

**Comment by WizMotiSaadon** [comment]
,החלוקה למאה אני עושה רק בשדות כספיים
אם זה מגיע בלי נקודה עשרונית אני יודע שזה באגורות

**Comment by wizayala** [comment]
אם מגיע ללא נקודה עשרונית אז לחלק

**Comment by WizMotiSaadon** [comment]
תיקנתי
WizImportMySql.dll

**Comment by wizayala** [comment]
אני מקבלת את ההודעה הבאה:

---------------------------
HSD
---------------------------

WizImportLogic.ImportData,ImportAccounts2 failed, return Import Failed
Function =   pIAccountData->Update
Exeption =   Import Failed
Function =  IbidiPtr pIbidi(__uuidof(bidi));
Exeption =  Can not load dll : WizBidiWrapper.DLL (regsvr32]
---------------------------
אישור  
---------------------------

**Comment by WizMotiSaadon** [comment]
אולי צריל לעשות רגיסטרי לקובץ
WizBidiWrapper.DLL
[H-Facebook]<https://www.facebook.com/Hashavshevetldt/>

**Comment by wizayala** [comment]
אחרי רג'יסטרי

---------------------------
HSD
---------------------------

WizImportLogic.ImportData,ImportAccounts2 failed, return Import Failed
Function =   pIAccountData->Update
Exeption =   Import Failed
Function =  IbidiPtr pIbidi(__uuidof(bidi));
Exeption =  Can not load dll : WizBidiWrapper.DLL (regsvr32]
---------------------------
אישור  
---------------------------

**Comment by WizMotiSaadon** [comment]
תני לי להתחבר
[H-Facebook]<https://www.facebook.com/Hashavshevetldt/>

**Comment by wizasher** [comment]
אני גם מקבל
![image](https://user-images.githubusercontent.com/69102026/115981168-9b101080-a59a-11eb-84e0-c878642cb1de.png)
---------------------------
WIZIMP~2
---------------------------
Invalid index.


---------------------------
OK   
---------------------------

תגיד לי מתי נח לך להתחבר

**Comment by wizasher** [comment]
זאת ההודעה הבאה אחרי אישור
---------------------------
HSD
---------------------------

WizImportLogic.ImportData,ImportAccounts2 failed, return Import Failed
Function =   pIAccountData->Update
Exeption =   Import Failed
Function =  CImportData::getFieldFromList #2#
Exeption =  COleException exeption: Invalid index.

---------------------------
אישור  
---------------------------

**Comment by WizMotiSaadon** [comment]
תוקן
WizImportLogic.dll
WizImportMySql.dll

**Comment by wizasher** [comment]
עכשיו נקלט מצוין ,
בודק מסביב .
תודה

**Comment by wizasher** [comment]
אצלי נראה תקין

**Comment by wizayala** [comment]
נקלט טוב
אך נדמה לי שהקליטה איטית
האם יש קשר ?

**Comment by wizayala** [comment]
גרסה הבאה 
מוטי , מה אתה אומר על האיטיות , יש קשר ?

**Comment by wizayala** [comment]
תקין מבחינת % הנחה 
מבחינת מהירות גם תקין 
קובץ טקסט של 4000 רשומות נקלט ב 39 שניות 
קובץ אקסל של 14000 רשומות נקלט ב 3 דקות שזה נראה לי סביר 

לכן סוגרת רשומה
