### ISSUE TITLE
יבוא תנועות מלאי - בדיקת מפתח פריט אות גדולה/ קטנה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#406]
בחברה הקולטת יש לי פריט שהמפתח שלו הוא 
3m
 בקובץ קלט יש לי פריט שהמפתח שלו הוא 
3M 
בממשק מסומן לי פתיחת פריטים חדשים. 
הבאג הוא שאנחנו פותחים פריט חדש
3M
יש לקלוט את הפריט כ 
3m
 אתה עושה את הבדיקה הזו ב**ממשק ספירת מלאי** , עשינו תיקון לזה בגרסה הקודמת

**Comment by WizMotiSaadon** [comment]
אני לא מוצא את הבעיה כפי שמתוארת

יכול להיות שהפריט שנפתח בטבלה
stockmoves
שונה 
מהפריט שכבר קיים בטבלה 
items
?

זה מה שקרה ביבוא ספירת מלאי

**Comment by wizayala** [comment]
כן 
בטבלת 
stockmoves 
נפתח פריט 
3M
במקום
3m

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds

**Comment by wizayala** [comment]
מצויין , אצלי תקין

**Comment by wizasher** [comment]
גם אצלי תקין

**Comment by wizayala** [comment]
התיקון הוא על הקובץ לגרסה הבאה לכן אני לא מעבירה את זה ל 
sp6
אני שמה את הקובץ במחיצה 
H:\HomeFolder\Ayala\2021
