### ISSUE TITLE
הודעות בזמן הפעלת מסופון2 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#408]
כאשר יש הודעות שגיאה / נעילות למיניהן בקליטת קבצים מרובים במסופון2 הקליטה נעצרת ומממשיכה רק לאחר שהלקוח מקיש אישור על הודעת השגיאה.
תיקון נעשה בקובץ prm2ini.dll
מתאריך 28.2.21
הקובץ הועבר למחיצה 
H:\HomeFolder\Ayala\2020a sp6

אשר , לפני שאני מעדכנת את ולרי ואפרת , תאשר לי שזה תקין גם אצלך

**Comment by WizMotiSaadon** [comment]
תוקן
prm2ini.dll

**Comment by wizayala** [comment]
שוב פעם העברת קובץ 
מה השינוי ?
הקובץ שהעברתי הוא מתאריך 28.2.21

**Comment by WizMotiSaadon** [comment]
השדות החדשים ביבוא חשבונות

**Comment by WizMotiSaadon** [comment]
> שוב פעם העברת קובץ
> מה השינוי ?
> הקובץ שהעברתי הוא מתאריך 28.2.21

לא העברתי, רק רשמתי תוקן

**Comment by wizayala** [comment]
סבבה , סוגרת גיט
