### ISSUE TITLE
אמריקן 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#409]
מוטי
תתקן בבקשה בחלון של יבוא chs 
שיופיע אמריקן ולא אמריקאן 

![image](https://user-images.githubusercontent.com/16633745/110247738-69090780-7f76-11eb-8931-5a8a277cb468.png)

**Comment by WizMotiSaadon** [comment]
תוקן
BANKIN.HDS

**Comment by wizasher** [comment]
CHS
זה השתנה 
![image](https://user-images.githubusercontent.com/69102026/110426412-b9838080-80ae-11eb-82a9-fc90119ceced.png)
אם כבר מתקנים אולי כדאי גם ב
RST , 
![image](https://user-images.githubusercontent.com/69102026/110426508-e768c500-80ae-11eb-878f-15cc9b340196.png)
תודה

**Comment by WizMotiSaadon** [comment]
תיקנתי
Bankin.hds
[H-Facebook]<https://www.facebook.com/Hashavshevetldt/>

**Comment by wizasher** [comment]
אצלי תקין .תודה
באיזה ממשקים הקובץ נוגע ?
כל הממשקים של דפי הבנק והאשראי ?

**Comment by WizMotiSaadon** [comment]
זה קובץ מסכים בלבד
רק 
UI

לא נוגע ליבוא עצמו

**Comment by wizayala** [comment]
אצלי תקין
