### ISSUE TITLE
שגויים ביבוא חשבונות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#41]
מוטי , בממשק נוספים דרך ייבוא חשבונות כאשר יש נתון שגוי אתה מציג ברשימת השגויים את אותה רשומה כמה פעמים. זה נובע מכך שבטבלת importaccounts  נוצרות מספר רשומות לאותה רשומה בקובץ וזאת בגלל השדות הנוספים. 
![image](https://user-images.githubusercontent.com/16633745/70981627-28e20e80-20be-11ea-9d03-20bfc67a22f8.png)

**Comment by WizMotiSaadon** [comment]
את מראה לי שתי טבלאות שגויים
,
את מתכוונת לטבלת השגויים מצד ימין או מצד שמאל
?

**Comment by wizayala** [comment]
לא .
תסתכל שברשימת השגויים, נתחיל מזה שאתה רואה שורה 1,5,9 כשבפועל בקובץ הקלט יש רק 4 שורות. הודעת השגויים הזו נובעת מהסיבה שבממשק חשבונות הזה אני קישרתי שדות נוספים . וכשאני מקשרת שדות נוספים בתוך טבלת ה importaccount נוצרות לי עוד שורות ולכן הודעת השגיאה מתייחסת לשורה הראשונה בקובץ קלט  אך היא מופיע כמספר הפעמים שהיא מופיעה בטבלת importaccount  מקווה שברור אם לא אכין לך דוגמא

**Comment by wizayala** [comment]
מצרפת לך קבצי קלט  שיעזרו להמחיש לך את הבעיה.




[cid:image001.png@01D5D9C9.8DE4E5A0]

איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
שלחתי לך דוגמא

**Comment by WizMotiSaadon** [comment]
תיקנתי 
HSImport23.sql

**Comment by wizayala** [comment]
מוטי
עכשיו כאשר אני מגיעה ליבוא חשבונות , בוחרת odbc  והפעלה לא נפתח החלון של בחירת בסיס נתונים אלא מיד "כאילו" מתבצע ממשק ונרשם לא נקחטה כל רשומה.
הרצתי את השאילתא ששלחת


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
> לא נפתח החלון של בחירת בסיס נתונים

זה נראה שחסר לך 
ODBCIMP.EXE

**Comment by wizayala** [comment]
מעולה
תודה


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/73655659-2ac85700-4697-11ea-816e-5ee4e87059d1.png)

תקין
