### ISSUE TITLE
ייבוא תנועות מלאי

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#414]
ביבוא תנועות מלאי אני מקבל 
"השדה סוג מסמך לא יכול להכיל תוכן מילולי"
למרות שהשדה תקין
![image](https://user-images.githubusercontent.com/69102026/111449811-6b0e5b80-8718-11eb-9144-4b23c21896df.png)
![image](https://user-images.githubusercontent.com/69102026/111449857-73669680-8718-11eb-8901-23c7ad93b0f7.png)
זה לא קורה במהדורה 2020
SP6
זה כנראה מהקבצים האחרונים שמיועדים ל
2021

**Comment by wizayala** [comment]
אשר מה קורה עם זה ?
האם עדיין יש תקלה כזו ?

**Comment by wizasher** [comment]
אני רואה שאין את ההודעה , סוגר את הגיט .
