### ISSUE TITLE
קליטת תנועות יומן - פס התקדמות לא מתמלא

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#42]
בגרסה החדשה כשקולטים קובץ טקסט של תנועות יומן , קובץ גדול של מעל ל 60000 רשומות , הייבוא הראשוני, אין שום סרגל - כאילו נראה תקוע אבל לוקח כ 20 שניות עד שעולה חלון של שגויים. לקוח בזמן זה יכול להניח שזה לא עובד או תקו. מדוע אין מיד סרגל של יבוא זמני או סרגל שמציג את הסטטוס של הקליטה.
זה נראה כך :
![image](https://user-images.githubusercontent.com/16633745/71615850-f6570c00-2bbb-11ea-82a9-5ea8dbaa1ed5.png)

**Comment by wizayala** [comment]
העברתי במייל קבצים לבדיקה

**Comment by WizMotiSaadon** [comment]
רואה
עובד על זה

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
מוטי
עדיין מופיע סרגל ללא התקדמות ובראש הסרגל נרשם לא מגיב

**Comment by wizayala** [comment]
שים לב, כאשר אני לא קולטת את המנה , עדיין משנה סיומת של הקובץ עם הודעה נקלט בהצלחה

**Comment by WizMotiSaadon** [comment]
> שים לב, כאשר אני לא קולטת את המנה , עדיין משנה סיומת של הקובץ עם הודעה נקלט בהצלחה
זה בגלל שיש לך ערבבו קבצים
IMP_LIB
גרסת לקוחות

**Comment by WizMotiSaadon** [comment]
> מוטי
> עדיין מופיע סרגל ללא התקדמות ובראש הסרגל נרשם לא מגיב

תוקן

**Comment by wizayala** [comment]
מופיע סרגל , נראה כאילו תקוע
![image](https://user-images.githubusercontent.com/16633745/76933785-976d7d00-68f6-11ea-8cba-827e9bbead77.png)

לאחר הודעת שגויים הסרגל לא מתמלא , לאחר הודעה שהשגויים בפעם השנייה אין הודעה של הקובץ נקלט , רק אם יוצאים ממסך הקליטה

**Comment by WizMotiSaadon** [comment]
כי אני עושה הכל בשרת
שיהיה יותר מהר

**Comment by WizMotiSaadon** [comment]
תוקן
