### ISSUE TITLE
יבוא תנועות הנה"ח - חלונות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#420]
ביבוא תנועות יומן מחלונות לחלונות שם החשבון מקבל את השם שקיים בקובץ קלט
  הכוונה אם בחברה הקולטת שם חשבון של מפתח  30001 הוא איילה
ושם חשבון של מפתח חשבון 30001 בקובץ קלט הוא מוטי
מה שנקלט הוא מוטי
ואין סיבה לדרוס את שם החשבון הקיים
כך היה גם בגרסה 2018
בגרסה הנוכחית זה השתנה

**Comment by WizMotiSaadon** [comment]
באיזה טבלה השם משתנה?
accounts?

**Comment by WizMotiSaadon** [comment]
לדעתי זה קשור לבאג 403

**Comment by wizayala** [comment]
מסכימה אבל שם היה עניין אחר שלא נרשם כלל חשבון הוקם...

**Comment by wizayala** [comment]
> באיזה טבלה השם משתנה?
> accounts.fullname?
> jurnaltrans.debname?

זה משתנה בטבלה 
jurnaltrans.debname

לעומת זאת נשאר תקין בטבלה 
accounts.fullname

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/116859480-b87f5300-ac08-11eb-91ee-023541c91ce0.png)


לעומת 

![image](https://user-images.githubusercontent.com/16633745/116859518-c6cd6f00-ac08-11eb-9f5d-d4e33ad06a43.png)

**Comment by WizMotiSaadon** [comment]
תוקן
jurnalin.hds

**Comment by WizMotiSaadon** [comment]
אבל לפי הצילומי מסך אני רואה שבעצם אין באג

כי את אומרת שאני שם בשדה
jurnaltrnass.credname
משרד

אבל את מראה לי שרשום 
מכירות

**Comment by wizayala** [comment]
נכון השם של החשבון בחברה הקולטת הוא משרד , השם בקובץ קלט הוא מכירות ואתה קלטת מכירות 
 לתוך טבלת
 jurnaltrans

**Comment by WizMotiSaadon** [comment]
אז את רוצה שאני אחליף את השם
?

**Comment by wizayala** [comment]
אני רוצה שאם הכרטיס קיים שישלף שם החשבון שקיים בטבלת accounts 
כך זה היה גרסה הקודמת

**Comment by wizayala** [comment]
אז התיקון הוא בסדר ?
לבדוק את הקובץ?

**Comment by WizMotiSaadon** [comment]
כן,
התיקון של שעה 13:39
jurnalin.hds

**Comment by wizayala** [comment]
יופי , אצלי זה תקין

**Comment by wizayala** [comment]
אשר , אומנם העברתי קובץ תיקון אך לא סגרתי את הגיט כדי שתוכל לעבור על זה . במידה ותקין אצלך ניתן לסגור גיט

**Comment by wizasher** [comment]
גם אצלי תקין
