### ISSUE TITLE
יבוא עצים - שדה משתמש

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#43]
מוטי
התווסף שדה חדש לטבלת עצים ולכן יש להוסיף אותו ליבוא עצים. מדובר על שדה trees.usefid  .
בנוסף מדוע יש רווח של שתי שורות בייבוא עצים 

![image](https://user-images.githubusercontent.com/16633745/71801690-54746b00-3064-11ea-80ec-3382ae19f546.png)

**Comment by wizayala** [comment]
הערך של השדה יהיה כמובן usefid  של המשתמש שקולט את הממשק

**Comment by WizMotiSaadon** [comment]
ALTER TABLE importrree ADD usefid varchar(50);

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
תקין
