### ISSUE TITLE
יבוא עצים - תאריך פתיחת עץ

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#44]
מוטי
יש להוסיף לקליטה תאריך פתיחת עץ trees.treedate , במידה ולא מקשרים את השדה יכנס ערך של תאריך קליטת הממשק

**Comment by WizMotiSaadon** [comment]
ALTER TABLE importrree ADD treedate varchar(50);

**Comment by WizMotiSaadon** [comment]
UpdateControlerValue("stTreeDate",Eadx( "imp_lib.hds","(EX)ProcessDateType",{TC___[DB1][IMPORTTREE]TREEDATE}))[;]


If(StrCmp({stTreeDate},"")=0,
If(CheckDate({stTreeDate})=0,


       UpdateControlerValue("st_ErrorString","תאריך לא תקין"),
       UpdateControlerValue("st_BadData",{stTreeDate}),


ExecuteExpr("(EX)AddErrorToErrTable") 

))[;]

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
מוטי
שים לב שם הטבלה בשאילתא לא נכון

ALTER TABLE importrree ADD treedate varchar(50

צריך להיות ImportTree


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
מוטי,
איך להתייחס למייל הזה ?



איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
סליחה
להתעלם, זה היה לעצמי תזכורת, ומחקתי את זה
________________________________
מ: wizayala ‏[notifications@github.com]‏
‏‏נשלח: יום שלישי 21 ינואר 2020 10:51
‏‏אל: wizayala/Hashavsheva
עותק: מוטי סעדון תוכנה; Assign
‏‏נושא: Re: [wizayala/Hashavsheva] יבוא עצים - תאריך פתיחת עץ (#44)

מוטי,
איך להתייחס למייל הזה ?



איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
בוטל

**Comment by wizayala** [comment]
תודה


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
תקין
