### ISSUE TITLE
יבוא תנועות קופה - הגדרות 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#441]
מוטי
נוספו בגרסה החדשה שני חברות סולקות  טרנזילה וקרדקום
החברות הללו סולקות בלבד לכן אין מקום להגדיר את כרטיס הקופה שלהם כפי שאנחנו מגדירים עבור ויזה וישראכרט
לכן הודעת השגיאה שחסרים קופות לא רלוונטית

![image](https://user-images.githubusercontent.com/16633745/124904504-c0cf8200-dfed-11eb-8684-86cefc189536.png)

![image](https://user-images.githubusercontent.com/16633745/124904944-30de0800-dfee-11eb-9c1f-a3345f8edc29.png)

**Comment by WizMotiSaadon** [comment]
איזה שמות מוזרים

**Comment by WizMotiSaadon** [comment]
תוקן 
kupain.hds

**Comment by wizasher** [comment]
אין הודעה 
תודה
בודק מסביב

**Comment by WizMotiSaadon** [comment]
תנסה אולי למחוק חשבון לכרטיס ישראכרט

**Comment by wizasher** [comment]
מחקתי , וקיבלתי 
![image](https://user-images.githubusercontent.com/69102026/125185393-412ff600-e22d-11eb-9742-65ebeb20e188.png)
זה טוב

**Comment by wizayala** [comment]
אצלי זה תקין

**Comment by wizayala** [comment]
אשר מה אצלך , תקין בסוף ?

**Comment by wizasher** [comment]
כן , תקין .
סוגר
