### ISSUE TITLE
 ייבוא קופה לקבוע - תאריכים נוספים

### ISSUE THREAD

**Issue by wizasher** [wizayala/Hashavsheva#442]
בייבוא קופה לקבוע , אני מקבל הודעה על תאריך נוסף 1 ותאריך נוסף 2
זה נראה שהוא הופך יום וחודש
![image](https://user-images.githubusercontent.com/69102026/125190873-1901c080-e248-11eb-9fb6-e7f76d913cbb.png)
לשלוח קבצי קלט ?

**Comment by WizMotiSaadon** [comment]
?אפשר קובץ קלט

**Comment by WizMotiSaadon** [comment]
תוקן
kupain.hds

**Comment by wizasher** [comment]
מצוין , תודה
בודק מסביב

**Comment by wizayala** [comment]
אצלי נראה תקין

**Comment by wizayala** [comment]
אשר , אפשר לסגור ?

**Comment by wizasher** [comment]
כן , נבדקו גיטים קשורים לקובץ .סגרתי
