### ISSUE TITLE
יבוא תנועות הנה"ח - תו מפריד

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#450]
ביבוא תנועות מסופון2 עם תו מפריד לא נקלט כהלכה , נראה שיש תזוזה
מוטי שלחת תיקון של קובץ 
jurnalin.hds  
מה הייתה התקלה ?

ייתכן ויש צורך להוציא תיקון גם לגרסת לקוחות אעדכן אותך בהמשך

**Comment by wizayala** [comment]
אשר תבדוק בבקשה גם אצלך 
שלחתי לך במייל את הקבצים , זה הגיע במקור מרחל טאובר

**Comment by WizMotiSaadon** [comment]
> מה הייתה התקלה ?
> 


התקלה הייתה 
שהיבוא היה בשיטת
FIXED
רוחב קבוע 

למרות שבמסופון2
הודרת מפריד פסיק

**Comment by wizasher** [comment]
הקובץ המתקן 
JURNALIN.HDS
יש תיקון ל- 2020 מתאריך 25/07/2021 -אצלי נבדק - תקין . נשלח לאפי .
ויש תיקון ל- 2021 מתאריך 23/07/2021 - אצלי נבדק - תקין.
