### ISSUE TITLE
יבוא פריטים כמות האריזה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#452]
מוטי 
בקובץ פריטים האחרון יש טעות ניתן לייבא פריטים עם כמות אריזה שונה מ 0 עבור פריטים מסוג מונה, טבוע ומכפלה
ז"א 
פריטים שהערך בשדה 
items.stockperunit= 1,2,3
 אריזות חייב להיות שווה ל 0שדה 
items.suf4 =0

**Comment by wizasher** [comment]
מוטי , אתה יודע אם התנאי הזה אמור להיות גם בפריט מטריצה 
?
כי אני רואה בתוכנה שהשדה חסום במטריצה ,והוא נותן לקלוט כמות באריזה במטריצה אבא ובן 
items.stockperunit=7,8
![image](https://user-images.githubusercontent.com/69102026/127101114-7a909ca3-af93-4397-a9bd-563346ba17dc.png)

**Comment by WizMotiSaadon** [comment]
> מוטי
> בקובץ פריטים האחרון יש טעות ניתן לייבא פריטים עם כמות אריזה שונה מ 0 עבור פריטים מסוג מונה, טבוע ומכפלה
> ז"א
> פריטים שהערך בשדה
> items.stockperunit= 1,2,3
> אריזות חייב להיות שווה ל 0שדה
> items.suf4 =0

תיקנתי
ITEMIN.HDS
WizImportMySql.dll
WizImportLogic.dll

**Comment by WizMotiSaadon** [comment]
> מוטי , אתה יודע אם התנאי הזה אמור להיות גם בפריט מטריצה
> ?

כן
כלומר עבור הערכים
1,2,3,7,8,9

אני אמור להודיע על שגיאה
אם הכמות שונה מאפס

**Comment by wizasher** [comment]
> > מוטי
> > בקובץ פריטים האחרון יש טעות ניתן לייבא פריטים עם כמות אריזה שונה מ 0 עבור פריטים מסוג מונה, טבוע ומכפלה
> > ז"א
> > פריטים שהערך בשדה
> > items.stockperunit= 1,2,3
> > אריזות חייב להיות שווה ל 0שדה
> > items.suf4 =0
> 
> תיקנתי
> ITEMIN.HDS
> WizImportMySql.dll
> WizImportLogic.dll

התיקון הזה כולל גם פריט מטריצה ?

**Comment by WizMotiSaadon** [comment]
> 
> התיקון הזה כולל גם פריט מטריצה ?

כן

**Comment by wizasher** [comment]
תודה

**Comment by wizasher** [comment]
אצלי עובד , בודק מסביב
![image](https://user-images.githubusercontent.com/69102026/127294215-f8d46315-90c0-4056-a226-3d954a9b3db6.png)

**Comment by wizasher** [comment]
אצלי תקין מסביב. תודה
![image](https://user-images.githubusercontent.com/69102026/127305906-6f4ff5e5-1c77-4d03-87f0-f1e4c27d106c.png)

**Comment by wizayala** [comment]
גם אצלי זה תקין

**Comment by wizayala** [comment]
העברתי לתיקיה 
H:\HomeFolder\Ayala\2021
