### ISSUE TITLE
ממשק חשבונות, פס התקדמות לא מתמלא

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#46]
שולחת לך במייל קבצי טקסט שיש שם מעל 80000 רשומות, זמן הקליטה הוא קצת מעל 4 דק'. אך בזמן הקליטה אין שום סרגל התקדמות ונרשם בכותרת not responding  יחד עם שעון חול שעובד.
האם יש אפשרות להוסיף סרגל ?

**Comment by WizMotiSaadon** [comment]
תוקן
