### ISSUE TITLE
יבוא קבלות - שדות נוספים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#48]
הוספת שדות נוספים ביבוא קבלות שדות , שדות stock.extratext1,2,3,4,5    stock.extrasum1,2,3

**Comment by WizMotiSaadon** [comment]
ALTER TABLE importkupa ADD STOCK_EXTRATEXT1 varchar(50);
ALTER TABLE importkupa ADD STOCK_EXTRATEXT2 varchar(50);
ALTER TABLE importkupa ADD STOCK_EXTRATEXT3 varchar(50);
ALTER TABLE importkupa ADD STOCK_EXTRATEXT4 varchar(50);
ALTER TABLE importkupa ADD STOCK_EXTRATEXT5 varchar(50);


ALTER TABLE importkupa ADD STOCK_EXTRASUM1 varchar(50);
ALTER TABLE importkupa ADD STOCK_EXTRASUM2 varchar(50);
ALTER TABLE importkupa ADD STOCK_EXTRASUM3 varchar(50);

**Comment by WizMotiSaadon** [comment]
תיקנתי
יבוא מ ODBC 
יבוא מ טקסט
שמתי במחיצה

**Comment by wizayala** [comment]
כרגע אין לי דרך להתחבר למחשב בת"א
אתה מעביר את הקבצים בגיט ?



איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
ראיתי את השדות שהתווספו , אך יש לתקן את הכותרות שלהם - עמודה  שם שדה תכיל את הכותרות של השדות הללו ועמודה תאור השדה יהיה  הערה נוספת 1, הערה נוספת 2 ... סכום נוסף 1.....


![image](https://user-images.githubusercontent.com/16633745/72717066-0428fd00-3b7c-11ea-9336-224e6888f5be.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
מוטי
משום מה לא נכנס לי הערך הנכון לשדה הערות1 למרות שלטבלת importkupa  נכנס הערך הנכון אבל לטבלת stock נכנס ערך אחר , הערך של סכום נוסף 1
![image](https://user-images.githubusercontent.com/16633745/73335058-00316500-4277-11ea-9a6d-5b7c8ca276d4.png)

![image](https://user-images.githubusercontent.com/16633745/73335070-07587300-4277-11ea-9682-e2e31a1690a0.png)

**Comment by WizMotiSaadon** [comment]
?את מתכוונת לתוכן שדה אא

?אני יכול להתחבר לראות

**Comment by wizayala** [comment]
אתה יכול להתחבר עכשיו ?


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
כשתרצה להתחבר אני אכין לך מחשב

**Comment by WizMotiSaadon** [comment]
תיקנתי

**Comment by wizayala** [comment]
תקין
