### ISSUE TITLE
ליבוא נתונים נוספים לטבועים- חסרה הודעה על טבועים לא קיימים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#49]
יבוא שדות נוספים לטבועים מתאפשר רק לטבועים שקיימים בטבלת itemsinstance  במקרה ואני מייבאת נתונים נוספים לטבוע שאינו קיים בטבלה , אומנם אתה לא עושה דבר אך מתקבלת הודעה העדכון הסתיים בהצלחה. יש לתת הודעה נכונה . לא התבצע עדכון טבוע לא קיים או משהו דומה לזה

**Comment by WizMotiSaadon** [comment]
בדקתי ואני מודיע
אני מודיע כזאת הודעה:
![image](https://user-images.githubusercontent.com/10919353/74420172-af636400-4e53-11ea-980e-9b4eb7677a7c.png)

**Comment by wizayala** [comment]
מקווה שיותר ברורה התקלה לאחר ההתחברות

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
כעת יש הודעה שאין צמד של מספר טבוע ופריט. בשאלה של האם להמשיך בעדכון בחרתי כן ומתקבלת הודעה העדכון הסתיים במקום "לא נקלטה אף רשומה " במקרה הספציפי שבדקתי בו קובץ הקלט מכיל רק רשומה אחת

**Comment by WizMotiSaadon** [comment]
<מתקבלת הודעה העדכון הסתיים
?את יכולה לצלם לי את ההודעה

**Comment by wizayala** [comment]
מתקבלת הודעה עכשיו לא בוצעה אף קליטה
