### ISSUE TITLE
תצוגה מקדימה שגויה ביבוא תנועות  CRM

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#5]
ביבוא תנועות crm  
תצוגה מקדימה שגויה אינה מציגה את השורות השגויות הנכונות

**Comment by WizMotiSaadon** [comment]
תוקן
[import_V2017_01_Februar_2015.zip](https://github.com/wizayala/Hashavsheva/files/112256/import_V2017_01_Februar_2015.zip)
[import_V2016_01_Februar_2016.zip](https://github.com/wizayala/Hashavsheva/files/112255/import_V2016_01_Februar_2016.zip)
