### ISSUE TITLE
יבוא פריטים - זמן ייצור

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#50]

**Comment by wizayala** [comment]
ביבוא פריטים קישרתי שדה זמן ייצור הכנסתי ערך 15.25 , השדה מוגדר כ double  אני מקבלת הודעת שגיאה כזו:
---------------------------
HSD
---------------------------

Error in SQL :Conversion failed when converting the varchar value '15.25' to data type int.

UPDATE  items  SET items.ProductionTime = IMPORTitem.ProductionTime   	  FROM items,IMPORTitem  WHERE	(    items.itemKEY = IMPORTitem.itemKEY 	           AND LEN( LTRIM(IMPORTitem.ProductionTime)) <> 0           AND IMPORTitem.ProductionTime IS NOT NULL           AND IMPORTitem.ERRORMESSAGE IS NULL  )
---------------------------
אישור  
---------------------------

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/72347264-6c8d5f80-36e0-11ea-9970-84cfc51e97cc.png)

**Comment by WizMotiSaadon** [comment]
אני מנסה להכניס לשדה מסוג שלם
שדה עשרוני
![image](https://user-images.githubusercontent.com/10919353/72503691-0c63fe00-3845-11ea-85bc-8feb09acca7e.png)

**Comment by wizayala** [comment]
ז"א שאם אני רוצה 15.25 צריך להכניס ערך 1525 ואת עושה המרה  ל 15.25 ?


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
לאחר התיקון נראה  כי כאשר יש ערך המכיל דיוק עשרוני של יותר משלוש ספרות , הערך נקלט כפי שהוא מספר עם דיוק עשרוני ארוך. יש לבצע עיגול למספר הנקלט לדיוק עשרוני של שתי ספרות או שלוש ספרות בהתאמה לשדה שקולטים לתוכו. עוד נראה כי העיגול נעשה רק עבור פריטים חדשים ואינו נעשה לפריטים קיימים למרות סימון של עדכון רשומות קיימות
