### ISSUE TITLE
יבוא עצים - שדות חדשים 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#54]
מוטי
הוספתי שדות חדשים :treedate , VersionDescription, usefid  ועדיין אני לא רואה אותם ביבוא 
![image](https://user-images.githubusercontent.com/16633745/72715844-e8245c00-3b79-11ea-864b-246d565ddbf3.png)
![image](https://user-images.githubusercontent.com/16633745/72715912-05f1c100-3b7a-11ea-9d8b-8dbadea5802f.png)

**Comment by WizMotiSaadon** [comment]
יש 
treedate 
.

Userfid - לוקח בעצמי
VersionDescription - איתן נותן לי

**Comment by wizayala** [comment]
הכוונה הייתה שאני לא רואה אותם בקישור השדות ( בשורות החומות)

**Comment by WizMotiSaadon** [comment]
מה הטעם להראות?
למי שמיבא אין שליטה על מה שאני שם

**Comment by wizayala** [comment]
צודק !
אבל אפשר לצמצם את שתי השורות 
במקום לרשום treedate  לרשום בשם השדה ובתאור תאריך הקמה / הוספה

**Comment by wizayala** [comment]
צודק, אבל יש לצמצם מרווחים ולתקן תאור שדה


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
> צודק, אבל יש לצמצם מרווחים ולתקן תאור שדה 
>
תיקנתי 
odbcimp.exe
