### ISSUE TITLE
ייצוא חשבונות- קובץ פרמטרים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#55]
כאשר אני מייצאת קובץ חשבונות ומשנה את שם הקובץ לדוגמא ל heshin1.dat  לא נוצר לי קובץ heshin.prm  לעומת זאת אם שם הקובץ יהיה heshin.dat  נוצר לי קובץ פרמטרים. מדוע זה קשור אחד לשני ?

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
זו ההודעה שמופיעה לאחר לחיצה על ייצוא

![image](https://user-images.githubusercontent.com/16633745/73334004-20abf000-4274-11ea-9d77-212ca43613a5.png)

**Comment by wizayala** [comment]
בחירה בכפתור בטל , ממשיך בהפקה נוצר קובץ dat  ללא קובץ פרמטרים

**Comment by WizMotiSaadon** [comment]
regsvr32 wizini.dll

**Comment by wizayala** [comment]
תקין
