### ISSUE TITLE
יבוא שרות - הוספת מסמכים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#56]
לאפשר יבוא של מסמכים נוספים ליבוא שרות הזמנת שרות
 documentid=107 שייקלט כמסמך הזמנת שרות סוכן
 documentid=117  , לקלוט כמובן הזמנת שרות סוכן 
documentid=117 
 ומסמך נוסף של הצעת שרות 106 =documentid

**Comment by WizMotiSaadon** [comment]
?את יכולה לערוך את זה מחדש
אני לא מבין

**Comment by wizayala** [comment]
לאפשר יבוא של מסמכים נוספים ליבוא שרות   
הזמנת שרות documentid=107 שייקלט כמסמך הזמנת שרות סוכן documentid=117 , 
וכמובן לאפשר קליטת מסמך הזמנת שרות סוכן documentid=117.

ומסמך נוסף של הצעת שרות 106 =documentid

**Comment by wizayala** [comment]
ערכתי מחדש , מקווה שעכשיו ברור


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
שלחתי לך במייל מסמך וורד עם תוספת המסמכים

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
תקין
