### ISSUE TITLE
יבוא עצים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#57]
ביבוא עצים מופיע ההודעה הבאה: 
---------------------------
יבוא מטבלה
---------------------------
WizImport.log 2020-01-28 11:30:33 
---------------------------
OK   
---------------------------

**Comment by WizMotiSaadon** [comment]
צריך לראות מה יש בקובץ לוג בשעה הזאת

**Comment by wizayala** [comment]
איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
שלחתי לך קובץ wizimport.log

**Comment by WizMotiSaadon** [comment]
נותן הודעה
שהשדות המקושרים לא נמצאים בטבלת הקלט

**Comment by wizayala** [comment]
o/k


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>
