### ISSUE TITLE
ייצוא חשבונות - מיקום קבצים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#58]
בייצוא קבצים בהגדרת נמען אני יכולה לבחור מיקום של הקבצים במחשב. כפתור 3 נקודות אמור להביא אותו לאותו מיקום של הקבצים אבל זה לא כך. זוכר מיקום אחרון שהייתי בו

![image](https://user-images.githubusercontent.com/16633745/73333910-e0e50880-4273-11ea-88a3-edb112d1a1cd.png)

**Comment by WizMotiSaadon** [comment]
את מתכוונת להמסך הזה?

![image](https://user-images.githubusercontent.com/10919353/73604323-5bc16280-4597-11ea-8659-8ada9fe7d271.png)

**Comment by wizayala** [comment]
לא אני מתכוונת שיש כפתור של שלוש נקודות שפותח את מיקום הקבצים שבחרתי

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by WizMotiSaadon** [comment]
AccOut.hds

**Comment by wizayala** [comment]
מיקום קבצים עכשיו מופיע ברירת המחדל . 
תקין
