### ISSUE TITLE
חסרה הודעת סיום לקובץ לוג ביבוא ממסופון

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#59]
ביבוא אנשי קשר ממסופון 2 , לא נרשם בקובץ err  האם יובא בהצלחה או לא .
בפועל היבוא מתבצע בהצלחה

**Comment by WizMotiSaadon** [comment]
תוקן

ContactsIn.HDS

**Comment by wizayala** [comment]
מופיעה הודעה "קליטת חשבונות " במקום קליטת אנשי קשר

**Comment by wizayala** [comment]
מוטי
האם אפשר שהודעת הסיום ,קליטת אנשי קשר ... ולא קליטת חשבונות.
מצרפת קובץ לדוגמא של err
איילה


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
קובץ תקין , רישום תקין בקובץ err טעות שלי הפעלתי ממשק חשבונות
