### ISSUE TITLE
הוספת שדות יבוא טבועים 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#6]
יש להוסיף את השדות הבאים לייבוא טבועים .
invest  - השקעה
costcode - קוד תמחיר
debitacc- חן חובה
creditacc- חן זכות

**Comment by WizMotiSaadon** [comment]
[import_V2017_04_Februar_2015.zip](https://github.com/wizayala/Hashavsheva/files/117246/import_V2017_04_Februar_2015.zip)
תוקן

**Comment by wizayala** [comment]
לא צריך שינוי db  ?

**Comment by WizMotiSaadon** [comment]
New fields:

ImportInstance.INVEST    varchar(50)
ImportInstance.COSTCODE  varchar(8)
ImportInstance.DEBITACC  varchar(15)
ImportInstance.CREDITACC  varchar(15)
