### ISSUE TITLE
יבוא עצים - עדכון עץ קיים 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#60]
![image](https://user-images.githubusercontent.com/16633745/73605808-8a493880-45ab-11ea-8f44-a0546a734df5.png)

הודעה שהמקבלת ביבוא עצים compenydefs.treever=0

**Comment by WizMotiSaadon** [comment]
treein.hds תיקנתי

**Comment by wizayala** [comment]
תקין
