### ISSUE TITLE
יבוא עצים - הסרת שדות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#61]
מוטי
אני מתצלת מראש אבל מכיוון שהחלטנו כרגע לא להתעסק עם העניין של הגרסאות יש לבטל גם את השורה של תאריך עץ.
השדות של תאריך עץ, משתמש יתעדכנו בטבלת
 trees 
 באופן אוטמטי ,
תאריך העץ יהיה תאריך הקליטה  והמשתמש יהיה מזהה משתמש קולט. 
זה עובד מצויין.

**Comment by WizMotiSaadon** [comment]
הורדתי

**Comment by wizayala** [comment]
תקין
