### ISSUE TITLE
יבוא תנועות מלאי - תאור שדות חדשים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#64]
מוטי, 
התווספו השדות החדשים הבאים יש להוסיף אותם באשפרות של הייבוא : stock.extranum1 stock.extranum2 , stock.extradate1, stockextradate2 , stockmoves.extranum1, stockmoves.extranum2, stockmoves.extradate1, stockmoves.extradate 2
יש לדאוג ששם השדה יהיה השם שמוגדר בהגדרות חברה ( אתה כבר עושה את זה עם השדות stock.extranote1  , stockmoves.extranote1
מקווה שזה ברור

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
או.קיי
עכשיו אני רואה את השדות
יש לשנת את תאור השדה. יש לעדכון בשדות הנוספים שמעדכנים שדות בטבלת stockmoves  לרשום מספר נוסף 1 תנועה... תאריך נוסף תנועה...


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
מוטי תסתכל על האפיון של השדות נראה שיש בלבול  שדה תאריך  הוא long  ואילו שדה מספר הוא מסוג date

**Comment by WizMotiSaadon** [comment]
![image](https://user-images.githubusercontent.com/10919353/74219595-eef44980-4cb5-11ea-871f-63674edff674.png)

**Comment by wizayala** [comment]
תראה איך זה אצלי 

![image](https://user-images.githubusercontent.com/16633745/74221352-9e331f80-4cba-11ea-97a6-18b014bd487d.png)

**Comment by WizMotiSaadon** [comment]
אפשר לראות צילום מסך של איפה שאת הוספת את השדדות האלה?

**Comment by wizayala** [comment]
למה הכוונה שאני הוספתי את השדות הללו ?


[cid:image001.png@01D5E0C8.9C1F5DC0]

איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
ExtraStockMovesDef

**Comment by wizayala** [comment]
אני לא הוספתי את השדות הללו , הם התווספו כתוצאה מהמולטי שהרצתי מה wizbasic  של הדס
[cid:image001.png@01D5E0C9.3AA4E0F0]

[cid:image002.png@01D5E0C9.3AA4E0F0]
איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
עכשיו זה תקין

**Comment by wizayala** [comment]
עדיין יש לשנות את תאור השדה (העמודה השנייה מימין )

**Comment by WizMotiSaadon** [comment]
?מה לרשום שם

**Comment by wizayala** [comment]
מספר נוסף 1,2 - כותרת  תאריך נוסף 1,2 - כותרת 
מספר נוסף 1,2 תנועה תאריך נוסף1,2 - תנועה

**Comment by WizMotiSaadon** [comment]
> מספר נוסף 1,2 - כותרת תאריך נוסף 1,2 - כותרת
> מספר נוסף 1,2 תנועה תאריך נוסף1,2 - תנועה

תוקן
odbcimp.exe

**Comment by wizayala** [comment]
מצויין
