### ISSUE TITLE
יבוא תנועות מלאי - עדכון שדה jurnaltrans.documentid

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#65]
מוטי
לאחר עדכון יבוא תנועות מלאי היוצרות גם תנועות יומן  יש לעדכן  שדה חדש jurnaltrans.documentid

**Comment by WizMotiSaadon** [comment]
אני לא מבין

**Comment by wizayala** [comment]
כאשר אנחנו מייבאים תנועות מלאי דרך מסופון2 ואנחנו מייצרים תנועות יומן , יש לעדכן עכשיו את השדה שרשמתי לך

**Comment by WizMotiSaadon** [comment]
צריך לשאול מי מתחזק את 
הפרוצדורה 
ISSUEDOC
אין לי שליטה על השדה הזה בתנועות יומן

**Comment by wizayala** [comment]
אבדוק מחר עם הדס


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
צודק
אבדוק שאכן שהפרוצדורה מעודכנת ואם עדיין לא עובד אבדוק מול הדס מי צריך לתקן את זה


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
עבד צריך לתקן
