### ISSUE TITLE
יבוא תנועות מלאי - שדות חדשים ?

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#66]
מוטי 
מדוע הוספת את השדות הבאים 
SMWAREHOUSE , SMDetails, SMDUEDATE

**Comment by WizMotiSaadon** [comment]
new fields:

importstock.SMDUEDATE         varchar(50) 
importstock.SMDetails         varchar(20)

**Comment by wizayala** [comment]
הדס העבירה לך אותם ?

**Comment by WizMotiSaadon** [comment]
זה הגיע ב WEB
ואז הייתי חייב לשמור שיהיה תואם

**Comment by wizayala** [comment]
אבל יש לנו אותם. אם כך זה כפילות


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
השדות הללו למה הם מקשורים בטבלת stockmoves  ?

**Comment by wizayala** [comment]
לדוגמא פרטים - מדובר על פרטים בתנועה 

![image](https://user-images.githubusercontent.com/16633745/74331112-a31bd000-4d9b-11ea-8e48-5807424e63f3.png)

**Comment by WizMotiSaadon** [comment]
עד עכשיו הכנסתי את הקישור "פרטים" גם ל
stock 
 וגם ל
 stockmoves


וסידרתי  ש קישור "פרטים" יכנס ל
 stock  וקישור "פרטים בתנועה" יכנס ל
 stockmoves

זה מתאים?

**Comment by wizayala** [comment]
אז אני מבינה שמחסן יהיה פעם אחת עבור ה stock ופעם אחת עבור ה stockmoves  וכנ"ל תאריך ערך ?


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
> אז אני מבינה שמחסן יהיה פעם אחת עבור ה stock ופעם אחת עבור ה stockmoves וכנ"ל תאריך ערך ? איילה ישראלי - בדיקות

?כן, יש בעיה עם זה

**Comment by wizayala** [comment]
לא
אז יש לתקן בהתאם את שמות השדות
הכוונה פרטים מסמך
פרטים בתנועה
מחסן מסמך , מחסן תנועה וכן הלאה


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
שאלה , מה קורה כאשר מקשרים רק שדה של מחסן ברמת מסמך ולא ברמת תנועה האם כברירת מחדל אתה תקח את  מה שמוגדר ברמת המסמך לתוך השדה של מחסן בתנועה?
מקווה שהשאלה שלי ברורה


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
> לא אז יש לתקן בהתאם את שמות השדות הכוונה פרטים מסמך פרטים בתנועה מחסן מסמך , מחסן תנועה וכן הלאה

תיקנתי

**Comment by WizMotiSaadon** [comment]
> שאלה , מה קורה כאשר מקשרים רק שדה של מחסן ברמת מסמך ולא ברמת תנועה האם כברירת מחדל אתה תקח את מה שמוגדר ברמת המסמך לתוך השדה של מחסן בתנועה? מקווה שהשאלה שלי ברורה

.אם השדה של התנועה ריק אני משאיר אותו ריק
אני יכול אם תרצי לגנוב מהכותרת

**Comment by wizayala** [comment]
כן
צריך להשאיר את זה כמו שהיה ורק אם קישרתי את השדות של התנועה אז הנתונים יתעדכנו בהתאם במידה ולא קישרתי שיעבוד כפי שהיה עד היום ז"א לגנוב מהכותרת


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
> כן צריך להשאיר את זה כמו שהיה ורק אם קישרתי את השדות של התנועה אז הנתונים יתעדכנו בהתאם במידה ולא קישרתי שיעבוד כפי שהיה עד היום ז"א לגנוב מהכותרת

תיקנתי את שלושת השדות
SMWAREHOUSE , SMDetails, SMDUEDATE
