### ISSUE TITLE
יבוא תנועות מלאי - הודעת שגיאה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#67]
ביבוא הודעת שגיאה מתקבלת ההודעה הבאה: איזה שדה לא תקין :

---------------------------
HSD
---------------------------

Error in SQL :The conversion of a varchar data type to a datetime data type resulted in an out-of-range value.
The statement has been terminated.

INSERT INTO STOCK (EVALCURRENCY,TRANSTYPE,VATFREETRANSTYPE,RATE,EXTRANUM1,EXTRANUM2,EXTRADATE1,EXTRADATE2,  EXFILE,CONTACT, CONTACTMAIL,DISTLINE,EXTRASUM1,EXTRASUM2,EXTRASUM3,EXTRATEXT1,EXTRATEXT2,EXTRATEXT3,EXTRATEXT4,EXTRATEXT5,OSEK874,TRANSSTORE,TRANSAGENT,PAYDATE,STATUS,PHONE,ISSUEDATE,REF3,COSTCODE,  REMARKS , VALUEDATE,DOCNUMBER,DUEDATE,DISCOUNTPRC,DISCOUNTPRCR, VATPRC ,REFERENCE ,WAREHOUSE, ACCOUNTKEY,AGENT ,BATCH,DOCUMENTID,ADDRESS,CITY, ACCOUNTNAME, DETAILS, COPIES, MAINRATE,CURRENCY)  VALUES                  ('אירו','ח','פ',3.690000000,5,666666,'31/12/2020','01/01/2021','','','',0,0,0,0,'','','','','','',0,0,'1/1/1990',5,'' , '02/13/2020' , 0 , '' ,   '', '02/13/2020',7845,'02/13/2020',0,0,17.00,0,2,'30001',  0, 9996 ,9,  'פינסקר 16','תל אביב 1234567478','כיתנס','',0,1,'ש"ח')
---------------------------
אישור  
---------------------------

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds

**Comment by wizayala** [comment]
תקין
