### ISSUE TITLE
יבוא תנועות - שדות ייצוא

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#68]
מוטי , תתקן בבקשה את הכותרות של השדות : 
Exportadress_PackingRemarks - הערות לייצוא
Exportadress_ExpAddress - כתובת לייצוא
![image](https://user-images.githubusercontent.com/16633745/74600659-453dff80-509d-11ea-81f1-e892d0ee53d2.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/74631668-31aa9b80-5166-11ea-964b-14ec646fc669.png)
תקין
