### ISSUE TITLE
יבוא תנועות מלאי - שדות נוספים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#69]
מוטי
ביבוא שדות נוספים נכנסים הערכים הנכונים של תאריכים ומספרים נוספים  בתנועה תוך טבלת importstock
אך מה שנכנס לטבלת stockmoves  הם הערכים של שדות תאריכים ומספרים נוספים כותרת 
![image](https://user-images.githubusercontent.com/16633745/74600683-8d5d2200-509d-11ea-801d-771771500330.png)
![image](https://user-images.githubusercontent.com/16633745/74600686-977f2080-509d-11ea-8f55-23d961ca0296.png)

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds

**Comment by wizayala** [comment]
תקין
