### ISSUE TITLE
הוספת שדות ליבוא נתונים נוספים טבועים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#7]
.יש להוסיף את השדות הבאים
invest - השקעה
costcode - קוד תמחיר
debitacc- חן חובה
creditacc- חן זכות

**Comment by WizMotiSaadon** [comment]
[import_V2017_04_Februar_2015.zip](https://github.com/wizayala/Hashavsheva/files/117245/import_V2017_04_Februar_2015.zip)
תוקן
