### ISSUE TITLE
יבוא תנועות יומן, שיטה מהירה לא תקין ב odbc

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#70]
האם יבוא תנועות יומן בשיטת odbc  היא גם מהירה ?
זה לא נראה כך

**Comment by WizMotiSaadon** [comment]
מהירות משופרת רק ביבוא מפרמטרים

**Comment by wizayala** [comment]
למה לא גם ב odbc  כפי שעשינו בחשבונות ופריטים ?


איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
כי אני נאלץ לעבור שורה שורה כדי לדעת מתי זה טרנזקציה חדשה

**Comment by wizayala** [comment]
הבנתי ששוחחת עם הדס בעניין וכן אפשר לשפר את המהירות

**Comment by WizMotiSaadon** [comment]
עוד לא בדקתי את זה,
נראה לי שכן אפשר

**Comment by WizMotiSaadon** [comment]
תיקנתי יבוא מהיר בכל השיטות

**Comment by wizayala** [comment]
זו ההודעה שמתקבלת 
---------------------------
WIZIMP~2
---------------------------
 CImportData::ExecuteSQL error #1# :  insert into jurnaltrans(osek874,Quant,jurnalmatchid,TransType ,Status,BatchNo   ,CostCode ,TransCredID,CurrencyCode,DatF3,TransDebID,Description,ValueDate,DueDate,Ref2            ,Referance      ,Ref3      ,suF      ,suFDlr         ,LockingIs,bdate,hour)                                           SELECT osek874,Quant,transid,										  transtype      ,										  2    ,										  168       ,										  CostCode     ,										  isnull(NULLIF(CredID1, ''),CredID2 )        ,										  CurrencyCode        ,										  DatF3 ,										  isnull(NULLIF(DebID1, ''),DebID2 )      ,										  Description       ,										  ValueDate     ,										  DueDate   ,										  Reference2             ,										  Reference            ,										  Ref3       ,										  case when Abs(CredsuF1 + CredsuF2)>Abs(DebsuF1 + DebsuF2) then (CredsuF1+CredsuF2) else (DebsuF1 + DebsuF2) end,										  case when Abs(CredsuFDlr1 + CredsuFDlr2)>Abs(DebsuFDlr1 + DebsuFDlr2) then (CredsuFDlr1+CredsuFDlr2) else (DebsuFDlr1 + DebsuFDlr2)  end            ,										  case when LEN(ISNULL(ImportJournal.CredID1,''))>0 and LEN(ISNULL(ImportJournal.CredID2,''))>0 or LEN(ISNULL(ImportJournal.DebID1,''))>0 and LEN(ISNULL(ImportJournal.DebID2,''))>0 or LEN(ISNULL(ImportJournal.TransType,''))>0  then 4 else 0 end       ,										  Convert(varchar(10), GETDATE(),120) ,										  DATEPART(hour, GETDATE())*60  +  DATEPART(minute, GETDATE()) 										   FROM ImportJournal where ('AYALAWIN10_10688' = ImportJournal.Computername And ImportJournal.ErrorMessage is null)  order by transid 
CDBException = Error converting data type varchar to float.

---------------------------
OK   
---------------------------

**Comment by wizayala** [comment]
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Runtime Error!

Program: C:\2019\Has.exe



abnormal program termination


---------------------------
OK   
---------------------------

**Comment by WizMotiSaadon** [comment]
אני חושב שתיקנתי
