### ISSUE TITLE
יבוא תנועות יומן -מלל על כפתור הפעלה שיטה מהירה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#71]
צריך לתקן מלל על כפתור הפעלה 
![image](https://user-images.githubusercontent.com/16633745/74602453-42e5a080-50b1-11ea-930f-578301d1d8e8.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
מעולה
