### ISSUE TITLE
יבוא תנועות יומן -כותרות הפוכות בהדפסת שגויים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#72]
בהדפסת שגויים בקובץ להדפסה : הנתון השגוי מופיע תחת תאור השגיאה ואילו תאור השגיאה מופיע תחת הנתון השגוי 

![image](https://user-images.githubusercontent.com/16633745/74602514-023a5700-50b2-11ea-8472-b7af4f27ba11.png)

**Comment by WizMotiSaadon** [comment]
ככה זה בכל סוגי היבוא?

**Comment by wizayala** [comment]
כן ככה זה נראה

**Comment by wizayala** [comment]
ככה זה נראה
למרות שלמיטב זכרוני זה היה תקין היום בבוקר
איזה קובץ אחראי לזה ?



איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
cnverr.ard

**Comment by wizayala** [comment]
תקין
