### ISSUE TITLE
צביעה באדום של רשומות לא תקינות ביבוא חשבונות ופריטים נוספים 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#73]
אין מספר שורות בחלון שגויים ואין סימון של שורות שגויות בתצוגה מקדימה ( שורות באדום) 
![image](https://user-images.githubusercontent.com/16633745/74676902-c2619580-51bf-11ea-9733-0752e6053f92.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
תקין
