### ISSUE TITLE
ניסוח לא תקין של הודעת שגיאה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#74]
מוטי תתקן בבקשה את הודעת השגיאה 

![image](https://user-images.githubusercontent.com/16633745/74714710-cb8c4a00-5233-11ea-9b4e-5c5a09c69526.png)

"שדה תאריך חייב להיות מסוג תאריך

**Comment by WizMotiSaadon** [comment]
ExtraHeshIn.hds
תוקן

**Comment by wizayala** [comment]
תקין
