### ISSUE TITLE
יבוא תנועות יומן - תו לא תקין

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#75]
שלחתי לך מייל עם קבצי קלט שבו יש תו לא תקין שנקלט לתוך התוכנה . מדוע זה קורה ?

![image](https://user-images.githubusercontent.com/16633745/74715860-0becc780-5236-11ea-9640-3941468dd27d.png)

**Comment by WizMotiSaadon** [comment]
?למה זה תו לא תקין

**Comment by wizayala** [comment]
תתיעץ על כך עם הדס

**Comment by wizayala** [comment]
מוטי
שולחת לך דוגמא לקובץ קלט שבו אנחנו קולטים תוים לא תקינים 
תבדוק בבקשה

**Comment by WizMotiSaadon** [comment]
WizImportLogic.dll

תוקן

**Comment by wizayala** [comment]
תצוגה מקדימה 
![image](https://user-images.githubusercontent.com/16633745/77637684-b5725780-6f5e-11ea-9dde-5a9c90d46aa0.png)

אפשר הודעת שגיאה בעברית
![image](https://user-images.githubusercontent.com/16633745/77638297-9d4f0800-6f5f-11ea-92b0-f7b2c4b830b2.png)

**Comment by WizMotiSaadon** [comment]
<אפשר הודעת שגיאה בעברית

HSImportJournal30.sql
תוקן

**Comment by wizayala** [comment]
o.k
