### ISSUE TITLE
יבוא תנועות יומן

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#76]
היי מוטי
 מה זה השדה הזה שהוספת ביבוא תנועות יומן  סוג תנועה ובתאור השדה נרשם תקציבית 
לא זכור לי שבקשתי כזה שדה 

![image](https://user-images.githubusercontent.com/16633745/74809276-76187180-52f5-11ea-8503-e3c08f6093fe.png)

**Comment by WizMotiSaadon** [comment]
זה נועד לקלוט קבצים שהגיעו מחשבשבת אינטרנט
כי שם אין יותר סוג תנועה 
"תק"

שאלתי את הדס 
והיא אשרה להוסיף

אני אשפר את התאור שדה

**Comment by wizayala** [comment]
זה מבלבל – כי לנו יש שדה סוג תנועה
אולי תוסיף מלל לגרסת אינטרנט.



איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
תיקנתי
odbcimp.exe

**Comment by wizayala** [comment]
מוטי 
בקליטת קובץ פרמטרים צריכה להיות  התייחסות  לשדה הזה ? 
השאלה שלי האם בקובץ פרמטרים אני צריכה שורה 30 - סוג מנה לאינטרנט 
                                                                       שורה 31 - אסמכתא 4 
                                                                        שורה 32 - אסמכתא 5 
וכן הלאה ...

**Comment by WizMotiSaadon** [comment]
את יכולה להסתכל בתצוגה מקדימה ולראות אם זה קיים

**Comment by wizayala** [comment]
ok
