### ISSUE TITLE
יבוא תנועות מלאי - נתקע

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#77]
מוטי
שלחתי לך קובץ אקסל שלא ברור לי מדוע הוא נתקע בייבוא 
(מייל מתאריך 17.2.20 בשעה 20:19)

**Comment by WizMotiSaadon** [comment]
תוקן
mlayin.hds

**Comment by wizayala** [comment]
מצויין 
מה הייתה הבעיה ?

**Comment by wizayala** [comment]
התקיעה הזו מתרחשת גם בגרסת לקוחות

**Comment by WizMotiSaadon** [comment]
ניסינו למנוע התנגשות עם היבוא קופה
ושיבשנו את החיתוך של המסמכים המיועדים לקליטה
