### ISSUE TITLE
האם אפשרי מקובץ טקסט,יבוא תנועות מלאי -שאלה לגבי שדות חדשים 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#78]
מוטי
האם השדות החדשים שהוספנו ביבוא תנועות מאי , האם אפשר לייבא אותם גם בקבצי טקסט ?

**Comment by WizMotiSaadon** [comment]
כן

**Comment by wizayala** [comment]
האם אני יכולה להוסיף לפרמטרים את השורות לפי הסדר שזה מופיע ב odbc  ?

**Comment by WizMotiSaadon** [comment]
כן
בתצוגה מקדימה תוכלי לראות אם זה מסתדר
