### ISSUE TITLE
יבוא נתונים נוספים מסמכים - גרסת לקוחות 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#79]
מוטי
משהו השתבש ביבוא נתונים נוספים למסמכים: לא מתעדכנים שדות הערות לייצוא , כתובות לייצוא שדות נוספים.
משהו השתנה, תוכל לבדוק ?
הגיע מלקוח !!!

**Comment by WizMotiSaadon** [comment]
לפי הקוד,
לא נראה שקלטתי אי פעם 
הערות לייצוא , כתובות לייצוא

**Comment by wizayala** [comment]
מוטי
מה בנוגע לסכום נוסף 1 -3 טקסט נוסף 1-5 ? האם נקלטו בעבר וכיום לא

**Comment by wizayala** [comment]
עדכון השדות כולל ייצוא היה בגרסה של 2018 30.6.2017

**Comment by WizMotiSaadon** [comment]
> מוטי
> מה בנוגע לסכום נוסף 1 -3 טקסט נוסף 1-5 ? האם נקלטו בעבר וכיום לא
לפי הקוד
נקלט בעבר

כעת אני לא יודע
לא בדקתי עדיין

**Comment by WizMotiSaadon** [comment]
> עדכון השדות כולל ייצוא היה בגרסה של 2018 30.6.2017

יש לך תיעוד של זה?

**Comment by wizayala** [comment]
איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by wizayala** [comment]
בלה בלה

**Comment by wizayala** [comment]
> > עדכון השדות כולל ייצוא היה בגרסה של 2018 30.6.2017
> 
> יש לך תיעוד של זה?

כן יש לי

**Comment by wizayala** [comment]
מוטי יש חדש בעניין זה ?

**Comment by wizayala** [comment]
יתוקן בגרסה הבאה 2020

**Comment by WizMotiSaadon** [comment]
StockHeadIn.hds

תוקן

**Comment by wizayala** [comment]
תקין
