### ISSUE TITLE
הוספת שדות יבוא רכוש קבוע

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#8]
יש להוסיף את השדות הבאים לייבוא רכוש קבוע.
invest - השקעה
costcode - קוד תמחיר
debitacc- חן חובה
creditacc- חן זכות

**Comment by WizMotiSaadon** [comment]
[שינויי דטה בייס מוטי סעדון.txt](https://github.com/wizayala/Hashavsheva/files/115648/default.txt)

**Comment by WizMotiSaadon** [comment]
[import_V2017_03_Februar_2015.zip](https://github.com/wizayala/Hashavsheva/files/115709/import_V2017_03_Februar_2015.zip)
תוקן

**Comment by wizayala** [comment]
ממתינה למספר הבהרות בעניין השדות הללו מהדס ואמשיך בבדיקה
