### ISSUE TITLE
יבוא תנועות יומן - שדות נוספים 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#80]

**Comment by wizayala** [comment]
שדות נוספים 
extradate1, extradate2, extranum1' extreanum2
לא מתעדכנים בטבלת jurnaltrans  לעומת זאת כן מתעדכנים בטבלת importjurnal

**Comment by WizMotiSaadon** [comment]
תוקן

HSImportJournal22.sql
journalin.hds

**Comment by wizayala** [comment]
אם אין לי נתון של תאריך נוסף נותן הודעת שגיאה . כשאין נתון יש לשתול תאריך מערכת

![image](https://user-images.githubusercontent.com/16633745/74934047-fe7a3d80-53ed-11ea-9a2b-f8356d7a3bad.png)

**Comment by wizayala** [comment]
בנוסף השדות הנוספים בשורה 1 לא מתעדכנים

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
שדה תאריכים נוספים מתעדכנים אבל שדות סכומים נוספים לא מתעדכנים ב 0 אלא ב 
null
![image](https://user-images.githubusercontent.com/16633745/77083281-eeae4300-6a05-11ea-85e4-71797351231e.png)

**Comment by WizMotiSaadon** [comment]
זה בכוונה ככה

**Comment by wizayala** [comment]
מה הרעיון ?
לפי המסמך של הדס צריך לקבל 0

**Comment by WizMotiSaadon** [comment]
איפה המסמך?

**Comment by wizayala** [comment]
איילה ישראלי - בדיקות

[cid:image003.png@01D2C731.09BE7F50]

www.hash.co.il<http://www.hash.co.il/>

**Comment by WizMotiSaadon** [comment]
תוקן
jurnalin.hds
