### ISSUE TITLE
ברירות מחדל לשדות תאריכים נוספים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#81]
במידה והשדות הנוספים אינם מקושרים צריך להתעדכן ברירות מחדל . ז"א שהשדות 
jurnaltrans.extradate1       jurnaltrans.extradate2 
מקבלים ערך של תאריך המערכת בזמן הקליטה.
נכון להיום שורה ראשונה מתוך קובץ הקלט מקבלת ערך של 01.01.1997 והאחרות מקבלות
null

**Comment by WizMotiSaadon** [comment]
jurnalin.hds

תוקן

**Comment by WizMotiSaadon** [comment]
וגם להריץ סקריפט
HSImportJournal23.sql

**Comment by wizayala** [comment]
עכשיו שדות תאריך מקבלים ערך null במקום לקבל תאריך ברירת מחדל של תאריך קליטה

**Comment by WizMotiSaadon** [comment]
![image](https://user-images.githubusercontent.com/10919353/75624628-ced1ef00-5bbe-11ea-802d-24f8fd985cba.png)

**Comment by WizMotiSaadon** [comment]
אצלי זה בסדר
הרצת את הסקריפט 
HSImportJournal23.sql
?

**Comment by wizayala** [comment]
הרצתי אצלי את הסקריפט ועדיין נרשם null

**Comment by WizMotiSaadon** [comment]
jurnalin.hds
תוקן
