### ISSUE TITLE
יבוא תנועות יומן ברירת מחדל שדה כמות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#82]
מוטי
שדה כמות צריך לקבל ערך ברירת מחדל במידה ולא מקשרים אותו. כשמייבאים ממשק שורה ראשונה מקבלת ערך 0 ושאר השורות מקבלות ערך
 null
יש לדאוג שכל השורות מקבלות ערך ברירת מחדל של 0 במידה והשדה אינו מקושר

**Comment by WizMotiSaadon** [comment]
תוקן
Journalin.hds

**Comment by wizayala** [comment]
עדיין אותו דבר:

![image](https://user-images.githubusercontent.com/16633745/74916133-01653600-53ce-11ea-9b7d-f080ec1f0eea.png)

**Comment by WizMotiSaadon** [comment]
אולי עכשיו
jurnalin.hds

**Comment by wizayala** [comment]
תקין
