### ISSUE TITLE
יבוא תנועות יומן - שדה נעילות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#83]
מוטי
בקליטת ממשק תמיד שדה נעילות 
jurnaltrans.lockingis 
היה מקבל ערך 4 כשיש ס"ת בתנועה
בגרסה החדשה מקבל ערך 1

**Comment by WizMotiSaadon** [comment]
לא מצליח לשחזר את זה,
אצלי יש 4

?את יכולה לשלוח לי צילום מסך

**Comment by wizayala** [comment]
גרסה 2020

![image](https://user-images.githubusercontent.com/16633745/74915092-4720ff00-53cc-11ea-9a25-8ffc82e59b50.png)

גרסהת לקוחות 
![image](https://user-images.githubusercontent.com/16633745/74915262-98c98980-53cc-11ea-9e85-c22dd96dac73.png)

**Comment by WizMotiSaadon** [comment]
?בטוחה שהאחד זה בגלל היבוא
?אולי משהו אחר גורם לזה
כי אני לא נגעתי בשדה הזה

**Comment by wizayala** [comment]
אני קולטת את אותו קובץ קלט בשתי הגרסאות גרסת לקוחות והגרסה הבאה . ובגרסה הבאה נקלט לי 1.
להעביר לך קובץ קלט ?

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
תקין
