### ISSUE TITLE
יבוא תנועות יומן - שדה מספר שורה

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#84]
ביבוא תנועות יומן עד היום שדה 
jurnaltrans.movenum 
קיבל ערך 99999999
היום ביבוא בגרסה החדשה זה ממוספר 100,200,300....
מה הנכון ?

**Comment by WizMotiSaadon** [comment]
100,200,300

**Comment by wizayala** [comment]
מוטי
שוב מקבל ערכים של 999999

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
תקין
