### ISSUE TITLE
jurnaltrans.documentid עדכון

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#85]
ביבוא תנועות מלאי דרך מסופון2 ניתן להגדיר שתרשם תנועת יומן בההנלת חשבונות. ישנו שדה לדש jurnaltrans.documentid  המקבל את סוג המסמך שנקלט . השדה הזה אינו מתעדכן נכון

**Comment by WizMotiSaadon** [comment]
את יכולה לערוך מחדש?
כי אני לא מבין

**Comment by wizayala** [comment]
ביבוא תנועות מלאי דרך מסופון2 ניתן להגדיר שבסיום הקליטה נוסיף תנועת יומן בהנהלת חשבונות.
 ישנו שדה חדש
 jurnaltrans.documentid 
השדה הז המקבל את סוג המסמך שנקלט . 
השדה הזה אינו מתעדכן נכון - יש לתקן את זה

**Comment by WizMotiSaadon** [comment]
צריך לבקש ממי שמתחזק את הפרוצדורה


ISSUEDOC


אין לי שליטה על השדה הזה בתנועות יומן

**Comment by wizayala** [comment]
נכון , זה של עבד העברתי לטיפולו
