### ISSUE TITLE
יבוא נתונים נוספים מסמכים - שדות נוספים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#87]
יש להוסיף את השדות הבאים ליבוא נתונים נוספים למסמכים לתוך טבלאות stock   ,  stockmoves

תאריך נוסף 1,2 ומספר נוסף 1,2  לכל טבלה

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/75624933-e8c10100-5bc1-11ea-90d4-1e426f324611.png)
חסרים אותם שדות עבור טבלת stockmovrs

**Comment by WizMotiSaadon** [comment]
תוקן
odbcimp.exe

**Comment by wizayala** [comment]
תקין
