### ISSUE TITLE
יבוא תנועות מלאי - Failed Second Try To Open Recordset Table Name :[DB1][IMN.TXT]

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#88]
מה פשר ההודעה ?
שלחתי לך במייל נפרד קבצי קלט 

---------------------------
HSD
---------------------------

Failed Second Try To Open Recordset Table Name :[DB1][IMN.TXT]
Too few parameters. Expected 17.

---------------------------
התעלם  בטל  
---------------------------

**Comment by WizMotiSaadon** [comment]
זה לא קשור לקבצי קלט,
נראה שהקובץ
mlayin.hds
השתבש, 
אני צריך לשמור מחדש

**Comment by WizMotiSaadon** [comment]
תיקנתי
mlayin.hds

**Comment by wizayala** [comment]
אני עדיין מקבלת את ההודעה .
תוכל להתחבר אליי אם תרצה 
שלחתי לך גם קבצי קלט , האם אצלך זה נקלט ?

**Comment by wizayala** [comment]
תקין לאחר עדכון prm2ini.dll
