### ISSUE TITLE
יבוא דפי בנק פועלים 

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#9]
להוסיף בייבוא דלג על הכל או יציאה ללא קליטה

**Comment by WizMotiSaadon** [comment]
[import_V2017_10_Februar_2015.zip](https://github.com/wizayala/Hashavsheva/files/124323/import_V2017_10_Februar_2015.zip)
[import_V2016_10_Februar_2016.zip](https://github.com/wizayala/Hashavsheva/files/124324/import_V2016_10_Februar_2016.zip)
תוקן

**Comment by wizayala** [comment]
כרגע התיקון כולל הגדרת חשבונות במספר חברות ועניין זה יוכנס לנמהדוקרה הבאה 2017
הגדרת החשבנונות תהייה מתוך כפתור הגדרת ממשקים

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
????????????????
