### ISSUE TITLE
יבוא דפי בנק - מיפוי חשבונות

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#91]
לאחר שיצרתי מצב שיש לי אותם חשבונות ולאותה חברה ממופים לשני חשבונות בנק בסימון "התעלם " באחת השורות אני מקבלת את ההודעה הבאה : 
---------------------------
WizIni
---------------------------
1582539483377 select COUNT(id) from demo-ayala.dbo.accounts where accountkey = 'פועליםחדש'Incorrect syntax near '-'.
Statement(s) could not be prepared.

---------------------------
OK   
---------------------------
---------------------------
HSD
---------------------------

---------------------------
אישור  
---------------------------

**Comment by WizMotiSaadon** [comment]
כנראה זה המקף בשם חברה
מנסה לטפל

**Comment by WizMotiSaadon** [comment]
איך זה עכשיו?

**Comment by wizayala** [comment]
האם כל wizini.dll  צריך לעשות לו רג'יסטרי ?

**Comment by WizMotiSaadon** [comment]
אם יש הודעת שגיאה שקשורה לרגיסטרי

אז צריך

**Comment by wizayala** [comment]
אגב אין שום מקף במפתח חשבון או בשם מסד הנתונים.
ועכשיו זה הסתדר עם העדכון האחרון
