### ISSUE TITLE
בעיית עברית הפוכה יבוא תנועות מלאי - קובץ טקסט

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#92]
קובץ טקסט  המקודד windows1255 תצוגה מקדימה רואים תקין, בפועל נקלט הפוך
![image](https://user-images.githubusercontent.com/16633745/75429860-1f451480-5953-11ea-909f-4969e6e72ebb.png)

![image](https://user-images.githubusercontent.com/16633745/75429896-308e2100-5953-11ea-927a-b7b812be8a68.png)

**Comment by wizayala** [comment]
נקלט תקין אם אני מסמנת ansi  

![image](https://user-images.githubusercontent.com/16633745/75430024-63381980-5953-11ea-8c8d-8fd75837d963.png)

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
o.k
