### ISSUE TITLE
יבוא תנועות הנהלת חשבונות - שגויים

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#94]
מוטי 
תסתכל על פירוט הודעת השגויים

![image](https://user-images.githubusercontent.com/16633745/75622738-5b26e680-5bac-11ea-9e45-7c324a7e92a7.png)

![image](https://user-images.githubusercontent.com/16633745/75622781-be187d80-5bac-11ea-9610-10fdb75a94f6.png)

**Comment by wizayala** [comment]
מוטי 
תסתכל על תוכן ההודעה של פרוט השגויים.
תמונה עליונה גרסה 2020
תמונה תחתונה גרסת לקוחות

**Comment by WizMotiSaadon** [comment]
הסתכלתי

**Comment by WizMotiSaadon** [comment]
HSImportJournal25.sql
תוקן

תריך להריץ סקריפט
HSImportJournal25.sql

**Comment by wizayala** [comment]
ועדכנתי קבצים מקבלת את ההודעה הבאה :
---------------------------
WIZIMP~2
---------------------------
CJournalData::Update
---------------------------
OK   
---------------------------

---------------------------
WIZIMP~2
---------------------------
CJournalData::ProcessTempTable()
---------------------------
OK   
---------------------------
ההודעות הסתדרו אך עדיין סדר המיון של השורות לא נכון 

![image](https://user-images.githubusercontent.com/16633745/75883886-7142da00-5e2c-11ea-90b4-f68319ff202f.png)

**Comment by wizayala** [comment]
עדכנתי שוב את הקבצים וההודעות הסתתדרו אך עדיין יש את עניין מיון השורות של השגויים. אגב אם אני לוחצת על הדפסת שגויים השורות ממינות נכון

**Comment by WizMotiSaadon** [comment]
תוקן
