### ISSUE TITLE
רשימת שגויים לא ממויינת

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#95]
רשימת שגויים אינה ממוינת נכון 
שלחתי לך קובץ לדוגמא

**Comment by WizMotiSaadon** [comment]
אפשר צילום מסך? לא קיבלתי קובץ

**Comment by wizayala** [comment]
שלחתי לך צילומי מסך וקובץ

**Comment by WizMotiSaadon** [comment]
תוקן

**Comment by wizayala** [comment]
עדיין לא תקין

**Comment by wizayala** [comment]
סוגרת את הקריאה הזו , יש אותו דבר ב #109
