### ISSUE TITLE
יבוא תנועות הנהלת חשבונות - קובץ טקסט

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#97]
קובץ טקסט iso המקודד עם עברית הפוכה , לאחר סימון היפוך כתב ראי , תצוגה מקדימה נראה מצויין 
![image](https://user-images.githubusercontent.com/16633745/75625664-03e33f00-5bc9-11ea-98bb-49e0c6970dde.png)

בתצוגה מקדימה כשיש שגויים עברית מופיעה הפוך

![image](https://user-images.githubusercontent.com/16633745/75625687-312fed00-5bc9-11ea-98ca-39f7deb51dcf.png)

**Comment by WizMotiSaadon** [comment]
תוקן
jurnalin.hds

**Comment by wizayala** [comment]
![image](https://user-images.githubusercontent.com/16633745/75884352-52911300-5e2d-11ea-883b-bbc82500993c.png)

מצויין תקין
