### ISSUE TITLE
 יבוא קודי תמחיר - רווח בחתך

### ISSUE THREAD

**Issue by wizayala** [wizayala/Hashavsheva#99]
מוטי, אין לאפשר קליטת קודי תמחיר שדה חתך המכיל המכיל רווח.
צריכה להופיעה הודעה:
**שדה חתך צריך להכיל 10 תוים**

**Comment by WizMotiSaadon** [comment]
//#99
If ( Find({st_CostCodeFilter},Space(1))>(-1),
UpdateControlerValue("st_ErrorString","חתך לא יכול להכיל רווח" ),
UpdateControlerValue("st_BadData",{st_CostCodeFilter}),


ExecuteExpr("(EX)AddErrorToErrTable"))[;]

**Comment by WizMotiSaadon** [comment]
תוקן
CostCodeIn.hds

**Comment by wizayala** [comment]
אחלה 
![image](https://user-images.githubusercontent.com/16633745/75884587-ca5f3d80-5e2d-11ea-9def-810a29b408d9.png)
